### ISSUE TITLE
Add host-authoritative powerup management

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#102]
This will be a fairly open-ended issue where we can add all of the bugs that host-authoritative powerup management will fix.

When a 4-pack of missiles is picked up, respawn the missiles that the player couldn't carry (i.e. a player can only carry 2, so when he picks up a 4-pack, 2 more missiles should be spawned somewhere).

**Comment by Mako88** [comment]
This would also deal with conc missiles respawning (since new ships always have several conc missiles)

**Comment by zicodxx** [comment]
The title of the issue is a bit misleading but yes, this is something I would like to fix by having the host manage or at least monitor powerups and respawn whatever is necessary. Right now, only consuming powerups will cause a respawn. So a loss caused by player timeouts or the issue described above will not be covered. Same as Vulcan ammo which is never respawned.

**Comment by zicodxx** [comment]
This should be covered by 901a554e96946fec1bd5e926a3957ce600da9023
