### ISSUE TITLE
Gauss Ammo Bugs

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#109]
This is a quote from Drakona describing the current gauss ammo bugs:

There were two of them.

One was less of a bug and more of a missing feature: in D2, if you run over a vulcan or gauss cannon and you already have one, you'd pick up the extra ammo from the cannon. Only . . . the game never told your opponent you'd done that.

So someone would die, drop a cannon with 20,000 rounds, you'd run over it and pick up 19,000 rounds (but leave the cannon). He'd come back and pick it up, and it'd still have 20,000 rounds on it in his game . . . boom, ammo doubled.

The other was a clear bug. In D1, if you die and you have a vulcan cannon, you drop the ammo on the cannon. If you have ammo but no cannon, you drop ammo boxes. In D2, it uses the same code . . . which unfortunately means that if you die and have a gauss but no vulcan, you drop the gauss cannon with ammo on it *and* (since you have no vulcan) you drop boxes for the ammo. Ammo doubled.

The net result was that every death, the ammo carried by one player doubled or tripled. The result was that level designers had no true control over the amount of vulcan ammo in the level. By late in a D2 game, it was always "way too much". Most noticable in Barathrum. The level had two gausses, no vulcans, and zero ammo packs. Gauss should've been ammo-limited, but by the end of a ladder match in there, both cannons are full and there are boxes floating around the level...

She ended up making vulcan ammo consistent as the game progresses in D2 (players drop any ammo they had picked up when they die, whether or not they had used any of it. This results in players being able to hoard "empty" ammo boxes until they die, because the ammo doesn't respawn until they die). She left the ammo depleting slowly in D1 as it has always been. (Both of these choices seem to be what most of the community want).

**Comment by zicodxx** [comment]
Things like this I would like to resolve with a host-centred powerup respawning. Right now, players respawn items either on death (player loot) or upon consumption (firing missile, etc). 
My idea would have the host to count the level inventory and the players spawn inventories (conc missiles and whatever other items the players are configured to spawn with) and count that as the "initial level inventory". Periodically (every 1-3 seconds), the host recounts the current level inventory, compared it against the initial inventory and respawns the difference (or even desintegrates overhead powerups if that ever may be necessary). 

This should account for problems like this as well as powerups lost due to player timeout or other differences - whatever the cause.

**Comment by zicodxx** [comment]
So these two issues are not directly covered by the revamped spawning feature but they would be kept at bay. The players could potentially still exploit these issues but in worst case you may end up with all Vulcan/Gauss cannons maxed out while using these cannons would eventually bring back the overall vulcan ammo count back to normal since ammo boxes would not respawn if an excess amount is detected. 

However I will address both issues with the following changes:
1) If a player hovers over a cannon, taking its ammo, an update packet will be sent, informing clients of the modified ammo state. 
2) For D2, upon a players death, there should be three different cases for vulcan/gauss drops
   * Player drops only ammo (having no guns)
   * Player drops either Vulcan or Gauss (depending on which gun they have - with all ammo contained in this gun)
   * Player drops both guns (if they have both - ammo is split between both)

**Comment by zicodxx** [comment]
These issues should now be addressed with 7684ce92e4170f1cccc602dc0d2a52fe29e4dfa2 and 416ea963c8de9fe55b30550d9f6691246117d611. I did some basic testing on it and all the pointed out exploits are fixed. The new powerup spawning would still balance out those exploits eventually but with them the levels will be and stay consistent.
If something else still comes up, please open a new ticket (unless it's related to these two issues). But for the time being, I'll close this.
