### ISSUE TITLE
Robots don’t see me on large distance

### ISSUE THREAD

**Issue by Totktonada** [dxx-rebirth/dxx-rebirth#11]
For example on descent 1 level 24. I can stop, quietly take aim and destroy each consecutively. I use d1x-rebith-0.58.1 on Linux.

**Comment by zicodxx** [comment]
After examining the demo (which I luckily still had saved), I can conclude that this is also related to the unique robot behavior addressed in #286. Logically this issue was not affected by the bug addressed in #286 but it explains @Totktonada 's observation. Comparing this demo to the original behavior shown in the MS-DOS version running via DOSBox, I can't see much of a divergence to current master. Closing.

**Comment by Totktonada** [comment]
Christian, thank you for take it into consideration! I’m okay with closing with the reason that it matches the original behaviour.

I edited my comment above to readd the demo file to make the issue more consistent.
