### ISSUE TITLE
Small compilation issue under certain circumstances

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#114]
After updating my GIT repo today, I ran into a little issue which can be triggered by calling "scons debug=1".

There, mem.cpp fails to compile with this:

> common/mem/mem.cpp: In function ‘void mem_display_blocks()’:
> common/mem/mem.cpp:316:8: error: ‘GameArg’ was not declared in this scope
>     if (GameArg.DbgShowMemInfo) {
>         ^

The problem seems to be that struct Arg is only defined under the condition that DXX_BUILD_DESCENT_I or DXX_BUILD_DESCENT_II is set. However this doesn't apply to mem.cpp as it is in common/. 
So should I rather proceed to remove the conditions around the Arg struct or would it be better to have the build conditions passed on to the files in common/, too? But I guess that would make those files re-compile two times when building both programs, right? Or may there be a better way to solve this?

**Comment by vLKp** [comment]
This is tied to `memdebug=1`, not `debug=1`.  You can set `debug=1 memdebug=0` to get runtime debug/developer options without getting the memory debugging code.  I usually use that mode, which is why I missed this.  Instance `GameArg` must be inside the game-specific guard because struct `Arg` has members that depend on whether `DXX_BUILD_DESCENT_I` or `DXX_BUILD_DESCENT_II` is set, and letting different object files of the same program see different definitions of struct `Arg` triggers a `-Wodr` warning in LTO mode.  I moved selected game-independent options into struct `CArg` (common Arg) to handle this.

Fixed in [Move DbgShowMemInfo to CArg](https://github.com/dxx-rebirth/dxx-rebirth/commit/fa9f2e626db0079f90c3bfd9d54e13c5001d86ab).
