### ISSUE TITLE
Compilation issue on d2x-rebirth multi.cpp

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#115]
I'm running into this issue now when compiling d2x-rebirth:

> Compiling d2x-rebirth . similar/main/multi.cpp
> similar/main/multi.cpp: In member function ‘void {anonymous}::hoard_resources_type::reset()’:
> similar/main/multi.cpp:4962:53: error: call of overloaded ‘exchange(int&, const std::integral_constant<int, -1>&)’ is ambiguous
>    d_free(GameBitmaps[exchange(bm_idx, invalid_bm_idx)].bm_mdata);
>                                                      ^
> In file included from common/include/u_mem.h:27:0,
>                  from similar/main/multi.cpp:34:
> common/include/compiler-exchange.h:9:18: note: candidate: T1 exchange(T1&, T2&&) [with T1 = int; T2 = const std::integral_constant<int, -1>&]
>  static inline T1 exchange(T1 &a, T2 &&b)
>                   ^
> In file included from /usr/include/c++/5.2.0/tuple:38:0,
>                  from /usr/include/c++/5.2.0/functional:55,
>                  from /usr/include/c++/5.2.0/memory:79,
>                  from common/include/u_mem.h:25,
>                  from similar/main/multi.cpp:34:
> /usr/include/c++/5.2.0/utility:199:5: note: candidate: _Tp std::exchange(_Tp&, _Up&&) [with _Tp = int; _Up = const std::integral_constant<int, -1>&]
>      exchange(_Tp& __obj, _Up&& __new_val)
>      ^
> similar/main/multi.cpp:4965:53: error: call of overloaded ‘exchange(unsigned int&, const std::integral_constant<unsigned int, 4294967295u>&)’ is ambiguous
>    const auto idx = exchange(snd_idx, invalid_snd_idx);
>                                                      ^
> In file included from common/include/u_mem.h:27:0,
>                  from similar/main/multi.cpp:34:
> common/include/compiler-exchange.h:9:18: note: candidate: T1 exchange(T1&, T2&&) [with T1 = unsigned int; T2 = const std::integral_constant<unsigned int, 4294967295u>&]
>  static inline T1 exchange(T1 &a, T2 &&b)
>                   ^
> In file included from /usr/include/c++/5.2.0/tuple:38:0,
>                  from /usr/include/c++/5.2.0/functional:55,
>                  from /usr/include/c++/5.2.0/memory:79,
>                  from common/include/u_mem.h:25,
>                  from similar/main/multi.cpp:34:
> /usr/include/c++/5.2.0/utility:199:5: note: candidate: _Tp std::exchange(_Tp&, _Up&&) [with _Tp = unsigned int; _Up = const std::integral_constant<unsigned int, 4294967295u>&]
>      exchange(_Tp& __obj, _Up&& __new_val)
>      ^
> scons: *** [similar/main/.d2x-rebirth.multi.o] Error 1
> scons: building terminated because of errors.

In case it might be helpful, here's the gcc info:
> gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/lto-wrapper
> Target: x86_64-unknown-linux-gnu
> Configured with: /build/gcc/src/gcc-5.2.0/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --with-default-libstdcxx-abi=gcc4-compatible
> Thread model: posix
> gcc version 5.2.0 (GCC) 

On another note, I was a bit confused today about the commands of d1x and d2x for scons.
> scons d2x=0 debug=1 
pretends that debug is a wrong command. I do have to specify both d1x=* and d2x=* together to make it work (i.e. d1x=1 d2x=0 or vice versa). Is this normal?

**Comment by vLKp** [comment]
I cannot reproduce the error with `exchange`, but I can guess what caused it.  Somehow you have a situation where the compiler supports `std::exchange`, but the configuration code incorrectly determines that it is unsupported, so it activates the emulated `::exchange` in `common/include/compiler-exchange.h`.  When `<memory>` -> `<functional>` -> `<tuple>` -> `<utility>` provides `std::exchange`, both definitions are visible, leading to an ambiguous resolution.  The configuration code should have defined `DXX_HAVE_CXX14_EXCHANGE`, which would prevent defining the emulated `::exchange`.  Could you provide the `sconf.log` for that environment?

I can reproduce the quirk with `d2x=0 debug=1`.  It is a side effect of the special case that setting `d1x=value` implies `d2x=0` if there are no `dxx=` or `d2x=` directives on the line, and likewise for `d2x=` implying `d1x=0`.  Since you used `=0` for your argument, you defined an environment which explicitly does not build Descent II and implicitly does not build Descent I.  With no games to build, no arguments are defined, so there is no `debug` parameter.

I will fix the error message so that scons exits with nothing to do.  Changing the special case not to imply disabling the other game when you explicitly disable the named game is a bit more involved.  I would need to search all the other game definitions to see if any of them were a game definition that is not a request to disable the game.  The workaround is easy: explicitly configure the game you want instead of explicitly disabling the game you do not want (`scons d1x=1 debug=1`).

**Comment by zicodxx** [comment]
Thanks for the explanation with d1x/d2x variables. That clears things up. :)

As for the compiler error, here is the sconf.log. It's pretty log and since Adding ">" in front of a ling becomes quite the work, I put it to pastebin so it doesn't clutter up the whole page: http://pastebin.com/zS4YJ2Rs
I hope you can see what's wrong. This is part of the realm of C++ and the scons-expansion where I am still absolutely clueless

**Comment by vLKp** [comment]
Yes, pastebin is a better choice for a large dump like this.  However, if you need a medium length paste inline, you can wrap it in triple backticks to force it into a block without modifying each line.  You could also modify all the lines automatically: `sed -e 's/^/> /' < sconf.log > paste.txt`.

Regarding the exchange problem, the log says that SCons thinks it failed once before and that there is no reason to re-test it, so it assumed that it would fail again:
```
scons: Configure: DXX-Archive.3: checking for C++14 exchange...
scons: Configure: ".sconf_temp/conftest_34.cpp" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp/conftest_34.cpp <-
  |  |
  |  |#include "compiler-exchange.h"
  |  |
  |  |#undef main       /* avoid -Dmain=SDL_main from libSDL */
  |  |int main(int argc,char**argv){(void)argc;(void)argv;return exchange(argc, 5);}
  |  |
  |
scons: Configure: Building ".sconf_temp/conftest_34.o" failed in a previous run and all its sources are up to date.
scons: Configure: The original builder output was:
  |g++ -c -g -O2 -Wall -Werror=extra -Werror=format-security -Werror=missing-braces -Werror=missing-include-dirs -Werror=unused -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=cast-align -Werror=missing-declarations -Werror=redundant-decls -Werror=vla -funsigned-char -std=gnu++14 -Werror -pthread -Wno-sign-compare -DHAVE_STRUCT_TIMESPEC -DHAVE_STRUCT_TIMEVAL -DOGL -DDEBUG_MEMORY_ALLOCATIONS -DUSE_UDP -DUSE_TRACKER -DDXX_HAVE_CXX14_EXCHANGE -Icommon/include -Icommon/main -I. -I/usr/include/SDL .sconf_temp/conftest_34.cpp -o .sconf_temp/conftest_34.o
  |
scons: Configure: (cached) no
```
Please override the scons cache (or just delete it by `rm .sconsign.dblite`) and try again.  I see that you are using an unqualified name for gcc (`g++` rather than `x86_64-pc-linux-gnu-g++-5.2.0` or similar).  SCons is supposed to detect when the cached results become stale, but if it did not, then perhaps it is remembering when `g++` referred to an older compiler that lacked support for `std::exchange`.

**Comment by zicodxx** [comment]
Removing the .sconsign.dblite file actually worked. Darn! Before posting this issue I did think that something may have gone wrong and I tried to fix it by using "-c". It's absolutely possible that a g++ update may be responsible for that - tho that must have been a bit longer ago ... 
But most important thing: Problem solved. Thanks. :)

**Comment by vLKp** [comment]
Unfortunately, **scons -c** only deletes targets registered by `SConstruct`.  It does not touch files managed by `scons`, such as the cache file.  There is an `scons` option to ignore the cache, but I find deleting it to be easier.  In some cases that may make it try to rebuild files that do not need a rebuild, but `ccache` easily covers that.

**Comment by vLKp** [comment]
> This is part of the realm of C++ and the scons-expansion where I am still absolutely clueless

If it would help, I can write up some documentation on one or both of those topics.  I have some basic comments on some of the older SConf tests, but I stopped writing documentation because I thought no one was reading it.

**Comment by zicodxx** [comment]
Don't stress yourself about this. I think a documentation could help but if it is too time consuming, it's not worth it. After all, I have to learn as well. :)
