### ISSUE TITLE
Time remains paused after failure to save in multiplayer

### ISSUE THREAD

**Issue by vLKp** [dxx-rebirth/dxx-rebirth#117]
I first saw this in 0.57.3, and it still happens today.  Steps to reproduce:

1. Host a multiplayer game.  This problem applies regardless of whether other users are in the game.  However, due to a related problem, its consequences are more severe if other users are in game.
2. Make the save directory unwritable.  This can be done by remounting it read-only or by changing permissions on it.
3. Save a game.  The save will fail.  A dialog will appear suggesting that you might be out of disk space.
4. Dismiss the dialog.
  * Expected result: game resumes.
  * Actual result: game time remains paused.

The reason for this is that the global variable `time_paused` is incremented once when the save starts, decremented once when the game window is "activated" by the dismissal of the dialog, and decremented again when the save fails.  This causes the counter to underflow.  In debug builds, this will trigger an assertion failure.  In release builds, it leaves `time_paused` set to -1.  Processing code treats `time_paused != 0` as a pause condition.  I do not know any way to recover from this situation.

**Comment by zicodxx** [comment]
I suspect this was introduced with the window/event system. I will need to investigate this in a greater detail but I think this should be completely reworked and can possibly be simplified as well by making the timer adjust accordingly to the state of Game_wind.

**Comment by vLKp** [comment]
Yes.  Git blame traces the game window `start_time()` to [Add EVENT_WINDOW_DEACTIVATED; move many game_flush_inputs, start_time and stop_time calls to game_handler...](https://github.com/dxx-rebirth/dxx-rebirth/commit/eb92f445cae76b801269473294ca287eadc912de), but the problem was likely introduced a month later in [...Always start time if it's stopped and the game window is activated](https://github.com/dxx-rebirth/dxx-rebirth/commit/e57602f117f6de79c705d51a4f164867238733d2).  After that commit, activating the game window will always try to `start_time()` if time is paused, but deactivating it does not stop time in multiplayer.  This allows `time_paused` to become unbalanced if the game window is activated in multiplayer and time was stopped by code which expects to restart it.

I would like to see the event system reworked to be based on a dispatch loop, but that will be invasive (and would be much easier with Boost's asio io_service).

**Comment by zicodxx** [comment]
I have to dig deeper in the original sources but I think the timer handling is actually much more complicated than it initially was and intended. The event system may not be the prettiest one but I am happy about everything that doesn't *have* to be be outsourced to another library. The fewer, the better is at least what I always strive for. 

As for the timers I think they simply lack a small and simple ruleset. I don't even think that the timers have or SHOULD in/decrement - even tho it's a good way of making sure they are not called redundantly as it is the case here. For all intends and purposes, on Singleplayer the timers should be active if Game_wind is active and on top while for Multiplayer it needs to be active while Game_wind exists. I think this is all the game actually needs in that regard and making the timer react accordingly I think should be rather easy to implement.... as long as there is no additional cases where the game expects the whole thing work different for some exotic reason... which may be possible... I'm going to check that...

**Comment by vLKp** [comment]
Part of the reason I would like to use a dispatching loop is that the current design has calls to multiplayer processing in odd places, for the purpose of keeping packet flows running while the game is otherwise sleeping.  A general dispatch loop would involve registering a callback for packet activity, registering the next time at which the game should run general processing, and then letting the loop sleep until one of those happens.  Incidentally, when this bug strikes, multiplayer processing is skipped, because that is handled by `GameProcessFrame`, which is skipped when `time_paused`.  That causes all players to drop from the game due to timeout, so the host has very little time to fix the problem with the save directory and save again.

**Comment by zicodxx** [comment]
Yes - having a way of keeping the packet flow intact would certainly be VERY handy. Especially if it would be possible to do that uncoupled from rendering. That is why I added more calls for the network frame inside the game sleeping function while waiting for a new frame. All I could think of was to add this to another thread but I do not think the engine could actually handle that without heavy rewriting. So the current solution is rather ugly and sure, I am open for improvement son the matter, even if it involves heavy testing.

But for the actual problem, having the timers actually being ABLE to stop in Multiplayer is a problem that should be fixed nonetheless. Even tho it is certainly helpful (albeit "accidental") to make sure packets are not sent when they are not supposed being sent (i.e. when the client has left the game or is not quite ready, yet).

**Comment by vLKp** [comment]
zicodxx wrote:
> I have to dig deeper in the original sources

[Provide D2X history](https://github.com/dxx-rebirth/dxx-rebirth/commit/31caaa37eabfce1d770bbae30e6167371eeda6a1) may be helpful if you want to trace into the distant past.  Bradley converted his history to Git, and I mirrored it into the Rebirth repository.  With the setup described in [its README.md](https://github.com/dxx-rebirth/dxx-rebirth/blob/31caaa37eabfce1d770bbae30e6167371eeda6a1/README.md), you can trace from Rebirth history into D2X history automatically.

> The event system may not be the prettiest one but I am happy about everything that doesn't *have* to be be outsourced to another library. The fewer, the better is at least what I always strive for. 

In the abstract, I agree, adding libraries should not be done lightly.  However, delegating work to a high quality library is easier than writing the functionality from scratch, and benefits from the thought and debugging put in by the maintainers of that library.  Libraries are only added to Boost if they [meet specific requirements](http://www.boost.org/development/requirements.html) (including permissive licensing) and [pass a formal review](http://www.boost.org/community/reviews.html).  Boost is portable to all the major platforms, provides a wide variety of utilities, and is widely known among C++ developers.  It is available as a standard package on all the major Linux distributions that I checked.  I believe that it builds unmodified on both Windows and Mac OS X.

For this discussion, I am specifically interested in the header-only library [Boost.Asio](http://www.boost.org/doc/libs/1_59_0/libs/asio/), which provides a dispatch-based approach for timers and sockets.

**Comment by zicodxx** [comment]
Don't get me wrong, I know it's a waste to re-invent the wheel over and over again. In fact that is why I love we have PhysFS and SDL in place. But with SDL we have the luck that it's pretty abstracted and while the jump from SDL1.2 to SDL2 won't be exactly a piece of cake, the SDL code is pretty isolated. PhysFS is a different thing. So if anything drastic ever happens to PhysFS - it becoming obsolete or similar - it will be a long road to fix that. But there we have the redeeming factor, that the PhysFS license allows us to integrate the latest version of the library directly into our code... 
That are the thoughts going through my head when it comes to Boost. I'm sure Boost won't go anywhere but I will wonder on how difficult it will be *if* it needs to be removed for whatever reason. 

But long story short: If you think it's really helpful to have Boost in there - I trust you on that decision. It's definitely true that the network calls are not very streamlined and if that can be fixed with the help of Boost, that would definitely an argument FOR it.

As for the timers and the bug at hand, I will see how that goes. If everything fails, I'll implement a small hack that makes sure the timers are balanced for this specific scenario. I still think the redundancy of these timers can be greatly simplified. And *should* be so that they actually do what they are supposed to.

**Comment by zicodxx** [comment]
Okay i have pushed 1aeb8505ee06a58750dfa1352ca3956cb75f70b8 that fixes the issue. 
Generally I have reordered some of the start/stop calls. There was one occurrence in the demo rewriting code that may have triggered a similar issue. Concerning savegames I have added more calls to make sure that a function that stops time will also resume it before it goes into a subfunction (state_save_all_sub) which in turn will stop the time if needed.
If writing fails, the game will not stop time at all to make sure other players will not time out while host stares at the error message. 

I still think there is a lot that can be done to reduce the amount of the calls. Especially concerning demo writing, most of those calls are obsolete nowadays since writing is buffered and even if the system would be too slow to do that accordingly, I am not sure simply pausing and resuming time is actually very helpful in that regard.

**Comment by vLKp** [comment]
I agree, some of these calls are probably unnecessary.  Since this is all single-threaded, most of them are probably unnecessary.  However, I did not take the time to find which ones are or are not needed.  The ones that are needed are likely only needed because of reentrancy issues.

**Comment by zicodxx** [comment]
Sure if you want, go ahead. Tho can we keep the original code for timers in the code for reference or possible rollbacks? Like just commented out? Oh and also make sure that the calls for reset_time are still in place. These are called much less frequent.

I guess that many of the calls in newdemo.cpp (these that write a few bytes for certain events (newdemo_write_***)) can actually be removed. It seems the only reason they are in place there is to not cause FrameTime to go haywire if an HDD writing operation takes much longer than expected. Those in songs.cpp probably make sense as CD Audio calls sometimes can stall the program for several seconds - at least they did a few years ago.
