### ISSUE TITLE
ADVANCED options in Host menu does not fit 4x3 game window

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#118]
If you show the ADVANCED OPTIONS menu when setting up a multiplayer game in a 4x3 aspect (640x480) and the fonts are properly scaled to this resolution, the menu will be too wide to fit on the screen.

Some options cause this. Most prominently the Kill Goal slider. Maybe this could be moved to a new line?
Also "Spawn Invulnerability" (+ its slider) and "Spawn only at 8 farthest sites" may cause a bit of trouble there but that should be possible to solve by rewording or shorting some words.

**Comment by vLKp** [comment]
There are quite a few advanced options that do not fit in 640x480.  On my system, the difficulty slider is almost entirely hidden in 640x480.  I cannot see the slider thumb, even if I move it all the way to the left.  The other classic sliders are also cut off, although not as badly.

We could get a bit of space back on Kill Goals if the slider crowded a bit more tightly next to the word **Kills**.  We need the gap between the colon and the number of kills because that is the only way to get the menu code to compute the correct width.

Switching to 800x600 helps some, but the affected items still do not fit entirely on screen.  I thought that the fonts were scaled up linearly with resolution, but if so, then these fields should be oversized on all resolutions, not just the small resolutions.

Past releases make everything fit on 640x480, even fields which have not changed content between then and now, but are broken now, such as Difficulty.

**Comment by zicodxx** [comment]
Yeah, the reason why all of them are cur off is because the sliders right-align to the menu window - which is in turn can be oversized by a single text string (and a slider). So a single option being too wide can break a whole menu screen. 

The fonts try to scale in an accurate way if you turn on some texture filtering. If that's off, they only scale by integer values - otherwise the scaling looks very jagged. 

I have always hated how large the fonts are in these menus tho changing them makes it hard to fit in sliders, radio boxes and such since they only exist in these fonts. 

Recently I've seen a Doom port handling sliders pretty well - they always have a fixed size but the slider position will only change every two steps if the amount is twice as high as the possible slider positions. I wonder if I can make this happen, too. Tho this will work best if you have a number representation of the slider value. Which made me think that we might as well put the slider in a new line.

**Comment by zicodxx** [comment]
Fixed in 41983dc05162282e98f78042bb7c3e140bf10c5e
