### ISSUE TITLE
Fix Tracker for Latest Builds

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#127]
I know this isn't directly the Rebirth's team's job, but I thought I'd make a github issue to be sure that this gets done before the release.

**Comment by vLKp** [comment]
This is Matt's responsibility, correct?

**Comment by zicodxx** [comment]
Yes. As of right now, game info packets sends text strings of varying lengths, while the tracker expects fixed strings. This affects:
Netgame.game_name
Netgame.mission_title
Netgame.mission_name

**Comment by Mako88** [comment]
Have either of you been in contact with Matt to see what the current status of the tracker is?

**Comment by vLKp** [comment]
I have not.  @Matt1360: are you available to work on this?

**Comment by Matt1360** [comment]
What has changed?  Is the client code updated?  I can update the current tracker - the new one still needs to be tested... I honestly can't even remember where I ended up with that.

**Comment by vLKp** [comment]
Some internal game-to-game messages were made variable length in December 2014.  Nothing was changed in the explicit tracker protocol, but based on [@zicodxx's comment](https://github.com/dxx-rebirth/dxx-rebirth/issues/127#issuecomment-142256504), it sounds like the tracker sometimes uses game-to-game messages to acquire extra information.

**Comment by Matt1360** [comment]
I can try to look at it this weekend unless you want to release sooner.

**Comment by Mako88** [comment]
@Matt1360 Have you had a chance to check this out yet?

**Comment by Mako88** [comment]
I tested today, and currently the beta builds aren't registering on the tracker at all. I thought they used to be just incorrect information, but now they're simply not there.

**Comment by Matt1360** [comment]
Working on the new one with @zicodxx 

@vLKp - did we ever settle using `libuuid` for player tracking, rather than the less favourable `d_rand()` thing I was using?  It looks like those were some of my last commits.

**Comment by vLKp** [comment]
No, we did not.  If you use a uuid, what will provide it?  Boost has a UUID library, but presently we do not have Boost as a build requirement.  I have no objection to adding such a requirement, but I do not want to import external libraries into the main Rebirth repository.  Instead, they should be listed in `INSTALL.markdown`, an SConf check added, and the user required to install them separately.  I can handle writing up SConf checks for whatever dependencies you want to add.

What is the scope of the uuid?  Is it per-mission (discarded when host aborts game or game ends due to finishing final level), per-process (discarded on program exit), or persistent on the filesystem (never discarded)?  For the latter two, is it scoped to a specific pilot or to the user's $HOME?

I am concerned about trying to add a new tracker implementation right before a release.

**Comment by Matt1360** [comment]
Bringing in Boost for UUID?  That sounds a bit... ridiculous, heh.  If anything, I'd use [`libuuid`](http://linux.die.net/man/3/libuuid), depending on the build environments for other OS targets (I only run Linux environments).  I'm not sure if Windows is still using MinGW, and if `e2fsprogs` is available there (and thus, the `libuuid` stuff).  I think it would be much less intrusive than the entirety of Boost.

The scope is bound to a pilot, used simply to identify a player when talking to the tracker.  It's how I intend to track pilot stats cross-game (think of a history of game stats).

I am equally concerned about the current trackers fragility.  It doesn't matter to me which one gets released.  I don't know what release schedule you have.

**Comment by vLKp** [comment]
Boost is already scheduled for inclusion for some optional features anyway.  So far, those optional features are niche things that would likely be disabled in the main release.  Using Boost.UUID merely moves up the time table and makes it required for more configurations.

Only gcc/clang are supported build environments at the moment, so yes, the Windows targets are built using mingw32.  I doubt e2fsprogs is available on Windows.  I strongly doubt that it is currently part of the Windows build environment.  You could use one of the Microsoft specific UUID facilities for Windows targets.  You could also specify the protocol to be that the tracker generates the UUID for unidentified pilots, then the pilot echoes the UUID back on all subsequent transactions.  That would remove the need for any of the client platforms to generate UUIDs.

Are the pilot UUIDs visible to other clients?  If so, are there any measures to prevent one pilot from spoofing the UUID of another?

**Comment by Matt1360** [comment]
Oh cool, I didn't know Boost was to be included.  That would make it simpler, and more portable, then.  If you'd like to do that in the `matt-tracker` branch, please feel free.  Even simpler would be your suggestion, that the tracker specifies the UUID, a simple `SecureRandom.uuid` will generate them, as it's being written in Ruby.

The UUIDs should not be visible to other clients, however there are a few things that would simplify implementation if the host were to send all the data, instead.  On client join, if they were to send that to the host, it would be easier for the host to aggregate any data, and report it.  The tracker will ping the games for much of the data as well, in which the host would require to know the UUIDs of the clients in order to apply stats to the correct pilots.

In the end, there are no measures to prevent spoofing, if someone knows their UUID, they'd be able to send any data to the tracker that they'd want.  I'm not really sure how concerned we should be about it with this target audience.  Of course, adding some kind of auth-based security would be ideal, but I'm not sure how much effort I'm willing to put into it, to be completely honest.

Adding a "login" of sorts to the tracker would be simple on the rails end (username/password or something), but I don't really have the biggest interest in implementing that client side (I'm sure it's actually pretty simple, from what I remember in previous experiences, but I'm not able to invest the time into extra menu items for that).  In this case, I would return a tracker-generated UUID as an auth token, and the client would still be sending the data on an interval to the tracker as the game progresses.  This flow would probably actually be the simplest, really, if I were to track say, stats on shots (like hit percent on weapons, or something like that).

¯\\_(ツ)_/¯

**Comment by vLKp** [comment]
I am not worried about a pilot spoofing his own stats, since he could do that using a modified game binary or just by having fake opponents who never fight back.  My concern was about the case that Eve loses a game against Alice and retaliates by impersonating Alice on the tracker and sending bad scoring data, such as reporting a high count of team kills, many deaths, etc.  Protecting against that scenario would require that the tracker be able to recognize the real Alice vs. someone who knows Alice's UUID.

We would not necessarily need menu items in the client.  Since the UUID is issued automatically, the authentication token could be issued at the same time the UUID is first assigned.  Users would only need to care about the UUID+token when migrating their profile to a new computer.  However, any design where the host is responsible for reporting statistics on behalf of guests would need to be careful that Eve cannot permanently impersonate any pilot who ever joined a game hosted by Eve.

**Comment by Matt1360** [comment]
Right.  We could consider a challenge/response.  Have the client Bob, request a new token for a given game ID, and send that to the host on Alice.  Alice, as the host will then use that temporary token when reporting to the tracker, which the token is only valid while the game is active.  This is the same way Steam validates users for their games.

I haven't really thought it through, but it should probably work.

**Comment by Mako88** [comment]
Poke @Matt1360 :)

How's it going?

**Comment by vLKp** [comment]
@Matt1360: as I understand it, this is one of the big issues holding the release.  Could you comment on progress?  Is there anything you can share early so that others can assist you?

**Comment by vLKp** [comment]
@Mako88, @zicodxx, since @Matt1360 seems to be unavailable, is it worth considering other approaches to let the release go out without finishing Matt's tracker?  As I see it, we have at least four options:

1. Continue waiting for Matt to finish the tracker.  Since he has not responded to Mako88's April 5 status request or my April 21 status request, it is hard to estimate how long it will take before he is both available and able to finish it.

1. Set aside Matt's tracker and write yet another new tracker.  The exact features of such a tracker are a major influence on how time consuming this would be.

1. Revert the changes which broke the old tracker.  As I understand it, it had an undocumented dependency on one or more of the game's internal control messages and is broken because I changed the layout of those messages.  I fixed up the parsers I had access to, but did not know about the tracker's dependency and do not have the source for the old tracker so that I could fix it.  In practice, these changes may not revert cleanly due to later work, but we could switch the message format back to the layout that the old tracker assumes is used.

1. Release without a working tracker.

We may have two other options:

<ol start="5"><li>Finish Matt's new tracker without his help.  This is only possible if he has already published its code somewhere.</li><br><li>Fix Matt's old tracker for the new message format.  This requires source to the old tracker, which may not be available.</li></ol>

**Comment by Mako88** [comment]
I actually just contacted Arch (the creator/maintainer of the Retro tracker). I had talked to him before about adding support for Rebirth in his tracker, but he didn't seem terribly interested. I asked him if he would be willing to post his code on Github or something, then we could make a pull request to add Rebirth support.

I feel like that would solve multiple issues:
1. Anyone we wanted could maintain the Rebirth side of the tracker through pull requests
2. We could get the release out in a timely fashion, since it would only be dependent on us
3. Retro and Rebirth games would be tracked in a single place (though only show up in their respective games), so that by looking at the tracker someone could see who was playing and just run the port they needed to play.

What do y'all think?

**Comment by zicodxx** [comment]
There is also another possibility:
Merging the "matt-tracker" branch and use the new tracker given that @Matt1360 doesn't shut it off.
From the last tests I ran with that branch in December, it was working perfectly fine.

But the problems remains that we don't have the source of the old nor the new tracker.

Regarding the Retro Tracker: If they are not really interested in supporting Rebirth, then I feel we may end up at the same point as we are right now. I appreciate all help in that regard but if we lack control, it's just too much of an uncertainty.

Which leads me to the ideal case: I should try to host a tracker myself. Problem being that I have only a webserver so I cannot really run any programs on it. So if the tracker isn't PHP based, using SQL or whatnot, I simply can't provide it without renting another server which is more of a money issue than anything else.

So we may as well merge the matt-tracker branch (after testing it still works) and live with it till @Matt1360  shows any sign of life or we figure out something different. If it stops working, we're just at the same spot as we are if we ship without a functional tracker.

**Comment by Matt1360** [comment]
Hi all,

I am buried in work, and am not really seeing the light at the end of the
tunnel, so to speak.

If the new tracker is indeed working (I honestly can't even remember
testing it with Zico), then I'll happily push the code under the
dxx-rebirth group.  I will not release the source of the old tracker mostly
out of shame, but also blatant lack of security... Recall that the original
tracker was hacked together in a weekend.  The new tracker is just a rails
app, for simplicity.  Everything is a web protocol, instead of a terrible
binary protocol that just barely worked, hehe.

Zico, please hit me up sometime this week on hangouts/jabber/whatever, and
I'll try to test this with you again (IPv4 and IPv6 should both work, it's
just web stuff).  If it's just a bug or two I'll try to fix it on the spot.

Kp, how far behind is the matt-tracker branch?  I assume it's quite a ways,
but how does the conflict look?

**Comment by Matt1360** [comment]
I'll also mention that hosting is not a problem for me.  I am the owner of
a (very) small cloud provider.  I'm happy to keep things running for the
Rebirth project.

**Comment by Mako88** [comment]
Awesome @Matt1360!! Is there any way you could publish the code for the new tracker (the rails app), so that in the future if anything happens, we could modify it our self if need be?

**Comment by Matt1360** [comment]
Once it is working I will push it to github under the rebirth group.
Specifically working and released.

It will also allow any group to start their own tracker and hide from
everyone else, which is what was asked a lot in the original for some
reason. I'd like to see more games on the tracker, even if
restricted/closed, to promote activity, but some groups want to stay hidden
I guess.

**Comment by Matt1360** [comment]
@vLKp did we ever sort out what to do for the player `uuid` handling?  I think [libuuid](http://linux.die.net/man/3/libuuid) would be the simplest, but I have no experience outside a Linux environment.

The alternative, would be for the player to ask the tracker for a new UUID, which I can generate on the fly at the tracker end.  It would add client complexity at the benefit of reducing another library required.

Thoughts?

**Comment by vLKp** [comment]
Branch `matt-tracker` is 24 commits ahead and 415 commits behind branch `unification/master`.  There are 18 files changed in `matt-tracker`, of which 5 cannot be automatically resolved by `git merge`.  The conflicts are mostly easy to resolve, although there are numerous conflicts in `net_udp.cpp` caused in large part by renaming `MplTrackerAddr` to `MplTrackerHost`.

Although not a conflict, I noticed a concerning comment added in [Merge remote-tracking branch](../commit/e5bfbb1fe85268a8dc42d2b026525ebb185d3c70):
```c++
		// This ntstring shit is fucking awful
```
This comment was not present in either parent, so it must have been added as part of a dirty merge.  Could you elaborate on this comment?

If third party trackers are practical, the client may be used with more than one tracker.  It would need to isolate data between tracker instances.  You do not want switching to a new tracker to overwrite your UUID from the old tracker, which it might if the new tracker is authoritative on UUIDs and rejects UUIDs it has not issued.

Regarding UUIDs, as best I can recall, all discussion of it happened in this issue.  If we do not have a resolution earlier in this thread, then we do not have a resolution anywhere.  I am fine with letting the tracker issue the UUIDs.

Does this mean that branch `matt-tracker` is ready for a code review?

**Comment by Matt1360** [comment]
Yeah there are probably a ton of conflicts, heh.  I haven't touched this in forever until recently.  I'll merge `master` into `matt-tracker` first.  The `MplTrackerAddr` was renamed to `MplTrackerHost` partly to make it easier for me to find all the references to it while going through it, and partly because `Addr` and `Port` aren't as relevant for a web protocol.  `URL` or similar probably would have made more sense, but whatever.

Yeah, I'm not a fan of the `ntstring` stuff.  I've done some casting to change them to other types for the `jsoncpp` library, and back again, as well as between `std::string` and back for something in the `cURL` code.  There are probably other cases, too.

Having said that, I assume there are reasons for introducing the `ntstring` class, but it's a first for me, and `std::string` would have just been faster.  ¯\_(ツ)_/¯

When this is released, anyone can host their own tracker.  Enough people were bitching at me to let them host a tracker, because they want to keep to themselves for whatever reason, and keeping a game restricted or closed must be too much of a burden.  When a pilot first makes contact with a tracker, if it doesn't have a UUID stored, it will ask whatever tracker it is configured for, for a new UUID, and will store that within its pilot profile.  It will then use that UUID anywhere it goes.

The tracker is completely accepting.  It's not like there's sensitive data, they're just scores, and likely to only be neat to see for historical purposes.  The game info packet will leak the UUIDs for each player, but I'm honestly not really concerned.  If anyone's going to complain about it, I'll just not track or store scores or game data over time, and keep it like the current tracker, where it's just for game listing.  This was just a neat idea that could be easily implemented, since I've currently tracked 128,937 games over the last few years.

I'll make a merge request when the tracker is ready™.

**Comment by vLKp** [comment]
Any name change for `MplTrackerAddr` would provoke merge conflicts since so much work had been done on it after your branch was created.  Among other things, it was moved to a different structure to facilitate the dsx work.

Casting is usually the wrong thing to do for non-numeric types.

`std::string` likely would not be faster and would often be less space efficient.  Some implementations still do not use SSO, and even those that do might not have enough internal storage to handle some of the strings that Rebirth stores.  `ntstring` is a wrapper around `std::array` with some extra utilities, so that the string is always stored internally.  If you have specific suggestions for improving it, please share.

**Comment by Matt1360** [comment]
Yeah, I'll clean up the conflicts.  I'll let you take a look at it when I make the merge request.  It's more of an "I'm trying to get this done quick and don't want to deal with this hassle", because I'm old and grumpy :).

**Comment by Mako88** [comment]
And, just another *bump* for @Matt1360 ;)

**Comment by Mako88** [comment]
Though there is still ongoing work on the new tracker, since it is already working, I'm going to go ahead and close this. 0.60 here we come! :)
