### ISSUE TITLE
Guidebot Invisible in Demos

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#129]
When a demo is recorded the guidebot is invisible when played back.

**Comment by zicodxx** [comment]
Hm actually I cannot directly reproduce this. I can see the Guidebot. However I did notice that certain objects that are close to the edge of the screen seem to disappear seemingly randomly when playing back a demo.

**Comment by zicodxx** [comment]
Actually this seems to affect random objects in random frames during demo playback. 

This is also not related to demo writing. I checked this with the original Descent2.dem and random objects simply fail to render sometimes.

**Comment by zicodxx** [comment]
I investigates a bit further. Unfortunately I could not bisect the issue as it seems to be rather old and I tend to hit commits where the game does not compile or is able to launch a demo. However it seems to be located in render_mine. I made a demo that shows the Guidebot being freed in D2 level 1 and while it was flying around, it occasionally disappeared (http://www.dxx-rebirth.com/tmp/guidebot.dem).

render_mine() states that Highest_object_index is 1 during this where Object 0 should be the player and 1 the Guidebot (Object[1].type = OBJ_ROBOT) but do_render_object() is not called all the time when the Guidebot should be visible. (affects both OpenGL and Software rendering build)

Maybe @vLKp can assist here?

**Comment by vLKp** [comment]
I will try to look at it at some point.  Generally, problems are easier to address if they are reported promptly.  When a feature sits unused for a long time and has no unit tests, bit rot is likely.

**Comment by zicodxx** [comment]
To be frank: I tested demos multiple times - usually with the demos shipped with Descent and Descent 2 and the render bugs are much harder to spot there as in a crowd of robots, you cannot really notice an explosion or debris disappear so easy. It becomes much more obvious when there is only a few objects recorded on screen.

**Comment by zicodxx** [comment]
I think this issue was somewhere introduced along the renderer optimizations. These affect different commits of builds that do not compile very well.
However the 3-pass renderer (which is the questionable part of the code) I once added to deal with clipping sprites didn't account for transparency effects back then (see issue #76). So it would actually make sense to overhaul this in the process. 
I am not sure I can optimize it that well but I could send you my patch for review first, @vLKp.

**Comment by vLKp** [comment]
> To be frank: I tested demos multiple times

After watching one of these, I see how it was missed.  From the initial comments, I thought the disappearance was persistent over many seconds.  I spotted one frame in `descent2.dem` where a Diamond Claw vanishes, then reappears on the next frame.

Incidentally, it looks like no one ever tested this under AddressSanitizer.  Descent records spurious `ND_EVENT_TRIGGER` on every segment transition, whether or not there is a wall present.  On playback, this provokes an invalid array reference the first time the viewer crosses a boundary with no wall.  I will fix this along the way.

**Comment by zicodxx** [comment]
Actually the effect can occur over various different frames (as soon in the linked demo). Older versions of Rebirth (tested with 0.58.1) play this back fine.

**Comment by vLKp** [comment]
I looked at this with the stock Descent 2 demo.  I see where the Diamond Claw drops out and comes back, but according to the debugger output, it was being rendered even in the frame where I cannot see it.

zicodxx wrote:
> These affect different commits of builds that do not compile very well.

Could you elaborate on this?  There have been intermittent build breaks over the years, but as far as I know, there was never a run of commits where the Linux build was completely broken.  There is an issue using gcc-5 with some of the valptridx code, but I fixed that as soon as it was reported.  You would need to use gcc-4.9 or below for commits before [Fix find_escort build with gcc-5](https://github.com/dxx-rebirth/dxx-rebirth/commit/834ae3b8855568245f486b4588e58087e5485530)

**Comment by zicodxx** [comment]
I have a two commits that affect the Rendering of the level and objects
84e3721ef08247517bc20503287785599d8b66a0 and 0b086b1b0d8cb0107c25b1d51bb62290a86a8410
and I assume the problem lies there somewhere. I manually restored the affected code parts of render_mine() with code from 0.58.1 and the demo playback issues vanish. 

However checking out the commits above and trying to compile them fails at multiple points with multiple errors like this: 
>In file included from d1x-rebirth/main/bmread.cpp:42:0:
> common/main/wall.h:181:104: error: no matching function for call to ‘WALL_IS_DOORWAY_sresult(unsigned int)’
>  static const auto WID_TRANSPARENT_WALL    = WALL_IS_DOORWAY_sresult(WID_RENDER_FLAG | WID_RENDPAST_FLAG);   // 0/1/1        transparent wall
                                                                                                        ^
> common/main/wall.h:119:54: note: candidate: template<unsigned int F> constexpr WALL_IS_DOORWAY_sresult_t<F> WALL_IS_DOORWAY_sresult(WALL_IS_DOORWAY_FLAG<F>)
> static inline constexpr WALL_IS_DOORWAY_sresult_t<F> WALL_IS_DOORWAY_sresult(WALL_IS_DOORWAY_FLAG<F>)
                                                      ^
> common/main/wall.h:119:54: note:   template argument deduction/substitution failed:
> common/main/wall.h:181:104: note:   mismatched types ‘WALL_IS_DOORWAY_FLAG<F>’ and ‘unsigned int’
> static const auto WID_TRANSPARENT_WALL    = WALL_IS_DOORWAY_sresult(WID_RENDER_FLAG | WID_RENDPAST_FLAG);   // 0/1/1        transparent wall

This repeats on multiple occasions.

**Comment by vLKp** [comment]
Your compiler is preferring to convert `WID_RENDER_FLAG` to `unsigned`, then bit-or it with `WID_RENDPAST_FLAG`, rather than the expected conversion of using `WALL_IS_DOORWAY_FLAG::operator|` to construct a new `WALL_IS_DOORWAY_FLAG`.  This is probably because the `operator|` in that commit is `constexpr` without `const`.  In C++11, `constexpr` implied `const` on methods, but this is not the case in C++14.  I fixed this in [Fix clang build of fwdwall.h](https://github.com/dxx-rebirth/dxx-rebirth/commit/c1c028362ee5ff0b6262afa7da9a14d40488e6ff) by marking the method as both `constexpr` and `const`.  You could force the compilation to be done in C++11 mode or you could apply an equivalent change (add `const`) to `operator|` in the affected commits.  Add `sconf_cxx14=force-failure` to disable C++14 mode even if your compiler supports it.

> I manually restored the affected code parts of render_mine() with code from 0.58.1 and the demo playback issues vanish.

That is interesting.  You reverted **only** `render_mine`, none of the other functions in render.cpp, correct?  If so, that narrows the search.

**Comment by zicodxx** [comment]
Yes, I did revert render_mine() which fixed the demo playback issue. I was about to restructure that "3-pass rendering" either way cause it's not working as it should since we have transparency effects. Objects behind force fields become invisible and explosion sprites can render robots behind them invisible, too - so the rendering order must be restructured to accommodate to that.
I could maybe rewrite this in style of the old 0.58.1 code but I am not sure if I can do this with your optimizations.

**Comment by vLKp** [comment]
I can write the optimizations again, and they may need to come out differently if you are changing the way the rendering passes are handled.  Reverting `render_mine` to its 0.58.1 form on tip breaks rather badly due to changes that have been made to other code.

Go ahead and make your fixes for the transparency effects.  If that requires removing some optimizations, I will write them again, and hopefully this time the demo playback will remain correct post-optimization.

**Comment by zicodxx** [comment]
Spent the day rewriting the rendering order just to find out that render_mine is not responsible for the playback issue. But with your info on fixing WALL_IS_DOORWAY, I could finally trace the exact commit on which the demo playback issue first occurred: 1bb1c0ad33749d3e8eeb6cc08fc51441730db8dd

I'm not sure why this may cause the issue but if you got an idea, let me hear it. If not, I'll continue looking tomorrow.

**Comment by vLKp** [comment]
I cannot see how that would be the commit that caused this.  It is more likely that it was broken in a nearby preceding commit that you were unable to test due to the break fixed in the commit you named.  Could you post your `git bisect` log?

**Comment by zicodxx** [comment]
You are right actually. Just like with the WALL_IS_DOORWAY patch, I had to use another one to make the demo playback work. 
1bb1c0a thre an exception when trying to play back a demo: 
> terminate called after throwing an instance of 'valbaseptridxutil_t<object, short>::index_range_exception'
>  what():  invalid index used in array subscript
I had to put yet another patch in to make this work: b0b2704961927cd144a3b57dc5081bdadaeac538

When posting my last comment, I completely forgot I still had this still in - despite git checkout warning me that the file was indeed modified...

**Comment by vLKp** [comment]
This should be fixed now.
