### ISSUE TITLE
Team Kill Goal of 100 doesn't work

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#131]
When playing a team game, a kill goal of 100 is reached, but nothing happens.

I did not test non-team games.

I did, however test a kill goal of 5 and 20 and they worked fine, so I would guess it may be a 3-digit problem (however, I didn't have the patience to test a 95 kill goal, etc. game).

**Comment by vLKp** [comment]
Internally, the goal is stored in a range of [0, 20] and multiplied up when it is compared to per-user counts.  Even the smallest integer type would have enough precision to represent this accurately.

**Comment by zicodxx** [comment]
How exactly did you test it?
The team mode should not really matter as the Kill Goal is computed per individual player - not the team. So only if one player of a team reaches the Kill Goal, the reactor should explode. I tested this in a Team game up to 5 and a non-Team Game up to 100 and I got the expected results.

**Comment by Mako88** [comment]
OK, so after some more testing Here's the results.

Firstly, the kill goal should be based on the team, not the individual player(s). (So a kill goal of 5 in a team game means when the team reaches 5, not when an individual reaches 5).

Secondly, at high kill goals, the reactor destruction is not triggered. (We tested 5, 20, 25, and 100. 100 was the only one that didn't work). Also, this was 100 for a single person, since there was only one person on the team (so the individual vs. team thing mentioned above isn't the reason for it not working).

**Comment by Mako88** [comment]
Here's the Retro commit where I believe this was fixed...around line 772 on:

https://github.com/CDarrow/DXX-Retro/commit/ce28160fa4dee5cb8f49396e39cc9f475449b787

**Comment by vLKp** [comment]
> Here's the Retro commit where I believe this was fixed

Unfortunately, that is a huge data dump commit, so it is a bit hard to work through.  Github inserts numerous internal anchors that you can use to make the link point to a specific area of the diff.  Which issue do you think was fixed by that commit?  This ticket now has two problems mentioned:

1. Kill goal of 100 does not work
1. Kill goals in team games are still tracked per-player.

Hunk [CDarrow/DXX-Retro@ce28160#d1/main/multi.c:784](https://github.com/CDarrow/DXX-Retro/commit/ce28160fa4dee5cb8f49396e39cc9f475449b787#diff-ced804c150659e3b5d1be38b7dfb9ba6R784) changes the kill goal processing, but Retro handled the change differently than what I did for Rebirth.  The kill goal is internally tracked as an integer in [0, 10] and scaled up for display/testing.  Retro changed the scale from `5` to `10` (mostly).  I changed the allowable range from [0, 10] to [0, 20], so that players still use a precision of multiples of 5.

Hunk [CDarrow/DXX-Retro@ce28160#d1/main/multi.c:792](https://github.com/CDarrow/DXX-Retro/commit/ce28160fa4dee5cb8f49396e39cc9f475449b787#diff-ced804c150659e3b5d1be38b7dfb9ba6R792) addresses your second point by tracking goals at a team level instead of an individual level.

**Comment by Mako88** [comment]
After further testing, I am now able to trigger a kill goal of 100...this leads me to believe that the only issue is that kill goals are tracked per-player in team games, and in my initial test the per-player score was not 100. (Though, I'm not entirely sure how that would have been possible, since the team that reached the kill goal was a team of 1 person.)

**Comment by vLKp** [comment]
[Use team_kills in team games](https://github.com/dxx-rebirth/dxx-rebirth/commit/4a0a2b7da5e39015aeccc8cbf8098d8173b635c6) should address point 2.  It also adds the team name of the victorious player.

**Comment by Mako88** [comment]
This doesn't seem to be fixed yet. With the latest code (tested in D1), I set a kill goal of 5, had 2 players on red team and 1 on blue team. Player A on red team killed the blue player 4 times, then player B killed him once, but the reactor wasn't triggered. Player B killed him again, giving a total team score of 7 and the reactor still wasn't triggered. Player A then killed him once more, making 5 kills for him personally, and the reactor was triggered.

**Comment by vLKp** [comment]
Correction: the previous commit would address that point, if it did not have the operands backward.  It uses `team_kills` when playing non-team games and personal kills when playing team games.

**Comment by vLKp** [comment]
Please update to [Fix operand ordering for team kills](https://github.com/dxx-rebirth/dxx-rebirth/commit/75104b80f0a7d2acd7ada2bb54607f94e4450494) and try again.

**Comment by Mako88** [comment]
It now seems to be fixed. I will close this issue, and it can be reopened at a later date if an issue is found.
