### ISSUE TITLE
Duplicate Powerups Disappearing

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#139]
Currently this issue has 3 "bugs":

1. maybe_drop_secondary_weapon_egg has a maximum of 3 objects. This should be raised to allow dropping everything that is carried.

2. Items in a 4-pack that is picked up that go over the max carriable limit are not respawned on the map.

3. Bombs are always in packs of 4, so currently if 3 packs are picked up (granting 10, not 12), then used, only 2 packs respawn (spawning 8, instead of 12). However, if 3 packs are picked up, then the ship is destroyed, 3 packs are dropped as expected.

**Comment by zicodxx** [comment]
I think this may be related to the powerup capping. If the initial mine powerup count is not raised along with the duplication setting, the powerups will not all be dropped when a ship explodes nor respawn when they are used up. 
I would actually vote to get completely rid of the powerup capping as cluttering is much less of a problem then loss (which I will fix later).

**Comment by vLKp** [comment]
I specifically guarded against powerup caps influencing duplicates.
```c++
void update_item_state::process_powerup(const vcobjptridx_t o, const powerup_type_t id)
{
	...
	for (uint_fast32_t i = count++; i; --i)
	{
		const auto no = obj_create(OBJ_POWERUP, id, o->segnum, vm_vec_avg(o->pos, Vertices[seg_verts[i % seg_verts.size()]]), &vmd_identity_matrix, o->size, CT_POWERUP, MT_PHYSICS, RT_POWERUP);
		if (no == object_none)
			return;
		m_modified.set(no);
		PowerupCaps.inc_powerup_both(id);
		...
	}
```

**Comment by zicodxx** [comment]
Another possibility may also be the object limit. Especially considering that many 4pack powerups will spawn as singular items after being used up (object count * 4), the game could prevent them from spawning altogether (caught in obj_create). And if I'm not mistaken, respawned concussion missiles will automatically despawn after ~3 minutes as a safeguard for overpopulation (since players always start with them). I could imagine these may be some of the reasons why powerups disappear.

IF this would turn out to be the cause, one way to fix this may be to raise MAX_OBJECTS (which would generally be a good idea I think). Would not be that much of an issue as long as it stays in short range (tho I'm not 100% positive on signed or unsigned). Savegames handle this as well - by simply referring to Highest_object_index. But I think the internal editor should still impose the original object limit for an initial level count.

**Comment by Mako88** [comment]
I think this should be added to 0.60, because it's a serious problem for long games.

**Comment by vLKp** [comment]
> As a game progresses duplicate secondaries slowly disappear.

Can you explain "disappear" in this context?  Are the secondary weapon powerups failing to respawn after they are used or are they disappearing with a despawn animation, like dropped energy, shields, and concussions have always done?

**Comment by Mako88** [comment]
I have never seen them despawn, however I can't verify with 100% accuracy that they don't. It seems that they aren't respawning like they're supposed to.

**Comment by vLKp** [comment]
Assuming they are lost due to a failure to respawn, rather than a failure to drop when players die, then the failure is probably in [`maybe_drop_net_powerup`](https://github.com/dxx-rebirth/dxx-rebirth/blob/b447adcce16b8e7e7af3a29829d3e237568b43e4/similar/main/fireball.cpp#L599).  The [call to](https://github.com/dxx-rebirth/dxx-rebirth/blob/b447adcce16b8e7e7af3a29829d3e237568b43e4/similar/main/fireball.cpp#L604) [PowerupCaps.can_add_powerup](https://github.com/dxx-rebirth/dxx-rebirth/blob/b447adcce16b8e7e7af3a29829d3e237568b43e4/common/main/multi.h#L405) tests whether the powerup can be added.  You could add a `con_printf` before the return to report powerups deleted.

**Comment by Mako88** [comment]
OK, I believe I have found the two bugs that are causing this.

Firstly, the maximum number of smarts and megas dropped, is 3. Even if you have 5, only 3 will be dropped when you die, so they slowly disappear as the game progresses.

The second bug, is when a 4 pack of missiles is picked up and doing so would you put you over the max, the extra missiles simply vanish. So if you have 9 homers, and grab a 4 pack, you will then have 10 homers, but the extra 3 in that pack won't respawn.

**Comment by vLKp** [comment]
Yes, those limits apply even in cooperative games, and as far as I know, they have always been there.  I too found that a bit annoying in some cooperative games on hard campaigns where death is sometimes unavoidable.  We could fix it, but then we would need to add a nostalgia preference for the players who like permanently losing powerups at death.

**Comment by Mako88** [comment]
How about we just only keep it that way for singleplayer and co-op, since it doesn't make sense in any other game mode? Also, now that we have the ability to duplicate weapons, this is happening MUCH more often, since you're often flying around with either the max or close to the max number of secondaries.

Also, this happens with prox bombs...if you pick up three packs and are killed, you drop 3 packs, but if you pick up 3 packs (giving you 10, not 12) then drop them, only 2 packs are respawned.

**Comment by vLKp** [comment]
> Also, this happens with prox bombs...if you pick up three packs and are killed, you drop 3 packs, but if you pick up 3 packs (giving you 10, not 12) then drop them, only 2 packs are respawned. (That bug is in addition to the 4-pack secondary bug I mentioned above).

That is a different problem.  Since proximity bombs and smart mines only come in packs of four, the game gives you `floor(current / 4)` powerups if you have `current` bombs at death.  If your ship had enough capacity to carry all 12, you would have gotten 3 powerups in return.  This is arguably a necessary result, since using `ceiling(current / 4)` would let you slowly fill the level with mines by picking up a powerup, dropping 3 of the 4 bombs, then dying, and getting a bomb powerup at death.

**Comment by Mako88** [comment]
So I guess the prox issue can't be done until host-authoritave powerups is implemented?

**Comment by vLKp** [comment]
That would make it more accurate, but it might do the right thing with the powerup cap code as it is now.  However, powerup caps are only enabled in deathmatch games.

**Comment by Mako88** [comment]
Can these issues be fixed in 0.60, or will they have to wait for host-authoritive powerups in 0.61?

**Comment by vLKp** [comment]
"Fixing" the issue with the game intentionally dropping less than all of your secondaries is easy, but we would need to check that it does not cause bad side effects when someone with an ammo rack + all missiles dies.  Such a player would drop a large number of objects.  If my quick estimate is right, that would require 92 objects for secondaries, not counting primary weapons or accessories.

- 40 Concussion
- 20 Homing
- 20 Proximity Bombs
- 10 Smart Missiles
- 10 Mega Missiles
- 40 Flash Missiles
- 40 Guided Missiles
- 30 Smart Mines
- 20 Mercury Missiles
- 20 Earthshaker Missiles

Of those, Concussion, Homing, Proximity Bombs, Flash, Guided, Smart Mines, and Mercury missiles can be dropped as 4-packs.  Assuming we round down on the smart mines, that means 10 + 5 + 5 + 10 + 10 + 7 + 5 -> 52 objects for 4-packs of the various types.  Then add 10 Smart Missiles, 10 Mega Missiles, and 20 Earthshakers to come to 92 objects.

Fixing the issue that partial pickups of 4-packs lose items is a bit harder.  We could easily hack in a preference that players could set to decline picking up a powerup that would be partially wasted.  I have thought about having that for politeness reasons in cooperative games anyway.  I have not looked at trying to immediately spawn in replacement objects for the wasted extras.

Fixing the rounding on proximity bombs / smart mines is also easy, if you only care about getting back enough that the overall count does not decline.  Fixing it and preventing unbounded growth of powerups would be easier with host authoritative powerups.

**Comment by Mako88** [comment]
How hard is it to raise the max object limit so dropping 92 things wouldn't be an issue?

(Also, that is an absolute worse case scenario...it would never actually happen in an actual game).

**Comment by vLKp** [comment]
The games currently cannot drop more than `MAX_NET_CREATE_OBJECTS` at once, which is [20 for Descent 1](https://github.com/dxx-rebirth/dxx-rebirth/blob/75104b80f0a7d2acd7ada2bb54607f94e4450494/common/main/multi.h#L107) and [40 for Descent 2](https://github.com/dxx-rebirth/dxx-rebirth/blob/75104b80f0a7d2acd7ada2bb54607f94e4450494/common/main/multi.h#L110).  It looks like you need 2 bytes per object for the drop message.  The entire message must fit in `multibuf`, which is `MAX_MULTI_MESSAGE_LEN` bytes long.  Currently, it is [90 for Descent 1](https://github.com/dxx-rebirth/dxx-rebirth/blob/75104b80f0a7d2acd7ada2bb54607f94e4450494/common/main/multi.h#L108) and [120 for Descent 2](https://github.com/dxx-rebirth/dxx-rebirth/blob/75104b80f0a7d2acd7ada2bb54607f94e4450494/common/main/multi.h#L111).

Also, the game has a hard limit of `MAX_OBJECTS` objects (covering players, robots, powerups, in-flight weapons, etc.), which is currently 350 for both games.  A player who came in fully loaded and died, spewing 92 secondary weapon powerups, would use up a large chunk of the total object limit.

I have never looked at raising these limits, so I am not sure what else might break if these limits were raised.

**Comment by zicodxx** [comment]
MAX_OBJECTS can be raised as long as they stay in range of Highest_objects_index (I tested that a while back but never committed this as I wanted to do this along a higher segment limit which significantly decreased the game performance). In a Singleplayer game, this can of course break a savegame being loaded in older builds that support a lower object limit. 

However simply raising MAX_OBJECTS would also allow to load levels that have a higher initial object limit and if levels like this are made, the problem would return. So this variable should be split up - making sure that the initial level object count is at 350 max while allowing the limit to be risen only during gameplay.

**Comment by vLKp** [comment]
Since we can raise the runtime `MAX_OBJECTS` almost to `USHRT_MAX` (less the magic values `-1` for none and `-2` for a guidebot error code), I would rather see the value split and both raised.  However, raising the limit does have secondary effects that would need to be considered.  Among other things, every `object` has a `laser_info` and every `laser_info` has a `std::bitset<MAX_OBJECTS> hitobj_list` for fusion cannon hit processing.  Using`std::bitset`  is more compact than the `ubyte hitobj_list[MAX_OBJECTS]` that was used in past releases, where every object cost `MAX_OBJECTS` bytes for tracking.  Now it costs only `MAX_OBJECTS` bits, but an object limit of 8192 would mean every object spends 1024 bytes on its `hitobj_list`, up from the current 44 (when `unsigned long` is 32 bits) or 48 (when `unsigned long` is 64 bits) bytes.  Currently, `hitobj_list` storage is effectively free since it is in a union with a larger structure (`ai_static`).  If not for that overlap, we would spend `350 * 48 = 16800` bytes on `hitobj_list` storage.  If we raise `MAX_OBJECTS` to 8192, then we would spend `1024 * 8192 = 8388608 = 8Mb` on `hitobj_list`.  Keeping a `hitobj_list` per `object` costs a total of `MAX_OBJECTS * MAX_OBJECTS / 8` bytes.

On x86_64-pc-linux-gnu, sizeof(ai_static) is 232 bytes and sizeof(laser_info) with `MAX_OBJECTS = 350` is 80 bytes.  We can grow `hitobj_list` to 200 bytes before `laser_info` exceeds `ai_static`.  `200 bytes = MAX_OBJECTS / 8` -> `1600 bits = MAX_OBJECTS` -> `MAX_OBJECTS = 1600`.  With 1600 objects, the total cost of all `hitobj_list` is `1600 * 1600 / 8` -> `320000` -> ~312Kb.

**Comment by zicodxx** [comment]
hitobj_list could actually be reduced to a stacking list - if we wanna be fancy. Soon as a persistent weapons stops being in touch with an object, it could forget about it, as the projectile is fast enough so the object would never be encountered again and if it does, it may as well do a second time damage to it. 

Of course transferring objects between games would also be a thing to consider, yes. But most of the objects that are breaking the limits would be explosions, weapon fire, debris and such. Powerups, polygon objects, etc could still follow the original object limit or just a slightly raised one. 

That may still cause some duplicated powerups to disappear but I don't see this as less of a problem than causing potential timeouts during player joining.

**Comment by Mako88** [comment]
So long term we want to raise the object limits and add host-authoratitve powerups. For the short-term (before the release), could we just allow dropping of all 5 smart missiles (and the other secondaries affected) instead of just 3 in all modes except singleplayer and co-op? That would take care of the majority of the issue, and then we can do the rest in the next release.

**Comment by zicodxx** [comment]
I committed a055aecee56b1f8de3492c402aa3f51fb7208db0 which removes the "count-to-3" cap in maybe_drop_secondary_weapon_egg for all secondaries but instead limit it to bombs - which seems to be the intended behavior judging from the comment in drop_player_eggs. I also raised the limit to 5 for Descent 2 due to the addition of the Ammo Rack.
But all in all I am not sure if this cap is ever needed. Since the bomb count is divided by 4 and integers should round down at all times, it should not be possible to drop more bomb packets than intended. So either I am overseeing something or this cap is absolutely useless (and harmless as well).

**Comment by vLKp** [comment]
As I commented on the commit (and [here on Oct 4th](#issuecomment-145395364)), the maximum smart mines with ammo rack is `15 * 2 = 30`.  Therefore, maximum powerups to drop a nearly full load of smart mines would be `int(30 / 4) = int(7.5) = 7`.  Dropping enough to restore exactly the right number is impossible, since the maximum is not an integer multiple of 4.

As for caps in general, as I explained [later on Oct 4th](#issuecomment-145399856), the game is hard capped on how many objects it can create at player death and this limit is far too low for a fully loaded player to drop all his items.  Removing the count-to-3 cap means that a heavily armed player will lose **all** of some weapon types to the cap.  On the positive side, for the most part, lower quality weapons are later in the drop list, so a fully armed player will tend to spew mostly high end weapons.  However, mercury missiles are the last secondary, and extra vulcan ammo is after mercury missiles.  Thus, a player will likely lose some or all of these if he hits the object drop cap.  I looked at arranging for a round-robin drop scheme to circumvent this, but apparently never published it.

**Comment by zicodxx** [comment]
Actually I thought the limit of Smart bombs was the same as Proximity. Should have double-checked. Oh well, I'll fix that later.

Also yes, of course you will lose a bit unless your proxies are dividable by 4. Pointed that out above. 

Also yes, I did not plan on fixing the max items a player can drop. As pointed out above, the comment in drop_player_eggs reads as if the 3-count limit is ONLY intended for bombs. 

As you said, it's still possible to lose powerups but after 0.60 is release, I plan on making player inventories shared. This will work around the MULTI_MESSAGE_LEN limitation and make players able to drop everything they have.

**Comment by Mako88** [comment]
So, this has been fixed and can be closed right? :)

**Comment by Mako88** [comment]
I tested it, and yes, it's fixed. Closing.
