### ISSUE TITLE
Add Gap Between Name List and HUD Items in Fullscreen

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#155]
In the fullscreen cockpit mode it would be nice if there was a single-line space between the list of names and the weapons/energy shield text.

**Comment by vLKp** [comment]
Shields are 6 lines up from the bottom of the screen.  Energy is 5 lines up from the bottom.  Names are positioned separately, and should not overlap.  However, they might come up against the other text.  Since the positions are computed independently, the easy choices are to move the energy/shields text up one line unconditionally or to reduce the number of names that can be shown.

**Comment by Mako88** [comment]
I say move the energy/shield up one line to keep the text from getting close to it.

**Comment by vLKp** [comment]
[Move shields/energy up another line in large games](https://github.com/dxx-rebirth/dxx-rebirth/commit/66cbd4ae0a6b58fb1a7a34c570064b4246c3ef15) moves the energy and shield lines up by one when `N_players` is greater than 3.
