### ISSUE TITLE
Non-Solid Objects

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#157]
In the latest beta (11/8/2015) your ship can pass through robots. Also most shots will travel right through them. In addition, hostages are impossible to pick up. This was tested in D1 First Strike level 1. This is a regression since 0.58.1

**Comment by vLKp** [comment]
Confirmed.  First broken in [Condense collision table](https://github.com/dxx-rebirth/dxx-rebirth/commit/44c4eb9dc3e647f51d9b7ef359310ccacd0fbfaa).  Fixed in [Move collide_two_objects swap back to top](https://github.com/dxx-rebirth/dxx-rebirth/commit/93888b4e372fc974862759db41d8f1865b234f04).  I tested the main change in `Condense collision table`, but then I reordered the code before committing and did not retest.

**Comment by Mako88** [comment]
Fixed in the latest beta build. Closing.
