### ISSUE TITLE
Weapon Remains Selected After Respawn

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#158]
When a player is killed (in multiplayer...singleplayer not tested) and respawns, the weapon he died with is still selected. With energy weapons he is able to fire a single shot. With projectile weapons, there is no ammo, so the it changes as soon as the player tries to fire.

**Comment by vLKp** [comment]
Confirmed, but the problem description is not quite right.  The weapon does not remain selected across respawn.  Rather, it is automatically reselected after respawn because the delayed autoselect is still set to the pre-death weapon and `delayed_autoselect` does not check whether the player has the weapon before making it active.
