### ISSUE TITLE
Demo content can select non-demo missiles; bogus graphic shown for non-demo missiles

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#165]
I've discovered a strange graphical glitch which happens when you run out of missiles in d2x (I did not test with d1x):

![no-missiles-glitch](https://cloud.githubusercontent.com/assets/1835702/11252154/e777eb74-8e34-11e5-84ad-2ebac2c4447c.jpg)

I can reproduce this issue only with the demo game content (maybe because of the low-res cockpit?), with the hog files from the retail version I does not occur. It is also necessary to set the right view to missile info, it does not appear when the right view is set to rear view or guidbot's PoV. 

Git-bisect resulted in:

a0a5aaef8df93c29703da779ebdc1aa41ce25d77 is the first bad commit
commit a0a5aaef8df93c29703da779ebdc1aa41ce25d77
Author: Kp <kp@valhallalegends.com>
Date:   Fri Nov 6 03:51:10 2015 +0000

    Fix bogus "You have no" selecting missiles
    
    Fixes: e130ea7b365b8141d0e5a33fb1bffac2e2d255ea ("Remove unnecessary secondary_weapon_flags")

**Comment by derhass** [comment]
OK, the very same commit also has another effect besides the grapichal issue: If one fired all missiles, aborts game, and starts a  completely new game from the main menu, one starts with no missiles at all. This again happens only with the demo content.

**Comment by vLKp** [comment]
Confirmed for the selection of non-demo missiles and for the graphical glitch when such a missile is shown.  I cannot reproduce the result of:

> one starts with no missiles at all.

The graphical glitch is because the demo content lacks graphics for the top end secondaries, so the game uses the fallback "bogus" bitmap, which is defined as a light background with a red X.  The ability to select top end secondaries is a bug.  Demo content has no definitions for them, so their `ammo_usage` (as well as most other fields) is set to 0.  You always have at least 0 missiles, so the current check for whether you have "enough" missiles always passes for high end secondaries with demo content.  When using full version content, `ammo_usage` is non-zero, which prevents selecting the missile when you have none of them.  Full version content also has proper graphics for those missiles, so if you did manage to select it, the game would not resort to the bogus bitmap.
