### ISSUE TITLE
Object BUG spew in Demo playback

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#167]
I noticed that during my last fix for demo playback, the game started to spew out a lot of object related bug information which is related to 9f26e2211e71036a155aad9a7ca3ff92d7b49c3c.
This is probably more of an issue with how the demos handle objects. Tho the reason why I am putting up this question is because I am not sure how serious this is and if it may eventually break things and if the demo playback needs to be fixed before this happens.

Coincidentally I also noticed that in some demos, the game displays the player shields as 0. This may be related to the fact that the shield recording behavior was changed in the past at some point so it would only record if there was an actual change in the shields (and at the beginning of the recording as the comparison variable is initialized with -1) - instead of recording it every frame, wasting space in the progress.

**Comment by vLKp** [comment]
This is just reporting a bug which has always been there.  Objects have a type (fireball, robot, player, etc.) and an id (the meaning of which depends on the type).  The new diagnostic is for cases where the id is read/treated as an id for type A, but is actually an id of type B.  In this case, the demo is testing for id `VCLIP_MORPHING_ROBOT` (value `10`), but applies the test even to things which are not fireballs.  Thus, if called for a robot of type supervisor2 (which has robot id 10), a class 2 drone attack (which has weapon id 10 (`CLS2_DRONE_LASER`)), or a lone concussion missile (which has powerup type 10 (`POW_MISSILE_1`)), the first clause of the if test will be true and the other clauses will be checked.  Hopefully, those clauses prevent the if block from running on the improper object types.  If the other clauses also evaluated to true, then the demo would improperly update the orientation of something which is not a `VCLIP_MORPHING_ROBOT`.  The fix is to add a new first clause of `obj->type == OBJ_FIREBALL`:

```diff
@@ -532,7 +532,7 @@ static void nd_read_shortpos(const vobjptr_t obj)
 	nd_read_short(&(sp.velz));
 
 	my_extract_shortpos(obj, &sp);
-	if (get_fireball_id(obj) == VCLIP_MORPHING_ROBOT && render_type == RT_FIREBALL && obj->control_type == CT_EXPLOSION)
+	if (obj->type == OBJ_FIREBALL && get_fireball_id(obj) == VCLIP_MORPHING_ROBOT && render_type == RT_FIREBALL && obj->control_type == CT_EXPLOSION)
 		extract_orient_from_segment(&obj->orient, vcsegptr(obj->segnum));
 
 }
```

I saw the shields at 0 bug when I first moved player shields to `struct object`, but I thought I fixed all cases of that before I published the change.  I do not recall writing the caching change you describe.  Does this problem affect all demos or only demos recorded with recent code?  Do any of the affected demos show the bug when viewed with the most recent release?

**Comment by zicodxx** [comment]
I currently have access to demos only recorded with older commits and older versions (0.57.3 or 0.58.1) and it seems kinda random. Some demos start with 100 shields, some start with 0 - even if recording started at the beginning of the level. I can upload them if it helps you. However a safe way to reproduce it seems to trigger a level change. That always works for me as the HUD reports 0 shields soon as I appear in the new level.

**Comment by zicodxx** [comment]
Okay as far as I see, the BUG messages seem to have gone with the most recent commits. As for the shield bug, I will open a new issue so we can keep this separated.
