### ISSUE TITLE
Non-cockpit HUD score_added not properly aligned with score

### ISSUE THREAD

**Issue by roncli** [dxx-rebirth/dxx-rebirth#175]
Cause is here:

https://github.com/dxx-rebirth/dxx-rebirth/blob/unification/master/similar/main/gauges.cpp#L743

Either someone copied and pasted the FSPACX(12) from the wrong place, or they fat-fingered the 1 into a 12. :)

Replace FSPACX(12) with FSPACX(1) and this will fix the bug.

**Comment by vLKp** [comment]
This line sees very little activity.  I touched it to [add some extra parameters](/dxx-rebirth/dxx-rebirth/commit/50f672ba34c765caf87d3f74c35757c2c3c31d53#diff-0d2b598e75d717b25fdb6f0dedb912acL705), but the `FSPACX(12)` was already there.  It was there in Jan 2013 when [zico applied my patch to switch from `gr_printf` to `gr_string`](/dxx-rebirth/dxx-rebirth/commit/b5b72b3ae32a7105e5645fdbcbe802893b8b5da2#diff-8c17c94f452663da9a206f0211499be5L788).  It [changed to `FSPACX(12)` from `FONTSCALE_X(12)`](/dxx-rebirth/dxx-rebirth/commit/8eb5c965d2d10fa7b447c3c0b3450225755271b9#diff-8c17c94f452663da9a206f0211499be5L431) (link warning: very large diff) in Feb 2008.

**Comment by roncli** [comment]
No doubt it's been there for a long time.  I first noticed it today when working on adding an in-game timer.  Changed it from 12 to 1, and it was aligned properly.

**Comment by vLKp** [comment]
What kind of data are you trying to show with your in-game timer?  We already have code to display how long the player has been on the level.

**Comment by roncli** [comment]
I've just been playing with a prototype, but haven't had time to flesh it out and test it thoroughly.  I'll have to check out the latest implementation when I upgrade my tool chain for the latest code.  But, that is merely describing how I found the bug with the alignment, since the code is related.

**Comment by vLKp** [comment]
After cycling HUD modes, I think the use of `12` was to avoid overlapping the front strut of the cockpit graphic.  I changed to a ternary expression that yields `1` for full screen mode and `12` for cockpit graphic mode.

**Comment by roncli** [comment]
Didn't notice that.  Is it different for different resolutions?  I'm at 1920x1080.

**Comment by zicodxx** [comment]
I think vLKp is right about that. This is present in the original game. The slight difference there is that the score (and life display) have a 3 pixel offset from the top of the screen, where D*X just has 1. This way, the score-added display is closer to the cockpit frame but gets enough space (about 3 pixels, thanks to the 12 pixel offset) to not overlap it. I may restore the original Y offset or slightly reduce the X offset to get the score-added closer to the cockpit frame.

I guess this is just a question of aesthetics/looks, trying to imply the score is part of the ships HUD (while it makes no sense in-universe).

Interestingly, the cockpit is stretched independently to the aspect while FSPACX should generally respect the proper scaling of the fonts (which is done by the Y resolution). So, technically, in Widescreen the score added comes closer to the cockpit frame while it never overlaps since it's closer to the top of the screen.

**Comment by vLKp** [comment]
I tried to keep the score from overlapping the strut because I thought it might be harder to read with the strut graphic overlapping it.

**Comment by vLKp** [comment]
Any objections to closing this issue as fixed?

**Comment by roncli** [comment]
None here.
