### ISSUE TITLE
.ini parsing doesn't allow inline comments with paramaters

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#180]
With the new .ini parsing, you can't have "-maxfps 30  ;a comment". You should be able to, so that people don't have to remove the comment lines already in the .ini file when enabling an option.

**Comment by vLKp** [comment]
That should already work.  Either way, ini parsing is an area (one of many) that needs a rework, but has been low priority.  I think it is backwards that arguments from the .ini file are processed **after** the command line, since it means that the .ini overrides command line arguments.  If you have `-pilot a` in your .ini file, specifying `-pilot b` on the command line has no effect.

**Comment by Mako88** [comment]
I agree, command-line should take precedence. I think this should be added to the 0.60 milestone, since people will see errors when trying to start the game after just removing the semi-colon in front of an argument with a parameter.

**Comment by Mako88** [comment]
Closing since #194 has been added.
