### ISSUE TITLE
6e1a1873ccf64e0b4f203c9a78c3e76d3a764b9f breaks D1 boss behavior

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#181]
As described in the title, the commit 6e1a1873ccf64e0b4f203c9a78c3e76d3a764b9f (found via git bisect and compared with the revision before it) breaks how the final Descent 1 boss (level 27) is supposed to behave. Usually it's meant to sit stationary, rotate towards the player (or the believed player position) and teleport around. This commit however enables the boss to move around. 

I am opening this report to ask why this was changed and how we can possibly fix this since AIM_HIDE and AIM_STILL are not defined anymore.

Interestingly, this also breaks the behavior of the boss when emulated in D2X.

**Comment by vLKp** [comment]
[Fix D1 behavior/mode confusion](/dxx-rebirth/dxx-rebirth/commit/6e1a1873ccf64e0b4f203c9a78c3e76d3a764b9f) should not break the emulated mode since the identified commit is inside a `#ifdef DXX_BUILD_DESCENT_I` block, so the changed code does not affect Descent 2 at all.

It was changed because the previous code was wrong.  It compared a behavior to a mode, but behaviors and modes use different numbers.  AIB_STILL is 0x80; AIM_STILL is 0.  AIB_HIDE is 0x82; AIM_HIDE is 5.  I suspect the boss has a behavior of `AIB_STILL`.  Prior to this commit, that value was not handled, so this `switch` was a no-op.  Now, it exhibits the behavior the original author intended: it changes the mode to `AIM_CHASE_OBJECT`.  Unfortunately, the original author of this code and the person who set the boss to behavior `AIB_STILL` disagreed on what that meant.  Now that the bug is fixed, the boss enters chase mode, which is not what players expect, even though it is what the author of this switch meant to do.  The fix is probably to change it so that behavior `AIB_STILL` does not change the mode.  This restores the practical effect of the original author's bug, without breaking the type enforcement changes that required this commit.

**Comment by zicodxx** [comment]
Okay I disabled the mode switch for this specific case (1e60e7f31ab0360a6bc3ddb0155ff9ed69befe13) and it does indeed restore the original behavior. I have made a few comparisons to the DOS build (using DOSBox) to see if other robots changed into an unwanted behavior but it seems to work as it was before. 
I left the line in however (just commented out) for future references.
