### ISSUE TITLE
Grant weapons at spawn not based on autoselect list

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#184]
Currently when you spawn and have weapons granted, it auto-selects the weapon that was last selected in a previous game, NOT the weapon that has highest priority on the autoselect list.

**Comment by zicodxx** [comment]
To be honest, I am not 100% certain how I could solve this. The game remembers your last weapon so you could go from one level to another, keeping the one selected you has before exiting the old level. This should be what currently toggles the unwanted behavior. 
I am not entirely sure how to fix that without messing up the intended behavior of keeping your weapon selection between levels. The order in which all this stuff happens is important and maybe I am missing something.

**Comment by vLKp** [comment]
I think @Mako88's concern is that it remembers the weapon even if you leave the game and enter a new one.  He wants it to reset in that case.  The game likely had an accidental reset normally, by way of entering the new game without any extra weapons and thus being forced to lasers.  Now you can enter the game with additional weapons, so any accidental reset is less likely to apply.

If these were tracked in a structure scoped to the game, reinitialization would be automatic.  Unfortunately, they are tracked in global variables, so they can persist even when they should not.

**Comment by zicodxx** [comment]
I have pushed 5c72b57b139ef2d8c921382ad78f569ed099abe6 which will properly re-initialize the weapons on a new game. This will default to the Laser/Conc weapon setup for each new game started.

I _guess_ some players would like to have the highest autoselect priority right from the get go when they launch a game with granted weapons but again, I do not know how to do that without keeping the selected weapon on loading a savegame or transition between levels.

**Comment by vLKp** [comment]
Responding to the original report:

On investigation of all writes to `Primary_weapon`, it does **both**.  First, the code I added for handling grants auto-selects the best weapon.  However, it does so by directly writing to `Primary_weapon`, since none of the other logic in `select_primary_weapon` was needed.  Then, before the user can do anything, the delayed autoselect calls `select_primary_weapon` to switch to `Delayed_primary`, if different from `Primary_weapon`.  Grants were added before the delayed autoselect, so grants were correct when they were written, and they only updated `Primary_weapon` since `Delayed_primary` did not exist.  Mako88's original implementation of delayed autoselect assigned a magic value for `Delayed_primary` to indicate that it should not be used.  When I pushed the final version, I changed this to use `Delayed_primary == Primary_weapon` to indicate that no change was pending.  Under this model, but not his, the value of `Delayed_primary` must always be updated when `Primary_weapon` is updated.  Failure to do so causes bugs like this one, where an old delayed value is mistakenly treated as current and changes the user's selection when not wanted.  We would probably be safer if `Primary_weapon` was a private member of a class, so that direct writes were disallowed.

In theory, his version was also wrong with respect to granted weapons, but in a much more subtle way that most people would not notice.  Under his implementation of delayed autoselect, the wrong result would only occur if someone requested a delayed autoselect, then died or moved to a new game before that autoselect was processed.  Under my model, the wrong result always occurs, even if you never used the delayed autoselect feature.

I have a patch that supersedes zico's change and restores the result requested in the opening comment of this ticket.  Grants worked this way prior to the introduction of the delayed autoselect.  Switching the grant to update the delayed autoselect value will make them work that way again, by discarding any unprocessed delayed autoselect when a new ship is created.
