### ISSUE TITLE
Clients don't carry weapons through to next level (and sometimes lose laser level 1)

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#187]
Tested in co-op. The host keeps his weapons, but the clients lose them, sometimes not even spawning with laser level 1. After the client dies, he then has laser level 1 again (or more if "grant weapons at spawn" was selected).

**Comment by vLKp** [comment]
What is the first bad commit?

**Comment by zicodxx** [comment]
After bisecting I realize it's a bug added over multiple commits starting from Nov 7th 2015.
From 2e28a491f29383f24ecea4ecba0a8de43b2f20f2 to 6b353cb9ac53ee940e93f2975f10ad7c37f7e2e8 player flags have been moved to object struct. 
And that seems to cause the reset over level transitions (for laser levels, primary weapon flags, ammo, secondaries, shields, energy, etc - depending on the commit).
Now I am not yet sure why the host object isn't reset not where it happens exactly but I'll keep investigating.

**Comment by vLKp** [comment]
[Poison objects on level load](/dxx-rebirth/dxx-rebirth/commit/3d246427e1008e28c837c571852381e8511f4523) addressed a similar problem, but only for player 0.  That is why this only affects guests.  I could easily fix this if we can assume that players retain their object number over multiple levels, but as zico says, we cannot assume that.

`gameseq_init_network_players`, which runs after the old data has been overwritten, rereads the entire object table to refresh `Players[...].objnum` based on the new objects.  Since it overwrites the object `->id` field, we cannot scan for an object with a matching id number.  Instead, we need to either duplicate the filter logic or defer the copy-back phase until after `gameseq_init_network_players` runs.

Storing players as a type of object is convenient for many things, but it has some unfortunate side effects when mixed with the aggressive object overwrite at level load and the lack of rules for which object slots will become players.

**Comment by vLKp** [comment]
[Widen scope of player_info preservation](/dxx-rebirth/dxx-rebirth/commit/c1503d0e0f411ad896c464c36f793976d77f85a2) should fix this.  I can only test it in single player though.  For now, it only saves the local player's state.  When the host becomes more authoritative, it will need to save all players' states.

**Comment by zicodxx** [comment]
I tested it and it seems to properly fix the bug. :)
I also made sure that shields and energy < 100 will be put up to 100 again and that works, too.
