### ISSUE TITLE
Descent2.dem force field graphical glitch

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#191]
Near the end of the playback of descent2.dem, the force field around the reactor is supposed to disappear. But it seems this is not fully the case as only the outward wall face is updated to disappear while the inward walls still show the force field. As seen here: http://www.dxx-rebirth.com/tmp/ff.jpg

I was initially posting this in #177 as I thought both bugs may be connected but in hindsight I can't say for sure.

**Comment by vLKp** [comment]
The bugs are not connected.  This bug appears in the demo, but is also visible in regular play, because the bug is in general code, not demo-specific code.  [Pass trigger &](/dxx-rebirth/dxx-rebirth/commit/0635dbf10861429044e6c2753b300621ab12f0b0) caused this bug [by allowing `wall1` to remain `nullptr` when `wall0.type != new_wall_type`](/dxx-rebirth/dxx-rebirth/commit/0635dbf10861429044e6c2753b300621ab12f0b0#diff-9d3eca8b28bd0b10eeb6cd8912a2b5a4R211).  In practice, it would be very rare for the `wall0` type to match `new_wall_type`, so this conditional bug almost always happens.  [Always check for valid cside for wall1](/dxx-rebirth/dxx-rebirth/commit/6b5bf5a549b96765c75d50cd642f628031a32ab5) fixes this for me.
