### ISSUE TITLE
Compile Error: Redefinition of 'struct timespec'

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#208]
I forced WINVER to 0x0400 via CPPFLAGS.

Also, on compiling I'm seeing the full output of each g++ command...is that something you changed, or is that something changed in my environment?

Compile Error:
```
d2x-rebirth/libmve/mveplay.cpp:116:8: error: redefinition of 'struct timespec'
 struct timespec
        ^
In file included from d2x-rebirth/libmve/mveplay.cpp:11:0:
c:\mingw\include\time.h:102:8: error: previous definition of 'struct timespec'
 struct timespec
        ^
scons: *** [d2x-rebirth/libmve/mveplay.o] Error 1
scons: building terminated because of errors.
```

**Comment by vLKp** [comment]
I have not made any recent changes to verbosity settings, nor to the `timespec` emulation.  You will get that error if your system headers define `struct timespec` and your preprocessor macros, after includes, satisfy
```
#ifndef _TIMESPEC_DEFINED
#if !defined(HAVE_STRUCT_TIMESPEC) || !HAVE_STRUCT_TIMESPEC
```

SConstruct defines `HAVE_STRUCT_TIMESPEC` for Linux and Darwin targets, but not for Windows.  Presumably this is because Windows has historically lacked a `struct timespec`.  I do not know why there is a test for `_TIMESPEC_DEFINED`.  It is not defined by Rebirth, nor by any system headers in my environment.

**Comment by Mako88** [comment]
9be68f4e9903221f88f425c23a0593d805295a1e seems to have fixed this. Closing.
