### ISSUE TITLE
-nostickykeys No Longer Works

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#211]
ThugsRook reported this on the forums and I verified. In the latest commit the -nostickykeys parameter no longer works. I don't know at what point it stopped working though.

**Comment by vLKp** [comment]
Please define "no longer works."  Do you mean that it is not accepted as a valid command line option, that it is accepted and does nothing, that it is accepted and does the wrong thing, or some other problem?

**Comment by Mako88** [comment]
It's accepted but does nothing. For example, set caps lock to flare. It will only shoot a flare every second time you hit the key.

**Comment by vLKp** [comment]
I cannot reproduce the reported result.  For me, when using `-nostickykeys` and binding CAPSLK as a key for firing flares, every press of the Caps Lock key fires a flare.

**Comment by Mako88** [comment]
This was tested on Windows 10. Zico mentioned on the forums that it isn't reproducible on Linux, only on Windows.

**Comment by vLKp** [comment]
That is unfortunate.  I cannot help you if the problem is only visible on Windows.  That would have been useful to include in this ticket, though.

Is it reproducible on Windows 7?  Is the problem absent when using 0.58.1 on Windows 10?

**Comment by zicodxx** [comment]
@Mako88 could you give this another test using the commit: 
https://github.com/dxx-rebirth/dxx-rebirth/commit/8e097e79f06fe1aa1ed8b8b79856486d6e464c49 ?

The 1 for the disabling argument was placed on the string terminator. So instead of SDL_DISABLE_LOCK_KEYS=1 we got SDL_DISABLE_LOCK_KEYS=01 (unterminated) which somehow worked on Linux. I guess it should work now on Windows, too.

**Comment by vLKp** [comment]
A session with `gdb` confirms zico's analysis that the index was off by one.  This appears to be harmless (despite being undefined behaviour) on my Linux builds, which happen to have an extra null after the incorrectly overwritten null.  History says that the relevant line was most recently touched in [Diagnose missing/invalid arguments](/dxx-rebirth/dxx-rebirth/commit/f1f4bb9db6ed65d028ff089e116af940fad6963d), but that was just code motion.  In the [preceding version](/dxx-rebirth/dxx-rebirth/blob/d3637e7524e1f7f3fdfccf66007b08805c3085b5/similar/misc/args.cpp) (commit "Invert sense of SysUseNiceFPS"; path similar/misc/args.cpp), that block was at lines [128-130](/dxx-rebirth/dxx-rebirth/blob/d3637e7524e1f7f3fdfccf66007b08805c3085b5/similar/misc/args.cpp#L128) and the most recent modification of the relevant line was in commit [Pass non-const string to putenv](/dxx-rebirth/dxx-rebirth/commit/6be4dc01c57e2c3acb77a4148f6bfd4316bc59f3).

That commit was necessary because some targets, such as x86_64-pc-linux-gnu, define `HAVE_PUTENV` in `SDL_config.h`.  When that define is present, `SDL_stdinc.h` will `#define SDL_putenv putenv`, rather than defining a custom function `SDL_putenv`.  The custom function `SDL_putenv` has prototype `int SDL_putenv(const char *)`.  On some targets, such as x86_64-pc-linux-gnu, the system function `putenv` has prototype `int putenv(char *)`.  Thus, when `HAVE_PUTENV` is defined, `SDL_putenv` requires a `char *`, not a `const char *`, as input.  Literal strings are `char []` in C, but stored in the rdata segment.  With gcc option `-Wwrite-strings`, literal strings get the more correct type `const char []`.  In C++, literal strings default to `const char []`, which cannot be passed as `char *` without a `const_cast` or a compiler diagnostic.  [Pass non-const string to putenv](/dxx-rebirth/dxx-rebirth/commit/6be4dc01c57e2c3acb77a4148f6bfd4316bc59f3) was made to ensure that the input was a `char []` so that it was legal for SDL to write to the string if it elected to do so, and so that there would not be a compiler diagnostic when the code was compiled as C++.

As for why this works on Linux, the static buffer `dcx::PostProcessGameArg()::sdl_disable_lock_keys` is 23 bytes of text, plus the terminator, making it `char[24]`.  In my build, the compiler places `sdl_disable_lock_keys` at xxxx10 and the next variable at xxxx48, meaning that there is a gap of 0x48-0x10 = 0x38 = 56 bytes between the start of `sdl_disable_lock_keys` and the next variable.  In my Windows cross-compile build, the data also looks like it would work (despite being undefined behaviour).  However, in [Mako88's Windows build for Descent 1 Rebirth](http://dxx-rebirth.com/download/dxx/user/afuturepilot/d1x-rebirth-082916.exe) (date 2016-08-29; [commit b2cad09c267ccd17abf250be0967c01f62745eb4](/dxx-rebirth/dxx-rebirth/commit/b2cad09c267ccd17abf250be0967c01f62745eb4); sha256 digest a52fed40905c1bd00889efec7e8528fb8d751661f022db222f8c9d66e72d02b0), array `sdl_disable_lock_keys` is placed such that the `=0` is followed by a null (overwritten by the bug), then a literal 0.  Thus, when SDL tries to convert the value, it converts `"010"`.  Depending on whether the preprocessor symbol `HAVE_ATOI` is defined, this will convert to `static_cast<int>(10)` or `static_cast<long>(8)`.  Either way, it will not be any of the three approved values recognized by `SDL_KeyboardInit`.  `SDL_KeyboardInit` recognizes `1`, `2`, or `3`, and silently ignores any other value, which would account for the report that the option "does not work."  [Mako88's Windows build for Descent 2 Rebirth](http://dxx-rebirth.com/download/dxx/user/afuturepilot/d2x-rebirth-082916.exe) (date 2016-08-29; [commit b2cad09c267ccd17abf250be0967c01f62745eb4](/dxx-rebirth/dxx-rebirth/commit/b2cad09c267ccd17abf250be0967c01f62745eb4); sha256 digest 911f5a0b66d3a95117bf7a07ac6fcfd7887cd15473fe1e45d1ef905a2cdc3dd8) has an additional four bytes of nulls after the end of `sdl_disable_lock_keys`.  Thus, despite the index bug, `-nostickykeys` would have worked as expected in Mako88's Descent 2 Rebirth build.  (This was also not mentioned in the ticket, and also important, since I usually test on locally built x86_64-pc-linux-gnu Descent 2 Rebirth unless specified otherwise.)

AddressSanitizer can detect this error even in builds where there are no user-visible problems, but only when the user passes `-nostickykeys`, since a user with non-sticky keys will not write to the array.

This has been undefined behaviour since 2012-11-24, but some environments happened to compile the code in a way that it still produced the expected results.  There is no end-user workaround available for affected builds.

**Comment by Mako88** [comment]
I have tested this in the latest builds and it now works as expected. Closing.
