### ISSUE TITLE
-notitles Prevents Main Menu Music

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#212]
When using -notitles in the .ini There's no music in the main menu. If you go to credits, and then back, it plays.

**Comment by vLKp** [comment]
This was probably caused by [Enable -notitles for Descent 2](/dxx-rebirth/dxx-rebirth/commit/29f79f0a6bc3d2b617568661f7c1e7cecbd4ed69).  The main menu music is not music for the main menu.  It is SONG_TITLE, which is now bypassed when you ask for `-notitles`.  The inconsistency with playing it on return from the credits is because it is not centrally managed, so code paths that do not attempt to show the title screen do not respect this change.

**Comment by vLKp** [comment]
[Reintroduce D1 title song bug](/dxx-rebirth/dxx-rebirth/commit/1402a2194637fe4ea06058f3dbd89d32fd5bb9d3) should resolve this.
