### ISSUE TITLE
Improve Default Keybindings?

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#214]
Just a thought...how would y'all feel about making the default keybindings more like a modern FPS with keyboard+mouse? It'd make things easier for newcomers, while old guys will all already have their preferred setup so it won't affect them.

**Comment by vLKp** [comment]
I have no objection to this.  Could you post your suggested bindings?  I changed my bindings from the Descent defaults, but my bindings may differ from what FPS users like.  My bindings are:

Slide on: l-alt
Slide lrud: adcx
Bank lr: qe
Accelerate: w
Reverse: s
Afterburner: g

**Comment by Mako88** [comment]
I'd suggest this:

Mouse: Pitch/Turn (Not inverted. Even though I prefer inverted, I think the majority prefer non-inverted).

Accelerate/Reverse: W/S
Slide Left/Right: A/D
Slide Up/Down: Space/L-Ctrl (I personally prefer Shift rather than L-Ctrl, BUT most FPS players will probably be used to space being jump and control being crouch. Also this frees up Shift for afterburner which is usually run in many FPSs)
Bank Left/Right: Q/E
Afterburner: Shift
Flare: F
Automap: Tab

**Comment by lstandish** [comment]
I use the numpad for ship movement, and I think it's the most intuitive way:

Slide LRUD: 4682
Bank LR: 79
Forward: 5
Reverse: 0
Afterburner: +
Flare: *

**Comment by Mako88** [comment]
Though that's a decent control setup Istandish, it's not very intuitive for someone used to playing FPS games.

I also wanted to amend my original suggestion slightly: Automap should be bound to 'M'.

**Comment by zicodxx** [comment]
I think the defaults provided by @lstandish are decent. But I wonder why the change of the Autmap from Tab to M? Especially with the WASD layout, the map is very easily accessible via Tab. In Descent you may find yourself using it a lot to find your way (orientation) or secrets (which is why I find this binding also very handy in Doom). 
So unless Tab is used for anything more important, I'd leave it like that or - which may be even more handy - making the second key for the map bound to M. That way you can use both.

**Comment by Mako88** [comment]
Yeah, you're right zico, I think adding M as the secondary would be good. The reason for it is just that most games bind map to M by default, and my goal is kind of to allow someone to hop into the game without having to change controls at all and everything make sense right out of the box.

**Comment by ryusei117** [comment]
Ha ha, gee, where have I seen those key bindings before? XD ... I'm actually the one who suggested that control setup to lstandish while helping him learn trichording. That setup allows me to use all eight trichording directions, including afterburner with the forward trichords - but the real beauty is that the slide buttons are all together on WASD, making it very easy to dodge with diagonal sliding.

It's true, however, that people accustomed to typical first-person shooters would find that setup confusing. WASD no longer does ground-based movements, but controls free floating in 3D space. So yeah, most players would probably find Mako88's bindings more familiar: WASD works the same as in first-person shooters. The afterburner key (Left Shift) fights with the slide down key (Left Control) for the little finger, but new players probably won't be doing fancy burning trichords for a long time.

**Comment by vLKp** [comment]
Since this only affects newly created player profiles, a command-line option to revert to the original bindings seems to be of very limited use.  Any existing pilot, even one who has never changed settings, will ignore the proposed change and continue to use whatever bindings were previously written in the player profile.  The command-line option would only be meaningful for someone who creates a new pilot profile just to get the original settings.

**Comment by ryusei117** [comment]
Yeah, now that I'm reconsidering it, such a command-line option does seem like a violation of "keep it simple". If I want the classic default controls for nostalgia, I can just create a pilot profile with those settings and keep it in my directory. I really shouldn't be making feature requests at 02:30 in the morning. (^-^;)

**Comment by vLKp** [comment]
Defaults updated.  Ultimately, I decided to avoid any changes that affected the weapons-fire keys, on the basis that a returning pilot with a new profile would find that to be too disruptive.

I also rewrote the defaults to be symbolic, so that they are easier to understand and patch further.
