### ISSUE TITLE
Failing physfs test: Not searching /usr/local/include for physfs.h

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#215]
When I build on Mac OS X El Capitan using the latest commit known to previously work 4b4077bab9fc468fbc748ebfd1bc50115a4570d4 (on 6 March 2016) I get the SCons error 
scons: *** Header physfs.h is missing or unusable.  See sconf.log for details.  Stop.
However, the real issue when looking at sconf.log (attached) is:
error: unknown warning option '-Werror=useless-cast' [-Werror,-Wunknown-warning-option]

I don't know if this is related to upgrading to El Capitan, but since it was working before I upgraded, it does seem to point to exactly that. What adjustment would need to be made to accommodate this?

[sconf.log.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/465286/sconf.log.txt)

**Comment by vLKp** [comment]
Recent commits enable `-Wuseless-cast` automatically, but that was added in [Enable -Wuseless-cast](ef93feca38d7cbb6c4cebd96e9680169db674508) dated 2016-08-19, which is far more recent than the commit you used.  If you are building from 4b4077b, then SCons should not be automatically activating that option for you.  If you are setting it by hand, and your compiler does not understand it, then do not set it.

Although Apple installed their compiler as `g++`, it seems not to understand options understood by every supported version of `g++`.  I will add an SConf test to enable `-Wuseless-cast` only when the compiler actually understands it, rather than expecting it to be supported on all modern compilers.

**Comment by kreatordxx** [comment]
Oops, I was looking at the wrong sconf.log! It **wasn't** finding physfs.h, because my Mac OS X Command Line Tools weren't up-to-date - it needs that to search /usr/local (without having to explicitly add /usr/local/include to the search paths). I've added some more text to INSTALL.markdown (attached) so hopefully other Mac users don't run into this issue, see if you like it.
[mac_tools_doc.patch.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/465803/mac_tools_doc.patch.txt)

**Comment by kreatordxx** [comment]
As I've unwittingly posted two issues here, one pretty much solved now and the other in progress, I'm renaming this one and posting a new issue for -Wuseless-cast (where I will quote and answer your question).

**Comment by vLKp** [comment]
That patch looks good.  [Add kreator's elaborations to Mac OS X install instructions](/dxx-rebirth/dxx-rebirth/commit/a578c48c5307ac9fe5fec2228a111782b83d3bd1) incorporates your text, with some light edits for Markdown rules and consistency with the style of the document.  In particular, Markdown requires a blank line on both sides of an indented line in order to provide the alternate styling.  This seems odd to me, but I added appropriate blanks to handle this.

**Comment by kreatordxx** [comment]
Thanks!
