### ISSUE TITLE
Clang Apple LLVM version 7.3.0 (clang-703.0.31) Chokes on similar/main/multibot.cpp

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#217]
After further compiling commit 4b4077bab9fc468fbc748ebfd1bc50115a4570d4 on Sun Mar 6 18:11:20 2016 +0000, Apple's Clang gives this output:
scons: Building targets ...
CXX d1x . similar/main/multibot.cpp
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/1k/j5_zb8w92g140swblhjqr3280000gn/T/multibot-fb6d7d.cpp
clang: note: diagnostic msg: /var/folders/1k/j5_zb8w92g140swblhjqr3280000gn/T/multibot-fb6d7d.sh
clang: note: diagnostic msg: 

********************
scons: *** [similar/main/.d1x-rebirth.multibot.o] Error 254
scons: building terminated because of errors.

This has been reported with Apple, bug report 28247284.

**Comment by vLKp** [comment]
I wondered if someone would hit this in the published code.  I ran into it in January using an outdated Linux clang, but never published the fix because it makes the code less readable and I hoped the compiler bug was fixed in newer clang.  More recently, I discovered that the trivial fix triggers a `-Wuseless-cast` warning on some targets.  Avoiding **that** warning in turn requires making the workaround even uglier, since the workaround is in code that is built by all targets, even though only clang needs the workaround.

On the positive side, the workaround is sufficiently self-contained that you can probably cherry-pick it onto a legacy commit like the one you tested.  Please retest using [Work around clang crash bug](/dxx-rebirth/dxx-rebirth/commit/f11235147a658ffb560567e9d9edad61b5742d47), either by updating to that commit or by using `git cherry-pick` to apply its change to your existing tree.

**Comment by kreatordxx** [comment]
This file compiles fine now, so closing.
