### ISSUE TITLE
Questionable license change

### ISSUE THREAD

**Issue by wm4** [dxx-rebirth/dxx-rebirth#22]
Commit ad7cb106bce2742b3f389c7d3dc855794462f73f changes from the Parallax license to GPLv3. There is no hint that this is officially endorsed by the original publisher of the source code.

**Comment by btb** [comment]
Since this came up, I don't suppose there is any issue with me adopting the same license for plain old d2x? I've been making adding some features for my own amusement and I wouldn't want to complicate matters if we want to copy bits back and forth.

**Comment by Matt1360** [comment]
There should be no issue that I can see with this, as long as other recent
contributors agree as well. I assume that's fine, in your case :).

**Comment by vLKp** [comment]
> I've been adding some features for my own amusement and I wouldn't want to complicate matters if we want to copy bits back and forth.

From a purely technical perspective, copying much code from Rebirth into d2x probably will be rather time consuming.  As you noted in another ticket, Rebirth relies on C++11 (and will use C++14 features where available).  I have made several sweeping changes to Rebirth:

* Conversion to C++11 (including using C++11 features such as range-based for on loops, which causes the entire loop to show as a "change").
* Conversion of magic numbers to symbolic constants (-1 was popular at Parallax to mean "none"; various sites now use named versions of -1 appropriate to the type (object_none, segment_none, wall_none, etc.), to make the code clearer).
* Conversion of Objects/Segments usage into passing pointers to the object/segment in question

Any of these is likely to mean substantial text conflicts if you try to backport Rebirth changes into d2x.  If you want to maintain a personal interest build, I recommend doing it as a fork of Rebirth, rather than trying to cherry-pick Rebirth changes back into the d2x code base.  You can keep that separate from your Rebirth contributions, or not, as you prefer.  There are also numerous bug fixes in the Rebirth code, not all of which were not specifically marked, so building on the d2x code base will expose you to Parallax bugs that we have already fixed.

**Comment by btb** [comment]
I might get to the point where I'm working off a fork, but it'll be a fork of the "d2x-rebirth/master" branch. C++ is simply too painful to work with and still have fun doing it.

**Comment by vLKp** [comment]
Original reporter ceased responding.  btb's inquiry was answered.  Nothing further to do here.
