### ISSUE TITLE
Descent 1 Mission 'Infested Mines' Crashes D1X-Rebirth

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#228]
When I play the [Infested Mines](https://github.com/dxx-rebirth/dxx-rebirth/files/500341/Infested.Mines.zip) mission, D1X Rebirth crashes when attempting to load an OpenGL texture (bad memory access, attempts to access null pointer).

It looks like it fails to page in texture 356 (a texture override for a robot) before attempting to load it in OpenGL. I haven't been able to figure out why, it does seem to call PIGGY_BITMAP_PAGE_IN for texture 356 in paging_touch_all, similar/main/paging.cpp. I can confirm the mission works with a copy of D1X Rebirth from 2012, but unfortunately there isn't enough history that will build on Mac OS X for me to use git bisect.

**Comment by vLKp** [comment]
Thank you for reporting this.  This level shows substantial breakage.  So far I have seen:

1. In D1 emulation mode, a breakpoint trap in `d2x::briefing_process_char` at `similar/main/titles.cpp:932` when debug=True.  Your build from 2012 would not have this, even if built with debug=True, since breakpoint traps were re-enabled in [Enable Int3 as d_debugbreak](/dxx-rebirth/dxx-rebirth/commit/33c118f999800471244e76caae3164a77a74ca6e) at Bradley's request.
1. In D1 emulation mode, if I play Infested Mines as the first thing after I start the game, I get an `Error` style abort in `dcx::PCXHeader_read_n` at `similar/2d/pcx.cpp:77` that seems to be caused by trying to read a header from an empty file, which itself has an empty name.  I am not sure why opening an empty name produces an empty readable file instead of producing an error.
1. In D1 emulation mode, if I play **Descent 2: Counterstrike**, bail out, and then play Infested Mines, I do not get the PCX error (which itself seems like a bug).  The game ought either to always have the PCX error or never have it, but not be conditional on what other missions I played first.  Instead, I get a `std::runtime_error` thrown from `d2x::trigger_type_from_flags` at `similar/main/switch.cpp:668` because the emulation mode cannot emulate a trigger that the map designer used.
1. In native D1 mode, I get through the briefing successfully, then crash at the `Prepare for Descent` window with context that seems to be the same as what you reported.

Aside from all the ways to crash the game, I also noticed that the D1 emulation mode shows the briefing in a way that makes the text unreadable.  Native D1 mode plays the briefing correctly.  This is a bug in the emulation mode, since it ought to be possible to play as if the game was native D1.

If I patch the level load code to force tmap_override to -1 (disabled) for all objects, I can load the level successfully.  I did not attempt to complete the level, but I was able to fly around and engage a few of the early enemies.

**Comment by kreatordxx** [comment]
No worries, I noticed two Descent II missions that crash as well and will report them.

**Comment by vLKp** [comment]
After stepping through both 0.58.1-d1x and current code in D1 native mode, I believe this to be a bug in the code for caching textures into OGL.  In 0.58.1-d1x, as part of level load, all non-disk textures were marked as paged out and their data pointer set to `Piggy_bitmap_cache_data`.  In current code, that data pointer is not set.  The crash happens because the code for caching textures into OGL assumes that the data pointer will be valid even when the flags mark that the texture is paged out.  This is not a valid assumption.  In native D2 mode, paged out textures have `nullptr` for their bm_data.  This may have been done in an attempt to find places that assumed paged out textures still had valid data, by forcing a crash from such sites.  The OGL code must check that it is not accessing a paged out texture.

This can be seen by the following two patches.  The first reverts [Disable piggy_bitmap_page_out_all](/dxx-rebirth/dxx-rebirth/commit/3c20c24ac0cc2d994f271a53ebd6e2f20356aa78) (and fixes the resulting minor breaks).  This makes `Infested Mines` playable.  The second makes a trivial change to match the Descent 2 logic, and that ought to be perfectly legal if all call sites respected the page-out flag.  However, that second change again breaks `Infested Mines`.

Fix crash:
```diff
diff --git a/common/main/piggy.h b/common/main/piggy.h
index e25895d..ea76ccd 100644
--- a/common/main/piggy.h
+++ b/common/main/piggy.h
@@ -124,9 +124,9 @@ constexpr unsigned MAX_BITMAP_FILES = 2620;
 #ifdef dsx
 namespace dsx {
 extern void piggy_bitmap_page_in( bitmap_index bmp );
+extern void piggy_bitmap_page_out_all();
 }
 #endif
-#define piggy_bitmap_page_out_all()
 
 namespace dsx {
 extern array<digi_sound, MAX_SOUND_FILES> GameSounds;
diff --git a/similar/main/piggy.cpp b/similar/main/piggy.cpp
index dd7b1aa..3d3aed9 100644
--- a/similar/main/piggy.cpp
+++ b/similar/main/piggy.cpp
@@ -1444,7 +1444,6 @@ void piggy_bitmap_page_in( bitmap_index bitmap )
 }
 }
 
-#if 0
 namespace dsx {
 void piggy_bitmap_page_out_all()
 {
@@ -1452,8 +1451,6 @@ void piggy_bitmap_page_out_all()
 	
 	Piggy_bitmap_cache_next = 0;
 
-	piggy_page_flushed++;
-
 	texmerge_flush();
 	rle_cache_flush();
 
@@ -1470,7 +1467,6 @@ void piggy_bitmap_page_out_all()
 
 }
 }
-#endif
 
 void piggy_load_level_data()
 {
```

Break code with bad assumptions, reintroduces crash:
```diff
diff --git a/similar/main/piggy.cpp b/similar/main/piggy.cpp
index 3d3aed9..01d0844 100644
--- a/similar/main/piggy.cpp
+++ b/similar/main/piggy.cpp
@@ -1458,7 +1458,7 @@ void piggy_bitmap_page_out_all()
 		if ( GameBitmapOffset[i] > 0 ) {	// Don't page out bitmaps read from disk!!!
 			GameBitmaps[i].bm_flags = BM_FLAG_PAGED_OUT;
 #if defined(DXX_BUILD_DESCENT_I)
-			gr_set_bitmap_data (GameBitmaps[i], Piggy_bitmap_cache_data);
+			gr_set_bitmap_data (GameBitmaps[i], nullptr);
 #elif defined(DXX_BUILD_DESCENT_II)
 			gr_set_bitmap_data(GameBitmaps[i], NULL);
 #endif
```

**Comment by kreatordxx** [comment]
I can confirm that applying the first patch fixes the issue. However, applying the second patch as well seems to make no difference - it still works fine.

**Comment by vLKp** [comment]
You are not supposed to apply either of those.  I posted those to demonstrate why it once worked, and why the logic (prior to my commit [Page in textures before caching them](https://github.com/dxx-rebirth/dxx-rebirth/commit/ffa53eb3c47f0311b77d994fb6e4d6fe8e8f9638)) was broken.  Prior to my fix, the OpenGL caching code would access `->bm_data` even if the flags stated that the data was paged out.  That is wrong, and faulted when `->bm_data` was `nullptr`, but happened to merely cache wrong data if `->bm_data` was set to a garbage readable value, such as `Piggy_bitmap_cache_data`.  If you have that commit, then you do not need either of the patches posted inline, but applying them should be harmless.

**Comment by kreatordxx** [comment]
All good, fixed with just the commit.
