### ISSUE TITLE
Descent 2 Mission 'Abalyon 4: Space Dock' Crashes D2X-Rebirth

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#231]
When I play [Abalyon 4: Space Dock](https://github.com/dxx-rebirth/dxx-rebirth/files/505472/aba4.zip) with the Release build it crashes with this output (truncated):
```
Application Specific Information:
abort() called
terminating with uncaught exception of type std::runtime_error: matcen triggers non-matcen segment
```
The responsible line is `throw std::runtime_error("matcen triggers non-matcen segment");` in similar/main/gamesave.cpp.

**Comment by kreatordxx** [comment]
I also get the same issue with [Abalone 6: Vertigo Hive](https://github.com/dxx-rebirth/dxx-rebirth/files/505478/aba6.zip) (though it just exits, it doesn't give a crash message).

**Comment by vLKp** [comment]
That `throw` was an `Int3` in earlier builds.  I think I converted to `throw` before I knew that `Int3` was historically a no-op.  It is about 20 years too late to get the level author to fix the problem with the level, so I will have to remove the `throw`.  I will probably replace it with a `con_printf(CON_URGENT)` diagnostic so that people building new levels know when they do it wrong, but people playing old levels can continue to play old (buggy) levels.

**Comment by vLKp** [comment]
[Downgrade matcen diagnostic from exception to con_printf(CON_URGENT)](/dxx-rebirth/dxx-rebirth/commit/635b3f54e3f33af79ef5858014ae8df9b675a461) removes the `throw` reported in comment #0.

**Comment by kreatordxx** [comment]
Fixed.
