### ISSUE TITLE
BUG: object <number> has type <number>, expected <number>

### ISSUE THREAD

**Issue by ryusei117** [dxx-rebirth/dxx-rebirth#234]
lloyd (that's his user name on the DXX-Rebirth forum) and I were playing D2 Cooperative with commit 437d1717d831b3478282d75b1eff6a2a65fd90bd a few days ago, and we noticed many of these "object type" messages in our terminals and `gamelog.txt` files. Here's the output from lloyd's game as we played through three levels of Descent 2: Counterstrike!:

[object_type_bug_lloyd_gamelog.txt](https://dl.dropboxusercontent.com/u/26944122/dxx_rebirth_issues/object_type_bug/object_type_bug_lloyd_gamelog.txt)

This seems to occur in any multiplayer game mode in both D1 and D2 if at least two players are present. I haven't seen it occur in singleplayer. I didn't notice any gameplay bugs, but thought I'd report it since the messages are labeled "BUG". Are these messages concerning?

**Comment by vLKp** [comment]
Sometimes they are important.  Sometimes they are just a sign that the wrong access function was used.  They are always worth reporting, since the code needs to be fixed not to generate them.

```
similar/main/multi.cpp:1742: BUG: object 0xdc0588 has type 4, expected 12
```
This one is interesting.  It looks like someone tried to respawn without being dead first.
```
similar/main/collide.cpp:1711: BUG: object 0xdc0588 has type 4, expected 2
```
This one is harmless.  I used the wrong access function.  The code produced the correct result.

**Comment by vLKp** [comment]
[Add special handling for multi_do_reappear get_ghost_id](/dxx-rebirth/dxx-rebirth/commit/779738fa8064d2886ee53c928555c78de4f76853) should resolve the first one.  I modified the test to permit both `OBJ_PLAYER` and `OBJ_GHOST`, rather than try to change the multiplayer code not to resurrect players who were not dead.

**Comment by ryusei117** [comment]
Yep, both messages no longer appear; well done. That first message, the one indicating `similar/main/multi.cpp:1742`, seemed to be happening when a client player spawned right after joining a game.
