### ISSUE TITLE
Null-Terminate Max-Length Game Info Strings

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#235]
I came across a problem while working on tracker stuff:

Normally the game name, mission name, and mission title that are sent in packets are terminated with a null character. However, if they are filled to their max length, there is no null character added.

This is an issue with my tracker because it separates those strings using null characters. (I could make a workaround for this, but I figured it'd be better to have it fixed in the client).

**Comment by vLKp** [comment]
What is there to fix?  Zico spent quite a bit of effort making the protocol compact, presumably to avoid fragmentation.  I extended that by using the technique you saw to omit nulls when they are unnecessary.  If you want to have messages sent to the tracker that do not use this optimization, go ahead.  Those messages will probably be smaller due to omitting game control data entirely.  As far as I know, the main game handles the current null-omission design correctly.

**Comment by Mako88** [comment]
Ah, OK, I didn't realize this was a feature lol.

I'll talk to Zico about whether he wants to change it for just the tracker, or whether I should parse it tracker-side.

Closing.

**Comment by Mako88** [comment]
Just mentioning here for information sake: the tracker now parses the strings itself, so nothing needs to be changed in Rebirth.
