### ISSUE TITLE
Losing Life on D2X-Rebirth causes loss of all missiles, even after save game reload

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#238]
When my ship is destroyed in a Descent 2 mission, I reload a saved game to find I lost most of the missiles that would have been saved in the saved game file, with the only saved ones being concussion and homing. If I relaunch D2X Rebirth and load the save file I find the missiles are still gone. Steps:

1. Accumulate some missiles or type the 'HONESTBOB' cheat
2. Save the game
3. Destroy your own ship (e.g. face a wall and shoot missiles, run into proximity bombs or let the robots do it!)
4. Load the saved game. Most of the missiles are gone.

**Comment by vLKp** [comment]
This is probably a regression introduced by moving fields from `struct player` to `struct player_info`.  I see a possible cause.

**Comment by vLKp** [comment]
I found the cause, and pushed [Fix object corruption loading save game](/dxx-rebirth/dxx-rebirth/commit/5114b8f8b69eb4e46da0148e48df4a762ea5ed57) to address it.  When `ctype.player_info` grew to the point that it overlapped `ctype.ai_info.ail`, a latent memory corruption began to cause problems.  Saved games dump robot `ai_local` state for all objects, regardless of whether the object is a robot.  Loading a game restored all `ai_local` values, regardless of whether the object was a robot on restore.  If the loaded data overwrote a `ctype.`_T_ that was in use, memory corruption occurred.  In your case, that corruption wiped part of `ctype.player_info.secondary_ammo`, starting at offset `[2]`, which is why you kept concussion and homing, but lost everything else.  You also lost several other, more subtle, fields:
```c++
	array<uint8_t, MAX_SECONDARY_WEAPONS>  secondary_ammo; // How much ammo of each type.
#if defined(DXX_BUILD_DESCENT_II)
	array<uint8_t, SUPER_WEAPON> Primary_last_was_super;
	array<uint8_t, SUPER_WEAPON> Secondary_last_was_super;
#endif
	fix64   cloak_time;             // Time cloaked
	fix64   invulnerable_time;      // Time invulnerable
	fix64 Next_flare_fire_time;
	fix64 Next_laser_fire_time;
	fix64 Next_missile_fire_time;
	fix64 Last_bumped_local_player;
};  // player_info
```

**Comment by kreatordxx** [comment]
Fixed.
