### ISSUE TITLE
Old High Scores Not Working

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#241]
The latest build can't load original high scores (the default high scores that come with Descent) or scores created from 0.58.1. The high score screen just shows all the scores as empty.

However, once you create a new high score, it is saved and loaded fine.

I'm not sure when this broke.

**Comment by Mako88** [comment]
First a bit more info:

Basically the descent.hi file that is created is incompatible between the latest revision and 0.58.1. So if that file doesn't exist, the original Parallax scores are shown fine, and any new scores created work great. However, if that file exists and was created by 0.58.1, then the old scores aren't shown, even though new ones work.

According to git bisect, e335cdacb3f5551fc0adb20b6de35fbc7739aaf3 is the faulty commit.

**Comment by vLKp** [comment]
The identified commit changed `COOL_MESSAGE_LEN`, which is used in the definition of a structure that is assumed, without any checking, to be laid out identically to an on-disk file.  `scores_read` will reject your scores file if its size is different than the size of `all_scores`; `all_scores` is influenced by `COOL_MESSAGE_LEN`.  The use of packed structures to represent disk files is bad practice due to portability problems.  It is especially bad practice if no one includes a static assertion that the size is as expected, since that omission allows unintended changes to go unnoticed.

We need to revert `COOL_MESSAGE_LEN` to its original value.  I see nothing in the code that would require it to have its new value.  Reverting it will, of course, break any scores files written after e335cda.

**Comment by Mako88** [comment]
Confirmed fixed. Closing.
