### ISSUE TITLE
Latest Commit Fails Build on Apple Clang (use sizeof instead of strlen?)

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#251]
When I build on Mac OS X (Apple Clang) I get this error:
```
similar/main/net_udp.cpp:5660:17: error: non-type template argument is not a constant expression
    array<uint8_t, 2 + strlen(UDP_REQ_ID) + sizeof("00000.00000.00000.00000")> pBuf = {};
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
Should the `strlen` be replaced with `sizeof` to fix the error? I can confirm this fixes the error and makes it build for release again.

**Comment by vLKp** [comment]
This was introduced with the code for Mako88's PHP tracker.  Apparently, gcc permits `strlen` on a constant string in a constexpr context, but clang does not.  I pushed a change to switch it to sizeof, which causes the buffer to be one byte larger (since sizeof counts the null terminator, but strlen does not), but should otherwise give the same result.

**Comment by kreatordxx** [comment]
Fixed.
