### ISSUE TITLE
Cxx11RequiredFeature('extended identifiers') breaks gcc-4.9.2 builds

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#254]
From the SConstruct` file:

    # This test could be made optional, but until someone reports an
    # otherwise-supported compiler that fails this test, it is
    # mandatory for simplicity.
    Cxx11RequiredFeature('extended identifiers', '''

So I found one: 
gcc version 4.9.2 (Raspbian 4.9.2-10)

Note that this is the _most_ _recent_ gcc version that is available in Raspbian stable.

**Comment by vLKp** [comment]
If you remove that feature test, the build otherwise succeeds?  When last I tried using gcc-4.9.3 on x86_64-pc-linux-gnu, I found that it failed to build some networking code because glibc provides an `ntohs` macro that provokes a warning from `-Wold-style-cast`.  gcc-5 and later treat text from a macro as coming from the macro's definition site, which suppresses warnings about macros from system headers.  gcc-4.9.x treats it as coming from the site of use, which causes a warning if `ntohs` is called.  Unfortunately, simple test programs that call `ntohs` do **not** provoke the warning, so I was unable to write a nice test to enable the warning conditional on having a compiler that does what I want.  The warning had been enabled for quite a while before I noticed that, so I thought no one was still using <gcc-5.

**Comment by vLKp** [comment]
On further investigation, the problem with `ntohs` is a bad interaction between <gcc-5, `ccache` with mode `CCACHE_CPP2=0`, and system headers that use old style casts.  It will be ugly, but I can write a test for this, which should make gcc-4.9 work again.

**Comment by vLKp** [comment]
[Add test and fallback for extended identifiers](https://github.com/dxx-rebirth/dxx-rebirth/commit/458070a08004390b5a1c4756be4dfcf98345ea8a) adds `-fextended-identifiers` when the compiler rejects extended identifiers by default, but permits them with that option.  For me, that let x86_64-pc-linux-gnu-gcc-4.9.3 build to completion.

On further consideration, and since the use of `ccache` is necessary for the `-Wold-style-cast` problem, I am inclined not to add a test to compensate for that edge case.  Users cannot use **CCACHE_CPP2=0 ccache gcc-4.9** *options* to build **net_udp.cpp**, but can build it if they:

* Do not use ccache  *or*
* Set `CCACHE_CPP2=1`  *or*
* Switch to >=gcc-5

**Comment by derhass** [comment]
Yeah, I did not hit this `-Wold-style-cast` issue because I was not using `ccache`, and I also agree that a test for this specific case wouldn't be necessary.
