### ISSUE TITLE
-Wuseless-cast in SDL headers in 32Bit builds

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#257]
This is on raspbian again, but I think it is just specific to 32Bit builds. It happens everywhere where `SDL.h` is inculded, e.g.:

```
In file included from /usr/include/SDL/SDL_main.h:26:0,
                 from /usr/include/SDL/SDL.h:30,
                 from common/include/joy.h:21,
                 from common/main/kconfig.h:28,
                 from common/main/playsave.h:78,
                 from similar/arch/ogl/ogl.cpp:59:
/usr/include/SDL/SDL_endian.h: In function ‘Uint32 SDL_Swap32(Uint32)’:
/usr/include/SDL/SDL_stdinc.h:85:71: warning: useless cast to type ‘Uint32 {aka unsigned int}’ [-Wuseless-cast]
 #define SDL_static_cast(type, expression) static_cast<type>(expression)
```
This is with libsdl1.2debian 1.2.15-10+rpi1 and gcc version 4.9.2 (Raspbian 4.9.2-10).

**Comment by vLKp** [comment]
It is not sufficient to be on a 32-bit system.  Using libsdl-1.2.15, I get an `SDL_endian.h` that has sha1 digest 654e3661f86f8348e7e9199b27623db6ad61d4ed.  The authors of that file included several architecture specific special cases behind preprocessor guards, which use processor specific assembly to implement the swap.  They have a final fallback case for unhandled architectures, which is implemented purely in C, and that is the one that Raspbian uses.  That version always violates `-Wuseless-cast`, but is only compiled on architectures that lack a special case higher up.  The guards (stripping non-preprocessor lines before the function) are:
```c++
#if defined(__GNUC__) && defined(__i386__) && \
   !(__GNUC__ == 2 && __GNUC_MINOR__ <= 95 /* broken gcc version */)
#elif defined(__GNUC__) && defined(__x86_64__)
#elif defined(__GNUC__) && (defined(__powerpc__) || defined(__ppc__))
#elif defined(__GNUC__) && (defined(__m68k__) && !defined(__mcoldfire__))
#else
static __inline__ Uint32 SDL_Swap32(Uint32 x) {
	return SDL_static_cast(Uint32, ((x<<24)|((x<<8)&0x00FF0000)|((x>>8)&0x0000FF00)|(x>>24)));
}
#endif
```
Thus, x86, amd64, ppc, and m68k users have special cases that avoid the error.

I will modify the test for `-Wuseless-cast` to cause it to declare `-Wuseless-cast` unsupported if SDL provokes the warning.  This is not ideal since it means some architectures will not detect any useless casts, but it will resolve your problem.  I already have a basic test since older versions of clang do not understand `-Wuseless-cast` at all.

**Comment by vLKp** [comment]
[Test whether SDL_endian.h provokes -Wuseless-cast warning](/dxx-rebirth/dxx-rebirth/commit/1ba67c0d301d14186ffd5015680375b3ba2432ef) should suppress this warning option on affected systems.
