### ISSUE TITLE
Compile error: missing macros AI_V4MAPPED, AI_ALL, AI_NUMERICSERV

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#259]
```
similar/main/net_udp.cpp: In static member function ‘static int {anonymous}::udp_dns_filladdr_t::apply(sockaddr&, socklen_t, int, const char*, uint16_t, bool, bool)’:
similar/main/net_udp.cpp:566:19: error: ‘AI_V4MAPPED’ was not declared in this scope
  hints.ai_flags = AI_V4MAPPED | AI_ALL | AI_NUMERICSERV;
                   ^~~~~~~~~~~
similar/main/net_udp.cpp:566:33: error: ‘AI_ALL’ was not declared in this scope
  hints.ai_flags = AI_V4MAPPED | AI_ALL | AI_NUMERICSERV;
                                 ^~~~~~
similar/main/net_udp.cpp:566:42: error: ‘AI_NUMERICSERV’ was not declared in this scope
  hints.ai_flags = AI_V4MAPPED | AI_ALL | AI_NUMERICSERV;
                                          ^~~~~~~~~~~~~~
```

**Comment by vLKp** [comment]
I cannot reproduce this failure on x86_64-pc-linux-gnu using gcc-5.4.0 both with and without the EDITOR option.

0.58.1-d2x-7168-ga0cd836

**Comment by Mako88** [comment]
This was using gcc 6 (Sorry I forgot to report that in my original post. Arch has officially moved to gcc 6, and it was a pain to downgrade every time, so I went ahead and switched. The bug that was in a previous version of mingw gcc has been fixed).

**Comment by vLKp** [comment]
I thought gcc 6 was not usable for you due to the anonymous namespace / `DXX_ALWAYS_ERROR_FUNCTION` problem reported in [Various Compile Warnings With GCC 6](210).

Downgrading should not be necessary.  Gcc can be installed slotted, and the Rebirth build tool has handled user-chosen compiler paths even before I rewrote it.  You could have kept both old gcc and new gcc, and specified the path to old gcc when compiling Rebirth.

The specific symbols missing in this ticket come from `<netdb.h>`, which is normally provided by glibc.

**Comment by Mako88** [comment]
I'm compiling using the following command (on Arch Linux):
```
scons dxx=mingw49 mingw49_CXX=/usr/bin/i686-w64-mingw32-g++ mingw49_PKG_CONFIG=/usr/bin/i686-w64-mingw32-pkg-config mingw49_RC=/usr/bin/i686-w64-mingw32-windres mingw49_host_platform=win32 -j 4
```

The version of GCC is 6.2.1. I do get various warnings while using it, but the build completes. If you would prefer, I can switch back to 5.x though.

**Comment by vLKp** [comment]
That invocation looks a bit odd (the trailing *49* in *mingw49* is supposed to mean running **mingw-gcc-4.9**), but your gcc is not a 4.9 series.

Your problem could be that the mingw headers guard those macros with `_WIN32_WINNT >= 0x600` (Windows Vista), and `common/main/multi.h` forces `_WIN32_WINNT` to `0x0501` (Windows XP).  I found some distributions that ship the headers that way, at least.  I pushed [Tighten getaddrinfo test](/dxx-rebirth/dxx-rebirth/commit/73d014c04807b8d8d0bde8a8535ea4e81f339510) to address this.

**Comment by Mako88** [comment]
Ah. What command SHOULD I be using?

**Comment by vLKp** [comment]
The effect of that command is fine.  It just looks odd because when I start reading it, I expect it to mean that you are using mingw32-gcc 4.9.x, but when I get to the text afterward, you say it is gcc 6.2.1.  The simplest thing would be to remove all the instances of *49* so that the version is unspecified.

**Comment by vLKp** [comment]
@Mako88: since you filed #270 based on newer code, is it correct to say that this issue is resolved?  Are you now able to build in the environment which originally failed?

**Comment by Mako88** [comment]
Yes, I am. Sorry I forgot to close this.
