### ISSUE TITLE
Excess reflected fusion shots

### ISSUE THREAD

**Issue by vLKp** [dxx-rebirth/dxx-rebirth#269]
This is a very old bug.  It applies in 0.57.3 and, as far as I can tell, was never fixed.

Some Descent 2 bosses have a special ability that reflects energy weapons used against them.  When a fusion cannon is used against the boss, the boss reflects more shots than for other weapons.  Internally, the boss never reflects weapon fire.  Instead, it creates a new weapon aimed opposite the original, and relies on the general physics processing to delete the weapon that triggered the reflection.  However, fusion shots are never deleted as a result of impacting a robot.  Instead, they are marked not to reprocess that robot and allowed to continue flying.  The test for whether the shot has already hit the robot occurs too late, so every frame that the fusion shot is in contact with the boss, a new reflected fusion shot is generated, even though the boss only runs normal damage processing for the shot on the first frame where the fusion shot hits.

**Comment by zicodxx** [comment]
I wonder if a logic change I did in the past may have caused this - I do not remember seeing this in the original game. But then again I was never a fan of the fusion weapon to begin with.

I think it would only make sense to remove the persistent flag of weapon in do_boss_weapon_collision right after the copy is created. That would allow the original projectile to die as persistent check is executed after do_boss_weapon_collision in collide_robot_and_weapon and the copied projectile would still have the persistent flag.

I assume we could also initialize the weapon owner right there as well to address #265.

What do you think?

**Comment by vLKp** [comment]
Clearing the persistent flag would mean that fusion shots cannot penetrate a reflective boss robot to damage robots on the other side, but could penetrate any other robot, including non-reflective boss robots.  That inconsistency seems wrong to me.

I would rather see the problem resolved by reordering the logic in `collide_robot_and_weapon` to detect and suppress duplicate hits before the call to `do_boss_weapon_collision`.  I filed this ticket primarily to create a record of the change, since it is very visible to users, so if anyone has a good case for keeping the current semantics, they have a chance to state it.

I looked at `historical/d2x^:main/collide.c` and it looks like it would have the same result as current code.

**Comment by zicodxx** [comment]
I thought about that, too but to be honest, I have no idea what the intended behavior would be. The logic only says that energy weapons should be reflected. Removing the Persistent flag wouldn't change that as another fusion shot is still generated which would also penetrate. It would appear as being reflected as observed by the player - with the exception that the collision sprite is visible which could underline as being an effect of the reflection. 

So I think it's only a matter of what's more "realistic": 'Fusion overriding boss reflect ability' or 'Boss reflecting fusion projectile effectively overriding its persistent behavior (while still retaining it)'. 

Which raises the question: How does the final boss of Descent 2 handle this? It's only supposed to take damage if hit from behind. If the fusion projectile can penetrate this boss, one would assume you can damage the boss from all angles as long as the glowing hit target on its back is in contact with the fusion bolt. If the boss has a reflective ability, I think it should go for fusion bolts, too as otherwise players would think they could legitimately damage the boss that way which - I think - should not be possible.

**Comment by vLKp** [comment]
You're right that the expected semantics are very unclear here.  Contrary to my prior post, I now think the most consistent approach would be to say that the boss reflection ability overrides fusion's penetration ability, so we should reflect exactly one fusion bolt back for each bolt in, and we should not allow the fusion bolt to penetrate the boss.  To the extent that any of this makes realistic sense, that would fit with the idea that the boss has a mechanism that reflects energy weapons.  Retaining the persistent flag would mean that the boss's reflection mechanism clones some attacks and reflects others, which is probably the weirdest outcome.

After thinking on it further, I decided to take a different approach.  The comment

```c++
			//	Make a copy of this weapon, because the physics wants to destroy it.
```

is true, but overstates the problem.  It is not **that** hard to prevent the destruction of the weapon because the destruction logic is only one layer up in the call stack.  We just need to pass a value up to tell the caller not to delete certain weapons, then update the physics data for the reflected weapon.  I will write that up and push it.  That should also fix the weapon ownership issue as a side effect, since we will no longer be creating new weapon objects.

As I read the code, the flow for the final boss would be that the bolt hits in an invulnerable spot, so it does no damage, but still adds the boss to `hitobj_list`.  Once added, future bolts continue to provoke the reflection code, but no longer reach the block where damage is dealt, so it is not possible for the player to cheat the invulnerability by routing a shot through the boss and hitting the dot spot on its way out.

**Comment by zicodxx** [comment]
That sounds like a good idea. Two birds with one stone. :)

**Comment by vLKp** [comment]
[Fix excess fusion reflection](/dxx-rebirth/dxx-rebirth/commit/1f929796c3ad9d348e46f3ed27e0673b77594c83) should resolve this, as well as some other subtle problems caused by creating new objects, such as resetting the lifetime counter on the object.
