### ISSUE TITLE
Invalid index exception throws whenever a robot launches a homing weapon

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#274]
In **master**, when a robot launches a homing weapon (other than an energy shield blob) it exits with this error:
`libc++abi.dylib: terminating with uncaught exception of type valptridx<d2x::object>::index_range_exception: invalid index used in array subscript: base=0x100bc6490 size=350 index=65021`
This happens since commit a59de2860e5410e388ba0b3967a6138a10778a68, which is a bit suspicious because all that did was poison uninitialised fields (including field of interest `objnum->ctype.laser_info.track_goal`) to `0xfd` recurring. (Long standing bug??)

Final level (27) of **Descent 1: First Strike!** is a good example.

**Comment by vLKp** [comment]
After reading through the code flow, I think you just reported the root cause of the infamous issue #69 ([Robot homers don't track while host is dead](69)).  I believe the flow is this:

1. Robot fires a homing weapon.
1. `obj_create` calls `obj_allocate` and gets a reference to a usable object slot.
1. `obj_create` zeroes the entire object structure (in older releases, it used `memset`, but the principle is the same):

    ```c++
	// Zero out object structure to keep weird bugs from happening
	// in uninitialized fields.
	*obj = {};
    ```

4. None of the other initialization steps for the new homing weapon touch `object::ctype.laser_info.track_goal`, so it retains its undefined value (0 for non-poison builds; 0xfdfd for poison builds).
1. When the weapon tries to track, it starts off tracking object 0, which is also player 0.  Robot homing weapons with no target will track players.  Robot homing weapons with a target will track objects of the same type as their current target:

    ```c++
			if (track_goal == object_none)
				goal_type = OBJ_PLAYER;
			else {
				goal_type = vcobjptr(tracker->ctype.laser_info.track_goal)->type;
    ```

6. When the host is dead, player 0 (and therefore object 0) has type `OBJ_GHOST`.  Robot homing weapons rely on the uninitialized `track_goal`, so they always start out tracking player 0.  If player 0 is `OBJ_GHOST`, then they only ever track `OBJ_GHOST`, but never live players, who would have type `OBJ_PLAYER`.  @zicodxx tracked the problem as far as seeing that robot homing weapons were incorrectly tracking ghosts, but he added a hack to force them to switch to tracking players, rather than prevent them from tracking ghosts in the first place.  Based on this, I think once I push a fix for your crash (by defining `track_goal` if, and only if, the weapon will use it), then it will be possible to revert zico's change without reintroducing issue #69.

This is the second time this month I cited that *weird bugs* comment as the explanation for a weird bug, not the explanation for why something worked correctly.  This is the reason why I added the poisoning code.  Weird bugs caused by undefined data that does **not** break the program are much harder to track than crashes caused by undefined data.

I will fix this crash with my next push.

**Comment by kreatordxx** [comment]
Thanks! Yes, I thought it was odd when I put breakpoints everywhere `ctype.laser_info.track_goal` is set and the exception always happened first. It looks like `create_homing_missile` is supposed to be called whenever a homing weapon is created, but its only use is in `create_smart_children` (homing plasma blobs from a smart missile or a robot with energy shields). That explains why the plasma blobs still worked.

**Comment by vLKp** [comment]
Perhaps `create_homing_missile` is meant to be used only for weapons where the caller guarantees that the weapon is a homing weapon.  For general robot weapons, some of them home and some do not.  Various other hacks in the code made robot homing weapons mostly work despite the missing initialization, so no one ever fixed the code.

**Comment by vLKp** [comment]
[Initialize track_goal for homing weapons](/dxx-rebirth/dxx-rebirth/commit/bf662e0bcc3302ccaf7b07db55958bbaeaec2582) fixes the crash for me.

**Comment by kreatordxx** [comment]
Nice, I can confirm robot homing weapons work (looking at the spew from my ship!)
