### ISSUE TITLE
Getting Stuck on Lava Causes Excessive Damage

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#276]
In D2: Counterstrike Level 1. Here's a demo: http://missionaire.org/ACK/Descent_Stuff/lava.dem

**Comment by zicodxx** [comment]
I pushed ffb68756e3fb2e8662149d3c09ba80e88370d6da which will fix the issue.

If you can verify the fix, @Mako88, I will close the issue.

Details:
Due to the nature of do_physics_sim(), an object can collide 8 times per frame. And especially on slopes, it's possible that the object collides with the same wall multiple times in a singular frame. The damage from lava is handled in scrape_player_on_wall and is properly scaled to FrameTime. But if multiple collisions occur per frame, the player will receive excessive damage. 

Similar to the bounce flag in do_physics_sim, I added a bool for the Player object to become true as soon as scrape_player_on_wall() produced damage, so the player will not receive more damage (nor see additional damage flashes, having another random bump vector, etc) in this particular physics frame.

Of course this handling does not distinguish between different walls in a single frame. Meaning that if we already received damage and a new wall in the same loop would theoretically cause damage as well, this damage is not added. Which however makes sense to me. If a player receives damage from touching lava, the damage from that should stay consistent and not double just because the player touches two separate lava surfaces for example.

**Comment by vLKp** [comment]
Is this bug a regression relative to 0.58.1?  I expected it was since there was no statement otherwise, but this does not seem like something that would have regressed.

I am not convinced that the player should receive reduced damage when touching two distinct lava surfaces, particularly since there is no requirement in the engine that the two (or more) surfaces have the same value for `tmap_info::damage`.  If the player pushes one wing into one lava wall, and also raises the ship's cockpit into another lava wall, two surfaces are exposed to lava, so it seems to me like it ought to deal double damage.  This could be handled by changing the code to track the walls which have been touched in this frame (rather than a single boolean) and applying the exclusion on a per-side basis.

If multiple surfaces have different values for `damage`, the existing boolean-based exclusion could produce strange results where the choice of how sides are numbered affects the damage the player takes when touching two sides.

**Comment by zicodxx** [comment]
This bug probably goes back to the DOS days and potentially never surfaced due to the relatively low FPS of the game as I see no indication of this being solved differently in the original source.

And yes, you are correct, if the lava surface have different damage values, my solution will not work properly. I did run a few tests and actually I could not find any surfaces that DO have different damage values. I thought of your proposed solution as well because of that I found it to be overkill. 
But sure I could implement it. Since the loop in do_physics_sim is capped at 8 iterations, that's the maximum of walls that would need to be tracked.

But again, I am still not convinced that this makes too much sense from an in-universe realism standpoint (i.e. potentially receiving twice the damage because two lava sides join). Although it IS how the game was designed to. Then again if I do slide along two joining lava sides, the game ship will still take damage from both - just one frame after another and not perfectly equally distributed of course.

I will doublecheck if level-editors even allow setting different damage values for lava.

**Comment by Mako88** [comment]
I can verify this is fixed, and I agree that hitting multiple sides of lava shouldn't increase damage, but I won't close the issue till y'all decide what you wanna do :)

**Comment by vLKp** [comment]
On the one hand, I never liked lava-heavy levels, so I feel odd arguing for more lava damage.  On the other hand, I either don't understand or don't agree with zico's last comment regarding realism.  If the ship is legitimately touching multiple distinct surfaces, it ought to, on each frame, be burned (once) by each of touched surface, meaning each of them ought to deal damage separately.  zico says:

> the game ship will still take damage from both - just one frame after another

This seems to me like saying that the ship will always take damage from somewhere (which is true), but not that it takes the same amount of damage as before this exclusion, even though the exclusion is meant to work around bugs in the simulation code bouncing the ship off the same surface multiple times, not to reduce damage from ramming the ship into multiple lava surfaces concurrently.  Is my understanding correct?

**Comment by zicodxx** [comment]
Yes, your understanding is correct and from that point of view I do understand the intent to track all possible collision sides per frame. Since you could easily meet two joining damage (lava) surfaces in a single frame. But I do not think the player should take twice the damage in this case. You could theoretically have a "sea of lava" that's constructed from multiple segments. Common sense would say that the damage from this whole surface is the same, while tracking individual sides per frame would allow the player receiving X times the damage upon scraping along the joining point of X sides. Per frame. So the player could technically scrape along a body of lava and suddenly - without much of an observable reason - take X times more damage. 

That's the problem: It may not be easily logical if we deal with two distinct lava surfaces (let's say one on the floor and one on the ceiling) or just two joining lava sides that form one seemingly connected body of lava.

So if we should track all possible sides individually by frame, I would personally vote to also track the total damage received in this frame and then divide it by the count of how many times the player received damage. In that case the damage would average out. 

And if we do that, since level editors apparently do not support giving lava surfaces different damage values (even tho the engine technically supports it), we end up with the same effect as we have now.

**Comment by vLKp** [comment]
I had not considered the case of transiting across multiple segments of lava that seem to comprise a flat surface, but that is an excellent counterexample.  I was concerned with the case that the player knows he is touching multiple distinct lava surfaces.  For example, suppose a standard cubic segment, 20 fix units on a side.  If the player hovers in the middle of the cube, he touches no sides.  Suppose that the cube is open on one side and the other five are all lava.  If the player crams the ship into a corner opposite the open side, he touches three of the five sides of lava.  Under the original model, he would take *at least* 3 times as much damage as touching a single side, and possibly more due to the bug you fixed.  Under the current code, he will take exactly one lava wall's worth of damage, even though he is touching three distinct lava walls.  I was advocating that he should take *exactly* 3 times as much damage as touching a single side, since he is in fact touching three sides: left, bottom, back.  In that case, different parts of the ship touch different lava walls, so each one ought to count separately.  However, you raise an excellent point that when the same part of the ship touches multiple lava walls, that ought not increase the damage.   I think players are more likely to encounter your counterexample than they are to encounter my example, so, given that it would be a lot of trouble to make both work properly, I say err on the side of less damage and keep the change you made, without further alteration.

**Comment by Mako88** [comment]
Since this has been fixed and agreed upon, I'm going to go ahead and close this issue.
