### ISSUE TITLE
"Sleeping" Guidebot in D2

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#278]
Sometimes (not always) when the guidebot is released, instead of immediately searching for the first goal, he will appear to "sleep" (drifting slowly) without actually saying anything. After awhile, he will "wake up" and act normally from then on. If you approach him and then leave BEFORE he initially "wakes up", he will appear to move normally while near you, but then "sleep" again once he leaves your vicinity. After he initially "wakes up" (either on his own, or by you issuing a command to him), he will never "sleep" again and act normally.

Here is a demo demonstrating:
http://missionaire.org/ACK/Descent_Stuff/Dead_guidebot.dem

This has been an issue since at least 0.52 (and possibly earlier, though that was the earliest I could test).

**Comment by Mako88** [comment]
I updated the original report with better and more accurate info.

I also removed the report about the little blue bots, since them "sleeping" occasionally seems to be original behavior.

**Comment by zicodxx** [comment]
I can now confirm this issue. It's in fact related to #286. It's not too noticeable since the Guidebot does not tend to stray away far from the player but it can happen. Due to the changes in find_connected_distance(), the Guidebot tends to wake up less reliably if its out of reach from the player. The player will need to move closer at all times to wake it up.

**Comment by zicodxx** [comment]
I did manage to recreate the scenario demonstrated in demo provided by @Mako88. As suspected, the commit pushed by @vLKp - 2c09f9fa906ec586f48e3364d1237fe625309a33 - does in fact change the behavior here, too. After freeing the Guidebot from such a long distance, it rests dormant for up to 2 seconds (up until the FCD flush) and then begins by its own to get back to the player as it should. 

So the observation of @Mako88 seems correct that the occasional sleeping is in fact normal and caused by find_connecterd_distance() storing a distance of F1_0*1000 and after flushing the cache it will return -1, causing the Guidebot to wake up again. 

As far as I can tell, the original behavior is now restored.
