### ISSUE TITLE
"Find my powerups" Doesn't Work

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#279]
If you have died and left your spew, and then tell guidebot to find it, he will say there's no spew in mine.

**Comment by zicodxx** [comment]
Fixed in bfe6149cdb5939b50694b03435534ef7d9a17fe7. 

This was a regression where the flag for player spew was moved inside drop_powerup but was only applies to case of OBJ_ROBOT (which never actually happens in the game as far as I know) but never to OBJ_POWERUP. 
This commit sets the flag for both and fixes the problem.

**Comment by vLKp** [comment]
@zicodxx: thanks for fixing this.  It looks like I made a mistake when I set that flag on robots instead of powerups.  I see no reason in the code to set the flag on robots.  The guidebot never tests for `OF_PLAYER_DROPPED` on objects which are not powerups, so the flag does not need to be set in that case.  Even if `drop_powerup` could ever be called to drop a robot from the player, the only use of `OF_PLAYER_DROPPED` is to help the guidebot distinguish player powerups from other powerups, and players would not expect the guidebot to lead them to dropped robots.
