### ISSUE TITLE
Doors Don't Always Close Properly

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#283]
In latest master, sometimes doors don't close at all, sometimes they get hung halfway, sometimes their animations don't play, etc. This seems to only happen when two doors are open at the same time.

1f434f98ad156bff3303adcd442491f1c9332583 is the first bad commit.

**Comment by vLKp** [comment]
Confirmed.  **Descent 2: Counterstrike** level 2 is a good test case.  You have ready access to two user-controlled doors right at level start.

**Comment by zicodxx** [comment]
wall.cpp:1243 is to blame:
> const auto &&r = make_range(vactdoorptr);

If I change it back to its former syntax:
> const auto &&r = partial_range(ActiveDoors, ActiveDoors.get_count());

the issue goes away. The problem is that I do not understand why that is. make_range is used in several other contexts and seems to work as expected as far as I can tell. Unfortunately I have a much harder time reading and adding some verbose output to these kind of loops than with traditional for's.

**Comment by vLKp** [comment]
> wall.cpp:1243 is to blame:

Could you explain how you came to this conclusion?  Using `0.58.1-d2x-7384-g06034a5`, I added the following patch and observed no assertion failures when playing on **Descent 2: Counterstrike** level 2 with the first 2 doors.  If `make_range` and `partial_range` were producing different results, I would expect one or both assertions to fail.

```patch
--- a/similar/main/wall.cpp
+++ b/similar/main/wall.cpp
@@ -1237,10 +1237,18 @@ bool cw_removal_predicate::operator()(cloaking_wall &d)
 #endif
 
 namespace dsx {
+
 void wall_frame_process()
 {
 	{
+		const auto &&pr = partial_range(ActiveDoors, ActiveDoors.get_count());
+		active_door &pab = *pr.begin();
+		active_door &pae = *pr.end();
 		const auto &&r = make_range(vactdoorptr);
+		active_door &mab = *r.begin();
+		active_door &mae = *r.end();
+		assert(addressof(pab) == addressof(mab));
+		assert(addressof(pae) == addressof(mae));
 		auto &&i = std::remove_if(r.begin(), r.end(), ad_removal_predicate());
 		ActiveDoors.set_count(std::distance(r.begin(), i));
 	}
```

I did observe that the timing of when doors open and close matters.  In particular, if you do not disable robots, it is harder to get the ordering right.  I found a reasonably reliable reproduction by starting the level, disabling robots with Del-P, then flaring open the first door, firing lasers to open the second door, then flaring the first door as soon as it begins to close.

So far it looks like the problem is that an `active_door` entry remains in existence for a wall that has entered state `WALL_DOOR_CLOSED`, which later confuses `wall_open_door` into creating a new `active_door` for the wall.

**Comment by vLKp** [comment]
After examining the problem, I decided that reverting to `partial_range`, as zico described, is the least invasive fix.  The other solution would be to reimplement a `std::remove_if` style algorithm that handles the proxy objects specially.

The same error happened with cloaking walls, so I switched it too.  As with `active_door`, the code compiled, but would produce incorrect results if run.

**Comment by Mako88** [comment]
Confirmed fixed. Closing.
