### ISSUE TITLE
Extra-Large End-Game Dravis With Mac Data

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#284]
When using Mac data files, if you finish D1, in the briefing at the end the picture of Dravis is huge and pushed partially out of the screen.

Marking for 0.61 and assigning to @zicodxx per his request.

**Comment by zicodxx** [comment]
This is a problem within show_briefing_bitmap which scales Dravis' head image via rescale_x/y which assumes a 320x200 resolution.
This could be solved using the MacPig variable to change the scaling factor or - which might be the more elegant solution - by reading the base resolution from the bitmap itself. I was planning to do a more flexible scaling for all content for a longer time - especially considering the hires AddOns that could theoretically allow for Widescreen art, too. 
But for the time being I will simply fix the scaling based on given content - which makes sense since this bitmap is read from the PIG file - not a HOG (so issues with custom AddOns are not given).

**Comment by vLKp** [comment]
This appears to be caused by [Properly scale and simplify arithmetic for briefing bitmap. Constrain by screen height, by just using rescale_y for width and height. Then use show_fullscr to fill the destination canvas.](/dxx-rebirth/dxx-rebirth/commit/2b4aba341d5143bbd34e79f20ddcfa423cba6e07).  Reverting that commit (and then fixing up the restored code for more recent changes) makes the Dravis image smaller and properly positioned.  When I first looked at this ticket, I thought the use of `rescale_y` for the width was wrong, but since the commit message specifically mentions doing that, it seems not to be a copying mistake.

The revert, taking into account recent changes:
```diff
diff --git a/similar/main/titles.cpp b/similar/main/titles.cpp
index c1a550a..9c1509f 100644
--- a/similar/main/titles.cpp
+++ b/similar/main/titles.cpp
@@ -1120,11 +1120,25 @@ static void show_animated_bitmap(briefing *br)
 static void show_briefing_bitmap(grs_bitmap *bmp)
 {
 	grs_canvas	*curcanv_save;
+#if DXX_USE_OGL
+	float scale = 1.0;
+#endif
 
-	auto bitmap_canv = gr_create_sub_canvas(*grd_curcanv, rescale_x(220), rescale_y(55), rescale_y(bmp->bm_w), rescale_y(bmp->bm_h));
+	auto bitmap_canv = gr_create_sub_canvas(*grd_curcanv, rescale_x(220), rescale_y(55), (bmp->bm_w*(SWIDTH/(HIRESMODE ? 640 : 320))),(bmp->bm_h*(SHEIGHT/(HIRESMODE ? 480 : 200))));
 	curcanv_save = grd_curcanv;
 	gr_set_current_canvas(bitmap_canv);
-	show_fullscr(*bmp);
+
+#pragma GCC diagnostic ignored "-Wold-style-cast"
+#if DXX_USE_OGL
+	if (((float)SWIDTH/(HIRESMODE ? 640 : 320)) < ((float)SHEIGHT/(HIRESMODE ? 480 : 200)))
+		scale = ((float)SWIDTH/(HIRESMODE ? 640 : 320));
+	else
+		scale = ((float)SHEIGHT/(HIRESMODE ? 480 : 200));
+
+	ogl_ubitmapm_cs(0,0,bmp->bm_w*scale,bmp->bm_h*scale,*bmp,255,F1_0);
+#else
+	gr_bitmapm(0, 0, *bmp);
+#endif
 	gr_set_current_canvas(curcanv_save);
 }
 
```

A simple `git revert 2b4aba341d5143bbd34e79f20ddcfa423cba6e07` was insufficient since the reverted code predates the conversion of `#ifdef OGL` -> `#if DXX_USE_OGL` and the introduction of `-Wold-style-cast`.  Since this revert is a demonstration, not a fix, I opted to disable `-Wold-style-cast` (and not even reenable it afterward), rather than complicate the diff by converting the reverted code to the new standards.

If you prefer to see just the changes required after running `git revert 2b4aba341d5143bbd34e79f20ddcfa423cba6e07`:
```diff
diff --git a/similar/main/titles.cpp b/similar/main/titles.cpp
index e9f7d67..9c1509f 100644
--- a/similar/main/titles.cpp
+++ b/similar/main/titles.cpp
@@ -1120,7 +1120,7 @@ static void show_animated_bitmap(briefing *br)
 static void show_briefing_bitmap(grs_bitmap *bmp)
 {
 	grs_canvas	*curcanv_save;
-#ifdef OGL
+#if DXX_USE_OGL
 	float scale = 1.0;
 #endif
 
@@ -1128,7 +1128,8 @@ static void show_briefing_bitmap(grs_bitmap *bmp)
 	curcanv_save = grd_curcanv;
 	gr_set_current_canvas(bitmap_canv);
 
-#ifdef OGL
+#pragma GCC diagnostic ignored "-Wold-style-cast"
+#if DXX_USE_OGL
 	if (((float)SWIDTH/(HIRESMODE ? 640 : 320)) < ((float)SHEIGHT/(HIRESMODE ? 480 : 200)))
 		scale = ((float)SWIDTH/(HIRESMODE ? 640 : 320));
 	else
```

I do not think reverting this is necessarily the answer, but seeing the cause and how it could be reverted might guide how to fix it properly.

**Comment by zicodxx** [comment]
Yes, this is about what I have in mind to fix this. But HIRESMODE is also not necessarily the answer - I need to check that. The games files are rather inconsistent in terms of which files actually provides content considered a HIRES, how files are named, if there even is LORES content, etc. So in this case, I would much rather use MacPig as the correct decision factor here (as that's the origin file of this particular bitmap and the Mac files only use 640x480 files exclusively while being named like the 320x200 files of the PC game content).

**Comment by zicodxx** [comment]
I pushed 3672bbd1f26347277d1abe3f6c845b6771d86770 fixing the issue.
As suggested by @vLKp I didn't revert the commit. I did use the scaling logic employed for the exit door which is similar to what show_briefing_bitmap used before to get float scaling on resolutions that are just slightly higher than the base resolution and scale the bitmap more accurately and as well keep the aspect correct - and at the same time using the new casting and still retaining the use of show_fullscr(). 
I tested this in both the PC and Mac data (full and demo) and it seems to work fine.
