### ISSUE TITLE
passive Thief Bot

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#286]
In current builds (I still have to bisect), the Thief Bot is way more passive than in 0.58.1 and the original MS-DOS release.
What that means is that it is way less likely to try and steal from the player.

Example: 
Start Descent 2 Level 9. After loading of the level has finished, just sit there for ~10 seconds. In 0.58.1, the thief bot will visit you and steal an item from you. In current master build I have been sitting on the player spawn point for 2 minutes and the thief did not even attempt to open the door leading to the room the player spawns in.

EDIT: Upon bisecting, I must correct my steps for reproduction in so far that the Thief will not ALWAYS steal from the player in this scenario but often runs away as soon as it comes in view of the player. This also happens in the original game. But current master still shows the issue that the thief will not even come that close to begin with. It never enters the same room the player is located in (through the door left to the player starting point).
Upon finding a good commit to start bisecting, I can already conclude that the issue was introduced between Feb 28th 2015 and March 28th 2015.

**Comment by zicodxx** [comment]
I can now confirm that the bug reported above is caused by 2c09f9fa906ec586f48e3364d1237fe625309a33. A rathe rold one, submitted by @vLKp on March 12th 2015. It's a rather lengthy commit and glancing over it, I didn't see anything that caught my eye immediately. Tho I checked the commit immediately before it (f7d0c853ba878c6099a6667dcc7610d909c67f50) and that one works fine.

**Comment by vLKp** [comment]
The most likely reason for any bugs caused by that commit is that the thief is now confused about how close it is to the player, which could cause it to run away even when it is not yet close enough that it should run.

**Comment by zicodxx** [comment]
@vLKp I found the problem. In find_connected_distance() there are three cases which return vm_distance::maximum_value and previously returned -1 before 2c09f9fa906ec586f48e3364d1237fe625309a33.

Restoring this to return vm_distance{-1} fixes the Thief issue. This whole section DOES look a little odd since in these cases a distance of F1_0*1000 was previously added to the FCD cache which you also changed to vm_distance::maximum_distance - which makes sense. Then again the FCD cache is flushed every two seconds...

There are various parts of the code which obviously change behavior in this case. For example digi_get_sound_loc specifically checks for a case in which path_distance must be larger than -1 (which makes me wonder now if some weird audio issues I hard were not related to my rather cheap onboard soundchip) and there are several AI functions in escort.cpp which check if connected distance is smaller than F1_0*500 which break in this case. 

I assume that -1 is meant to be treated as a special case in which bots can occasionally find the player even if they are VERY FAR away. And it makes sense as especially the Guide Bot and the Thief are supposed to be able to find the player in any case. 

Personally I would like to go and restore find_connected_distance to return vm_distance{-1} again. Whether maximum_distance or F1_0*1000 is added to the fcd cache I don't think makes too much of a difference but I'd suggest the latter - just to keep the code here original and keep consistency of Connected_distance value of 1000 which is also added to FCD cache in this case.

**Comment by vLKp** [comment]
Based on your analysis, I pushed [Add workaround for passive thief bot](/dxx-rebirth/dxx-rebirth/commit/3a4eafac03c432560d291e9bb00a728a17c8af82) to change it back (and credit your analysis for identifying the cause).

I suppose this leads to a new bit of bug hunting advice: Whenever a regression makes no sense, look for suspicious uses of `-1` where negative values are otherwise prohibited or illogical (distances, indexes, or other unsigned quantities).  The original authors seem to be very fond of using a literal `-1` as an anonymous magic value.

**Comment by zicodxx** [comment]
Yes, I can confirm that your commit fixes the issue. 

and thanks for the hint. Yeah, I know about excessive usages of -1 in a lot of cases. In earlier versions they often were blatantly used as an array index, I am not even sure how the game ran as stable as it did (DOS4GW magic?).

**Comment by vLKp** [comment]
That hint was partly to you, but also partly as a reminder for myself and anyone watching, that when reviewing a "bad" commit that looks like it should be fine, special attention should be given to any lines that added/removed a `-1`.

As for stability under DOS4GW:

Accessing an array with an invalid index is Undefined Behavior.  The compiler is permitted to do anything when this happens.  The simplest thing to do, which many compilers will do in optimizing mode, is to assume that Undefined Behavior never happens and generate code without regard to what would happen if the Undefined Behavior occurs.  For arrays, this would mean that there is no check for a valid index and it will instead treat nearby memory as another element of the array.  In some cases, this is relatively harmless, particularly when the invalid access is a read of an integer value.  Nearby memory is often filled with values that, interpreted as integers, represent values that will not cause significant problems.  The game's extensive use of index values, rather than pointers, in its data structures made it less likely for garbage data to have a value that caused a major problem.  Additionally, DOS had such poor memory protection that even reading NULL was not necessarily fatal.  All this let the original game get away with a variety of errors that kill modern error-checking builds quickly.

On a slightly related note, my `valptridx` work makes it much more likely that invalid values are trapped quickly and verbosely, so that we know where they are introduced instead of seeing strange problem reports far removed from the actual bug.  Similarly, `partial_range` disallows creating ranges that exceed the underlying container.  This checking is what caused Blarget's level to crash on load instead of exhibiting the bizarre memory corruption that past releases showed.
