### ISSUE TITLE
'vector' not recognised in render.h (Mac OS X Yosemite)

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#29]
When I build in SCons I get this error:
> common/main/render.h:42:7: error: no type named 'vector' in namespace 'std'

After Googling it looks like it needs `#include <vector>` at the top of render.h but I thought I'd check first. After all, I only know bits and pieces of C++ at this stage.

**Comment by vLKp** [comment]
Yes, that is the correct fix.  On Linux, gcc headers happened to `#include <vector>` for other reasons, so this worked by accident.

It looks like the chain is:
* `render.h` included `"3d.h"`
* `"3d.h"` included `"vecmat.h"`
* `"vecmat.h"` included `<algorithm>`
* `<algorithm>` included `<bits/stl_algo.h>`
* `<bits/stl_algo.h>` included `<random>` for `std::uniform_int_distribution`
* `<random>` included `<bits/random.h>`
* `<bits/random.h>` included `<vector>` to implement `discrete_distribution`

This should be fixed by 3ad422a4bea332cd42db7ec4e0885f1d629c4c5c.
