### ISSUE TITLE
Mac OS X Clang Error on Latest Commit on Master (unused function)

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#295]
I tried building the latest commit f634b084ed5459050338782bc8925afea0140564 on Mac OS X (**master**) and I get this error from SCons:
```
CXX dxx . common/misc/vgwphys.cpp
common/misc/vgwphys.cpp:10:13: error: unused function 'dxx_vg_wrap_check_value'
      [-Werror,-Wunused-function]
static void dxx_vg_wrap_check_value(const void *, const void *, unsigned long);
            ^
1 error generated.
scons: *** [common/misc/vgwphys.o] Error 1
scons: building terminated because of errors.
```

**Comment by vLKp** [comment]
That function is only used if you have `DXX_ENABLE_wrap_PHYSFS_write` enabled (which defaults to the value of `DXX_HAVE_POISON_VALGRIND`, which in turn is 1 if `poison=valgrind` is set and 0 otherwise).  The current construct was the only way to avoid duplicating logic, adding ugly multiline macros, adding ugly preprocessor hook macros, or adding even more headers.  That declaration needs to exist before [`common/misc/vg-wrap-physfs.h`](/dxx-rebirth/dxx-rebirth/blob/55822d0b4db827176a2e13d039ee3606efe7d279/common/misc/vg-wrap-physfs.h) expands its uses of `DXX_VG_DEFINE_WRITE`.  To fix your error, it needs to exist only if those uses will be expanded.  However, without duplicating the logic or splitting the files, we do not know if those uses will be expanded until we are already evaluating [`common/misc/vg-wrap-physfs.h`](/dxx-rebirth/dxx-rebirth/blob/55822d0b4db827176a2e13d039ee3606efe7d279/common/misc/vg-wrap-physfs.h).

Interestingly, gcc with `poison=none` compiles this file successfully and produces no functions (which is correct).  I think the ugly preprocessor hook macro is the least bad choice available.  I pushed [Use ugly preprocessor hook hack to fix Clang build failure](/dxx-rebirth/dxx-rebirth/commit/2c4af523ddb1ad020a51222ca86cb5766166ebdf), which should resolve this.  I could not reproduce the original failure with `gcc`, but inspecting the preprocessor output of that commit confirms that the declaration is now absent in `poison=none` builds.

**Comment by kreatordxx** [comment]
Fixed, thanks @vLKp.
