### ISSUE TITLE
Proposed change: Increasing MAX_DELTA_LIGHTS, MAX_ROBOT_CENTERS, MAX_NUM_FUELCENS

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#300]
Usually I would hesitate to bring something like that up during the BETA phase but considering the heavy changes in the window/event handling, this is rather tame in comparison. 

During the run of the first BETA, players have hit limits with some levels:
1) Original LEVELS OF THE WORLD level VENUS PRODUCTION PLANT has 24 Robot Centers while the game allows 20 set via MAX_ROBOT_CENTERS. http://www.dxx-rebirth.com/frm/index.php/topic,1530.0.html
2) Blarget's level hits the MAX_DELTA_LIGHTS limit. http://www.dxx-rebirth.com/frm/index.php/topic,2140.0.html

@vLKp, you have already proposed to increase MAX_DELTA_LIGHTS from 10000 to to a potential segment maximum (65534) as I understand correctly. 

Additionally I would also like to raise MAX_ROBOT_CENTERS to fix the issues with VENUS PRODUCTION PLANT and potentially a few other levels as well. I think a limit of 255 would be more than sufficient (even is maximum segments are raised). The number is arbitrary as it's only used to specify the size of the array. Savegames with with Num_robot_centers. 
And while we're at it, I would propose doing the same change with NAX_NUM_FUELCENS. They work with the same rules regarding savegames (Num_fuelcenters) and increasing their numbers should not prove an issue either. 

And feedback, thoughts?

**Comment by vLKp** [comment]
The recent changes to the window/event handling are all on [`master`](/dxx-rebirth/dxx-rebirth/tree/master), but the beta is from [`unification/master`](/dxx-rebirth/dxx-rebirth/tree/unification/master).  You can roll all those changes into the beta if you want (by using a merge to the beta branch), but you are not obligated to take those changes into 0.60.  I have been publishing somewhat more aggressive changes to `master` on the expectation that it was not to be included in 0.60 in full.

No, I did not propose to raise anything to 65534.  I observed that raising `MAX_DELTA_LIGHTS` to 20000 was enough to make Blarget's level not crash.  He asked for more segments, and I observed that the maximum for segments is 65534 due to data structure limitations.

There is no use to raising `MAX_ROBOT_CENTERS` that high.  It controls the size of array `RobotCenters`, which is frequently indexed by `segment::matcen_num`.  Unfortunately, `segment::matcen_num` is declared as `sbyte` (a legacy type that is more commonly spelled `int8_t`).  Since this type is signed, any load will be sign-extended, so any value above 127 will access negative elements of `RobotCenters`.  Additionally, various code uses `-1` in `matcen_num` to mean None, so if we change the type to `uint8_t`, there might be odd effects from code that does not handle the unsigned type well.  Absent more invasive changes, the maximum useful value for `MAX_ROBOT_CENTERS` is 128, which would give us addressable elements `[0..127]`.

**Comment by roncli** [comment]
FYI, Retro increased MAX_DELTA_LIGHTS to 32000 for blarget some time last year.  I haven't noticed any issues with it, but am not entirely sure what I'd be looking for if it were broken. :) https://github.com/CDarrow/DXX-Retro/commit/c8937c282559624190998b8aee49d1d3fd9f6c6b

**Comment by vLKp** [comment]
Given its generally limited usage in the code, the main issue I would worry about is performance when many lights flicker.  The flickering light code searches the delta light table for affected segments.  Prior to some optimizations I made (which are not in Retro), that was a full table scan every time.  Even with a full table scan, the complexity is `Num_delta_lights * (number of lights flickered this frame)`, which is probably fairly manageable on most modern hardware.

**Comment by zicodxx** [comment]
@vLKp You were referring to the potential maximum segments to 65534 in that thread which I thought you implied raising MAX_DELTA_LIGHTS accordingly to at least technically match the maximum amount of segments (even tho having a level with each segment flicking would probably be a nightmare :D). 

But since Retro changed this up to 32000, I changed it to the same value to keep consistency in that regard: b644ab575c3f2fc80c9b68110d3d8c0b85785735.

As for Robot and Fuelcenters, you are right, I missed that sbyte. I raised both definitions to 128: 5acbb949ded8fb5f4ab862d51a44d0cbcda7a54e. I think that's plenty and it properly fixes the problematic levels in both cases.
