### ISSUE TITLE
Player loses keys collected on a secret level if they die

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#314]
If a player collects keys on a Descent 2 secret level (or types the ORALGROOVE cheat), then dies, any keys collected on that visit to the secret level are permanently lost. An example is with Level 4 of 
[Dr Moreau's Saga of Death](https://github.com/dxx-rebirth/dxx-rebirth/files/728724/Dr.M.Saga.zip).

This probably happened with the original game as well. I would argue that the player should keep the keys no matter what, just like when the player dies on a normal level.

Proposed fix in #313.

**Comment by vLKp** [comment]
I have always thought of the secret level/death mechanic as being that dying in the secret level rolls back all changes that happened inside the secret level.  If there are levels that rely on keeping state despite dying in the secret level, I have no objection to making Rebirth act differently than retail.

**Comment by zicodxx** [comment]
I agree with @vLKp. During investigation of #309, it's evident that dying in a secret level does roll the player back to a state as if died normally. But in a normal case this does not revert the keys. Since D2 never had secret levels with keys (to my knowledge) I think this is merely an oversight that never surfaced. So having Rebirth act differently - and correctly in my opinion - makes sense.
