### ISSUE TITLE
(D2) Level 24 boss is vulnerable to shots from front

### ISSUE THREAD

**Issue by ryusei117** [dxx-rebirth/dxx-rebirth#332]
Tested versions with this bug:
D2X-Rebirth 0.59.100
D2X-Rebirth commit 986c76e00f0834feb1f8c0b168b2e35a8fb4f0ce

Tested versions without this bug:
D2X-Rebirth 0.58.1

The boss robot of Descent 2: Counterstrike!, level 24 normally takes no damage when shot from the front (and also reflects energy weapon projectiles); it must be shot in the back. In recent development versions of D2X-Rebirth, however, you can destroy the boss by shooting its front with any weapon. Strangely enough, shooting the boss from the front still produces the correct "invulnerable" sound effect, and energy weapon projectiles still reflect as usual.

Also, when shot from the front with the Fusion Cannon, the boss normally reflects a massive barrage of Fusion Cannon projectiles - but that isn't working in D2X-Rebirth development versions either. The boss now reflects only one Fusion Cannon shot (two projectiles). I wonder if that's a related bug?

**Comment by vLKp** [comment]
> Also, when shot from the front with the Fusion Cannon, the boss normally reflects a massive barrage of Fusion Cannon projectiles - but that isn't working in D2X-Rebirth development versions either. The boss now reflects only one Fusion Cannon shot (two projectiles). I wonder if that's a related bug?

Yes.  Parallax got this wrong.  I noticed it several years ago, and finally filed it in November 2016 as [Excess reflected fusion shots](/dxx-rebirth/dxx-rebirth/issues/269), then analyzed and fixed it in [Fix excess fusion reflection](/dxx-rebirth/dxx-rebirth/commit/1f929796c3ad9d348e46f3ed27e0673b77594c83).  Looking at that commit, some of the nesting looks like it may be wrong.  There is a spurious brace that I misread at the time, causing the sound effect to be guarded, but the remainder of the damage processing block is improperly unguarded.

**Comment by vLKp** [comment]
[Fix ordering of boss weapon collision test](/dxx-rebirth/dxx-rebirth/commit/f03fee7eca5b1b9256e403c23c30a806484297e3) should resolve this.

**Comment by ryusei117** [comment]
Yep, the boss is once again invulnerable to shots from the front. Thanks!

So the huge Fusion reflection reaction was actually a bug from the original engine ... I never realized that wasn't intentional! Kind of disappointing that it's been removed; I always thought it was a cool-looking effect. But I guess there's always DOSBox for playing with original bugs like this ...

**Comment by vLKp** [comment]
I consider it a bug, based on [a comment in the original source](/dxx-rebirth/dxx-rebirth/blob/9bd1ba7c4748a77d1e8dab0d898f79bedba22eac/main/collide.c#L1539):

```c++
			//	Make a copy of this weapon, because the physics wants to destroy it.
```

Whoever wrote that (true attribution is unknown, since it was present when btb imported the source drop from Parallax) seems to have expected that the original player-fired shot would be deleted soon after, and for all non-fusion weapons, that expectation holds.

As for disappointing - reverting that commit conflicts due to the fix added here, but a semantic revert (under guard of an appropriate conditional) is likely not that difficult.  I fixed the bug because the reflected shots did not work properly (among other things, they were always owned by player zero, not the player who fired them).  If there is community interest in resurrecting bugs which had neat effects, rather than causing serious problems, I am not opposed to providing some way to bring back those effects.

**Comment by ryusei117** [comment]
I wonder if I should ask around and determine how players feel about this issue. I have a feeling I won't get many responses, but I might try talking to some of the Rangers directly. But yeah, that would be my vote - to restore the Fusion barrage effect while fixing the quirks, such as always being owned by player zero. Another quirk I noticed is that the Fusion barrage is frame rate-dependent: the boss seems to reflect projectiles every frame. Ultimately, it's up to you guys whether this is worth the trouble, of course. :-)

**Comment by vLKp** [comment]
The framerate dependence is a good point.  My framerate is stable enough that I never noticed it, but now that you mention it, I cannot recall anything that would prevent that problem.  The entire game was designed to be framerate dependent.  Zico has been adding ad-hoc workarounds for things by scaling to `FrameTime` or adding local governors to prevent excessive instances when the user has a high frame rate, but I expect we will keep stumbling into framerate sensitive events unless the event loop is overhauled to separate rendering from processing.

As for responses, take your time.  Extrapolating forward, you have quite a while before the next release comes out. ;)  If this gets changed, I would like to do it right.  So far, the defects I know of are:

1. Always attributed to player 0.  Easy to fix.  Copy parent information from the weapon, or reset the parent to the boss robot.
2. Framerate dependant generation.  Theoretically easy to fix by adding yet another ad-hoc counter, but ugly.
3. Not synchronized in multiplayer.  No messages are sent to coordinate the generated weapons with other players' screens.

**Comment by vLKp** [comment]
@ryusei117: any feedback from your player group as to whether this will be missed?

**Comment by ryusei117** [comment]
@vLKp: Not much, unfortunately. I asked a few of them during our monthly Co-op Saturdays, but none of the players I asked had a strong preference either way, and lately there have been very few Co-op players around to ask. :-\ Verran did make a general statement that some bugs become accepted as gameplay elements - for example, trichording was originally unintended program behavior that just so happened to enhance the gameplay by demanding more skill from the player. I'm not sure this Fusion barrage bug falls into that category, though, as it's mostly something that a player would trigger by accident.

So I guess this can be summarized as a cool visual effect generated by some sloppy code. :-) If it's too awkward to keep it in the game, though, I'm totally fine with using DOSBox when I want to play with the original engine's bugs. (I already use DOSBox to play with 320 x 200 software-rendered graphics without needing an ancient CRT display that supports the 320 x 200 resolution properly. :-P )

**Comment by vLKp** [comment]
It'd be a bit awkward to implement properly, but I'm not strongly opposed to doing so.  For now, I will close this issue (since the boss is again properly invulnerable).  If you (or anyone who finds this later) feel strongly that the multiple reflection should be restored, please file a new issue (and reference this one in the opening comment, so that anyone reading this issue can easily find that one).  Regarding the defects above:

1. Weapon ownership is trivial to fix.
1. Framerate sensitivity is ugly to fix quickly, but easy.  There are plenty of ad-hoc framerate limiting governors in the code (unfortunately), so one more to stabilize this effect is not a huge impact.
1. Multiplayer sync is a bit ugly to fix because any newly generated objects need to be tracked and explicitly passed to the multiplayer code.
