### ISSUE TITLE
(D2) Yellow Door is invisible on Coralbank Quarry (v0.59.100)

### ISSUE THREAD

**Issue by LordKane1701** [dxx-rebirth/dxx-rebirth#334]
On level 7 (Coralbank Quarry) of D2 the yellow door is invisible and does not render. if you fire a flare or weapon into it with a key it will function as normal (you will even hear the door open) 
it does not prevent progress.

**Comment by vLKp** [comment]
This sounds like a duplicate of [[D2X-R 0.60 beta 1 Windows 7] Level 7 yellow door invisible](http://www.dxx-rebirth.com/frm/index.php/topic,2133.0.html) reported by Yarn on 2016 December 21 and fixed by me on 2016 December 24 in [Scrub invalid primary textures at level load](/dxx-rebirth/dxx-rebirth/commit/d085175cbd2e3a5248d9654bb6af2f0a3e08855a).

**Comment by LordKane1701** [comment]
so does that mean it will be fixed in the next beta update?

**Comment by vLKp** [comment]
Yes.

**Comment by LordKane1701** [comment]
Awesome, Closing issue.
