### ISSUE TITLE
Mingw64: compiler segmentation fault in template substitution in common/2d/bitblt.cpp

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#335]
When trying to compile the latest master for Windows I get the following error:

```
common/2d/bitblt.cpp: In substitution of ‘template<class F> void dcx::gr_for_each_bitmap_line(grs_canvas&, unsigned int, unsigned int, const grs_bitmap&, F) [with F = <missing>]’:
common/2d/bitblt.cpp:82:50:   required from here
common/2d/bitblt.cpp:82:50: internal compiler error: Segmentation fault
  gr_for_each_bitmap_line(canvas, x, y, bm, memcpy);
                                                  ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
scons: *** [common/2d/bitblt.o] Error 1
scons: building terminated because of errors.
```

**Comment by vLKp** [comment]
[Current master](/dxx-rebirth/dxx-rebirth/commit/17a09d83d20518ba983272854677a0bb6dc2ccb2) builds fine for me with `x86_64-pc-linux-gnu-gcc-4.9.4` and `mingw32-gcc-5.4.0`.  That message is generated by gcc, not by me.  It is a directive to report the problem to the gcc maintainers because the compiler **crashed** trying to process a source file.  That should never happen.  Since I cannot reproduce the problem, and you did not specify the tool versions involved, my ability to address this is limited.  You could try the below patches, but I doubt they will help:

```diff
--- a/common/2d/bitblt.cpp
+++ b/common/2d/bitblt.cpp
@@ -79,7 +79,7 @@ static void gr_for_each_bitmap_line(grs_canvas &canvas, const unsigned x, const
 
 static void gr_ubitmap00(grs_canvas &canvas, const unsigned x, const unsigned y, const grs_bitmap &bm)
 {
-	gr_for_each_bitmap_line(canvas, x, y, bm, memcpy);
+	gr_for_each_bitmap_line(canvas, x, y, bm, &memcpy);
 }
 
 #if !DXX_USE_OGL
```

```diff
--- a/common/2d/bitblt.cpp
+++ b/common/2d/bitblt.cpp
@@ -25,7 +25,7 @@ COPYRIGHT 1993-1999 PARALLAX SOFTWARE CORPORATION.  ALL RIGHTS RESERVED.
 
 #include <algorithm>
 #include <utility>
-#include <string.h>
+#include <cstring>
 #include "u_mem.h"
 #include "gr.h"
 #include "grdef.h"
@@ -79,7 +79,7 @@ static void gr_for_each_bitmap_line(grs_canvas &canvas, const unsigned x, const
 
 static void gr_ubitmap00(grs_canvas &canvas, const unsigned x, const unsigned y, const grs_bitmap &bm)
 {
-	gr_for_each_bitmap_line(canvas, x, y, bm, memcpy);
+	gr_for_each_bitmap_line(canvas, x, y, bm, std::memcpy);
 }
 
 #if !DXX_USE_OGL
```

**Comment by Mako88** [comment]
Neither of those helped (the first had the same problem, the second said memcpy is not a part of std).

I'm using mingw g++ 6.3.1 on Arch Linux.

**Comment by vLKp** [comment]
> Neither of those helped (the first had the same problem, the second said memcpy is not a part of std).

Strange.  `std::memcpy` exists on `x86_64-pc-linux-gnu-g++`.  As part of `namespace std`, I would expect it to be available on all standard conforming platforms.

> I'm using mingw-w64-g++ 6.3.1 on Arch Linux.

That is good news.  As a very recent version of gcc, it is more likely that you can get someone interested in patching it not to crash.  Compilers should never crash, even when given an ill-formed program; as far as I know, this program is not ill-formed.  I cannot reproduce this crash using `x86_64-w64-mingw32-gcc`, which also targets 64-bit Windows.  Oddly, the newest 6.3.x gcc from upstream seems to be 6.3.0.  I do not know why yours on Arch is 6.3.1.

**Comment by vLKp** [comment]
I modified the issue title to more clearly describe the problem.  I am not opposed to modifying the code to work around a compiler bug (this has been necessary several times for clang); however, since I cannot reproduce the fault, and none of the obvious changes helped, I am not presently trying to resolve this.  If you can propose a minimal patch to prevent the compiler crash, and it has no other side effects, I will look at merging it.

**Comment by vLKp** [comment]
I pulled the [Arch Linux PKGBUILD file for mingw-w64-gcc](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/mingw-w64-gcc).  It looks like Arch Linux packaged a pre-release snapshot of gcc 6.3.1 (still not released at the time of this writing) rather than packaging the tagged 6.3.0 release.  I do not know why they did this, but I see nothing in the gcc commit history between [gcc tag 6.3.0](https://gcc.gnu.org/git/?p=gcc.git;a=shortlog;h=refs/tags/gcc-6_3_0-release) and [Arch Linux snapshot 4ca53f06ff7d346ef8021a23108f23a5406a0417](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=4ca53f06ff7d346ef8021a23108f23a5406a0417) that, in my admittedly non-expert opinion, looks like it would account for the difference between my working toolchain and your faulting toolchain.

I was not able to find any bug reports about this compiler fault on Arch Linux or on gcc upstream.  Could you link to the relevant report(s)?

**Comment by vLKp** [comment]
While working on an [unrelated project](/dxx-rebirth/dxx-rebirth/commit/9478d1e6a5f13ade7e6ab27008f31c7d7a895390), I needed to try out `i686-w64-mingw32-g++-6.3.0` to see how it would handle my changes.  In this context, `i686-w64-mingw32-g++-6.3.0` is a cross-compiler targeting 32-bit Windows, not the 64-bit that you tried to use.  `x86_64-w64-mingw32-g++-6.3.0` handles this code correctly.  `i686-w64-mingw32-g++-6.3.0` crashes with an error that looks very similar to the one you posted, though mine also includes a partial compiler backtrace.

Using `i686-w64-mingw32-g++-6.3.0`, I tested a [workaround](/dxx-rebirth/dxx-rebirth/commit/49cc3aa3243cc2bb2f6ed5d22e252c6873863cbc) that prevented the crash for me.  Please try it in your environment.

**Comment by Mako88** [comment]
That worked! I'll post the builds on the forums :)

Thanks!
