### ISSUE TITLE
[D2X latest git - OSX] Level ending cutscenes - no video

### ISSUE THREAD

**Issue by Havner** [dxx-rebirth/dxx-rebirth#345]
This one is strange. I've managed to build latest release on OSX and everything works fine except the level ending videos. Strangely enough sound is playing for them, just not the video, the screen remains black. It also doesn't happen 100%, but still most of the times. For my testing I've had the issue 15 times and just once managed to get it to play (and I'm not even sure now it did work that one time, cannot reproduce again).

All the other videos (intro/briefing bots videos/chapter start) play just fine.

I have not encountered this issue on latest window nightly. This might be related to latest commits or just to OSX in general. I've built using SDL frameworks and physfs from macports.

Not sure how to debug this one, nothing strange is happening. Nothing in the gamelog.txt, just the regular:
`21:39:36 You have escaped the mine!`

I can try to assist with the debugging, just point me in the right direction if you can't reproduce this.

EDIT: just to be clear, it works fine for me on 0.58.1 on the same data files. Using hires movies. "Smooth cutscenes" option is irrelevant to this issue.

**Comment by Havner** [comment]
Another clarification. The build I've managed to get is 64bit. SDL frameworks and physfs from macports are 64bit and that's the default setting of the compiler.

I've tried to get a 32bit build and I did (-m32) using Frameworks and physfs from 0.58.1 (just added physfs header), but it doesn't run for me:

`similar/arch/ogl/gr.cpp:368: ogl_init_window: error: Could not set 1920x1200x32 opengl video mode: Error setting OpenGL fullscreen: invalid fullscreen drawable`

So I cannot check whether the 32/64 cause the problem or macports frameworks. 0.58.1 downloadable from the webpage is only 32 bits.

**Comment by Havner** [comment]
I've managed to get a working 32bit build using SDL/SDL_mixer Frameworks downloaded directly from their homepage. Still no go for the ending videos. So this is not 32 vs 64bit bug.

**Comment by vLKp** [comment]
What cutscenes are missing?  Is this the autonomous sequence of the Pyro flying through an exploding tunnel and emerging on the surface of a planetoid, a pre-rendered video, a post-mission debriefing, or something else?  On which levels should I observe the cutscene when it plays successfully?  I thought the Pyro sequence happened only in Descent 1.  I don't recall ever seeing it in Descent 2.

Since it fails for you fairly frequently, could you try to bisect history to see where it first broke?  That may give some hint as to how it is broken.  0.58.1 was a long time ago (more than 4 years), and most things have been touched since then.  You could try the 0.59.100 Mac beta from last December as an initial data point.

Also, as a minor tip, please do not use "latest git" to indicate the version you tested, since that will change over time.  Instead, identify the Git commit you tested.

**Comment by vLKp** [comment]
In [an unrelated thread (*Is it possible to lower the volume of the pre-rendered cutscenes?*)](https://forum.dxx-rebirth.com/showthread.php?tid=986), a chance comment from @ryusei117 led me to the answer to the question I posed immediately above: the missing cutscenes are pre-rendered movies triggered by flying through the exit trigger in game.  In Descent 1, this trigger provokes a special automated flight mode, where the game's normal engine is used to move a game-controlled Pyro through the exit tunnel.  In Descent 2, that was replaced with pre-rendered movies.  However, the movies are silently skipped if the movie files are not installed.  I had not installed the movie files, so my game always jumped immediately to the post-level score screen.

Once I knew what was missing, I was able to investigate.  I found that the problem occurs on Linux, and bisected it to [Track visited segments as a local](/dxx-rebirth/dxx-rebirth/commit/03cca2b3dce62ae29c1ab7509df5105423365b4a), which made no sense, but multiple iterations confirmed: when that commit was present, movies were blank; when it was absent, movies worked.  I rebuilt with AddressSanitizer, reproduced the problem, and was immediately rewarded with a crash.  Movie code was following a global pointer to a dead variable and overwriting unrelated stack data that occupied the space previously held by a temporary canvas.  Prior to [Track visited segments as a local](/dxx-rebirth/dxx-rebirth/commit/03cca2b3dce62ae29c1ab7509df5105423365b4a), the overwritten stack space was apparently unimportant, so the overwrite had no observable negative side effects.  That commit added a large local variable, which changed stack layout, which must have moved something important to a location corrupted by the invalid store.

[Clear canvas to fix missing exit tunnel movie](/dxx-rebirth/dxx-rebirth/commit/ca804d518682e248617639b5a342f6ed1195d414) resets the global canvas pointer to the default canvas so that it does not point to a dead variable.  This fixes the failure for me.  The global canvas pointer ought to be removed to prevent other bugs like this.

**Comment by Havner** [comment]
Sorry for not getting to that myself. It's been too long on my TODO list (disecting myself).

I've checked latest git, it works fine so I can confirm it's been fixed on OSX too.
Unfortunately while testing this I've run across another 2 issues ;-). Will report in a separate bugs.
