### ISSUE TITLE
'srcdir' not defined in scons

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#350]
While trying to compile the latest, I get the following error:

```
scons: Reading SConscript files ...
NameError: name 'srcdir' is not defined:
  File "/home/john/dxx-rebirth/SConstruct", line 3887:
    class DXXArchive(DXXCommon):
  File "/home/john/dxx-rebirth/SConstruct", line 3937:
    'texmap/scanline.cpp'
  File "/home/john/dxx-rebirth/SConstruct", line 3894:
    __get_objects_common=DXXCommon.create_lazy_object_getter([os.path.join(srcdir, f) for f in [
Compilation failedn
```

**Comment by vLKp** [comment]
I generally try to test before pushing, so things broken for me usually don't get out.  That applies here.  Current tip of tree is [Remove obsolete D1 hostage editor code](/dxx-rebirth/dxx-rebirth/commit/8d80300e0a9e8f9b567b665fe8b077372936cb4c), which builds fine for me using:
```
$ scons --version
SCons by Steven Knight et al.:
        script: v2.4.1.rel_2.4.1:3453:73fefd3ea0b0, 2015/11/09 03:25:05, by bdbaddog on ubuntu1404-32bit
$ python2 --version
Python 2.7.12
```

Assuming *latest* means that tip, this would be:

https://github.com/dxx-rebirth/dxx-rebirth/blob/71cfd9bc6ca230ae3893e14e8c3ee617cacf348f/SConstruct#L3890-L3894

This code has not been changed in a very long time.

[Github blame for that area](https://github.com/dxx-rebirth/dxx-rebirth/blame/master/SConstruct#L3890) says the assignment lines are from 2013-03-03.  The function definition line is much more recent, from 2016-08-19, making it only about 14 months old.  Since you have built successfully during that 14 months, the problem is most likely in your environment.  Perhaps you are using some Python implementation that fails to search the containing class.  I cannot tell if this is the cause since you did not provide any identifying data.  If you provide enough information that I can reproduce the problem or refine my speculation, I will investigate further.

**Comment by vLKp** [comment]
Other users have built successfully in a variety of configurations:

* psyke83 for Raspberry Pi
* ef314159 for Windows
* Me for Linux

No response from original reporter.  Closing pending more information.  If this still fails for you, please reopen and provide more information.

**Comment by Rouji** [comment]
The problem is with python3 somehow. Either use a python2 version of scons (if available), or just explicitly run it using python2: 
```python2 `which scons` ```

**Comment by vLKp** [comment]
The problem _was_ with Python3.  I switched to a Python3-enabled SCons in April and fixed up all known failures caused by it.

* [Fix parsing SConstruct file lists in Python 3](/dxx-rebirth/dxx-rebirth/commit/1c0001d31d71fc1ff8f6dddb921f74586d255d92)
* [Add compatibility shims for Python 3 dictionary API change](/dxx-rebirth/dxx-rebirth/commit/a3d6bdd3f1a642df29df3b61dc2b53120a6308e8)
* [Adapt PreservedEnvironment to Python 3 dictionary API changes](/dxx-rebirth/dxx-rebirth/commit/8b4586bd2083e5a591b4aee1df43d800a1e19322)
* [Adapt configure tests to Python 3 filter API change](/dxx-rebirth/dxx-rebirth/commit/6148327e4b540bde9d49e12183cd896204cdb74b)
* [Adapt to Python 3 strict bytes vs str rules](/dxx-rebirth/dxx-rebirth/commit/0a5e9eb592a4be39d64d53b554c98017a965ce5d)
* [Adapt PCHManager to Python 3 `__new__` rules](/dxx-rebirth/dxx-rebirth/commit/7249e4569f3664f110d2b25441f274f52174c67f)

I suspect the topmost of those is the fix for the issue originally reported here.  They look similar, at least.  @Mako88 never responded to describe the build environment though, so this is speculation.

Are you seeing this problem in a current checkout?
