### ISSUE TITLE
Xbox One Game Pad Controller for Windows 10 LT and RT Triggers not programmable 

### ISSUE THREAD

**Issue by DescentMax** [dxx-rebirth/dxx-rebirth#355]
All the buttons work brilliantly except for the back left and right triggers (LT RT). I cannot get the game to recognize those two triggers. Windows Recognizes them as Z axis on the gamepad settings.

**Comment by vLKp** [comment]
As I have neither an Xbox Game Pad Controller nor Windows 10, I cannot address this without more detail.  What SDL event is generated to the game when you press the non-functioning triggers?

**Comment by DescentMax** [comment]
When I click the triggers nothing happens. I went to the game log and this is what is shown:

21:14:51 D1X-Rebirth v0.59.100 0.59.100-743-g425b78b8a63b  Nov  8 2017 19:04:57
21:14:51 This is a MODIFIED version of Descent, based on Registered v1.5 Jan 5, 1996.
21:14:51 Copyright (C) 1994, 1995 Parallax Software Corporation
DESCENT is a trademark of Interplay Productions, Inc.
21:14:51 Copyright (C) 2005-2013 Christian Beckhaeuser
21:14:51 Using SDL_mixer library v1.2.12
21:14:51 sdl-joystick: 1 joysticks
21:14:51 sdl-joystick 0: Controller (Xbox One For Windows)
21:14:51 sdl-joystick: 5 axes
21:14:51 sdl-joystick: 10 buttons
21:14:51 sdl-joystick: 1 hats
21:14:51 sdl-joystick: 5 axes (total)
21:14:51 sdl-joystick: 14 buttons (total)

Here is my specs
Windows 10 Pro 64-Bit
12GB DDR3
AMD FX 6300 3.5GHz 4.1GHz Turbo
240GB SSD
NVIDIA 650TI 2GB GDDR5
Realtek HD Audio
D1x and D2x 0.59.100-743-G425B78B8A63B ( latest November Nightly build)

**Comment by vLKp** [comment]
If nothing happens when you press them, that suggests the system is not passing those events to the game at all.  If the game is not notified you pressed the trigger, how is it supposed to react to the trigger being pressed?

That does not look like `-debug` output, so SDL events are not logged.  When logging SDL events, you should get lines like (for mouse):

```
Sending event EVENT_MOUSE_BUTTON_DOWN, button 0, coords 160,244,0
Sending event EVENT_MOUSE_BUTTON_UP, button 0, coords 160,244,0
```

These lines should be generated for every button press while in game.

How exactly did you determine that you cannot get the game to recognize these triggers?  To which control axes (`Pitch U/D`, `Turn L/R`, `Slide L/R`, `Slide U/D`, `Bank L/R`, or `Throttle`) did you try to bind these triggers?

**Comment by ryusei117** [comment]
I think I might know what's happening here ... Most modern gamepads (including the Xbox One Controller) have analog triggers, enabling them to control analog functions like the gas and brake pedals in a car as well as digital functions like firing weapons. Players who use gamepads often want to use the triggers to fire weapons, since that's pretty much standard practice. The problem is that Descent and Descent II have never supported binding analog axes to digital game controls the way modern games do. So basically, this is more of a feature request than a bug report. :-) I can see that the numbers of buttons, axes, and hats in DescentMax's game log are reasonable for an Xbox One Controller, so the detection is probably working correctly.

[Here's a similar thread about gamepad triggers on the forum.](https://forum.dxx-rebirth.com/showthread.php?tid=540&pid=7764#pid7764)

One thing that's *incredibly* irritating, though, is that Windows seems to detect the two triggers on an Xbox One-style gamepad as a single axis. If you press them simultaneously, Windows thinks the "axis" is centered, as if neither trigger is pressed. (-_-); GNU/Linux correctly detects the triggers as separate axes that are at their minimum value when fully released and at their maximum value when fully pressed. Modern Windows games usually use Microsoft's XInput API, which detects the triggers correctly - but naturally, it's not cross-platform.

**Comment by DescentMax** [comment]
Gotta love Windows and Microsoft haha. I am trying to get the LT to slide up and RT for Primary Weapon but when I click LT and RT nothing happens. Its like the game doesn't detect I am pressing the triggers but I see what you are saying.

**Comment by vLKp** [comment]
`Slide Up` or `Slide U/D`?  They are different controls.

As @ryusei117 says, you will not be able to bind the trigger to `Fire Primary` because Windows reports the trigger as an analog input, and `Fire Primary` is a button (boolean) input.  You cannot half-press a button, but you can half-depress an analog input.  For the same reason, you cannot bind the trigger to `Slide Up` (nor `Slide Down`, `Slide Left`, `Slide Right`) because those are also button inputs.  You must bind analog inputs (reported as an axis in the Windows control panel) to analog events (reported as axis in the Descent controls panel).  You must bind button inputs to button events.

**Comment by roncli** [comment]
A bit late on this, but I realized someone's already doing this.  There's a player b2af that uses a piece of software called XPadder to allow him to use triggers as if they are buttons.

XPadder: https://www.xpadder.com/?lang=english&country=US

b2af's discussion about the XB One Elite controller: http://descentchampions.org/forum/viewtopic.php?f=4&t=807&p=7787

**Comment by vLKp** [comment]
I have some incomplete patches intended to allow input remapping.  I hope to publish them soon.

**Comment by xStedmanx** [comment]
Does anybody know how to re-program the RT and LT triggers to input as analog button presses instead of being on axis?

**Comment by vLKp** [comment]
Are you asking how to configure this in Rebirth or how to configure it in your chosen operating system?  You cannot do this in Rebirth at this time.  Your operating system may support this outside Rebirth.  I hoped to publish patches for it in Rebirth, but I never finished the UI for managing the remapping.  It's still sitting around unfinished.  Other projects took priority.
