### ISSUE TITLE
Flare doesn't always work after loading a save game

### ISSUE THREAD

**Issue by asacchetto** [dxx-rebirth/dxx-rebirth#357]
Flares stop working after loading a save game. Basically you press the flare key and nothing happens. After completing the current level or dying, it starts to work again. I found this issue with d1x-rebirth-0.59.100.

**Comment by vLKp** [comment]
If I recall correctly, that is a known issue in [v0.59.100](/dxx-rebirth/dxx-rebirth/releases/tag/0.59.100) and was fixed in [Narrow scope of state_restore_all_sub variables](/dxx-rebirth/dxx-rebirth/commit/44d153696940e36e52428911083dc8a453dee43d) (Dec 2016).  Please retry with a current nightly build.

**Comment by vLKp** [comment]
No response from reporter after 6 weeks.  Issue is suspected to be a known bug in the reported version, which was fixed more than a year ago.  Closing.

OP: please reopen if you observe the issue using a recent snapshot build.
