### ISSUE TITLE
New target OpenBSD?

### ISSUE THREAD

**Issue by thfrwn** [dxx-rebirth/dxx-rebirth#360]
d1x-rebirth builds nicely on OpenBSD (still working on getting d2x to build). Any objections to an OpenBSD target? Also see my pull request in that regard. thx

**Comment by vLKp** [comment]
I welcome more supported platforms, but question your implementation.  The platforms list is primarily present because each of Mac/Windows/Linux require handling that at least one of the other two does not require.  Your addition seems at first glance to have no purpose, so I would like to understand it and perhaps include a comment for the understanding of later readers.  I will post specific comments in your pull request.

As for d2x, if you require assistance, please ask.  I do not use OpenBSD, but I may be able to explain any errors you see.

**Comment by thfrwn** [comment]
Thanks for the replies. This project is really awesome - I just played through the 1st level of d1x and it's fantastic!

we got d2x fixed by locally disabling -Werror in SConstruct, if I understand bcallah@'s adjustments correctly.

my goal with the pull request would be to account for openbsd as a non-linux unix target which will make it easier to maintain a working port in sync with your development. This can open the door to other *nixes, most significant of which (in terms of user numbers) would probably be FreeBSD. I'm not running it, but if you are interested in a more general inclusion of BSD targets, I'd be happy to look into it and try to adjust patches for that purpose.

**Comment by vLKp** [comment]
I'm not familiar with bcallah.  Could you link to the adjustment in question?  You shouldn't need to disable `-Werror`.

Yes, support for the other members of the BSD family would be fine.  You'll probably need to whitelist them as you did with `openbsd6` here.

**Comment by thfrwn** [comment]
here is the mail with the port submission with tarball that contains the patch. Please let me know if you prefer that I just send/post the SConstruct diff! bcallah is one of the openbsd devs.

https://marc.info/?l=openbsd-ports&m=151405497906459&w=2

**Comment by vLKp** [comment]
That tarball is fine (but it'd be nice if the patch files ended in `.patch` so that editors would automatically set syntax rules ;)).

Interestingly, the lambda capture issue mentioned in https://marc.info/?l=openbsd-ports&m=151402743101761&w=2 is a harmless Rebirth bug, not a clang bug.  The automap pointer does not need to be captured, so clang is correct to warn about it.  [Remove unused lambda capture in draw_all_edges](/dxx-rebirth/dxx-rebirth/commit/071a1dd48629ec4c26851a2367d0a56e495268e4) should fix this for you.

As for the patches, it looks like the author didn't understand at least some of what he was doing.  At the very least, the changes could use better documentation.

> patch-similar_main_mglobal_cpp
```diff
$OpenBSD$

Always enable full template instantiation.

Index: similar/main/mglobal.cpp
--- similar/main/mglobal.cpp.orig
+++ similar/main/mglobal.cpp
@@ -117,7 +117,7 @@ valptridx<wall>::array_managed_type Walls;
 #if (defined(__NO_INLINE__) && __NO_INLINE__ > 0)
 #define DXX_VALPTRIDX_ENABLE_FULL_TEMPLATE_INSTANTIATION	1
 #else
-#define DXX_VALPTRIDX_ENABLE_FULL_TEMPLATE_INSTANTIATION	0
+#define DXX_VALPTRIDX_ENABLE_FULL_TEMPLATE_INSTANTIATION	1
 #endif
 #endif
 
```

This should only be needed if the compiler emits dead uses of symbols.  If so, the patch ought to document what fails when it is not used.  It's possible that there is a real bug hidden here, but without knowing what symbol(s) were missing, I cannot say.

> patch-similar_main_inferno_cpp
```diff
$OpenBSD$

account for __OpenBSD__ in ifdefs

Index: similar/main/inferno.cpp
--- similar/main/inferno.cpp.orig
+++ similar/main/inferno.cpp
@@ -95,7 +95,7 @@ char copyright[] = "DESCENT II  COPYRIGHT (C) 1994-199
 #endif
 #include "event.h"
 #include "rbaudio.h"
-#ifndef __linux__
+#if !defined (__linux__) && !defined (__OpenBSD__)
 #include "messagebox.h"
 #else
 #if DXX_WORDS_NEED_ALIGNMENT
@@ -673,7 +673,7 @@ static int main(int argc, char *argv[])
 int main(int argc, char *argv[])
 {
 	mem_init();
-#ifdef __linux__
+#if defined (__linux__) || defined (__OpenBSD__)
 #if DXX_WORDS_NEED_ALIGNMENT
 	prctl(PR_SET_UNALIGN, PR_UNALIGN_NOPRINT, 0, 0, 0);
 #endif
```

It'd be nice if the patch description was a little more verbose, but informed readers can work it out.  This is included in your pull request (aside from the confusion of when to use `||` versus `&&`).  [Treat OpenBSD as Linux for msgbox handling](/dxx-rebirth/dxx-rebirth/commit/2b058c7150000169af810fc3c8311d695e4eb829) applies this change (with credit, but no history, due to the .orig files in your pull request).

> patch-similar_editor_med_cpp
```diff
$OpenBSD$

account for __OpenBSD__ defined

Index: similar/editor/med.cpp
--- similar/editor/med.cpp.orig
+++ similar/editor/med.cpp
@@ -891,7 +891,7 @@ static void close_editor()
 {
 	//	_MARK_("end of editor");//Nuked to compile -KRB
 	
-#ifndef __linux__
+#if !defined (__linux__) && !defined(__OpenBSD__)
 	set_warn_func(msgbox_warning);
 #else
 	clear_warn_func();
```

Same comment as previous patch.  It probably should have been all in one file, since it was all for the same purpose.

> patch-SConstruct

This is the big one, and the one where I question whether the author understood the implications of the changes.

> patch-SConstruct
```diff
Index: SConstruct
--- SConstruct.orig
+++ SConstruct
@@ -803,7 +803,6 @@ help:assume C++ compiler works
 		forced, expected = self._check_sconf_forced(calling_function)
 		caller_modified_env_flags = self.PreservedEnvironment(context.env, self.__flags_Werror.keys() + testflags.keys())
 		# Always pass -Werror
-		context.env.Append(**self.__flags_Werror)
 		context.env.Append(**testflags)
 		# If forced is None, run the test.  Otherwise, skip the test and
 		# take an action determined by the value of forced.
```

This change looks wrong, and was probably done in an attempt to eliminate all uses of `-Werror` without regard to context.  Configure tests always set `-Werror` because some tests only detect the right result when warnings are errors.

> patch-SConstruct
```diff
@@ -1736,7 +1735,7 @@ help:assume compiler supports __attribute__((unused))
 		self._check_macro(context,macro_name=macro_name,macro_value=macro_value,test="""
 __attribute_unused
 static void a(){}
-""", msg='for function __attribute__((unused))', successflags={'CXXFLAGS' : [get_Werror_string(context.env['CXXFLAGS']) + 'unused']})
+""", msg='for function __attribute__((unused))', successflags={'CXXFLAGS' : 'CXXFLAGS'})
 	@_custom_test
 	def check_attribute_warn_unused_result(self,context):
 		"""
@@ -2285,7 +2284,7 @@ $ x86_64-pc-linux-gnu-g++-5.4.0 -x c++ -S -Wformat -o 
 	@_custom_test
 	def check_compiler_useless_cast(self,context):
 		Compile = self.Compile
-		flags = {'CXXFLAGS' : [get_Werror_string(context.env['CXXFLAGS']) + 'useless-cast']}
+		flags = {'CXXFLAGS' : 'CXXFLAGS'}
 		if Compile(context, text='''
 /*
  * SDL on Raspbian provokes a warning from -Wuseless-cast
```

These are completely wrong.  The value of the dictionary should be valid arguments to the C++ compiler, not the literal string `CXXFLAGS`.  The hunk ought to be dropped entirely, but if the packager insists on patching this, then the correct patch would be to:

- set `successflags = {}` for `check_attribute_unused`
- delete `check_compiler_useless_cast` entirely (or prevent its execution by deleting the `@_custom_test` decorator)

> patch-SConstruct
```diff
@@ -2420,8 +2419,6 @@ where the cast is useless.
 ''', msg='for struct timespec', successflags=_successflags)
 	__preferred_compiler_options = [
 		'-fvisibility=hidden',
-		'-Wsuggest-attribute=noreturn',
-		'-Wlogical-op',
 		'-Wold-style-cast',
 		# Starting in gcc-7, Rebirth default options cause gcc to enable
 		# -Wformat-truncation automatically.  Unless proven otherwise by
```

This should not be required.  This section probes for supported compiler arguments.  They should be dropped automatically if the compiler is too old to understand them.  If they aren't dropped automatically, that is a bug in SConstruct that should be reported.

> patch-SConstruct
```diff
@@ -2452,7 +2449,6 @@ where the cast is useless.
 		#	   snprintf(SecludedSpawnText, sizeof(SecludedSpawnText), "Use %u Furthest Sites", Netgame.SecludedSpawns + 1);
 		#	   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 		#
-		'-Wno-format-truncation',
 		# gcc-7 with -Wextra enables -Wimplicit-fallthrough, which warns
 		# for various sites in Rebirth.  All the sites where fallthrough
 		# is obviously correct are already marked to suppress this
```

If the compiler silently ignores unknown `-Wno-foo` arguments, as gcc does, this should not be necessary.  If the compiler implements `-Wformat-truncation` similar to how gcc does it, removing this will **add** warnings because the gcc implementation is paranoid and warns about situations that are impossible (but that it cannot prove to be impossible).  Perhaps clang is far more clever about format truncation warnings, or perhaps it is far less paranoid.

> patch-SConstruct
```diff
@@ -3398,7 +3394,7 @@ class DXXCommon(LazyObjectConstructor):
 				'variable': EnumVariable,
 				'arguments': (
 					('host_endian', None, 'endianness of host platform', {'allowed_values' : ('little', 'big')}),
-					('host_platform', 'linux' if sys.platform == 'linux2' else sys.platform, 'cross-compile to specified platform', {'allowed_values' : ('win32', 'darwin', 'linux')}),
+					('host_platform', 'linux' if sys.platform == 'linux2' else sys.platform, 'cross-compile to specified platform', {'allowed_values' : ('win32', 'darwin', 'linux', 'openbsd6')}),
 				),
 			},
 			{
```

No problem (aside from the note at the top of the patch file from its author regarding the ever-growing list of BSD variants).  Such a list could be easily addressed by patching Python on OpenBSD not to include an OS major version number. ;)

> patch-SConstruct
```diff
@@ -3803,22 +3799,10 @@ class DXXCommon(LazyObjectConstructor):
 				RCCOMSTR						= "RC  %s %s $SOURCE" % format_tuple,
 			)
 
-		Werror = get_Werror_string(user_settings.CXXFLAGS)
 		env.Prepend(CXXFLAGS = [
 			'-ftabstop=4',
 			'-Wall',
 			'-Wshadow',
-			Werror + 'extra',
-			Werror + 'format=2',
-			Werror + 'missing-braces',
-			Werror + 'missing-include-dirs',
-			Werror + 'uninitialized',
-			Werror + 'undef',
-			Werror + 'pointer-arith',
-			Werror + 'cast-qual',
-			Werror + 'missing-declarations',
-			Werror + 'redundant-decls',
-			Werror + 'vla',
 		])
 		env.Append(
 			CXXFLAGS = ['-funsigned-char'],
```

This seems like a bad idea.  While I recognize that an unqualified `-Werror` is unpopular with packagers (and therefore went out of my way to support it), I strongly discourage disabling non-error warnings.

> patch-SConstruct
```diff
@@ -3884,7 +3868,6 @@ class DXXCommon(LazyObjectConstructor):
 		env = self.env
 		user_settings = self.user_settings
 
-		env.Prepend(CXXFLAGS = ['-g', '-O2'])
 		# Raspberry Pi?
 		if user_settings.raspberrypi == 'yes':
 			rpi_vc_path = user_settings.rpi_vc_path

```

This seems pointless (although it may have been copied from the upstream Gentoo ebuild, which carries an equivalent patch).  These flags are **left**-inserted, so any user options will override them.  This is by design, so that a build with no other options enables optimizations and debug symbols, but users can choose otherwise by setting appropriate CXXFLAGS.

**Comment by thfrwn** [comment]
Thanks. Will review this for our porting. In the meantime thanks for the adjustments.

**Comment by vLKp** [comment]
As a general note if you package snapshots (which seems likely, with Rebirth's release manager on hiatus), snapshots are *usually* able to cross-play without being an exact version match.  In cases where the in-game protocol changes, I update a `#define` in one of the headers, and incompatible versions will receive an error message on attempting to join the same game.  When that happens, all users will need to run a build from the same side of history as that `#define`.

If you see any other build errors, even ones that you can bypass by disabling `-Werror`, please report them.
