### ISSUE TITLE
Compile errors in common/include/console.h: Building with Xcode Version 9.2 (9C40b) Command Line Tools

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#362]
When I compile common/include/console.h I get this error:
```
In file included from common/arch/sdl/event.cpp:20:
In file included from common/include/window.h:20:
common/include/console.h:58:56: error: unused parameter 'level'
      [-Werror,-Wunused-parameter]
static inline void con_puts(const con_priority_wrapper level, T &&str)
                                                       ^
```

**Comment by vLKp** [comment]
That does not make any sense.  It is used a few lines farther down as the first parameter of a different overload of `con_puts`:

https://github.com/dxx-rebirth/dxx-rebirth/blob/e8d53ca4870a2681901092a873217ca6ff272ca2/common/include/console.h#L58-L62

This may have been caused by the compiler being confused after the error in `d_srcloc.h`.  Please retry with [Fix compile error for !DXX_HAVE_CXX_BUILTIN_FILE_LINE](/dxx-rebirth/dxx-rebirth/commit/d2612734a35d35e6890f609a3275347010386e4e).

**Comment by kreatordxx** [comment]
Fixed.
