### ISSUE TITLE
Starting death count goes random for non-hosts

### ISSUE THREAD

**Issue by roncli** [dxx-rebirth/dxx-rebirth#363]
Looks like Ashes found a bug in v0.59.100 build 7390. He hosted a couple games, and in 2 out of the 4 cases, his partner's death count was wrong.

The first instance came in the 2nd level (level 6) while doing co-op. https://www.twitch.tv/videos/210501375 … About 30:40 in you'll see Alec finish that level with -191 deaths.  The second instance came in an anarchy game where Alec starts the game with a score of -9.  Same video, about 54:22.

I don't know if this is something that has already been fixed, but @zicodxx asked me to report it here so it doesn't fall through the cracks. :)

**Comment by vLKp** [comment]
Unfortunately, Twitch has never worked for me.  It gets stuck on some bad Javascript and just hangs without loading the video player.

The reported problem doesn't sound familiar, but I can't tell for sure without knowing what commit is involved.  You said build 7390, but I don't recognize that identifier.  It's not a date, nor a prefix of any commit in the Rebirth repository history, and I don't see identifiers of that form associated with any of AFP's weekly snapshots.  Where can this build be downloaded?  Do you know what commit it was drawn from?  The version `v0.59.100` has been on every commit since zico bumped up for the beta a bit over a year ago.  Actual commit data is placed in the `g_descent_version` array by the build system (if Git and repository data are available).  `g_descent_build_datetime` can also be helpful, but I prefer version when both available).

**Comment by roncli** [comment]
Unfortunately, I won't have time to actually test this on the new builds, as it was just something I observed happen.  I think it's going to be safe to close this for now. :)
