### ISSUE TITLE
Mouse behavior is broken on automap on some setups

### ISSUE THREAD

**Issue by roncli** [dxx-rebirth/dxx-rebirth#365]
I was testing this bug I found in Retro and realized Rebirth 0.58.1 had it too.

Here's the deal.  I have a mouse (Steelseries WoW Legendary Mouse) that polls at a rate greater than the framerate of Rebirth.  The MINIMUM option is 250Hz, I typically use 1000Hz.

This is causing shenanigans in the automap where the automap will occasionally - and often - jump from one position to the next, rendering it nearly unusable.  Happens no matter what polling rate I select, 250 500 or 1000.

**Comment by vLKp** [comment]
From your ticket so far, I do not understand what inputs the program receives, so it is difficult to speculate as to why the program behaves undesirably.  What exactly does the program see with this mouse?

**Comment by roncli** [comment]
Well, what I mentioned above is about as good as I can explain it, perhaps I can get a video for you of it later tonight.  Sirius is also experiencing it, and also has a 1000Hz mouse.

**Comment by roncli** [comment]
Here's a ZIP of a quick video that demonstrates the problem.

[2018-02-01_20-13-38.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/1688032/2018-02-01_20-13-38.zip)

**Comment by vLKp** [comment]
That video confirms my understanding of your initial description.  However, my problem was not that I did not understand your reported symptoms, but that I do not know, and would prefer not to guess, what inputs the program is receiving that cause it to behave as shown.  That is why I asked what the program sees with the mouse.  If I were to guess, my top two theories would be:

* The mouse is reporting too many ticks of movement for a given amount of hand movement.  If so, the problem might be resolved by downscaling the reported ticks.
* The mouse sensitivity is so high that it is not polled sufficiently often, leading to underflow in the motion variables.  If you instrument `mouse_motion_handler` to print `mme->xrel` and `mme->yrel`, do the jumps correspond to unusual values?  These fields are only defined in SDL as signed 16-bit integers, so I could believe that insufficiently frequent polling might cause an underflow if the mouse builds up too much movement.

Am I correct that this mouse is otherwise usable as-is for regular desktop work, other games (counting Rebirth and Retro as the same game, given common heritage), etc.?  There is no undesirable overshoot or missed motion in other programs?

**Comment by roncli** [comment]
I'll check on those variables and get back to you.  Seems plausible.

Note this does NOT happen in actual game play, and I have not seen anything like this in other games.

**Comment by roncli** [comment]
Ready for this one?  (Hint: You're not.)

It works fine with the -debug switch.  o_O  What about -debug would cause this to suddenly start behaving correctly?  Removing the switch gets the unintended behavior again.

**Comment by vLKp** [comment]
That is *weird*.  If you had said a debug __build__ behaved differently, that would be entirely plausible.  Debug builds have a different framerate cap than non-debug builds.  However, that is not what you saw.  I do not see anything in the code that would explain your observed result.  The command line option `-debug` only changes `CGameArg.DbgVerbose` to `CON_DEBUG` and has no other direct effect.  None of the uses of `CGameArg.DbgVerbose` look like they should cause such a change.

I am a bit doubtful that `-debug` would produce the output to answer my above query, since nothing like this has ever been needed before.  If you can rebuild, apply this patch, rebuild, and repeat the automap test without `-debug`:

```diff
diff --git a/common/arch/sdl/mouse.cpp b/common/arch/sdl/mouse.cpp
index af282f1c7..75b94d652 100644
--- a/common/arch/sdl/mouse.cpp
+++ b/common/arch/sdl/mouse.cpp
@@ -166,8 +166,8 @@ window_event_result mouse_motion_handler(SDL_MouseMotionEvent *mme)
 	event.dy = mme->yrel;
 	event.dz = 0;		// handled in mouse_button_handler
 	
-	//con_printf(CON_DEBUG, "Sending event EVENT_MOUSE_MOVED, relative motion %d,%d,%d",
-	//		   event.dx, event.dy, event.dz);
+	con_printf(CON_NORMAL, "Sending event EVENT_MOUSE_MOVED, relative motion %d,%d,%d",
+			   event.dx, event.dy, event.dz);
 	return event_send(event);
 }
 
```

Although not useful for diagnosing this, I now wonder whether `-verbose` will change the observed results.  It is more verbose than passing no option, but notably less verbose than passing `-debug`.

Regarding other games, do you know if any of the other games that you tested use SDL1 for their input handling?

**Comment by roncli** [comment]
OK, on further review it *does* happen with `-debug`, but in a very minuscule way.  `CON_NORMAL` without `-debug` has the same result as `CON_DEBUG` with `-debug`.

I can tell this, because somehow `automap_process_input` occasionally gets called with the same event multiple times consecutively.  Note that the `Pitch, Heading` output below is a `con_printf` from within `automap_process_input`.

```
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion -48,3,0
21:59:15 Pitch, Heading - -138 - -590 
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion -12,2,0
21:59:15 Pitch, Heading - -81 - -294 
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion -7,2,0
21:59:15 Pitch, Heading - -61 - -128 
21:59:15 Pitch, Heading - -61 - -128 
21:59:15 Pitch, Heading - -61 - -128 
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion 6,0,0
21:59:15 Pitch, Heading - 0 - 110 
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion 21,0,0
21:59:15 Pitch, Heading - 0 - 386 
```

I'm still investigating deeper, but this info seemed significant enough to report back with.

**Comment by roncli** [comment]
This is starting to look like 2 bugs.

First is that `EVENT_IDLE` is routed to `automap_process_input`, which is confusing.  If you're idle, why are you processing input?  This means that for every `EVENT_IDLE` event, the last motion that was saved in `am->controls` gets repeated.  This is what I discovered in the log shown above.  Seems like not handling EVENT_IDLE in `automap_handler` is the correct answer here.

The second almost seems like an SDL bug.  The same mouse movement event occasionally gets sent multiple times - anywhere from 2 to 5 - and thus processed multiple times, in a single call to `event_poll`.  Why this is happening is not immediately clear, and cursory Googling doesn't reveal any results, and I can't find anything like this bug on the SDL bug tracker.  I'm not sure how to try to debug this further at the moment.

**Comment by vLKp** [comment]
> This means that for every `EVENT_IDLE` event, the last motion that was saved in `am->controls` gets repeated.

Could you elaborate on this?  Also, please post the implementation of the `con_printf` you added.  I would like to see which variables you are printing to produce that output.

For debugging this, you may find useful the gamelog's ability to show subsecond time (controlled by C preprocessor symbol `DXX_CONSOLE_TIME_SHOW_MSEC`).  It is enabled by default as of early December.

https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/automap.cpp#L916 This is a workaround for the inappropriate use of a global.  The automap-specific state `am->controls` is copied into `Controls` since `kconfig_read_controls` always reads/writes `Controls`, regardless of automap state.

https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/automap.cpp#L917 `kconfig_read_controls` resets various fields at start:

https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/kconfig.cpp#L1091

Further, for `EVENT_IDLE`, it also resets mouse state:
https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/kconfig.cpp#L1237-L1239

Incidentally, I think this is why `EVENT_IDLE` is handled this way.  It is required to make the flight simulator mouse mode work properly.  I think it is also required to make press-and-hold keyboard navigation work correctly.  The remainder of `kconfig_read_controls` handles converting the inputs into specific movements, but for this path, all the inputs should be zero, so the result should be zero.  If so, then nothing should be repeated.

However, in writing this post, I noticed a related oddity.  The motion is not applied when the user generates input (including the pseudo-input of idle).  Instead, motion is applied when the window is drawn, since `EVENT_WINDOW_DRAW` calls `automap_apply_input`.  That motion is not scaled to FrameTime, so motion increases as a function of how often the window is redrawn.  This seems wrong, but does not explain your symptoms.

**Comment by roncli** [comment]
Pitch and heading are `am->controls.pitch_time` and `am->controls.heading_time`, and are put in `automap_process_input` after `am->controls` is set.

Your explanation makes me think it's not `am->controls` that is being saved, but it's rather a repeat of the event details.  But the controls are definitely being repeated somehow.  If I were to add `event->type`, the output would look like this:

```
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion -48,3,0
21:59:15 Pitch, Heading, EventType - -138 - -590 - 8 
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion -12,2,0
21:59:15 Pitch, Heading, EventType - -81 - -294 - 8 
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion -7,2,0
21:59:15 Pitch, Heading, EventType - -61 - -128 - 8 
21:59:15 Pitch, Heading, EventType - -61 - -128 - 0 
21:59:15 Pitch, Heading, EventType - -61 - -128 - 0 
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion 6,0,0
21:59:15 Pitch, Heading, EventType - 0 - 110 - 8 
21:59:15 Sending event EVENT_MOUSE_MOVED, relative motion 21,0,0
21:59:15 Pitch, Heading, EventType - 0 - 386 - 8 
```

I did *not* check to see what the actual event data contained, however.  I could try to check that out if you think I should. :)

Note your reply only addresses the first/Rebirth bug.  I am still lost on the second/possible SDL bug.  Sirius might play around with debugging this when he has time as well.  `DXX_CONSOLE_TIME_SHOW_MSEC` will not help with the second bug because we already know that the duplicate events are being polled from SDL in a single call to `event_poll`, and it's definitely not Rebirth causing it.  More research is needed for this.

I'd like to try this on 0.60 for some extra debugging, but don't have a 0.60 development environment.  I'll have to set that up at some point if I want to tackle this on that version.

**Comment by vLKp** [comment]
> Pitch and heading are `am->controls.pitch_time` and `am->controls.heading_time`, and are put in `automap_process_input` after `am->controls` is set.

I agree that those fields represent that data, but I do not see that `automap_process_input` touches them at all.  The whole implementation of `automap_process_input`:

https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/automap.cpp#L914-L936

All references to `.pitch_time` | `.heading_time` in master:similar/main/automap.cpp:

https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/automap.cpp#L558
https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/automap.cpp#L562
https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/automap.cpp#L563
https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/automap.cpp#L597
https://github.com/dxx-rebirth/dxx-rebirth/blob/2571081962f448a4882d0cf3735ea5d64c3cfa9e/similar/main/automap.cpp#L598

Those are all read accesses, not writes.

>  If I were to add ...

As I asked above, please share the exact `con_printf` call you are using (preferably as the output of `git diff HEAD; git log -1`), so I can see which variables you are printing and on what tree you are based (likely 0.58.1 from other comments).  I recognize that the two lines with EVENT_IDLE are repeating the variable of the most recent non-idle event.

Events contain only the fields necessary.  You cannot usefully print mouse motion data from an idle event.  You would be printing undefined memory from near the idle event.

Yes, I ignored a possible SDL bug.  If you're right that it is an SDL problem, then there's nothing I can do about it.  If you're wrong and it's another Rebirth problem, then I don't have enough information to work on it yet, nor any way to reproduce it. :)

> I'd like to try this on 0.60 for some extra debugging

I always use tip for my references.  If you have problems building it, please file an issue and I will try to help.

**Comment by roncli** [comment]
Hey there, just checking in.  I may not get to this for a few days as something has come up, but it is the next thing I'm looking to tackle, so stay tuned. :)

**Comment by roncli** [comment]
Just got back to this one today!  I offhandedly mentioned this bug to Zico, and he was sure this was fixed. 
 Sure enough, a8ed0aaa9c83edc023b70793be721509fe718b70 had the answer I was looking for.  This issue is closed!
