### ISSUE TITLE
Robot Models not Rendering in Breifing (Descent 2 and Vertigo)

### ISSUE THREAD

**Issue by hegyak** [dxx-rebirth/dxx-rebirth#367]
Issue:
The Robot Models are not rendered in the Briefing screens.

To recreate:
Start Descent 2 and start a new game.  The game should show briefing text on the various new robots.  But, the robot model itself is not rendered.

Version used:
https://github.com/dxx-rebirth/dxx-rebirth/commit/4a01fab66d98cf593e9e46e64d763393de019037

Severity:
Minimal/low.

I am not sure if I put the ROBOTS-H.MVL and ROBOTS-L.MVL into the wrong folder.  Those files are currently in the Movies subfolder.  The Descent 2 intro (The Asteroid Belt) does play correctly.

Descent 1's briefing does render the Robot Models correctly.

Edit:
The gamelog.txt file says:
```
15:31:46.752 Using SDL_mixer library v1.2.12
15:31:47.125 sdl-joystick: 0 joysticks
15:31:47.945 Can't open movielib <intro-h.mvl>: (null)
15:31:47.945 Can't open movielib <intro-l.mvl>: (null)
15:31:47.946 Can't open movielib <other-h.mvl>: (null)
15:31:47.946 Can't open movielib <other-l.mvl>: (null)
15:31:47.947 Can't open movielib <robots-h.mvl>: (null)
15:31:47.947 Can't open movielib <robots-l.mvl>: (null)
15:31:47.947 Can't open movie <intro.mve>: (null)
15:31:47.948 Can't open movie <titles.mve>: (null)
15:31:51.376 Can't open movie <pla.mve>: (null)
15:31:51.501 Can't open movie <rbJ.mve>: (null)
15:31:53.786 Can't open movie <rbN.mve>: (null)
```

[@vLKp edit: switch to multi-line code block for gamelog.txt]

**Comment by vLKp** [comment]
Technically, Descent 2 does not render robot models in briefing screens.  It can, with the right setup, render movies in the briefing screens, and the Parallax-shipped movies look like an artist's conception of the corresponding robot model.  There is no technical enforcement that the robot movies look anything like the robot models.  In practice, this only matters for people who make custom robots, but it is important to know that the robot movies bear only a general resemblance to the robots you will face in the game.  In contrast, Descent 1 reused the robot renderer for its briefings, so the robots shown in the briefings exactly matched what you would face in the game.

To your immediate problem, your `gamelog.txt` output says that it failed to open `robots-h.mvl`, `robots-l.mvl`.  This would definitely explain your problem.  On my system, where this works, `robots-h.mvl` is in `$HOME/.d2x-rebirth/`, not in a `movies` subdirectory.  As best I can tell, the game does not even try to use a `movies` subdirectory.  Try moving the `*.mvl` files up to the main data directory.

Also, beware that the commit you played is quite old and has known bugs that have been fixed in more recent snapshots.  I recommend upgrading (although none of those bugs are related to your current issue).

**Comment by hegyak** [comment]
@vLKp Thank you.  I put the MVL files into the root of the D2X Folder and that does get the Robots to render during the Briefing.
