### ISSUE TITLE
Tracker NAT hole punch is enabled by default, but users are not adequately informed of the consequences

### ISSUE THREAD

**Issue by vLKp** [dxx-rebirth/dxx-rebirth#372]
As part of the third tracker iteration, @zicodxx and @Mako88 enhanced Rebirth to automatically perform a [NAT hole punch](https://en.wikipedia.org/wiki/Hole_punching_(networking)) when a potential guest tries to join a game hosted on the tracker.  This enables by default zero-configuration Internet-accessible games for users behind a NAT device.  Unfortunately, this also enables by default zero-configuration Internet-accessible games for users who **don't want** to be Internet-accessible, but did not disable the tracker.  Per a comment on the Rebirth forum, at least one user was unaware of the new feature and did not want uninvited users joining his game.

This feature should be revisited in light of the user's extremely adverse reaction to an uninvited guest.  Possible solutions:

* First-run in-game messaging specifically informing the user of this capability, including instructions on how to disable it if the user wishes.
* Every-run in-game messaging mentioning the capability when it initializes successfully.
* Apply a heuristic to limit the feature, such as by only enabling it for *Restricted* games (but not *Open* games).  This would give the host the opportunity to reject uninvited guests.
* Provide a dedicated checkbox to control the feature, and default it to off.

**Comment by Mako88** [comment]
I think the two best solutions would be either:
* A one-time message the first time a user hosts a game
* Defaulting the tracker to off, but adding a command-line switch to default it to on

The issue as I see it is caused by a user unknowingly tracking a game, not with the game automatically performing a hole-punch. If a user is knowingly tracking a game, a hole-punch causes no issues...it simply allows users to join as would be expected by someone with no knowledge of networking. (They host a game, people can find it and join it). However, clearly if someone doesn't realize their game is tracked and visible, then it can be an unwelcome surprise to have someone suddenly join.

**Comment by vLKp** [comment]
[Warn users about tracker NAT hole punch feature](/dxx-rebirth/dxx-rebirth/commit/144515ff887f7641aa81bc9741c2f16f078cfdce) adds a first-run dialog, and a checkbox that can be used to toggle the feature later.

I think this is sufficient to avoid surprising users with uninvited guests.
