### ISSUE TITLE
Player selection menu doesn't remember setting with embedded \r

### ISSUE THREAD

**Issue by derhass** [dxx-rebirth/dxx-rebirth#380]
In 0.58.1, the player selection menu (before the main menu) remembers the player which was used last time and this one is already pre-selected as the current entry. In newer verstions, the menu always starts with the top-most "create new player" entry selected.

**Comment by vLKp** [comment]
Using current tip of a9fb3c9df9604d27c1e204c61d30f3fa4efab846, this seems to work correctly for me in Descent 2.    On what platform(s) did you see this?  Is `descent.cfg` writable?  If yes, is it updated when you choose a pilot and then exit the game?  Memory of last pilot is supposed to be handled through the `LastPlayer` field in `descent.cfg`.

**Comment by derhass** [comment]
OK, the issue seems to be a bit different. The file is updated well. If I create new players, they are also remembered correctly. 

It is that my player name is just broken. In the menu, it is shown as just "HASS" but the file name in `~/d1x-rebirth` is indeed `hass\r.plr`, with a weird carriage return in there. No idea how it got there, but 0.58.1 still can deal with that somehow (never versions also can still load the file just fine). I never manually fiddled with those files, so it must have been some d1x-rebirth version I created that pilot with. No idea if anyone else has player files with this issue.

**Comment by derhass** [comment]
Yeah, that makes all sense. This feels more and more like a non-issue. The more interesting question seems to be: where did that `\r` come from? Was there some possibility to name a player like that in one of the official releases? Is there one in the current tip? So far, I have not been able to reproduce this. But if there is or was a way how should one handle such player files? If not, this can probably be closed without further action. There is really no point in supporting carriage return in player names.

**Comment by vLKp** [comment]
I am not aware of anything that ever meant to allow carriage returns.  I cannot say for certain that the game never allowed it, but I have never seen any code that was supposed to allow it.  Naming restrictions are only enforced at create time, through `playername_allowed_chars`.  I had to get mine by using `mv` to rename a regular player profile to contain an embedded `\r`.

If we need to support it, the short term solution would be to use a configuration reader variant that can be told to assume all files are newline-only, so that carriage returns pass through to the caller.  Longer term, if breaking changes are up for consideration, then the data should be stored in a format that is unambiguous regardless of user content.  As is, a pilot name with `\n` in it would confuse even 0.58.1.  If backward compatibility is required, then strings which do not require quoting must be written as they are today, and only exotic strings can be quoted.  Adding quoting in such a setup is possible, but more trouble.  If no compatibility is required, the format could be switched such that all user controlled strings are quoted (as base64, as JSON, etc.).

For what it is worth, while investigating this issue, I stumbled into an infinite loop in the menu handling code, so some good came from this ticket. ;)

For reference, my debugging patch for this ticket:

```diff
diff --git a/similar/main/menu.cpp b/similar/main/menu.cpp
index c4bd2738c..d8a8914a4 100644
--- a/similar/main/menu.cpp
+++ b/similar/main/menu.cpp
@@ -394,6 +394,7 @@ int RegisterPlayer()
 		{
 			// Read the last player's name from config file, not lastplr.txt
 			plr.callsign = GameCfg.LastPlayer;
+			con_printf(CON_URGENT, "callsign=\"%s\"", static_cast<const char *>(plr.callsign));
 		}
 	}
 
@@ -419,6 +420,7 @@ int RegisterPlayer()
 
 	m[i++] = TXT_CREATE_NEW;
 
+	con_printf(CON_URGENT, "Iterating list ...");
 	range_for (const auto f, list)
 	{
 		char *p;
@@ -433,6 +435,7 @@ int RegisterPlayer()
 		p = strchr(f, '.');
 		if (p)
 			*p = '\0';		// chop the .plr
+		con_printf(CON_URGENT, "Iterating element is \"%s\" ...", f);
 	}
 
 	if (NumItems <= 1) // so it seems all plr files we found were too long. funny. let's make a real player
@@ -444,10 +447,16 @@ int RegisterPlayer()
 	// Sort by name, except the <Create New Player> string
 	qsort(&m[1], NumItems - 1, sizeof(char *), string_array_sort_func);
 
-	for ( i=0; i<NumItems; i++ )
-		if (!d_stricmp(static_cast<const char *>(get_local_player().callsign), m[i]) )
+	con_printf(CON_URGENT, "Sorting list ...");
+	for (i = 1; i < NumItems; ++i)
+	{
+		const auto r = d_stricmp(static_cast<const char *>(plr.callsign), m[i]);
+		con_printf(CON_URGENT, "compare \"%s\" \"%s\" -> %i", static_cast<const char *>(plr.callsign), m[i], r);
+		if (!r)
 			citem = i;
+	}
 
+	con_printf(CON_URGENT, "citem=%i", citem);
 	newmenu_listbox1(TXT_SELECT_PILOT, NumItems, m.release(), allow_abort_flag, citem, player_menu_handler, list.release());
 	return 1;
 }

```

**Comment by derhass** [comment]
> Naming restrictions are only enforced at create time, through `playername_allowed_chars`. 

Maybe we should re-validate player names every time they are loaded. Currently, players can rename the files to for example include newlines, which doesn't look to good in the multiplayer score list.
