### ISSUE TITLE
Build Failure: draw.cpp - error: call to ‘dcx::vm_vec_sub_same_values’ declared with attribute error

### ISSUE THREAD

**Issue by Enverex** [dxx-rebirth/dxx-rebirth#385]
I have a feeling this may be a GCC 7.3 issue. I'm specifically using 7.3.1 right now. The actual error is:

```
CXX dxx . common/3d/draw.cpp
In file included from common/include/dxxerror.h:30:0,
                 from common/3d/draw.cpp:14:
In function ‘dcx::vms_vector& dcx::vm_vec_sub(dcx::vms_vector&, const dcx::vms_vector&, const dcx::vms_vector&)’,
    inlined from ‘dcx::vms_vector dcx::vm_vec_sub(const dcx::vms_vector&, const dcx::vms_vector&)’ at common/include/vecmat.h:284:39,
    inlined from ‘bool dcx::g3_check_normal_facing(const dcx::vms_vector&, const dcx::vms_vector&)’ at common/3d/draw.cpp:84:31:
./dxxsconf.h:53:3: error: call to ‘dcx::vm_vec_sub_same_values’ declared with attribute error: vm_vec_sub with equal value inputs
  F(); \
common/include/vecmat.h:275:3: note: in expansion of macro ‘DXX_ALWAYS_ERROR_FUNCTION’
   DXX_ALWAYS_ERROR_FUNCTION(vm_vec_sub_same_values, "vm_vec_sub with equal value inputs");
   ^~~~~~~~~~~~~~~~~~~~~~~~~
scons: *** [common/3d/draw.o] Error 1
```

**Comment by vLKp** [comment]
This looks like a problem that I fixed in June 2017 after @parkerlreed reported it in #337.  Your line numbers are a bit different from the ones shown in that ticket, so you probably used a different commit.  It looks like you didn't attach the SConf log, so I cannot see why the fix for that ticket did not work for you.  The files involved don't change often enough for me to guess which Git commit you used, but if you're tracking tip, this should not happen.

Please identify the Git commit you used and attach your SConf log.

**Comment by Enverex** [comment]
My mistake, I was compiling 0.59 by accident when I thought I was compiling 0.60 which explains how it's such an old problem.

**Comment by vLKp** [comment]
Mistakes happen.  If you have any problems with tip, please report them, and include the information requested above.  Until then, enjoy.
