### ISSUE TITLE
Archive https://www.dxx-rebirth.com/download/dxx/user/afuturepilot/dxx-rebirth_v0.60-beta-2-src.tar.gz should be commit 0.60-beta2, but is instead approximately 0.60-beta2~1

### ISSUE THREAD

**Issue by vLKp** [dxx-rebirth/dxx-rebirth#390]
New user @KynikossDragonn filed ticket #389 due to a build failure using the source from https://www.dxx-rebirth.com/download/dxx/user/afuturepilot/dxx-rebirth_v0.60-beta-2-src.tar.gz.  This ticket is a duplicate of #375, which is _weird_ because [tag 0.60-beta2][tag] includes the fix for #375.  Specifically, [tag 0.60-beta2][tag] points at the commit that fixed #375, so the archive [dxx-rebirth_v0.60-beta-2-src.tar.gz][2] should have included the fix for this failure.  On investigating that issue, I found several problems with the archive:

1. The files are improperly executable (mode +x).
1. `.gitattributes` and `.gitignore` are missing (not a serious problem, but surprising).
1. Symbolic links have been replaced with their target's contents (normal for zip files, but surprising and undesirable for tar files).
1. Every file I checked has CRLF line endings, which makes `git diff` *very* unhappy when trying to compare it to a commit in the repository.
1. The change in the commit tagged as 0.60.0-beta2 is missing.
1. There is no leading directory name on the archived files (traditionally, named the same as the archive itself, but without the extension, so `dxx-rebirth_v0.60-beta-2/`).

@Mako88, how did you create this archive?

Issue #1 and issue #3 could be explained by creating the file on Windows.  Issue #4 might also be caused by using Windows.  Issue #2 and issue #5 are inexplicable.  Issue #6 is likely a process issue, which should be easy to address.

As a related process note, if you choose to fix the archive, please delete the existing archive and upload the fixed archive to a new name.  This will allow the URL to unambiguously indicate whether it is the original archive or a corrected version.

[tag]: /dxx-rebirth/dxx-rebirth/releases/tag/0.60.0-beta2
[2]: https://www.dxx-rebirth.com/download/dxx/user/afuturepilot/dxx-rebirth_v0.60-beta-2-src.tar.gz

**Comment by Mako88** [comment]
I can answer some of what's going on here, but I won't be able to fix it for a while because of IRL stuff going on currently.

1. The files are improperly executable (mode +x). - I'm fairly confident this is an issue with Windows. I'm not sure what to do to fix it though :/
2. .gitattributes and .gitignore are missing (not a serious problem, but surprising). - I deleted all the .git* files as well as the .git folder. zico requested I do that with the previous beta, but I can leave them in with future archives if you'd rather.
3. Symbolic links have been replaced with their target's contents (normal for zip files, but surprising and undesirable for tar files). - Again, I'm fairly sure this is an issue with Windows and I'm not sure how to fix it. There may be a command-line switch when archiving that I can look into.
4. Every file I checked has CRLF line endings, which makes git diff very unhappy when trying to compare it to a commit in the repository. - This is my own fault. I setup git to checkout with CRLF and commit with LF. I can change this in the future.
5. The change in the commit tagged as 0.60.0-beta2 is missing. - I may have mis-pulled somehow when creating the archive. I'm not sure what's up with that either.
6. There is no leading directory name on the archived files (traditionally, named the same as the archive itself, but without the extension, so dxx-rebirth_v0.60-beta-2/). - Do you mean on the .exe files themselves? I can re-add this if you'd prefer.


As I said, I currently have stuff going on (my newborn daughter is currently in the NICU and probably will be for a month or so), so it may be a while before I'm able to push another archive.

**Comment by vLKp** [comment]
So most of these problems are process issues relating to using Windows tools to package this instead of using the Git native tools.  The fix is easy: use `git archive` as Linus intended.

1. Fixed by `git archive` setting generated permissions based on repository metadata.
2. Fixed by `git archive` storing all controlled files (except those otherwise excluded), but not storing the `.git` directory.
3. Fixed by `git archive` generating symbolic links directly into the archive, even if your host filesystem does not support symbolic links.  (Supported on almost every major non-Windows host filesystem.)
4. Might be fixed by `git archive` since Git will have control over the contents of the files placed in the generated archive.
5. Probably operator error, but could be partially mitigated by letting Git pick the archive name based on repository metadata, so that in case of error, Git will name the archive based on what is exported, making it clear to everyone that this is not the tagged commit.  I care more about having the metadata line up with reality than about having reality be perfect.
6. No, not on the exe.  On the files in the archive.  Currently, when I do `tar xf dxx-rebirth_v0.60-beta-2.tar.gz`, I get `SConstruct` (among many other files) dumped in the current working directory.  Instead, what I want (following Gentoo practice) is that I get `dxx-rebirth_v0.60-beta-2/SConstruct`, `dxx-rebirth_v0.60-beta-2/similar/`, etc.  The extraction should create a directory named `dxx-rebirth_v0.60-beta-2` and all extracted files should be placed in it.  This mirrors how the Windows zip utility suggests unpacking zip files, but with tar files, it is the responsibility of the sender, not the receiver, to add this level of structure.

A `git archive` command to perform this packaging is:

```
(
 set -e;
 commit="HEAD";	# or any other commit
 desc=$(git describe --tags "$commit");
 git archive --format=tar.gz --prefix="$desc/" -o "dxx-rebirth-$desc-src.tar.gz" "$commit"
)
```

I saw in another thread about your offline troubles.  Take the time you need.  No hurry on fixing this (although all that's needed is re-archive the source, so if you want to work it, you can fit it in almost anywhere).  No need to rebuild anything.  I could do it in a couple minutes time if I had upload access to the server.

**Comment by Mako88** [comment]
If you could create the archive and email it to me or attach it to this ticket, I can get it uploaded in the next couple days :)

**Comment by vLKp** [comment]
You already indirectly created an acceptable archive when you tagged the release on Github.  Grab [0.60.0-beta2.tar.gz](https://github.com/dxx-rebirth/dxx-rebirth/archive/0.60.0-beta2.tar.gz) from Github, rename it to add the leading `dxx-rebirth-` to the filename, and upload it.  There is no need to unpack or modify the contents at all.

I checked that it has the correct prefix `dxx-rebirth-0.60.0-beta2/` in all its generated files, and is `diff`-wise an exact match for the tag `0.60.0-beta2`.

**Comment by Mako88** [comment]
I finally got this posted. The file name is dxx-rebirth-0.60.0-beta2-git.tar.gz to differentiate it from the original version.

In the future I'll just use the auto-generate git source .tar.gz file for the source :)
