### ISSUE TITLE
No longer compiling for me following ccc2a28

### ISSUE THREAD

**Issue by bdamm** [dxx-rebirth/dxx-rebirth#391]
This is just a heads-up note that commit ccc2a288f180e826bda2c91bf382b242ce0e1c99 was a breaking change that ends up with a compile failure in font.cpp on MacOS X (10.11.6) (Xcode 7.3.1) `Apple LLVM version 7.3.0 (clang-703.0.31) Target: x86_64-apple-darwin15.6.0`. 

Code:
```
similar/2d/font.cpp:149:31: error: conditional expression is ambiguous; 'font_scaled_float<'x'>' can be converted to 'const short' and vice versa
similar/2d/font.cpp:149:10: error: default initialization of an object of const type 'const float'
similar/2d/font.cpp:149:10: error: default initialization of an object of const type 'const int'
```

I don't know why the change causes this error, but I'm branching from just before this point because I can't compile anywhere after it.

Cheerio,
-Ben

**Comment by vLKp** [comment]
There is no need to file problem reports in triplicate ([as an inline commit comment](/dxx-rebirth/dxx-rebirth/commit/ccc2a288f180e826bda2c91bf382b242ce0e1c99), [as a Github issue](), and [as a forum post](https://forum.dxx-rebirth.com/showthread.php?tid=1055)).  I read all three sources.  Github notifies me about unread activity on commits and issues.

When you filed the Github issue, you should have been presented with a template drawn from [`ISSUE_TEMPLATE.md`](/dxx-rebirth/dxx-rebirth/blob/3201097be8282240652115db3123fce7e454d538/ISSUE_TEMPLATE.md) to prompt you on the information to provide.  In particular, it should have prompted you to include the `sconf.log` generated by the build.  This would have been quicker to debug had that been available.

Problem confirmed, but only in a fallback configuration triggered by deficient compiler support for C++11 inheriting constructors.  If the compiler fails to inherit constructors, or implements inheritance in a way that is known to cause compilation failures later, I fall back to the hack of using a variadic forwarding constructor.  The only way I found to reproduce the reported problem is to force use of the variadic forwarding constructor instead of using C++11 constructor inheritance.  Variadic forwarding loses the `explicit` modifier from the base class, allowing the derived class constructor to provide implicit conversions.  Constructor inheritance preserves the `explicit` modifiers and prevents the implicit conversion.  The presence of the implicit conversion causes the ambiguity in the conditional expression.

According to Git logs, I committed the logic to detect the bad inheritance behavior in May 2015.  I would have expected that Apple could sort out their constructor inheritance support with three years (plus however long before I became aware of it) to work on the problem.  Perhaps they did, and you hit some other problem.  `sconf.log` would confirm or reject the diagnosis.

Regardless, the workaround is an explicit disambiguation at the usage site.  This is unfortunate, since it means that every place that I use inheriting constructors with `explicit` is vulnerable to this type of breakage.  Even more unfortunate, rebuilding the whole project with variadic forwarding constructors reveals other sites that break in the presence of modifier-unaware forwarding.  Some are less easy to fix.

I pushed commits to address all the breaks I found using variadic forwarding.  Please sync to tip and retry.

- [Mark variadic forwarding constructor as `constexpr`](/dxx-rebirth/dxx-rebirth/commit/479235d5bc2335b6ff9834991ea594d8119fd3db)
- [Force type of ternary expressions](/dxx-rebirth/dxx-rebirth/commit/d786122b3789118b6a69ef8576c1ecbc1b19159f)
- [Fix OS X build break](/dxx-rebirth/dxx-rebirth/commit/d5bfeb0813527795b46f505fafc01d2e5cc83009)

**Comment by bdamm** [comment]
I'm terribly sorry; I stumbled my way to filing the github bug, and in future will go directly to filing the bug, and also including the sconf.log output for the build. As I'm compiling from Xcode I wasn't sure at first where the sconf.log was, but I see it now.

Thanks for the fix! I will go test it now.

And, I think upgrading the compiler is possible. My Xconf installation is not the newest. If I run into any difficulty resulting in the same error, I'll upgrade and let you know what the result is.

Let me say again that I am very impressed by the work you've put into this project, just remarkable. And the result is a real joy.

**Comment by bdamm** [comment]
It works for me. Thank you!

**Comment by vLKp** [comment]
If you have time, please update to the latest Xcode, checkout a version predating my fix above, and try to build.  If it still fails, please attach the `sconf.log` so that I can see how a modern Xcode/clang got into the state that a fallback for old compilers was activated.
