### ISSUE TITLE
Build failure:  Invalid value for option host_platform: msys

### ISSUE THREAD

**Issue by jammer1** [dxx-rebirth/dxx-rebirth#405]
### Environment

forked from commit: 0df57f5b0f86c80979000389d68b23403afd52eb

compiled using an [MSYS2](http://www.msys2.org/) environment with installed packages:

```
$ pacman -S mingw-w64-x86_64-toochain mingw-w64-x86_64-dlfcn \
        mingw-w64-x86_64-physfs mingw-w64-x86_64-SDL mingw-w64-x86_64-SDL_mixer \
       scons
```

for completeness, here's the full list of installed packages with `pacman -Q`: https://gist.github.com/jammer1/46ef02e36129a29a5b6de36ace5d415a
 
#### Operating System Environment

* Microsoft Windows
  * [x] Microsoft Windows 7

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

### Description

build output:

```
 $ scons
scons: Reading SConscript files ...
===== D1X-Rebirth v0.59.100 0.60.0-beta2-154-g0df57f5b0f86 =====
===== D2X-Rebirth v0.59.100 0.60.0-beta2-154-g0df57f5b0f86 =====

scons: *** Invalid value for option host_platform: msys.  Valid values are: ('darwin', 'linux', 'openbsd', 'win32')
File "/home/jammer/cc/remote/dxx-rebirth/SConstruct", line 4960, in main
```

Adding 'msys' to the list seemed to default to a linux-based build, I was able to change GL and GLU to opengl32 and glu32 by modifying the SConstruct file and commenting out a compiler error in `similar/misc/physfsx.cpp`, but eventually got linker errors, probably because the right libraries are not being linked.

Modifications: https://github.com/jammer1/dxx-rebirth/commit/4538ab967a23c1e35fa3da5d5bcc9fc839237c69

Outputs the following when building:

stdout: https://gist.github.com/jammer1/f0e0d16de89b73fad51c90f90e5c5c51

stderr: https://gist.github.com/jammer1/78680f2a42aa5e984d6cf925def227cc

**Comment by jammer1** [comment]
The error with the SHAREPATH block was that CGameArg does not have a member named 'SysNoHogDir'.

So using host_platform=win32 gets things started, however it looks like I am stuck with a gcc 8 regression error: [[Bug debug/86593] New: [8.0 Regression] internal compiler error: in based_loc_descr, at dwarf2out.c:14272](http://gcc.1065356.n8.nabble.com/Bug-debug-86593-New-8-0-Regression-internal-compiler-error-in-based-loc-descr-at-dwarf2out-c-14272-td1496387.html)

[(build output of `scons host_platform=win32`)](https://gist.github.com/jammer1/4c21f788048baa9fd53ba75c02956a8e)

There is a gcc 7 package under the "msys2-devel" package group, but it gets installed in a different file system hiearchy (/usr/bin/gcc vs. /mingw64/bin/gcc), and there are missing symbols.

[(build output of `CXX=/usr/bin/gcc scons host_platform=win32`)](https://gist.github.com/jammer1/e765b0e3581f5cf5e27e506578105818)

[(and sconf.log)](https://gist.github.com/jammer1/cb5605c8698f6e6a85f9ec7050321971)

**Comment by vLKp** [comment]
`SysNoHogDir` is defined `#if defined(__unix__)`.  It is used `#ifdef SHAREPATH`.  This inconsistency is unfortunate, but I wanted to avoid defining `SHAREPATH` in every file since most do not use it, but changing it causes a rebuild of every file that is allowed to see it.  Normally, it is not a problem, because only `LinuxPlatformSettings` permits `sharepath` to be defined.  Windows and Mac both forcibly clear it.  The failure happened because you used `LinuxPlatformSettings`, but your environment did not define `__unix__`.  I can fix that by repeating the `#if defined` guard around the test, but not the block itself.  This actually points up an area for improvement.  Currently, non-Linux cannot have a SHAREPATH, even when that would be useful.

[`SHAREPATH` is defined `if sharepath`](/dxx-rebirth/dxx-rebirth/blob/e6e0d525b6bc3e4a84e2cb34aa4c13192739f913/SConstruct#L4639).  [`sharepath` is `self.user_settings.sharepath`](/dxx-rebirth/dxx-rebirth/blob/6e6e0d525b6bc3e4a84e2cb34aa4c13192739f913/SConstruct#L4636).  `user_settings.sharepath` is controlled by the user, but [defaults to the result of `self.__default_DATA_DIR`](/dxx-rebirth/dxx-rebirth/blob/6e6e0d525b6bc3e4a84e2cb34aa4c13192739f913/SConstruct#L3506) (where `self` is an instance of `UserBuildSettings`, so `self.__default_DATA_DIR` is [UserBuildSettings.__default_DATA_DIR](/dxx-rebirth/dxx-rebirth/blob/6e6e0d525b6bc3e4a84e2cb34aa4c13192739f913/SConstruct#L3418).  (However, as above, if your platform is not Linux, the value is later cleared.)

---

Regarding your gcc-8 regression, it looks like you could get past that by flipping the value of `-fomit-frame-pointer`.  Normally, I force frame pointers to enabled for Windows because stack traces without them are very inconvenient to use.  However, if your choice is between not building at all or building and having unreadable stack traces, I think the latter is an acceptable compromise.

---

For your physfs problem, that is a bug in their headers.  It was described by A Future Pilot in a footnote to his first post in [How to Compile Rebirth on Windows](https://forum.dxx-rebirth.com/showthread.php?tid=857).  He says there that he reported it upstream.  It was [re-reported by \@MaddTheSane](/dxx-rebirth/dxx-rebirth/issues/325#issuecomment-381732075), who worked around it by defining the missing symbols to 0.

**Comment by jammer1** [comment]
It worked! I was able to successfully build an unmodified version using gcc 8:

CXXFLAGS='-fomit-frame-pointer' scons host_platform=win32

**Comment by vLKp** [comment]
I am still considering whether to add a workaround to detect versions of gcc affected by the `-fno-omit-frame-pointer -g` assertion failure.  The commit above should remove the need to specify `host_platform` explicitly.
