### ISSUE TITLE
Provide music synthesis options for FM

### ISSUE THREAD

**Issue by jpcima** [dxx-rebirth/dxx-rebirth#407]
Hello. I wish to suggest a feature request to enable a different music synthesizer to play on dxx-rebirth.
The idea in particular is to enable playback of OPL3 FM.

It is an idea to accomplish the same job as made in GZDoom, where it provides [libADLMIDI](https://zdoom.org/wiki/LibADLMIDI) as a configurable replacement for Doom's DMX.
This library is a reengineered and largely improved version of Bisqwit's OPL3 player.

I can think of some reasons why it may interesting to use it.
- it has the original Descent banks in
- may also play GM version of musics, as supports more polyphony and custom banks
- supports a DOS build based on hardware chip
- will get direct support for the HMI and HMP format [WIP]
(bonus: OPNMIDI supports also the OPN2 chip, that GZDoom also has in)

Do you think of such a feature as good to add?

**Comment by vLKp** [comment]
I never use music during Rebirth, but I have no objection to supporting another music backend if it is clean.  From a quick look at the library you linked, licensing could be a problem.  Rebirth's license is awkward due to how Parallax released the code.  We could probably only use the parts that are more permissively licensed (LGPL, MIT).  With that constraint, if you want to propose code changes to support it, I'm happy to review them.

**Comment by vLKp** [comment]
Regarding the code, while I always appreciate submissions that are ready to merge as-is, I don't mind reviewing or revising submissions as needed.  The important part to me is that you have a working proof of concept, so that I do not need to master the library and write all the glue code.  Rough edges can be smoothed out in a development branch.  If you have a list of known issues (e.g. memory leaked on error paths, features that don't work as users might expect, etc.) that is also appreciated.

Regarding licensing, I have two requirements:

- Any source code added to the Rebirth tree needs to be under the existing Rebirth license.  I think this is not a problem here, assuming you wrote that code or have the consent of its author.
- Redistribution of a compiled Rebirth program must be reasonably straightforward.  Any additions that cause Rebirth to depend on non-free components must provide a way, either through a compile-time switch or through runtime linking (with graceful failure) to let a redistributor exclude the non-free component and have an otherwise functional Rebirth.  Ideally, it should be possible for Debian to redistribute in their main repository.  I mention them specifically since they have a reputation for being strict about license compliance.  Since this is a new feature and is not essential to gameplay, I think having a compile-time switch that can drop the entire feature is an acceptable, if somewhat excessive, way to satisfy redistribution concerns.  As I understand your comment, there are substantial portions of your work that could be freely redistributed, so it might be better to have a three-way switch:
  - One mode to disable everything that requires new external libraries (even free ones), so that builders who want not to have any new dependencies can do so.
  - One mode to disable non-free dependencies, so that the resulting program has the maximum possible functionality while being freely redistributable.
  - One mode to enable everything, to be used when the person building it can satisfy the requirements of the non-free components (by having appropriate license(s), by being in a jurisdiction that does not recognize the non-free terms as legally binding, etc.).

**Comment by vLKp** [comment]
1. a. Licensing for your code: that is good enough for me.
 b. I think that would be acceptable.  Redistributors would need to disable use of this feature or ship a stripped down libADLMIDI that lacked the GPL-covered pieces.  Since libADLMIDI does not seem to be packaged on some Linux distributions at all, I will add and maintain a build system flag that can be used to exclude this functionality.

2. * You say you did not know a better way to do it when you wrote it.  Do you know a better way now?  If not, do you think it likely that there is a better way that you don't know, or is this the best it will be?
   * Fixed: Acknowledged.
   * For a first iteration, a release note about affected banks is likely good enough.  If users show an interest in the feature, a knob could be added to influence the multiply.
   * Agreed.  I can take the work of adding new configuration values to Rebirth if you indicate, whether here or as review comments on the commit, which constants need to be replaced by which configuration values.
   * I keep the Windows target buildable, but do not maintain it much beyond that.  In particular, I don't test its sound code at all.  I would likely add this code first for platforms where it works as-is, then expand to cover Windows later.

What, if any, further work do you want to do on this before it is merged?  I am willing to merge a disabled-by-default feature and add tweaks, such as configuration knobs, later.  However, as there is presently no scheduled release[1], there is no rush to merge this if you want to work more on it before it is added.

[1] Next scheduled release is ~2 years ago according to the Github milestone tracker.  Currently, interested dusers are expected to build and use development snapshots, pending the return of the people who post prebuilt binaries.

**Comment by jpcima** [comment]
>You say you did not know a better way to do it when you wrote it. Do you know a better way now? 

Unfortunately no. I'm not under the impression that SDL-Mixer can load any custom kind of `Mix_Music` instances other that formats it internally supports.
I have kindly requested of @Wohlstand for some advice about this commit, as he is very experimented on this (being author of [SDL-Mixer-X](https://github.com/WohlSoft/SDL-Mixer-X), a library having ADLMIDI playback).

>What, if any, further work do you want to do on this before it is merged?

- About the `hook_finished`, that one is ignored on the MIDI path based on Win32, so maybe it's not so strictly important to handle it?

- ADLMIDI should be pulled in by `dlopen()` calls, or by Windows equivalent `LoadLibrary()`.
It must indicate a file location for the library, which must be found in a varying way according to platform; I don't have access to all of them for a test. (by not all of them, I mean Mac, and I'm also not familiar with a way to make a MinGW cross-build from Linux based on Scons)

- I've been timid about splitting the work into several files, possibly a number of things will be better if moved somewhere outside. Most importantly from now, the dynamic loading API definitions of libADLMIDI, in replacement of `#include <adlmidi.h>`.

>I can take the work of adding new configuration values to Rebirth if you indicate, whether here or as review comments on the commit, which constants need to be replaced by which configuration values.

Most importantly there are

- A switch on whether to use ADLMIDI or SDL-Mixer for MIDI. Current code is going to try ADLMIDI, and SDL-Mixer on failure. (meaning, the SDL path is normally never taken)
- Number of chips (polyphony). More increases CPU consumption, needs vary depending on bank. DMXOPL3, which is the community based Doom bank, recommends 6 for playback of GM.
`adl_setNumChips(adlmidi, N)`
- The bank of instruments. An index into the embedded bank set, or a file on the disk.
`adl_setBank(adlmidi, N);` OR `adl_openBankFile(adlmidi, FILE);`
I picked the number `31` for no particular reason other that trying a few, and finding it to be good sounding; it designates "Little Big Adventure :: 4op". [Here](https://github.com/Wohlstand/libADLMIDI/blob/master/banks.ini) is a listing of the embedded banks.

**Comment by vLKp** [comment]
> * About the `hook_finished` ...

I rarely work with the Windows sound path.  I cannot say whether this is important.

> * ADLMIDI should be pulled in by `dlopen` ...

I prefer load-time linking whenever practical, but since you already wrote the dynamic loader for it, I am inclined to support that.

I will review the pull request and likely merge it within the next few days.

**Comment by jpcima** [comment]
As I understand it, the purpose of the finished hook is to begin a different track after the completion of a current one. The finished hook has appeared in 2 occurrences.

https://github.com/dxx-rebirth/dxx-rebirth/blob/726233e043e954049d2a8380baf4e64b647c79a2/similar/main/songs.cpp#L470-L474
https://github.com/dxx-rebirth/dxx-rebirth/blob/12b57e84e6f2c90e011d45848c4e485762f994f5/similar/arch/sdl/jukebox.cpp#L354

On libADLMIDI playback, it's not difficult to check for a finished track: it takes a call `adl_atEnd` and a wait until the sample stream becomes 0.

My problem about the SDL mixer has been this: where to invoke the callback from while the music stream was hooked? probably not from the hook callback itself. According to this [documentation](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_60.html):
`NOTE: NEVER call SDL_Mixer functions, nor SDL_LockAudio, from a callback function.`

So, to invoke into `mix_play_file` at the end of callback is likely going to break the library contract.

**Comment by Wohlstand** [comment]
For this case it's possible to have some sort of a hack - the atomic boolean that will be checked in a different thread from which you are able to call SDL Mixer's functions safely.

**Comment by jpcima** [comment]
That's an idea of a workaround, however I haven't yet found a way how I could possibly plug this in the same thread which manipulates the SDL mixer.

Maybe I have found another defect about the music hook. It's likely that `Mix_HaltMusic` inside `mix_stop_music` is not going to have any effect. Documentation of `Mix_HookMusic` also says:
`All the music playing and stopping functions have no effect on music after this.`

**Comment by vLKp** [comment]
@jpcima : I made a few commits on top of your branch, including adding SCons support for turning the feature off at build time.  I haven't written up a configuration parser for it yet, but plan to do so soon.  In the meantime, if there are any last changes you want included before it is merged to master, now would be the time to suggest them.  Similarly, if you want to rebase the series to change any commit messages, this is the time to do so.

Your work, with my commits on top, is temporarily pushed to [`experimental/adlmidi`](/dxx-rebirth/dxx-rebirth/tree/experimental/adlmidi).  That will be removed when I merge it to `master`.

**Comment by vLKp** [comment]
That branch is now removed, and the work is in master.  It has a configuration file hook, but no GUI yet.  I have plans to rework parts of the GUI configuration soon, so it seemed a waste to add a GUI for it that will shortly be replaced.

**Comment by Wohlstand** [comment]
While reading this https://github.com/dxx-rebirth/dxx-rebirth/blob/a76487405cfe662c21b95f9a0aa80f9d95ec4c1d/d2x-rebirth/RELEASE-NOTES.txt#L71-L72
I have something to note:

Please add the note that the "ADLMIDI" that is meaning my library https://github.com/Wohlstand/libADLMIDI which is calling as "libADLMIDI", but not the original ADLMIDI console player https://github.com/bisqwit/adlmidi which is very old and develops very very slow. libADLMIDI is directly basing on original ADLMIDI and contains over 4 years of hard work that was made by me and friends include @jpcima. It's now far-far different from original ADLMIDI.

**Comment by vLKp** [comment]
Naming the successor project so much like the original is a bit confusing.  Would it be sufficient to **s/ADL MIDI/libADLMIDI/** in both those lines?  If not, please propose specific wording that you would like used here, and I will add it.

**Comment by Wohlstand** [comment]
Yes, the "libADMIDI" is fine ;3
Anyway, you gave me the idea that I would to rename my project into something like "libOPLMIDI" or something that I'll begin a discussion on my end.
