### ISSUE TITLE
d1x-rebirth - N_secret_levels triggers SIGTRAP

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#41]
Loading the standard Descent 1 campaign in d1x-rebirth triggers a SIGTRAP when initializing N_secret_levels. This variable links to Current_mission->n_secret_levels. However if I read the code correctly, this one should be initialized properly before load_mission_d1() is called. What am I missing here?

**Comment by vLKp** [comment]
I can confirm a SIGTRAP using v1.5 data, but not at the site you report.  For me, the trap is because the filesize matches `D1_MISSION_HOGSIZE2`, which is not handled in the `load_mission_d1` switch statement.  The code is wrong, but the Int3 was always silently ignored until btb requested that they be enabled.  The default case happens to fall through to `D1_MISSION_HOGSIZE`, so the code works.  Adding a case statement for `D1_MISSION_HOGSIZE2` fixes the crash and does not change normal code flow.  After fixing this SIGTRAP, the game starts fine for me.  Could you post a backtrace for your SIGTRAP?

**Comment by vLKp** [comment]
Commit 5a015b38e58d2555e79392c42db098483f698663 fixes the SIGTRAP I saw.

**Comment by zicodxx** [comment]
Actually your commit fixed the SIGTRAP for me as well. I do not know exactly why it does as the backtrace ended at "N_secret_levels = 3;" - under the addition you made. I have to learn more about these events and how to address them properly. Thank you.

**Comment by vLKp** [comment]
I usually prefer a backtrace over a specific line indicator.  Optimized builds reorder code flow in ways that can cause misleading debugger output.  There is only one `N_secret_levels = 3;` and it occurs as the next line after the Int3 that trapped.
