### ISSUE TITLE
Glass shattering does not trigger switches

### ISSUE THREAD

**Issue by wm4** [dxx-rebirth/dxx-rebirth#419]
When a switch is "shattered" as glass by a nearby explosion, it doesn't trigger it. This leads to broken gameplays, and e.g. levels cannot be completed. This is a regression.

Reproduction:
- start level 1(builtin mission)
- open the door in front of you (the room with the lava flow and the hostage door)
- run honestbob cheat (all weapons)
- fire earthshaker missile and hit approximately the ceiling between the switch and the door on the sides
- earthshaker will indirectly destroy the switch through bng processing
- but the walls the switch opens are still closed

Commit causing the regression: f6352e7957368975c56e74d2010fc2beb1cd6826 (didn't reverify whether it's really the correct commit, or whether the commit fixed by it is the cause)
My fix and analysis: https://github.com/wm4/d2x-c/commit/57cf8027c285ffc7deb9062b869252b6e243717d
Note that I reverted this new behavior in the commit after that because I don't like it; as far as I remember, the fix worked, though.

**Comment by vLKp** [comment]
Confirmed for the unwanted results.  However, the game has _never_ run triggers when the switch is destroyed by the glass logic.  Skipping triggers here is a bug.  The difference is that the cited commit made it _much_ easier to provoke this bug.  Previously, the game would cast a `player_info` to a `laser_parent`, which almost always resulted in values that tricked `check_effect_blowup` into aborting early due to the logic that was supposed to prevent origins other than the player or guidebot from triggering it.

The above commit prevents the switch from being destroyed, which aligns with how the game previously worked.  However, now it is prevented explicitly, rather than prevented accidentally through type confusion.
