### ISSUE TITLE
Runtime bug: D1X-R, Cannot chose level from NEW GAME in First Strike

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#428]
### Environment

Happens in current builds such as da59e1ff5a8026053b1f04f671f34d441754beab

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Description

The issue affects Descent: First Strike campaign being played in D1X-Rebirth.
When you finish a level in this campaign, return to the main menu and select NEW GAME. You should be presented with an input box prompting you to input a number of any level you already played so you can start in it.
However in current versions of D1X-Rebirth, no matter how many levels you finished, you will not get this selection but are shown the difficulty selection instead (which should happen after the level selection).

#### Regression status

The issue stems from a commit of March 10th: https://github.com/dxx-rebirth/dxx-rebirth/commit/9898d136f106b96b821cc6ba7da01b98faa64988
After some investigation, I believe I can isolate the issue further to the function get_highest_level() which was modified in the commit mentioned above. I am a bit rusty, but I think it comes from the fact that mission.filename == 0 will automatically default to DESTSAT, setting the highest level number to 0. Before the commit, this would only modify highest_saturn_level. Again, I could be wrong here.

### Steps to Reproduce

1) Launch D1X-Rebirth.
2) Start Descent: FIRST STRIKE campaign.
3) Finish the first level and enter the second.
4) Press ESC and return to the main menu.
5) Select NEW GAME and select Descent: FIRST STRIKE again
You should be presented with the level selection now, but it is not present.

* Engines affected:
  * [X] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by Neurochild247** [comment]
The bug is confirmed to be only present in the current versión. I have other three previous versions and in all of the, the level select is working.

I used a pilot from the current version and it works with the others.

v0.58.1:
![scrn0001](https://user-images.githubusercontent.com/52017370/59812489-cefdb900-92d3-11e9-8488-fba39a13e218.png)
![scrn0002](https://user-images.githubusercontent.com/52017370/59812717-8a265200-92d4-11e9-9331-48edacf8d3a2.png)

v0.60 Beta 1:
![scrn0001](https://user-images.githubusercontent.com/52017370/59812731-990d0480-92d4-11e9-97d7-1ec415fcad94.png)
![scrn0002](https://user-images.githubusercontent.com/52017370/59812735-a0cca900-92d4-11e9-950b-52ab3c0d22e6.png)

v0.60 Beta 2:
![2019-06-20 01-24-18](https://user-images.githubusercontent.com/52017370/59812883-29e3e000-92d5-11e9-83a6-e2ae7ac57879.png)
![2019-06-20 01-24-28](https://user-images.githubusercontent.com/52017370/59812895-3831fc00-92d5-11e9-9941-040fa841a9ed.png)

commit 7e362f9 (current version)
![2019-06-20 01-19-37](https://user-images.githubusercontent.com/52017370/59812949-6283b980-92d5-11e9-859e-fb5e8b822fb5.png)
![2019-06-20 01-19-48](https://user-images.githubusercontent.com/52017370/59812957-6adbf480-92d5-11e9-9ea3-1fec490abefd.png)

**Comment by vLKp** [comment]
Yes, an empty mission filename is treated as an alias for `"DESTSAT"`.  In Descent 2, playing the original campaign filled `Current_mission->filename` with the value `"descent"`.  In Descent 1, it is left blank and incorrectly triggered the alias.  Is there any reason not to fix this by setting `Current_mission->filename` to `"descent"` in both games?

**Comment by zicodxx** [comment]
@vLKp Yes, actually, the game uses the filename for savegames and demos as well, breaking backwards compability with them. There's more - such as the hli in the player save itself, mission checking in Multiplayer (not that critical considering version checking), but it's a rabbit hole.

I think if we wanted to get rid of the different declarations in mission.h, it might be less painful to have D2X see First Strike with an empty filename, since Descent 2's campaign uses "d2".

**Comment by vLKp** [comment]
D2X users could have saved a game while playing First Strike through the D1 emulation.  I did that at least once.  Changing D2X's name for First Strike would break such savegames, according to your remark about savegames remembering mission filenames.

I reverted the code logic to how it worked before, though retaining use of the newer helpers.  I also restricted the check to D1X, since D2X doesn't use an empty string for First Strike, and even if it did, I find it unlikely that someone would have played Destination Saturn in Descent 1, then copied their high score file to a D2X directory and expected to keep their progress.

The above commit should fix this issue.  Please reopen if the problem persists.

**Comment by zicodxx** [comment]
Makes sense. Thank you. You work fast! :D
