### ISSUE TITLE
Level select not working in D2X-rebirth 

### ISSUE THREAD

**Issue by chaosshade** [dxx-rebirth/dxx-rebirth#432]
Level select isn't working no matter what I do.

I'm using d2x-rebirth version 20190621-win on Win10 x64, running the program as admin.  I have all levels unlocked as far as the game is concerned.

**Comment by vLKp** [comment]
Administrator should only be required if you previously ran the game as administrator and its files were created with restrictive permissions.  Normally, running without administrator should be fine.  I frequently run the game without the ability to write back its files, and the only consequences are that I can't save my game and that my player preferences tend to be forgotten.  The game otherwise plays normally.

Using [the current HEAD commit](/dxx-rebirth/dxx-rebirth/commit/75de1c23c1d65283c0f1a8fd7e2c04d3facb10f5), which differs from your version only in ways that should be irrelevant, I do not see any problems consistent with your report.

You wrote:
> I have all levels unlocked as far as the game is concerned.

Does that mean that, when you choose the mission (such as `Descent 2: Counterstrike!`), the game asks you on which level to start?  If so, and you choose a level higher than 1, you start on level 1 anyway?  I tested that here and it works as expected for me.  If this is not what you meant, please provide exact steps to reproduce.  Starting at the main menu, tell me which menu items to choose and how to answer the questions the game asks.

**Comment by chaosshade** [comment]
I just run it as admin out of habit, I doubt that really has any bearing on it.

Steps to reproduce:
 - Clear the last level for the mission pack using cheats (24 or 20)
 - Main menu
 - New game
 - Select <Descent 2: Counterstrike!> OR <Descent 2: Vertigo>
 - SURPRISE!  kicks to Zeta Aquilae FMV OR the Vertigo briefing

The level select DOES NOT appear for me, if I want to play a specific level I need to use FREESPACE to warp to a different level.

________________________________

**Comment by vLKp** [comment]
That is what I already tried.  I have Vertigo unlocked all the way to the end on my test pilot, and I get both the level prompt and difficulty prompt.  Do you not receive the difficulty prompt before the briefing begins?  That should always be shown.

The only way not to get the level select prompt is if `get_highest_level` returns that your highest level is not greater than 1.  This happens if the mission is not previously known, or if your highest level is actually 1.

Note that if you use cheats, the game does __not__ update your highest level visited:

https://github.com/dxx-rebirth/dxx-rebirth/blob/75de1c23c1d65283c0f1a8fd7e2c04d3facb10f5/similar/main/gameseq.cpp#L1937-L1938

You must reach the new level without cheating, and be in single player.

**Comment by chaosshade** [comment]
In OG (and in previous versions) the "highest level visited" updated just fine if I finished the game using cheats.

and yes, the difficulty selector appears, I'm so used to clicking through it that it's a step I missed, sorry.

________________________________

**Comment by vLKp** [comment]
According to `git blame`, the call to `set_highest_level` has been indented like that since btb imported the source in 2001.  The conditional was last touched by zicodxx in [Moved all these unsorted global cheat variables to a handy structure; Simplified reading of the cheats without trying to make it complicated so no one finds them (everyone can get the source); Removed one or two cheats which carry more garbage than they are worth; Added replacement for the bittersweet cheat; Made FPS Counter an option of Graphics menu](/dxx-rebirth/dxx-rebirth/commit/d6fbef4e43406f7f5400e4c2b0cb2ef6984955a4), when he renamed `Cheats_enabled` to `cheats.enabled`.  Prior to that change, the conditional _also_ had not been touched since btb's import.  I don't see how prior versions of Rebirth could have allowed you to hit this call with cheats enabled.  It's possible that the DOS game behaved differently from the source that btb imported, but not likely that someone would have changed this in that window.

Note that it's not about whether you finish the game using cheats.  It is about whether you entered the level without using cheats.  Once the flag is enabled, the only way to clear it is to start a new game.  Reloading a saved game reloads the flag from the save file.

Does the level select work correctly for you if you reach a new level without using cheats?

**Comment by chaosshade** [comment]
Yes, the level select works fine if I clear the levels legitimately.

________________________________

**Comment by vLKp** [comment]
In that case, the program appears to be working as intended.  If you know of a specific prior version where cheats could be used and the game recorded the progress anyway, please reopen and this can be reviewed as a regression.

**Comment by Descender1032** [comment]
Comments on my own experiences with this:
- I suddenly found my entire progress with Counterstrike and Vertigo lost, unfortunately not quite sure when this happened, but definitely not before upgrading from 0.58 to 0.61 
- Haven't lost any progress with custom missions
- Counterstrike no longer registers progress. Even if you beat a level, you don't get to choose which level to start from
- Despite the apparent progress reset, this is not an issue for Vertigo. Custom missions work with no problems. Level progress registers fine with every mission other than Counterstrike.  This behavior is directly analogous in D1X. 
- I tried reverting to 0.58 in D2X and completing level 1 did let me select between 1 and 2. After returning to 0.61, I could still select between levels 1 and 2, but beating level 2 didn't unlock level 3 for selection.

**Comment by vLKp** [comment]
There is special code to reorder the progress list to move builtin missions to the top, so that they are never lost.  I think this code is correct, but if it misbehaved, it could have discarded builtin progress.

Failure to remember progress sounds like a real issue.  According to @chaosshade, progress was remembered when not using cheats.  I doubt it would have broken since his test, but I can check that.  Reopening until I can test it.

**Comment by vLKp** [comment]
Progress is recorded for me.  These are the ways that progress might not be recorded:

- You used cheats.  I discussed that earlier, so I will assume you saw that and were not cheating.
- You were in multiplayer.  These rules both applied in 0.58.1, so we can rule this out too.
- `set_highest_level` returned without saving.
  - Your player file had an error reading in.
      https://github.com/dxx-rebirth/dxx-rebirth/blob/ac4f76136be9e0dc7e2b2042938c121096c024c9/similar/main/playsave.cpp#L1198-L1200
  - `find_hli_entry` found nowhere to save your current mission's progress.
      https://github.com/dxx-rebirth/dxx-rebirth/blob/ac4f76136be9e0dc7e2b2042938c121096c024c9/similar/main/playsave.cpp#L1203-L1206
- Your progress was saved under the wrong mission name, so it is not detected when you go to start a new game.
- Your player file was not saved properly, so the updated record was lost.  You would likely get an error message for this, and it would probably corrupt the player file in a very noticeable way.

I don't see a way for `read_player_file` to fail and not break other things, so you probably would have noticed that.  Similarly, `find_hli_entry` prints a diagnostic if it refuses to save an entry, and that should not happen for `Descent 2: Counterstrike`.

The game should evict old entries if your mission table is full, and has special handling to try to avoid evicting builtin missions.

Can you post your player files, so I can check whether progress is saved when I play using that pilot?

**Comment by vLKp** [comment]
No response from reporter.  Cannot reproduce.  Closing.

Please reopen if you can provide information to allow further investigation.
