### ISSUE TITLE
Menu upgrades and improvements

### ISSUE THREAD

**Issue by bliebeg** [dxx-rebirth/dxx-rebirth#457]
hi! I've been working with zico to get Rebirth to compile on Windows so I can start helping out. zico gave me the basics of what needs to be improved but I wanted to post here to get a list of what needs to be worked on. I searched for a GUI-related Todo list, but couldn't find one.

**Comment by vLKp** [comment]
It's been so long since anyone volunteered to do any work, I stopped trying to maintain public to-do lists.  The GUI subsystem is actually in relatively good shape, unless you want to tackle some complicated issues.  Among the things that could be better:

- If font scaling is enabled (default), some menus don't fit well on the screen because the game's original resolution was so small.  If font scaling is disabled, the menus fit fine, but some people may not like how tiny the in-game fonts are when scaling is disabled.  It could be interesting to split scaling of menu fonts from in-game fonts, so that the in-game messages can be upscaled (for easy reading during battle) while the menus are not (since they will generally be accessed outside of play).
  - More generally, it would be nice to be able to write detailed and expressive menus without worrying that font-scale-enabled users would have trouble accessing the menu.  Some menu items are not explained as clearly as I would like, because there is insufficient space to explain it well.
- Writing good menus is painful.  I've avoided working on certain features because I recognize that configuring the feature would be best done through a GUI, I don't want to deal with writing that GUI with the limited tools available, and I expect players would refuse to use the feature if it did not have a good GUI.
  - The menu system assumes that each menu item gets its own line.  The kconfig interface doesn't use the menu system at all, due to its more complicated layout requirements.  Supporting menus that can put multiple items on one line, or can handle items that require more than one line, would be nice.
- Eliminate the global `grd_curcanv`, and fix all the things that break when it is missing.  I started on this a few years ago and did most of the easy parts.  Many things that need the current canvas now receive it as a parameter.  However, there are quite a few sites that expect to change the canvas, call some functions, then change the canvas again.  These should be fixed to pass the correct canvas to the relevant subfunctions.
- Better text input processing in menus would be nice.  Emulating some of the common parts of readline could be interesting (backward-kill-word, paste, etc.)
- Currently, game logic and window rendering are intertwined.  It's not practical to have a headless game server.  When a level-ending event happens, it is propagated up through multiple layers of return codes in window processing.  It would be better to isolate the viewing of the game from the execution of the game.

This is all fairly high level.  If you want more information about a topic, please ask.

**Comment by bliebeg** [comment]
Lemme see what I can figure out. I was way-laid at work and now have a weekend off. 

Are you on Discord at all? It may be easier to chat about what I can manage there, than comments back and forth.

**Comment by vLKp** [comment]
> Are you on Discord at all?

No.  I see the value of chat services, but I don't use Discord.

**Comment by bliebeg** [comment]
IRC, perhaps? I don't mind github, but real-time chatter can be better.

In the meantime, I have my latest batch of errors from trying to get D2X. Maybe you can help shed some light of how to fix it?
https://pastebin.com/rJjmvCmd

A lot of the code and macros are above my head... I'm also not sure what all files need to compiled vs what can be ignored.

**Comment by vLKp** [comment]
I don't normally use IRC either.

It would help if you enable `verbosebuild=1` or equivalent in your tool, so that the command line used is shown as well.  `SConstruct` is currently the definitive reference for what should be built.

- `-Wsign-compare` warnings: ignore these, or turn them off entirely.  I'd like to see them fixed, but they are numerous and not obviously wrong.  `SConstruct` suppresses these.
- A small amount of C++14 support is required.  `SConstruct` probes for this and aborts if the compiler cannot provide it.  You probably need to add `-std=gnu++14` to the command line, or switch to a gcc version that defaults to a new standard.  According to the [gcc-6 release notes](https://gcc.gnu.org/gcc-6/changes.html), it defaults to `-std=gnu++14` for C++.  Either you're using an older gcc or your current build options explicitly selected an old standard.  Fixing this will resolve your issue with `d_enumerate`, among others.
- `C:\CodeBlocks\dxx-rebirth\common\arch\win32\except.cpp|200|error: 'AddVectoredExceptionHandler' was not declared in this scope|` - you tried to enable the crash dump handler, but your system headers don't support it, or are configured incorrectly.  Did you set `_WIN32_WINNT` to at least Windows XP?  (If you had shown your command lines, I could check that for you.)

Some of your other errors would probably go away if you fix these problems, so I will stop here.  Fix those, retry, and report back with anything that still does not work.

**Comment by bliebeg** [comment]
Here's the dxxconf.h I cobbled together. I wasn't exactly sure what I needed to include, so I copied as much as I think I needed. zico mentioned the main bulk of defines to be used. I don't really understand what they all do, or why there are so many of them, so I'm pawing in the dark, somewhat.
https://pastebin.com/x9jNhMdV

And here are the errors. https://pastebin.com/6Afp596B

I'm going to ignore the -Wsign-compare bits. I added the flag, but they still popped up.. whatever..

The SConstruct was... a bit much to understand. I've never dealt with one before, so I have next to no idea how to make use of what it says. I could use some pointers.

**Comment by vLKp** [comment]
I have touched `SConstruct` 1003 times over 6 years, so yes, it's quite extensive by now.  Interestingly, `SConstruct` has been touched a total of 1245 times, so I account for a majority of it.  This is even more pronounced in `git blame`.

Yes, many of the options require reading the `SConstruct` file to determine their purpose and use.

You enabled `-Wsign-compare`, which was already enabled by default.  You were supposed to set `-Wno-sign-compare`, to _disable_ that warning.

`SConstruct` is Python, with some extra libraries preloaded.

It looks like you have no definition for `_WIN32_WINNT`, unless your compiler is inserting one for you.  You probably want `_WIN32_WINNT=0x600`.

`gcc-5.1.0` is an odd choice.  `gcc-5` went up to `gcc-5.5` before upstream moved on.  On principle, I suggest using the latest stable version of the compiler in whatever series you choose to use.

You have no definition of `DXX_INHERIT_CONSTRUCTORS`.  This omission will definitely cause problems, and probably explains your error with d_event_joystick_moved.  I would have expected a diagnostic at the site where that macro is called, though.

For the `DXX_CALL_PRINTF_DELETE_COMMA_` errors, seeing the post-processed output might be helpful.

**Comment by vLKp** [comment]
In the time since this ticket was opened, the minimum C++ standard was raised to C++17, and gcc-7.x is now the minimum required compiler version.

@bliebeg: are you still interested in working on this?

**Comment by vLKp** [comment]
No response from original reporter.  Closing.  If you wish to work on this, please post back and reopen.
