### ISSUE TITLE
Runtime crash: Descent 2 map secret exit, crash on loading secret map

### ISSUE THREAD

**Issue by Daniel-Leontiev** [dxx-rebirth/dxx-rebirth#465]
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [x] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.8
  * [ ] Mac OS X 10.9
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13

* Debian
  * [ ] Debian Wheezy
  * [ ] Debian Jessie
  * [ ] Debian Stretch
  * [ ] Debian Buster
* Fedora
  * [ ] Fedora 26
  * [ ] Fedora 27
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 16.10 (Yakkety Yak)
  * [ ] Ubuntu 17.04 (Zesty Zapus)
  * [ ] Ubuntu 17.10 (Artful Aardvark)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

### Steps to Reproduce

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

* Players affected by issue:
  * [ ] Game host
  * [ ] Game guests

When playing Descent 2 map 3, there is secret exit (red portal). When entering the port
message is displayed that secret level is found, and the current map finishes with
the score sum screen, however the secret level never load, game just crashing. No log!

**Comment by vLKp** [comment]
By "Descent 2 map 3", I assume you mean `Descent 2: Counterstrike` (as opposed to `Descent 2: Vertigo`).

I don't see in the report an indication of what commit you played or how it was built, so I built the [current master
](/dxx-rebirth/dxx-rebirth/commit/d2640462cb9e816e72816b3b8ad8635484f873da) and used that.

Next time, please provide more specific instructions for how to reproduce a problem.  I don't have the maps memorized, and spent several minutes just trying to find the exit.  Once I found it, it worked fine for me.  No crash.  No error message.

For the record, teleporting to segment 109 will arrive very close to the secret level teleport.

What do you see that makes you think the game crashed?  Usually, if the game crashes, it should tell you that, and provide you with additional information to report.

**Comment by Daniel-Leontiev** [comment]
I apologize for incomplete info.
The version that I'm using is `dxx-rebirth_20191018-win`.
`D2X-Rebirth v0.61 0.60.0-beta2-551-g9d22103d45cf  Vertigo Enhanced  Oct 18 2019 16:53:17`

And yes this is a standard Decent 2 Map 3 secret exit.
What happens is that after the dialog `You have found secret exit` I hit enter to go to next map. The game simply exits to desktop.

I've enabled `-safelog -debug -verbose` in `ini` and saved the game just before entering secret exit.
This is all there is in the log:

```
18:49:06.646 D2X-Rebirth v0.61 0.60.0-beta2-551-g9d22103d45cf  Vertigo Enhanced  Oct 18 2019 16:53:17
18:49:06.646 This is a MODIFIED version of Descent 2, based on Full Version v1.2.
18:49:06.646 Copyright (C) 1994-1996 Parallax Software Corporation
18:49:06.646 DESCENT is a trademark of Interplay Productions, Inc.
18:49:06.646 Copyright (C) 1999 Peter Hawkins, 2002 Bradley Bell, 2005-2013 Christian Beckhaeuser, 2013-2017 Kp
18:49:06.646 D2X-Rebirth built with PhysFS 3.0.2; loaded with PhysFS 2.0.3
18:49:06.646 D2X-Rebirth built with libSDL 1.2.15; loaded with libSDL 1.2.15
18:49:06.646 D2X-Rebirth built with SDL_mixer 1.2.12; loaded with SDL_mixer 1.2.12
18:49:06.646 Getting settings from DESCENT.CFG...
18:49:06.685 Using SDL_mixer library v1.2.12
18:49:06.830 sdl-joystick: 2 joysticks
18:49:06.830 sdl-joystick 0: Controller (Gamepad F310)
18:49:06.830 sdl-joystick: 5 axes
18:49:06.830 sdl-joystick: 10 buttons
18:49:06.830 sdl-joystick: 1 hats
18:49:06.830 sdl-joystick: 5 axes (total)
18:49:06.830 sdl-joystick: 24 buttons (total)
18:49:06.830 sdl-joystick 1: Razer Orbweaver
18:49:06.830 sdl-joystick: 6 axes
18:49:06.830 sdl-joystick: 24 buttons
18:49:06.830 sdl-joystick: 1 hats
18:49:06.830 sdl-joystick: 11 axes (total)
18:49:06.830 sdl-joystick: 64 buttons (total)
18:49:06.831 Going into graphics mode...
18:49:07.366 DXX-Rebirth: OpenGL: version 4.6 (4.6.0 NVIDIA 436.48)
18:49:07.366 DXX-Rebirth: OpenGL: GL_EXT_texture_filter_anisotropic available, max anisotropy: 16.000000
18:49:07.366 DXX-Rebirth: OpenGL: GL_ARB_sync available
18:49:07.366 DXX-Rebirth: OpenGL: vendor: NVIDIA Corporation
18:49:07.366 DXX-Rebirth: OpenGL: renderer: GeForce GTX 1070/PCIe/SSE2
18:49:07.366 DXX-Rebirth: OpenGL: disabling automatic GL sync since VSync is turned off
18:49:07.366 DXX-Rebirth: OpenGL: using no explicit GPU synchronization
18:49:07.422 Failed to open movie <pre_i.mve>: (null)
18:49:07.422 Rebirth: found encoded subtitles in "intro.txb"
18:49:13.579 PHYSFS: failed to unmap canonical directory "D:\Games\Descent 2x\descent.hog" (relative name "descent.hog"): "No such entry in search path"
18:49:17.260 EXTRA LIFE!
```

There is also `stderr.txt` and `stdout.txt` but both are empty.

**Comment by Daniel-Leontiev** [comment]
I have just confirmed that version `D2X-Rebirth version: 0.58.1, date: 2013/08/04` from the archive does not have this issue, it properly loads secret level.

**Comment by vLKp** [comment]
It looks like that snapshot was built without minidump support.  @zicodxx / @Mako88 : is that right?

@Daniel-Leontiev : can you rebuild with minidump support enabled?  If not, can you bisect to find the first bad commit?  0.58.1 was more than _6 years_ ago.  There have been more than twice as many commits since then as there were from the import of d2 to the release of 0.58.1.
```
# Commits from when zico imported d2x to when 0.58.1 was released (excludes history of d2x project)
$ git --no-replace-objects log --oneline 0.58.1-d2x |wc
   1716   30707  207758
# Commits from the import of d2 to when 0.58.1 was released (includes history of d2x project)
$ git log --oneline 0.58.1-d2x |wc
   3098   40656  278778
# Commits after 0.58.1
$ git log --oneline github/master --not 0.58.1-d{1,2}x |wc
   7173   46195  389839
```

Without a crash dump, a first-known-bad commit, an error message, or working steps to reproduce here, there is nothing I can do.

**Comment by Daniel-Leontiev** [comment]
I've done some testing and have tested every release up to this point, the last working release is this `commit: 38fabd7, date: 2019/08/14`

**Comment by Daniel-Leontiev** [comment]
The working release is dated `2019/08/14` but the actual commit `38fabd7` is `Commits on Aug 8, 2019`

**Comment by Daniel-Leontiev** [comment]
There is commit:
`79e0e2f` `dxx-r.sng: add !Rebirth.secret` on `Aug 15, 2019`
`6588bd6` `refactor secret level music code` on `Aug 18, 2019`

**Comment by vLKp** [comment]
That narrows it down.  If [Fixed two issues `...`](/dxx-rebirth/dxx-rebirth/commit/38fabd7c499e48193c1748d5e957fba63db90218) is known good and [Merge branch 'Daivuk:axis_buttons' into master](/dxx-rebirth/dxx-rebirth/commit/d6b2ab51a7d5a43fa16c279eeb927450922361f4) (the next build, dated 2019/09/04) is known bad, then there are only 51 commits in the search range.  This should be bisectable in 6 steps.  Can you isolate this problem to a specific commit?

I reviewed the commits you cite when they were proposed, and I re-reviewed them now.  I was not, and am not, happy with the use of `realloc`, but I doubt that is the cause of your problem.  I waived that use through then because it was copied from existing bad code elsewhere, and I try to avoid asking new contributors to clean up existing theoretical messes as a precondition to accepting their work.  Even if that were failing for you, it should cause a `nullptr` dereference, which would manifest as a game crash, rather than the silent exit you reported.  I see nothing in the cited commits that I think would explain your problem, particularly since they are primarily about adding a new feature that you have not indicated you are using.

**Comment by Daniel-Leontiev** [comment]
I have found what the issue is via testing!

This may be related to `6588bd6 refactor secret level music code on Aug 18, 2019`.

While playing D1x I have experienced a similar exit to desktop, as soon as I've entered secret level.
But that was second secret in the game. The first secret level was fine, turns out that I had music on!

I was able to reproduce this issue by enabling built-in music. But when I've selected `no music` option
in the `options` the crash did not happen anymore.

You can now fix this by looking at music code on or after commit `6588bd6`

Hope it helps!

**Comment by vLKp** [comment]
Thank you.  The tip about enabling music was key.  When I tested earlier, I had music off because that's how my pilot is normally configured.  Once I enabled music, I got a crash immediately on entering the secret level, and a backtrace to go with it.

```
Thread 1 "d2x-rebirth-edi" received signal SIGFPE, Arithmetic exception.
0x0000555555638196 in d2x::songs_play_level_song (offset=0, levelnum=-1) at similar/main/songs.cpp:616
```

The crash is a divide-by-zero because the array of secret level songs was zero-length, but was not null.  The original secret song code from @ziplantil (added in the commit you cite) had a test for `Num_secret_bim_songs > 0`, which should have prevented this.  That test was removed in my commit [Refactor song loading](/dxx-rebirth/dxx-rebirth/commit/c355e207fe3c3c633516c5dc5f30ac27f6914e7f) (which, incidentally, fixed the `realloc` issues I mentioned above) and replaced with a test for whether `BIMSecretSongs` was null.  Normally, that would have been a safe change, but due to the way a zero-length array was tracked, my new test was not correct.

The above commit fixes the crash for me.  Please reopen if the problem persists in a build with that change.
