### ISSUE TITLE
Alternative to GLU Dependency

### ISSUE THREAD

**Issue by shoober420** [dxx-rebirth/dxx-rebirth#468]
### Environment

https://github.com/dxx-rebirth/dxx-rebirth/commit/93d3793b306cebb50be1dc86f974204d5d877ac0

#### Operating System Environment

* [ ] Arch

#### CPU environment

* [ ] x86\_64 (64-bit Intel/AMD)

### Description

The only program that needs "glu" installed I use personally, is dxx-rebirth, even when building the sdl2 port. Why is "glu" a hard depencency? Can an alternative to "glu" be used?

### Steps to Reproduce

Try to compile dxx-rebirth with "glu" uninstalled, and the compile error will occur.

```
similar/arch/ogl/gr.cpp:70:10: fatal error: GL/glu.h: No such file or directory
   70 | #include <GL/glu.h>
      |          ^~~~~~~~~~
compilation terminated.
scons: *** [build/similar/arch/ogl/.d1x-rebirth.gr.o] Error 1
scons: building terminated because of errors.
Failed target count: total=1; targets with enable_build_failure_summary=1: 1
Failed node list:
        build/similar/arch/ogl/.d1x-rebirth.gr.o
Failed command list:
 x86_64-pc-linux-gnu-g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=redundant-decls -Werror=vla -pthread -funsigned-char -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -flto -std=gnu++14 -Werror=unused -Werror=useless-cast -Wno-implicit-fallthrough -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wsuggest-attribute=noreturn -Wlogical-op -Wold-style-cast -Wno-sign-compare -D_FORTIFY_SOURCE=2 -DPHYSFS_DEPRECATED= -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_I -D__STDC_FORMAT_MACROS -DDXX_USE_SHAREPATH=1 -Icommon/include -Icommon/main -I. -Ibuild -I/usr/include/libpng16 -I/usr/include/SDL2 -Id1x-rebirth/main "similar/arch/ogl/gr.cpp" -o "build/similar/arch/ogl/.d1x-rebirth.gr.o"
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by derhass** [comment]
That is an interesting point.

> Why is "glu" a hard depencency? 

Currently, the OpenGL version of the game simply uses `glu`, so it is a hard dependency because the code was written that way then the original OpenGL port was made.

> Can an alternative to "glu" be used?

Actually, the game uses only 2 `glu` functions:

* `gluPerspective`, and it already has an alternative implementation for the GLES version for that, so one  could get rid of that easily.
* `gluBuild2DMipmaps`. Newer GL versions (beginning with 3.0) could use `glGenerateMipmap` as a replacement, but for legacy GL, one would have to build the whole mipmap pyramid manually. However, since only power-of-two textures are used, it would be quite a simple average of each 2x2 pixel block to vuild a pixel of the next level, so it shouldn't be too much work. `gluBuildMipmaps` also checks if the texture size is supported by the implementation, that logic would have to be replicated, too.

**Comment by shoober420** [comment]
@derhass Thank you for all that info. I tried googling some info about GLU, but mostly got a bunch of hits for GLUT, which I’m almost for certain is a different thing.

The reason I ask, is not only is DXX-Rebirth the only program I have installed that requires GLU, I’m under the impression that GLU is outdated, and for legacy use only. Basically it’s obsolete, and superior methods exist for what GLU does.

I saw there’s some alternatives to at least GLUT (GLFW and FreeGLUT), but I don’t think that corresponds to GLU though, but I could be wrong.

In the end, I’m wondering if a more modern approach can be used to replace GLU, and make GLU optional for legacy systems, and the superior method preferred.

With the info you posted, this seems very likely. Thanks for sharing. Until then, I’m going to play through Descent 1 and 2 using SDL2 and look for bugs.

**Comment by derhass** [comment]
> @derhass Thank you for all that info. I tried googling some info about GLU, but mostly got a bunch of hits for GLUT, which I’m almost for certain is a different thing.

Yes, GLUT is a competely different library.

> The reason I ask, is not only is DXX-Rebirth the only program I have installed that requires GLU, I’m under the impression that GLU is outdated, and for legacy use only. Basically it’s obsolete, and superior methods exist for what GLU does.

Well, `glu` is outdated for sure. It provides some utliti functions for the legacy OpenGL which is really outdated. However, dxx-rebirth is using leagcy GL istelf, so using `glu` for that is fine. 

> I saw there’s some alternatives to at least GLUT (GLFW and FreeGLUT), but I don’t think that corresponds to GLU though, but I could be wrong.

No it doesn't. `GLFW` is for managing Windows and OpenGL contexts, and GLUT is usually used for the same purpose (although it also contains some furthe OpenGL utilities, but these are even more outdated). DXX-Rebirth uses SDL for these purposes.
 
> In the end, I’m wondering if a more modern approach can be used to replace GLU, and make GLU optional for legacy systems, and the superior method preferred.

Well. As I wrote earlier, there are not much `glu` functions wich really are used here, so we could get rid of it if we really want to. However, it is unclear what we really gain from this. There is a `glu` library for any platform there is support for legacy GL (and there will be, since most legacy GL apllications depend on `glu` too), so it is really not a limiting factor for the portability here.

**Comment by shoober420** [comment]
I see. Well upon learning this info, would it be possible to have an alternative to using GLU, while keeping both legacy rendering and modern rendering selectable?

Maybe like this, when one is using SDL2, the modern rendering method is selected by default. Then, when SDL1 is used, legacy rendering (GLU) method is used by default.

For instance, when one builds DXX-Rebirth, not having GLU installed would be fine, and would force SDL2 and the new modern rendering method.

**Comment by vLKp** [comment]
I'm not attached to the legacy GL code, although as derhass says, this capability is available everywhere.  If someone contributes a patch to replace the dependency, I'll look at it.  Otherwise, I'll look at changing `SConstruct` to detect whether glu is present.

**Comment by lemming104** [comment]
Paradoxically, that test fails on my system (it finds a usable GLU.h, but NOT a usable GLU library), which was previously producing builds that worked just fine.

I'm using MSYS2 on Windows, building for x64, and I've got basically the same set of packages that install.md recommends for Arch Linux, which uses the same package manager.  I've got GLU.h at `mingw64\x86_64-w64-mingw32\include\GL\glu.h` but there is no corresponding `glu.o` or `glu.a` file.  I think it may be using `mingw64\x86_64-w64-mingw32\lib\libglu32.a`, but I am not certain.

If I remove your test from SConstruct, I can still build, and it still works.

**Comment by vLKp** [comment]
Windows uses a different name for it.  I pushed 6af0595cfe463e2ce2aa5646a6aa36f41663b80f, which fixes this for my Windows cross-build environment.  If this still fails for you, please attach `sconf.log`.

**Comment by lemming104** [comment]
The test seems to pass now.  Thanks!

**Comment by vLKp** [comment]
The code, as currently written, requires GLU to function.  No one has offered patches to remove this requirement.  The dependency on GLU might go away if Rebirth used only modern OpenGL.  I did some private experiments on that, but it is nowhere near complete.

The configure test, as now written and amended based on feedback above, will correctly detect systems that do not provide the required GLU functionality.

Closing on the basis that (1) there is no currently usable alternative and (2) the configure script will advise users of the requirement.
