### ISSUE TITLE
Allow navigating menu with a gamepad/joystick

### ISSUE THREAD

**Issue by GadWissberg** [dxx-rebirth/dxx-rebirth#469]
Hello, I've been using DXX-Rebirth for a long time. Now I started using it with RetroPie on my TV using gamepad only. I came across a problem where I can't navigate the menus with the controller. This forces me to have a keyboard connected to my Pi only for navigating the menu.
I'd be happy to have an option to navigate the menus too with the gamepad.
Thanks

**Comment by vLKp** [comment]
This was [requested a year ago on the Rebirth forum](https://forum.dxx-rebirth.com/showthread.php?tid=1085).  The summary version is that I have no interest in writing such a feature for myself, and none of the people who want it have done anything to advance it.  I suggested in that thread (and quoted below, since the forum will close Real Soon Now) that a good first step would be for someone to write up a requirements document on what exactly the feature should do.  One user responded saying he would.  If he did, he never posted back to announce its completion.

My position posted then stands:
- I have no use for it.
- I have other things I use my time to work on.
- If someone else writes it, I will review it for inclusion.
- If someone writes a good enough requirements document, I _might_ work on the feature despite having no use for it.


> From the forum:
---
> No promises on when or if this gets implemented, but if you want to help, a great way to start would be to write up a requirements document.  From the posts here, I understand that interested users want the game to be usable with just a joystick, without using any other input devices (keyboard, mouse).  There is considerable wiggle room in satisfying that generality, and at least some ways of satisfying it probably won't satisfy the people who want to use it.  For example:
> * Is it acceptable if you need to use joystick buttons, not axes, to navigate?  Axes are analog inputs, so if an axis can be used, then the navigation code is more complex because movement below a certain joystick-specific threshold is noise and needs to be ignored, but movement above that threshold is user action and needs to be handled.  Buttons are digital inputs, so we can assume that all button presses are deliberate user action and all button presses should be handled.
> * If button-only is acceptable, how should the end user specify these buttons?  Does Rebirth ship with a fixed list and you are required to use those, with no ability to change them without recompiling the game?  Does Rebirth load user customizations and, if it does, how does the user enter those customizations?  Can we assume the user has a keyboard for entering complex configuration files, but he chooses to use the keyboard <u>only</u> for data entry, not when actually playing the game?
>     * If we can make that assumption, then it's easy to say that the user who wants customizations must use the keyboard to change how the buttons map to actions before he can play the game.
> 	* If we cannot, then we need an in-game interface that can be driven with the default controls and used to create non-default controls.  (Full disclosure: I'm not interested in writing such a user interface, so if your requirements document includes requiring an in-game interface, I won't be fulfilling your requirements.  Sorry.  I'll still consider including it if someone else writes it, though.)
> * Should the navigation be implemented by having the joystick controls act as a proxy for mouse controls (complete with using the joystick to move the on-screen cursor) or is it sufficient that the user can configure the game from the joystick without becoming frustrated with the controls?
> 
> Generally, think about what you would put in the instructions on how to use the new feature, and any caveats you would include to users about things that they cannot expect to work as a user might guess.  Going with the above example, some users might hear "Works with just a joystick" and expect to use pushing the joystick axis for "Pitch down" to navigate in one direction in the menu, and "Pitch up" to navigate in the other direction.  If the joystick-in-menu support is button-only, these users will be disappointed and/or frustrated, so the notes should warn them that this is not supported, and describe how to do it in a supported way.
---


One quirk that is new after that post is that someone contributed a hack to treat axis movement above a certain threshold as a button.  This was done to work around the oddity that some game controllers ship with triggers that report as axes, not buttons.  This hack may simplify the menu navigation feature, since a button-based navigation with configurable buttons could bind one of the axis pseudo-buttons as a navigation button, at which point the user could move an axis input to trigger the button and the associated navigation.

**Comment by vLKp** [comment]
I believe this is resolved by the work that @kajott contributed.
