### ISSUE TITLE
Runtime bug: Weapon hits appear to be allowing robots to turn much faster than normal

### ISSUE THREAD

**Issue by AlumiuN** [dxx-rebirth/dxx-rebirth#471]
### Environment

2019-10-18 Nightly Build (https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20191018-win.zip)

#### Operating System Environment

Microsoft Windows 10

#### CPU environment

x86\_64 (64-bit Intel/AMD)

#### Game environment

Only tested with Descent 1 (and user maps thereof)
(EDIT: Appears to affect D2 as well)

### Description

Hits on a robot with any weapon (including Plasma) appear to allow that robot to turn much faster than would normally be allowed, in some cases a single hit allowing a robot to turn a full 180 degrees to face a player almost immediately. (weapons also appear to have more of an effect on robots as far as knockback and other physics effects are concerned, but I'm less sure about that)

#### Regression status

Problem was not present in v0.59.1; unsure about any newer versions.

### Steps to Reproduce

The most obvious way to reproduce this issue is to be in Trainee difficulty, find a cloaking device, position yourself directly behind a robot with any weapon and hit them with it.

**Comment by MaddTheSane** [comment]
> [...]find a cloaking device,[...]

Alternatively, you could just cheat to give yourself a cloaking device.

**Comment by AlumiuN** [comment]
> > [...]find a cloaking device,[...]
> 
> Alternatively, you could just cheat to give yourself a cloaking device.

Well, yeah, the method doesn't really matter, just become cloaked :P (it's not strictly necessary anyway, but it's the easiest way of ensuring there's a big enough angle for the robot to turn that the bug is obvious)

**Comment by vLKp** [comment]
There was no 0.59.1.  Do you mean 0.58.1, or 0.59.100?

I can confirm that a PIG spins around quickly after being hit by level 1 lasers in `Descent 2: Counterstrike`.  I don't usually sneak up on robots, so I would not have noticed when this broke.

**Comment by AlumiuN** [comment]
Ah, my bad, it was 0.59.100. It does appear that enemies are also getting knocked around more than they would otherwise; it's most noticeable on the big ones (fusion hulks and the big orange ones in D2 with phoenix and mercury missiles that I can't remember the name of), where hitting them will often make them spin around in place.

**Comment by ziplantil** [comment]
I had noticed the same issue myself when testing a custom level set. I've checked that no robot properties for the Sidearm have been changed from the original D2 values (there's no HXM that modifies the Sidearm, for instance), but it turns around a lot more than I feel it should.

![sidearm_bug](https://user-images.githubusercontent.com/33909451/69000440-5e85b300-08d8-11ea-8ef7-37175a63782e.gif)

**Comment by vLKp** [comment]
0.59.100 was 1415 commits ago, so if that's the nearest known good commit, and the good/bad test is a subjective estimate of how much the robot gets pushed around, this will be a bit of a nuisance to hunt down.  Are there any particularly good test case levels or procedures either of you would recommend for this?  I can reach a Sidearm pretty quickly in `Descent 2: Counterstrike` level 5 `Quartzon System 1: Seaspring Gorge`.

**Comment by AlumiuN** [comment]
That's probably the fastest way of testing it in D2; if you want to test it in D1, there's a bunch of fusion hulks pretty close to the start of level 27 if you go through the first door on the right. The lasers seem to cause it more obviously than the other weapons.

**Comment by AlumiuN** [comment]
OK, so I've tested with all of the releases, and it would appear that the bug was introduced between the 2019/06/21 release and the 2019/07/10 (as it occurs in the latter build, but not in the former).

**Comment by vLKp** [comment]
Thank you.  That narrows the range quite a bit.  It suggests that e6716643327d7474fdb357bf6ddb9ed112d5b204 (dated 2019-06-20) is probably clean and f84cdff6a2817913ea9c29dfd7216cfbc69cb052 (dated 2019-07-07) is probably dirty.  There are 30 commits in that range.  None look obviously bad, but I have a couple of priority targets based on what they did.

- [Change object::signature to be a generation counter](/dxx-rebirth/dxx-rebirth/commit/bfeca84bb86ab75365f18d60c17e18f36dbfaf1d): this was invasive (`13 files changed, 143 insertions(+), 75 deletions(-)`) and can have surprising effects if it causes the game to get confused about the relationship of objects.
- [Reset definedness of per-game globals on new game](/dxx-rebirth/dxx-rebirth/commit/bea95ce1df86f643d0409896e93165ad3fea2583): though small, an early unpublished prototype of this caused some odd bugs when it reset more data than intended.  Those bugs were identified quickly and the offending portions reverted.

**Comment by vLKp** [comment]
Neither of the commits I suspected was at fault, though the bad commit was in the range that AlumiuN identified.  [Move Difficulty_level to GameUniqueState](/dxx-rebirth/dxx-rebirth/commit/1eaaff3016cc7631e751e451ac1c8a9973709e22) changed the type of `Difficulty_level` from `int` to `unsigned int`.  This in turn caused arithmetic expressions that used it to switch to unsigned computations, such as using unsigned division instead of signed division.  This caused wildly incorrect results when signed numbers were used in unsigned division, which is why sometimes robots would react very strongly and sometimes react normally, depending on whether the input was negative.

The above commit fixes the issue for me.  @AlumiuN: thank you for the report and the testing to identify the relatively narrow affected range.  Please reopen if you still see problems in current code.  Also, @ziplantil, thank you for the animated sequence demonstrating the wild turning in Sidearm robots.  AlumiuN had mentioned that robots seemed to be more strongly affected by physics knockback, and ultimately it was more efficient to test by knocking Sidearms around than by sneaking up on them and trying to let them turn on their own.  Looking back at the bug, I suspect that the problem reported in the title is actually another manifestation of the physics knockback effect, rather than that the robots were empowered to turn on their own.
