### ISSUE TITLE
Build failure: SConstruct is python2 but scons is python3

### ISSUE THREAD

**Issue by SanskritFritz** [dxx-rebirth/dxx-rebirth#475]
Build fails on Archlinux:
```
scons: Reading SConscript files ...
  File "dxx-rebirth/src/dxx-rebirth-0.59.100/SConstruct", line 17
    print "%s: %s" % (program.program_message_prefix, msg)
                 ^
SyntaxError: invalid syntax
```
Scons depends on python3 in archlinux.
How do I build dxx-rebirth with this scenario?

**Comment by parkerlreed** [comment]
Is this recent? I swear this has been building for me just fine.

```
[parker@stealth build]$ pacman -Q d1x-rebirth-git 
d1x-rebirth-git 0.60.0.beta2.r575.gca383c1fe-1
```

So yeah newest commit is installed (Using the dxx-rebirth-git from AUR)

**Comment by parkerlreed** [comment]
Wait why are you trying to build a 3 year old release?

![image](https://user-images.githubusercontent.com/841440/69283630-c1b66480-0bba-11ea-86ad-4add21ec197f.png)

Either use the newer or pull form master

**Comment by vLKp** [comment]
As parkerlreed suggests, this is _definitely_ not recent.  Line 17 doesn't even have a `print` statement on it and has not since at least a3d6bdd3f1a642df29df3b61dc2b53120a6308e8 in April 2018, which added quite a bit of Python3 compatibility and also pushed the `print` statement deeper into the file.  Digging deeper into history, line 17 has not had the particular `print` statement shown in the opening post since af863fdef7eb3d351c7ac6d6677a245fc3aae3af added Python3 print compatibility in October 2017.

To answer your immediate question: the preferred solution is to do as parkerlreed said, and use a supported version of current code.  You could also choose to run `scons` with a python2 interpreter.

I don't usually close issues outright, but since the limited information provided shows that this was filed for the old and unsupported snapshot 0.59.100 and the reported issue has been fixed for more than a year, I think a closure is appropriate here.  @SanskritFritz: please try a current snapshot.

@SanskritFritz: did you download the code by hand or is there an Arch Linux package that tried to build this snapshot?  If the latter, please advise its maintainer that an update to a newer version is needed.

**Comment by SanskritFritz** [comment]
I'm trying to create a package for the "stable" release and I thought 0.59 is the last stable release. Which release should I consider stable now?

**Comment by vLKp** [comment]
The last full release was 0.58.1, but that is much older and almost certainly will not work for you.  I consider current master to be quite stable, though that isn't a release as such.

**Comment by SanskritFritz** [comment]
So for packaging purposes I can use the latest tarball from [here](https://www.dxx-rebirth.com/download-dxx-rebirth/)?

**Comment by vLKp** [comment]
I would pull straight from the Github generated zip or tar.gz that was mirrored to that page, but yes, that page is a decent choice.

**Comment by SanskritFritz** [comment]
So I did and it is working well! The packages are done too:
https://aur.archlinux.org/packages/d2x-rebirth/
https://aur.archlinux.org/packages/d2x-rebirth/
Thanks guys!

**Comment by vLKp** [comment]
You are listed as the maintainer of the Arch package.  I see some differences between [your PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=d2x-rebirth) and [the one in Rebirth Git](/dxx-rebirth/dxx-rebirth/blob/ca383c1fe76bf519f3064d2188d77ab54f2b6b42/contrib/arch/d2x-rebirth/PKGBUILD).

- Mine builds everything in the `package` function.  (I think this was inherited from the reference copy I used.)  Yours uses a `build` function.  Is it correct to say that I should move the compilation to `build`?
- Yours has an obsolete `sed` call.  The line that the `sed` tries to rewrite was removed in [Move command line settable values into class Settings](/dxx-rebirth/dxx-rebirth/commit/e2e89ec8f56125f44804acd8905e23bddc442c19) (February 2013).  This `sed` could be removed.
- Yours does not use parallel compilation.  Rebirth is much more demanding on compiler time than it once was.  Parallel compilation can be a significant time saver if the build host has the resources to support it.

**Comment by SanskritFritz** [comment]
Oh, I didn't even know there is a PKGBUILD here! Here are my answers to your points:
- Yes, according to [archlinux guidelines](https://wiki.archlinux.org/index.php/Creating_packages#build()), building the program should happen in the build() function.
- Thanks for the heads-up! I'll remove that part.
- You explicitely set -j4 in your build for every system out here. I for example have a two cores processor, so it is more efficient to set -j2 for me. This flag can be set individually for every system in the /etc/makepkg.conf file (mine is: MAKEFLAGS="-j2").

**Comment by vLKp** [comment]
* OK, that should be changed.  I can make this change, but I don't have an Arch system on which to test it.  Would you be interested in submitting a pull request to update the `PKGBUILD` in Rebirth's Git repository to align with recommended style for Arch (for this and any other places where the existing Rebirth one would not pass review in Arch)?
* \[No further discussion needed.]
* That's a fair point: `-j4` may not be right for everybody.  I see from [the documentation](https://www.archlinux.org/pacman/makepkg.conf.5.html) that `/etc/makepkg.conf` has the same problem with `MAKEFLAGS` that Gentoo's Portage has with `/etc/portage/make.conf` specifying `MAKEOPTS`: the variable is documented as being used for flags to be passed to Make.  `SCons` is not Make, so while it understands `-jN` for jobs (and the manual page even states _`scons` supports the same command-line options as GNU `make`_), it does not understand some Make options like `-l`, so users who set such an option in their `MAKEFLAGS` / `MAKEOPTS` will get unwanted behavior.  In Gentoo, the utility library that wraps calls to `scons` tries to extract a reasonable `-j` value from the more general Make flags specified by the user.  Does Arch have a recommended way of passing the job preference of such users through to non-Make systems, so that parallelism is enabled and the user doesn't get an error when the user gives a Make-specific flag?  If not, is it preferred to pass `$MAKEFLAGS` and hope users are not setting Make-specific flags or is it better not to enable parallelism at all?

**Comment by SanskritFritz** [comment]
- I also have some general concerns about your PKGBUILD. First question is, why have a PKGBUILD in your source tree? It is distribution dependent, and should be maintained by the distribution to follow the changes in the distro (rebuild if depedencies change, etc). Moreover that PKGBUILD actually defines a -git package because it always builds from the git head. Hence it changes whenever you rebuild it, even if the version is not changed, that is misleading. Archlinux has [build in methods](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function) to change the version automatically. There is a -git package in the AUR, not mine, I haven't looked at it yet. Also your version number doesn't even exist in the git releases list.
- ...
- Oh I hoped makepkg would pass the $MAKEFLAGS to scons too. Well, I think most archlinux users would only set the -j flag, so it is pretty safe to pass it to scons. But I would simply leave it as-is, to avoid confusion.

**Comment by vLKp** [comment]
I wrote:

> (I think this was inherited from the reference copy I used.)

Looking back, I didn't use a reference copy.  Zico added the first version of this, and I applied some adjustments later.

---

- I have a `PKGBUILD` in the source tree because I don't have write access to the Arch repositories, but I do have write access here.  I also keep a Gentoo ebuild and a Fedora RPM specfile in the tree for the same reason.  I would keep a Debian/Ubuntu build setup, but no one has contributed one (and the last time one was maintained in-tree for Rebirth predated a major overhaul of the build system, so the package script would need an update), and I haven't been motivated enough to find/write one.  If I made some change that would be of interest to packagers, updating the `PKGBUILD` here would let me demonstrate how to use it.  Similarly, if I make a change that obsoletes an existing step, such as the `sed` in your `PKGBUILD`, I can remove it from the reference copy in the Rebirth tree.  Distributions are welcome and encouraged to keep a package in their distribution repository that builds Rebirth.  I keep these files as a reference copy, with the hope that distributors will both use these as a baseline and will contribute back improvements.  In the case of Arch, you have offered several valid criticisms, so we are on our way toward improving the reference copy.  The next step is for someone (maybe you, maybe me) to formalize the criticisms as a patch and then get the changes into the repository.

- - Since this is a build recipe, rather than a precompiled binary, I'm not sure what dependencies the distribution would change that would necessitate a change here.  I could see a distribution policy change (such as requiring `set -e`, or mandating how parallelism is done) could require a change here though.
- - For the version criticisms, I recognize them as valid, note that they were written by someone else, and agree that they should be changed.  Most likely, they should be handled as I did with the Gentoo ebuilds: a `-git` version that always pulls latest, and some version-pinned ones that always reference a specific commit, and so rebuilding them uses the same source every time.

  In the case of Gentoo, I know that they are behind on packaging Rebirth, and I would rather provide an up-to-date ebuild here that users can put in a local overlay than have users run the now very outdated version in the Gentoo tree or ask users to compile the package by hand.

**Comment by SanskritFritz** [comment]
Thanks for that detailed explanation.
You can have access to the packages, as the AUR is a user repository. I can give you co-maintainer status to my packages.
But anyway, I'll fix my PKGBUILD and then I can send a PR if you wish.
About the version change: the pkgrel variable is increased whenever some libraries that d1x depends on change to trigger a rebuild.

**Comment by vLKp** [comment]
Yes, please file a pull request with whatever changes you think are appropriate.

> pkgrel ...

I see.  Gentoo handles that through a different mechanism, where the package build script declares that it needs a "matching" configuration, and the package manager records the actual configuration used.  When the supporting library changes its subslot, that triggers the package manger to want a rebuild on the consuming packages, without the need to directly edit the ebuild files of the consuming packages.

**Comment by SanskritFritz** [comment]
Yes, but gentoo builds from source, while arch is binary, so the package version has to be changed in order to the package manager pick up the new package when updating.
