### ISSUE TITLE
does not auto record demo or record demo name

### ISSUE THREAD

**Issue by swrench** [dxx-rebirth/dxx-rebirth#476]
It does not auto record or name it despite it being turned on in the ini file

**Comment by vLKp** [comment]
Please provide more information.  Your report did not answer any of the standard questions posed in the new issue template.  You did not specify what commit you built.  You did not describe your test in enough detail that I can replicate it from what you posted.  When I _did_ attempt to replicate it, I received the expected result, so I have marked this issue as __cannot-reproduce__.

Steps not to reproduce:
- `git checkout ca383c1fe76bf519f3064d2188d77ab54f2b6b42` #Current HEAD of `master`
- `scons d2x=1 editor=1` # compiler=gcc-9
- `printf '%s\n' '-no-such-option' > $D2X_REBIRTH_HOME/d2x.ini`
- Try to start the game.  The game dies complaining that `-no-such-option` does not exist.  This confirms that it is reading the ini file.
- `printf '%s\n' '-auto-record-demo' > $D2X_REBIRTH_HOME/d2x.ini`
- Start the game.  Start `Descent 2: Counterstrike` level 1.  Observe that the demo counter is running.  Try to leave the game.  Receive a prompt for the demo name.  This is expected, since I did not assign an automatic naming scheme.  Your report states that auto-record did not work, but it works for me.

**Comment by vLKp** [comment]
I see your closure, but no comment.  Should I interpret that to mean that you identified an error in your testing, and the problem was not in the code, or should I interpret it to mean that you no longer wish to discuss the problem?

**Comment by swrench** [comment]
> I see your closure, but no comment. Should I interpret that to mean that you identified an error in your testing, and the problem was not in the code, or should I interpret it to mean that you no longer wish to discuss the problem?

I identified an error: It was me
