### ISSUE TITLE
Descent 2 Rebirth - Secret levels don't load

### ISSUE THREAD

**Issue by utreplix** [dxx-rebirth/dxx-rebirth#481]
Whenever I enter a secret level in Descent 2 Rebirth, it simply closes the game. No error messages or anything. I haven't seen anyone with this issue, so any help would be appreciated. 
I am using Windows 7 if that is the issue. 
So happy that this mod exists by the way.  :)

**Comment by AlumiuN** [comment]
Which version are you using? There was an issue with a number of past releases where this would happen if the built-in music was enabled; if it's the same bug causing it, the latest release should fix it.

**Comment by utreplix** [comment]
> Which version are you using? There was an issue with a number of past releases where this would happen if the built-in music was enabled; if it's the same bug causing it, the latest release should fix it.

I was using dxx-rebirth_20190917. 
I just downloaded the newest version and it works now!
Thanks for the help. :D

**Comment by vLKp** [comment]
Good to see you already found a solution.  Based on the symptoms and your success, this is probably #465.  It's not silent on Linux; you get a proper crash and a report of a divide-by-zero.  That problem was introduced in [Refactor song loading](/dxx-rebirth/dxx-rebirth/commit/c355e207fe3c3c633516c5dc5f30ac27f6914e7f) (25 Aug 2019) and fixed in [Fix crash entering secret level with music on, and no songs](/dxx-rebirth/dxx-rebirth/commit/93d3793b306cebb50be1dc86f974204d5d877ac0) (2 Nov 2019).

**Comment by utreplix** [comment]
> Good to see you already found a solution. Based on the symptoms and your success, this is probably #465. It's not silent on Linux; you get a proper crash and a report of a divide-by-zero. That problem was introduced in [Refactor song loading](/dxx-rebirth/dxx-rebirth/commit/c355e207fe3c3c633516c5dc5f30ac27f6914e7f) (25 Aug 2019) and fixed in [Fix crash entering secret level with music on, and no songs](/dxx-rebirth/dxx-rebirth/commit/93d3793b306cebb50be1dc86f974204d5d877ac0) (2 Nov 2019).


Hmm.  I probably should've looked again before I posted. I thought it was a specific issue to me though. Thanks for the info :D .  Awesome community you guys have here. I'll be sure to take a look if I have any other issues.
