### ISSUE TITLE
Co-op ship gets stuck during level progression

### ISSUE THREAD

**Issue by TORRaven** [dxx-rebirth/dxx-rebirth#483]
Seems after the 4th or 5th level progression through the campaign in co-op (D1), the hosts (me) gets stuck at the starting point.  Ship can look around and fire weapons, but cannot move or be moved from its starting spot.  Player 2 does not see this issue, and they are free to move about the level.

Running latest version of Rebirth with latest version of Descent 1 Retail.
Windows 10 Pro.

**Comment by TORRaven** [comment]
Just tested it again, starting in Level 1 - Ship stuck when Level 4 starts.  
Allowed Robot to destroy ship:  Lifter Robots do not move the ship, it sits stationary (Normally they bump and move you) and once ship is destroyed, the Camera does not pan out to show your death roll, it also sits stationary.  After death, ship still stuck.  After the mine is blown and the next level starts, control of the ship is restored.

**Comment by vLKp** [comment]
Confirmed, but only if I enable extra player slots.  It looks like the code for synthesizing player starts moves the host to a position that triggers some problems in the physics engine.  As a workaround, set max players to 4 or fewer so that synthetic starts are not created.

I will try to fix the start synthesis code.

**Comment by TORRaven** [comment]
The response to this bug is faster than most companies!  Fantastic work, and thank you @vLKp for your attention to this 👍

**Comment by vLKp** [comment]
I would have been about an hour faster, but in the course of trying to debug/reproduce this, I hit a different problem that seemed just similar enough to your symptoms that I had to run it down first.  It's not the same problem, and it's not likely to affect most players.

**Comment by vLKp** [comment]
The problem is that the level designer started the player very close to one side of the segment, so there is little room to move the player backward without moving the start entirely out of the segment.  The synthesis code assumes such movement is safe if the segment is big enough that two players can fit in the segment, and this segment is big enough for two ships.  The fix is to change the synthesis code so that the displacement does not move the player to a new segment, by detecting that a simple move would be out of bounds and doing something more elaborate, like moving the player toward the center of the segment first.

**Comment by vLKp** [comment]
The above commit fixed the issue for me.  Please update and retest.  Please reopen if you still see this problem.
