### ISSUE TITLE
Auto-select always picks highest weapon in recent builds

### ISSUE THREAD

**Issue by mmbetley** [dxx-rebirth/dxx-rebirth#508]
###Environment
#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200401-win.zip
https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200501-win.zip

### Description

When you are carrying at least three types of weapons and run out of one, auto-select should shift to the next highest on the list (e.g. if you have Smart > Flash > Concussion > Guided and run out of Flash Missiles, the game should switch to Concussion Missiles). Instead, newer builds will always select the highest weapon you are carrying, no matter which one you just ran out of.

#### Regression status

There was about a two-year gap before I started playing the monthly builds again, so I can only confirm this problem dates back to at least April 2020.

### Steps to Reproduce

Enter either game and test the auto-select order with at least three secondary weapons. Use one of the middle weapons on the auto-select list until you run out, and see which weapon gets selected.

I haven't played any multiplayer on either build, but I assume the same issue applies there.

* Engines affected:
  * [X] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [?] Multiplayer competitive
    * [?] Anarchy
    * [?] Team Anarchy
    * [?] Robo-Anarchy
    * [?] Capture the Flag
    * [?] Bounty
  * [?] Multiplayer cooperative

* Players affected by issue:
  * [?] Game host
  * [?] Game guests

**Comment by AlumiuN** [comment]
It looks like this was intentionally changed in commit 9c5b5b3e3657acc506fd88d41ba278a4b785a3bd. I'm not entirely sure why; the commit didn't include a reasoning and it's a change in behaviour from DOS.

**Comment by vLKp** [comment]
The commit did not include a citation to the motivating issue, but according to the remark I added in the release notes, this was done for issue #156.  The change was intentional, and was motivated by the belief that the DOS behavior was less desirable than the new rule.  Whenever weapon exhaustion forces you to switch weapons, why would you want to switch to a weapon that is even lower priority than what you just exhausted, when you have the option of switching to a weapon that is higher priority than what you just exhausted?

**Comment by mmbetley** [comment]
I feel like the old system was more flexible, though. It allowed you to make use of the same priority in different environments.

If you just respawned and collected everything and need the biggest missile for a dogfight, the Mega Missiles are in the right spot at the top.
If you're saving them for the next boss and you just ran out of Homers, the old system selecting Flash or Concussion meant a lot less chance of accidentally wasting a Mega.

That's why I'd like that option to return, and I hope you'll consider it.

**Comment by vLKp** [comment]
I think that argument can easily go the other way.  To avoid unintentionally switching to a mega missile on acquisition while recapturing dropped items, the player might put mega missiles lower in the list, and then the old rules would end up accidentally firing one after running out of homing missiles.  Under the new rules, the selection would move back to the top, away from the mega missiles.

To conserve mega missiles, you would want them to be below the cutoff line.  The auto-select should never be able to switch you to an item that is below the auto-select line, so putting precious weapons below it would avoid auto-selecting them both for weapon pickup and for weapon exhaustion.

I have no particular attachment to one system versus the other, but I generally dislike adding toggles to the user interface, because of the pressure from players to keep the menu system viable even with very low screen resolutions, which limits explanatory text.  I also get push back for having toggles that can only be set through editing a configuration file, which would otherwise be an easy way to keep the menu system clean.

I am not ruling out reverting this, but I am not yet convinced that it should be changed.  When a change has been active for years without negative feedback, users may have adopted the new rules, so reverting it would just trigger another ticket from someone who liked the rules as they are now.

**Comment by vLKp** [comment]
No further response from original reporter.  As noted in my prior comment, I am reluctant to revert a years-old change without a strong argument, and I am not convinced by the 2020-05-08 post that reverting would be more useful than doing nothing.  This issue would be a good place to discuss the merits of one system versus the other, but there is no reason to leave it open if there is no discussion.  The issue will _not_ be locked, so future commenters could still speak up to discuss the options.  If substantial discussion appears, the issue will be reopened.  Until then, closing.
