### ISSUE TITLE
Runtime bug: Shield state gets pushed in afterburner state in multiplayer (full screen)

### ISSUE THREAD

**Issue by snytek** [dxx-rebirth/dxx-rebirth#521]
### Environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200630-win.zip

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [X] Microsoft Windows 10

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

No special mission is needed to reproduce the issue.

### Description

The shield and afterburner info gets scrambled/overlapped in a multiplayer level with more than 3 players in full screen mode.

It seems that the resolution has no impact on this.

Image showing reduced Cockpit (all ok):
http://clan-ggc.bplaced.net/bug/ReducedCockpit.jpg

Image showing issue in lower left corner:
http://clan-ggc.bplaced.net/bug/FullScreen.jpg

#### Regression status

Unknown.

### Steps to Reproduce

1. Player starts a muliplayer game (e.g. Anarchy).
1. Player picks up an afterburner.
1. The player presses F3 until he gets to the full screen mode. The shield, energy and afterburner info resides now in the lower left corner. As long as there are only 3 players in the game, there is no problem as there is enough space for the palyer names below the ship info.
1. If player 4 joins the new player name will be added to the list pushing the Energy and Shield info line one line up. The afterburner info however is not, resulting in 2 texts overlapping.

* Engines affected:
  * [ ] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [X] Multiplayer competitive
    * [X] Anarchy
    * [X] Team Anarchy
    * [ ] Robo-Anarchy
    * [X] Capture the Flag
    * [X] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
Based on visual inspection of the code (but without actually playing with enough people to test it), I believe your report is correct:

Shields are shown in [`hud_show_shield`](https://github.com/dxx-rebirth/dxx-rebirth/blob/4f26a205ead1ccf7bbf1b777a50379bc9f5243c8/similar/main/gauges.cpp#L1793):
https://github.com/dxx-rebirth/dxx-rebirth/blob/4f26a205ead1ccf7bbf1b777a50379bc9f5243c8/similar/main/gauges.cpp#L1793

In multiplayer, the vertical displacement is `6` for `N_players <= 3`, and `7` otherwise (`6` + `true` = `6` + `1` = `7`).
https://github.com/dxx-rebirth/dxx-rebirth/blob/4f26a205ead1ccf7bbf1b777a50379bc9f5243c8/similar/main/gauges.cpp#L1802

----

Afterburner charge is shown in [`hud_show_afterburner`](https://github.com/dxx-rebirth/dxx-rebirth/blob/4f26a205ead1ccf7bbf1b777a50379bc9f5243c8/similar/main/gauges.cpp#L1204):
https://github.com/dxx-rebirth/dxx-rebirth/blob/4f26a205ead1ccf7bbf1b777a50379bc9f5243c8/similar/main/gauges.cpp#L1204

In multiplayer, the vertical displacement is a fixed `7`, regardless of number of players:
https://github.com/dxx-rebirth/dxx-rebirth/blob/4f26a205ead1ccf7bbf1b777a50379bc9f5243c8/similar/main/gauges.cpp#L1214

----

The fix is probably just to move the afterburner line, either adding a similar player count test or moving it always.

**Comment by snytek** [comment]
Great, that sounds like a plan :-).
Adding the same logic to move the line similar to the other lines sounds like the better (more consistent) solution.

**Comment by vLKp** [comment]
The above commit should resolve this.  Please reopen if you still see problems.
