### ISSUE TITLE
Possible to block the Windows Key?

### ISSUE THREAD

**Issue by snytek** [dxx-rebirth/dxx-rebirth#523]
Would it be possible to block the windows key (which is located between Ctrl and Alt) so I won't be thrown back to windows if I accedentily press it?

Currently I'm using an AutoHotkey script, which I launch when D2X is started, to block this key...

**Comment by vLKp** [comment]
If AutoHotkey can block it, then it probably can be blocked by the game.  However, I do not think that it is appropriate for the game to decide which hotkeys are enabled.  Further, I think that blocking it within the game is the wrong solution, because then you must patch every game to do this.  Instead, you should configure your window manager not to interrupt the game when this key is pressed.
