### ISSUE TITLE
Build failure: opengl-es on arm linux -> cannot find -lGLES_CM

### ISSUE THREAD

**Issue by clort81** [dxx-rebirth/dxx-rebirth#525]
Can't build! :(
```
/usr/bin/ld: cannot find -lGLES_CM
```
### Environment
dxx-rebirth master, 2020-07-20
git rev-parse HEAD
bb6bf76b0f0a5dafc5335dc0e504b0905a371632

#### Operating System Environment
linux: devuan beowulf 
armhf
arm (32-bit)

#### Regression status
not found

### Steps to Reproduce
 scons d2x=1 opengles=yes  screenshot=legacy verbosebuild=1
or
 scons d1x=1 opengles=yes  screenshot=legacy verbosebuild=1

verbose output: http://0x0.st/ivdc.txt

It looks like GLES_CM is some compatibility module or interface tween opengl and opengl-es?  It is not in debian / devuan repo.  Removing -lGLES_CM yields many undefined references' to standard opengl functions.

My device (droid4) does not have native opengl support, only opengl-es 1 and 2.

Cheers!

**Comment by clort81** [comment]
I found that  -lGLESv1_CM works to link final stage.

**Comment by vLKp** [comment]
`GLES_CM` is picked as the default OpenGLES library, except on the Raspberry Pi, which uses `brcmGLESv2`.  You can override the default by setting `opengles_lib=GLESv1_CM` as a build option.  I am not familiar with the affected platform, so I cannot say why it uses a different filename, or whether the current default is still a good choice on most systems.

Since you found a solution, what do you want to do with this ticket?  If you can provide specific guidance on how the build system should recognize your Droid as different from the Raspberry Pi or from other default GLES systems, I can add a configure test to pick the right library.  I could write a test that tries each of the three filenames, but since I have none of the target systems, I don't know what C functions I should test for in each of the relevant libraries.  Could you provide examples of specific functions that are used by Rebirth and present in `GLESv1_CM`?

----

Please do not use pastebin services, particularly non-https ones, for build logs.  Attach them to the ticket or, if they are short, write them inline inside a multiline code block (\```).

**Comment by vLKp** [comment]
No response from original poster.  Poster found a solution, albeit suboptimal.  I lack the environment to develop a better solution, and original poster did not provide any guidance on how to handle these environments.  Closing.

Please reopen if a specific test for this environment is available.
