### ISSUE TITLE
Windows precompiled packaged from August 28th is still MULTI_PROTO_VERSION = 10, built from April source code

### ISSUE THREAD

**Issue by MasonP57** [dxx-rebirth/dxx-rebirth#537]
I downloaded the package off the Rebirth website today (August 29th) to play with a guy who's self-compiled the linux code. I'm using Windows.

I replaced all the files in my pre-existing D1 Rebirth directory and it failed to join, citing Game Protocol mismatch. Mine says 10, his says 12.

As a control, I made a new directory entirely and used the code from the Rebirth download, same issue.

I have a clone of the repo on my local machine and I double checked the code, it shows MULTI_PROTO_VERSION is cast to be 12.

I think maybe the windows version just didn't get updated?

(Sorry if I didn't follow your bug report format, I didn't think most of the details were important but if they are let me know and I'll do the whole thing).

Thanks for all the help and hard work. :)

**Comment by MasonP57** [comment]
I managed to compile the source code from my cloned github repo and when I went to run the new executable is failed due to missing SDL_image.dll.

So if I'm understanding how these things work correctly, the new Windows package needs to include that file as well.

**Comment by vLKp** [comment]
> I think maybe the windows version just didn't get updated?

That appears to be the case.  This looks like it was built from a checkout of f0a47c358ba6f084c07562b946ff2f98aa363774, which occurred in April.  That would also explain why it was built with C++14, not C++17 as I would have expected.  C++17 is the minimum as of ea0f4eb02a7353a591a48261d667916e4eb8f172.

> (Sorry if I didn't follow your bug report format, I didn't think most of the details were important but if they are let me know and I'll do the whole thing).

For this case, it's fine.  It would have been slightly better if you had directly linked to the download with which you had an issue, but I understood from context that you meant <https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200828-win.zip>.  You are correct that most of the other data is irrelevant, since you already did the work of tracing the problem to the unwanted protocol version number.

> So if I'm understanding how these things work correctly, the new Windows package needs to include that file as well.

Correct.  This is a default-enabled dependency as of 3114874713fb8f9fa8ca1ae966a7a5825950437a.  It can be disabled, but then you cannot load PCX files.  Most people want PCX files to load, so I discourage disabling it.

----

The prebuilt Windows packages are provided by someone else, usually either @Mako88 or @zicodxx.  One of them would be better positioned to comment on why the build is from an old version, and to replace it with a build from more current code.

**Comment by snytek** [comment]
If I'm not mistaken, the september release for windows is still wrong.
Is this an automatic build/release process?

**Comment by vLKp** [comment]
Based on the strings in the binary, I concur with you that it is wrong.  It appears to be another build of f0a47c358ba6f084c07562b946ff2f98aa363774, the same commit that prompted this ticket.  I also see that there is an uncommitted local small change to `similar/main/laser.cpp` in the working copy from which this was built.

I do not know how @zicodxx builds this.  If I had to guess, I would say that the uncommitted local change is preventing use of `git checkout` to advance to current HEAD, and the build process ignores that error and builds anyway.

**Comment by vLKp** [comment]
Based on comments in #459, it appears that the monthly snapshots are now updated as intended.
