### ISSUE TITLE
Runtime bug: The "outrunning the fireball" animation doesn't play in Descent 1

### ISSUE THREAD

**Issue by Donkyhotay** [dxx-rebirth/dxx-rebirth#544]
### Environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20200930-src.tar.xz

#### Operating System Environment

Linux - Lubuntu 20.10

#### CPU environment

AMD Ryzen 5 2600

#### Game environment

d1x-rebirth - descent.hog = 6856701 bytes

### Description

When exiting the mine in Descent 1 the "outrun the fireball" animation doesn't play. The level just immediately ends and takes me to the score summary screen. The game does continue with the next level and I do see mission briefings, the game simply skips "outrunning the fireball". It also doesn't play the "exiting the mine" music though I think that is because the animation doesn't play.

#### Regression status

I upgraded to commit 1fc8663 from commit 0b141ea, both of which I downloaded from the www.dxx-rebirth.com download page. Both versions I compiled and played on this same system however I had no problems with the "outrunning the fireball" animation playing when ending a level on commit 0b141ea.

### Steps to Reproduce

Start game in d1x-rebirth, complete any level by exiting the mine in single player mode, get taken straight to the score summary screen without seeing the "outrunning the fireball" animation as expected.

* Engines affected:
  * [X] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

Only tested with single player, did not test with multiplayer.

**Comment by Donkyhotay** [comment]
I have done a little bit more testing and confirmed that if I compile 5b56ed1 the "outrunning the fireball" animation plays normally but if I compile 96d108b which is the very next commit then the animation doesn't play. Naturally I am assuming the changes made to gauges.cpp in that commit are the source of the problem. I will try compiling with the most recent code except for that specific file reverted and see what happens.

**Comment by Donkyhotay** [comment]
So even though git shows the last change to gauges.cpp was 96d108b the game refuses to compile if I simply use the old version of gauges.cpp. I suspect I'm missing something as while I know a little about git and programming I'm not much of a coder. Regardless, I'm still pretty certain something related to that merge is the source of this bug.

**Comment by vLKp** [comment]
Thank you for the report, and the attempt to bisect it.  Unfortunately, your attempt was disrupted by a common problem when bisecting around merges.  You identified the merge commit as bad, because one of the parents of the merge was good, and the other parent was bad - but the merge itself is not bad, and the bad parent is only bad because it descends from a bad commit.  The actual bad commit is de4efc4f46512e50734fd9e0f91f96a8feb249e7, where an index and an array value were incorrectly swapped, so the array index was compared to a constant that was supposed to match one of the array values.  This caused the comparison to give the wrong result, which in turn confused the endlevel logic into not finding the end of the tunnel.  As a fallback, if the tunnel does not have a proper end (the special terminating next-segment field `-2`), then the animation is skipped.

Please sync to the above commit and retest.  I was able to reproduce the problem you described before that commit, and not after it.

**Comment by Donkyhotay** [comment]
I downloaded and compiled both de4efc4 and 2b8522f, the commit right before it. I confirm that de4efc4 does not play the animation while 2b8522f does. I also downloaded and compiled c482d01, currently the most recent commit, and confirmed that the the "outrunning the fireball" animation works normally again. Thank you very much for the quick response on this. 

On a side note, while I'm obviously not the best of coders nor very familiar with git, I have no problems using SCONS to compile code for testing on Linux. If you need help confirming a bug, or lack thereof, in a specific commit of dxx-rebirth feel free to message me. Be aware I don't have a windows system to either compile on nor test with.

**Comment by vLKp** [comment]
I appreciate the offer.  I use Linux and not Windows, so Linux testing is relatively straightforward for me.  Even so, there are many library and tool combinations, so having more people testing and reporting is always good.
