### ISSUE TITLE
XInput support so both triggers can be used simultaneously on XBox controllers?

### ISSUE THREAD

**Issue by aybe** [dxx-rebirth/dxx-rebirth#556]
As you may know, triggers in Xbox controllers for Windows share an axis in their DirectInput driver for so said compatibility.

Therefore, you can only press one or the other, unless you read the joystick with XInput API.

https://docs.microsoft.com/en-us/windows/win32/xinput/xinput-game-controller-apis-portal

Any chance we get XInput support so triggers are each known as individual axis?

**Comment by vLKp** [comment]
Rebirth gets joystick input via SDL, so whether this works depends on whether SDL can use XInput to read your joystick.  Rebirth does not directly use XInput or DirectInput.  I see on the SDL wiki that there is also some direct support for game controllers, but Rebirth does not use that functionality.  Game controller support is not present in SDL1.

To your question: if SDL supports this, then yes, you can get it easily.  Otherwise, it would require a patch to Rebirth, either to bypass SDL or to use the SDL game controller support (if that support can do what you want).  I have no compatible game controllers, and so no way to test any work on this.

**Comment by aybe** [comment]
Searching for `SDL XInput` brings this: https://wiki.libsdl.org/SDL_HINT_XINPUT_ENABLED.

Looks nice and easy but only for SDL2 actually.

**Comment by vLKp** [comment]
As I read that page, SDL XInput support is enabled by default, and that hint exists to disable it for cases where the program needs support for additional gamepads.  Thus, when using SDL2, the controller should work without any special action from Rebirth.  Is that not your experience?

**Comment by aybe** [comment]
The `dxx-rebirth_20201029-win` I tried is like this:

<img width="597" alt="CFF_Explorer_2020-11-30_06-30-28" src="https://user-images.githubusercontent.com/1537591/100572385-9db15700-32d5-11eb-91de-a2fa0cb2dd6b.png">

- SDL.DLL -> SDL1
- zero imports from any XInput*.dll

And when your triggers have a shared axis on XBox controllers, it's absolutely using DirectInput.

Don't forget that https://wiki.libsdl.org/SDL_HINT_XINPUT_ENABLED is only for SDL2.

**Comment by vLKp** [comment]
I don't know if SDL1 can do what you want.  Most documentation seems to be about SDL2 now.  I expect that SDL1 may use only DirectInput, in which case a Rebirth built to use SDL1 will also use DirectInput, and will not do what you want.

@aybe wrote:

> SDL.DLL -> SDL1

Right, so the hint you found will not work.  That is why I wrote above "when using SDL2, ...".  What happens if you try your controller with a Rebirth built to use SDL2?

**Comment by aybe** [comment]
We're talking about the same thing:
- I know that SDL1 doesn't support it as it predates it
- I would like to try a SDL2 build but there isn't any to download from https://www.dxx-rebirth.com/download-dxx-rebirth/

**Comment by vLKp** [comment]
I do not provide prebuilt binaries, for any platform.  I have not done this to date.  I have no plans to start doing so.  Other people are welcome to perform this service, and @zicodxx graciously provides snapshot builds for users who choose not to build the code themselves.  If the builds he provides do not meet your requirements, your best bet is to build the code yourself, configured to the libraries and requirements you want.

**Comment by aybe** [comment]
Okay, I thought this repository was affiliate with the website, alright.

**Comment by vLKp** [comment]
This repository prominently links to that website.  Likewise, the website's news links back to this issue tracker as the place to report problems.

So - what happens if you try your controller with a Rebirth built to use SDL2?

**Comment by aybe** [comment]
I don't have any SDL2 build at hand nor could build one under Windows but I see no reason why a SDL2 build wouldn't fix the bug.

**Comment by vLKp** [comment]
Based on the comments here, and my reading of the SDL documentation:

- This cannot be changed in Rebirth, because Rebirth relies on SDL to get the joystick input data. 
- This will not work in SDL1.
- This probably will work in SDL2.
- The current behavior is not a Rebirth bug.  It is a limitation of SDL1.
- Nobody in a position to test it for SDL2 has done so.

Since Rebirth supports SDL2 as-is, I think there is nothing more to do here.  Closing.
