### ISSUE TITLE
Lack of MIDI output options, defaults to GS Wavetable Synth

### ISSUE THREAD

**Issue by DukeSkinny** [dxx-rebirth/dxx-rebirth#574]
I'd like to run DXX-Rebirth with the music passing through my Sound Canvas VA MIDI synth, which I have configured with Loopmidi. Being able to choose my own MIDI output the way GZDoom allows me to would be the final brushstroke to this source port in my case. I haven't found any way to accomplish this, even using methods such as creating ports in Loopmidi named "Microsoft GS Wavetable Synth".

I know there's the sound pack, but I really enjoy the natural audio decay & I assume it isn't a particularly non-trivial task (in which case I totally understand).

Thank you for your consideration!

**Comment by AlumiuN** [comment]
In lieu of an in-game solution, this might help - https://coolsoft.altervista.org/en/midimapper

**Comment by DukeSkinny** [comment]
You absolute life-saver! That did the trick!
Still, even if I'm happy with this I think it's a good idea to provide a simple solution to everyone. Playing around with different synth sounds can be very enjoyable!

**Comment by vLKp** [comment]
The game does not have any references to the string `Wavetable`, so if it is defaulting to that MIDI device, then the default is either by index or is handled outside the game's code, such as in a supporting library that the game uses.  I normally do not run music through the game, and have not worked on the game's MIDI code in detail.  If a patch is proposed, I will review it.  If you can point me to where the game needs to request a non-default MIDI device from the system, I can try to write a patch for it.  Otherwise, this feature request will likely stay in the backlog for a while.

**Comment by vLKp** [comment]
No response from original reporter.  No indication of where to change the code or what system functionality would be needed.  Closing.  If you want to resume work on this, post back and reopen.
