### ISSUE TITLE
Runtime bug: Ping meter only works for host.

### ISSUE THREAD

**Issue by Birdseye6dof** [dxx-rebirth/dxx-rebirth#575]
Environment

Affects all .6XX versions

Operating System Environment
 Microsoft Windows 10 (me and others in the games)

 x86_64 (64-bit Intel/AMD)

Game environment:
Any Multiplayer game

Description

Ping meter works for the host only. The host gets the correct pings, but all other players joining see the hosts's set of pings, rather than their own pings.

Regression status
I have not seen this problem in other versions of Descent 1.

Steps to Reproduce
Join any game as a "guest" with the ping meter enabled

Engines affected:

[ x] D1X-Rebirth
[ x ] D2X-Rebirth

Game modes affected and tested:

[x ] Multiplayer competitive
[x ] Anarchy
Probably the others but I have not tested. 

Players affected by issue:

[ x] Game guests

**Comment by vLKp** [comment]
The ping mechanism collects the round-trip-time between the host and each guest, then on the next ping, advises all guests of the collected RTTs of all guests, relative to the host.  This produces the result that if RTT(Host, Alice)=1, and RTT(Host, Bob)=20, Bob will see RTT(Alice)=1 in the display, just as the host sees it.  There is no direct ping measurement between Alice and Bob; the best that could be done would be for Bob to see a reported RTT(Alice) as RTT(Host,Alice)+RTT(Host,Bob), reflecting that getting a ping from Bob to Alice and back requires passing it through the host.  As far as I know, Rebirth has worked like this at least since the introduction of UDP-based multiplayer.  IPX may have worked differently.

I am closing this issue because:
- The reported behavior matches what the code does
- The code seems to be written this way deliberately; likely as a decision made based on how regular updates are distributed among the players
- The code has been this way for a very long time, and changing it now may confuse more players than it helps
- The only fix I see (adding the guest's own ping time to all non-self lines) does not seem useful to me.  Players who understand the current rules can readily enough do that themselves, and reading ping times is not likely to be done under time pressure, so players can take the time to do these sums, even if that means breaking out a calculator and typing in the values.

If you disagree, please describe what you think should happen instead, and why you think that would be better than the current logic.

**Comment by AlumiuN** [comment]
I missed this when it was initially posted, but I should mention that this is what every game I've ever seen does. It's not terribly useful to have the ping from one client to another when the clients are not communicating with each other, only the server.

**Comment by Birdseye6dof** [comment]
> I missed this when it was initially posted, but I should mention that this is what every game I've ever seen does. It's not terribly useful to have the ping from one client to another when the clients are not communicating with each other, only the server.



> The ping mechanism collects the round-trip-time between the host and each guest, then on the next ping, advises all guests of the collected RTTs of all guests, relative to the host. This produces the result that if RTT(Host, Alice)=1, and RTT(Host, Bob)=20, Bob will see RTT(Alice)=1 in the display, just as the host sees it. There is no direct ping measurement between Alice and Bob; the best that could be done would be for Bob to see a reported RTT(Alice) as RTT(Host,Alice)+RTT(Host,Bob), reflecting that getting a ping from Bob to Alice and back requires passing it through the host. As far as I know, Rebirth has worked like this at least since the introduction of UDP-based multiplayer. IPX may have worked differently.
> 
> I am closing this issue because:
> 
> * The reported behavior matches what the code does
> * The code seems to be written this way deliberately; likely as a decision made based on how regular updates are distributed among the players
> * The code has been this way for a very long time, and changing it now may confuse more players than it helps
> * The only fix I see (adding the guest's own ping time to all non-self lines) does not seem useful to me.  Players who understand the current rules can readily enough do that themselves, and reading ping times is not likely to be done under time pressure, so players can take the time to do these sums, even if that means breaking out a calculator and typing in the values.
> 
> If you disagree, please describe what you think should happen instead, and why you think that would be better than the current logic.


Alright, good to know that there is no actual P2P networking. This means that rebirth is suitable for 1v1 but nothing else unless everyone lives very close. Original Descent is a Peer to Peer game. This plays a lot worse networking wise without true peer to peer. It was never client server in any regard, this was all invented later by Rebirth. We have had great 1v1s and some smaller games, but most games with more players play absolutely terribly.

We have some coders in our group so maybe we'll end up working on our own version that has P2P networking as this will not be a long term viable option for our group. Retro gets too much about the actual gameplay wrong, but it has P2P networking. Rebirth gets the gameplay right but doesn't have P2P.

**Comment by vLKp** [comment]
> This means that rebirth is suitable for 1v1 but nothing else unless everyone lives very close.

Having played quite successfully in games where this was not true, I disagree with this assessment.

> It was never client server in any regard, this was all invented later by Rebirth.

It was also originally not enabled for UDP/IP play.  That too was invented by Rebirth.

> We have some coders in our group so maybe we'll end up working on our own version that has P2P networking as this will not be a long term viable option for our group.

If you get it working, please consider posting it for inclusion.  Back before the licenses diverged, I reviewed the Retro code with an eye toward trying to pick up their peer-to-peer support, but the git history for Retro was such a mess that I gave up.

I have thought intermittently over the years about trying to overhaul the Rebirth networking code, but I have always had higher priority projects to pursue, and the networking code has no serious bugs that I am aware of, so an overhaul would likely, at least in the short term, risk more problems than it would fix.
