### ISSUE TITLE
Crash on last level of Descent 1

### ISSUE THREAD

**Issue by Q3BFG10K** [dxx-rebirth/dxx-rebirth#576]
Win64-Oct20, playing Descent 1 with D2X build: https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20210126-win.zip

Flew through the red door, started fighting, and it randomly crashed. I couldn't replicate it.

Save & log files attached in zip.

Thank you.

![Crash](https://user-images.githubusercontent.com/40132921/108620107-980b7d80-748e-11eb-95a7-b95fe3603f11.png)

[Save & Log.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/6017418/Save.Log.zip)

**Comment by vLKp** [comment]
`segment_none` (the invalid non-segment) was used as an array index.  This is probably the `vmsegptridx` from:

https://github.com/dxx-rebirth/dxx-rebirth/blob/0d70c3831c31700ca1ad6edb73f6d3bce1d58a84/similar/main/fireball.cpp#L1271

If so, an object was exploded while not in the mine.  Without the ability to replicate this, or a dump file, I will not be able to determine how an object ended up outside the mine.  If I had to guess, a generated robot or powerup was too close to a wall and somehow was placed outside, but I would have expected that to be cleaned up differently.

I could add a guard against objects in impossible segments, but since it should never happen, I am reluctant to mask the bug with a test here.  That might just move the crash somewhere else.

@zicodxx: could you enable Windows minidump support in future builds?

**Comment by zicodxx** [comment]
@vLKp As soon as I get my build environment running again, I can certainly look into that. :)

**Comment by vLKp** [comment]
Yes, it defaults on.  I believe both you and Mako88 had added a local configuration option to switch it off, because at one time, you were both building with Mingw32 headers that were too old to provide the functionality required by the minidump logic.  Hopefully, your distribution package maintainers have since updated you to a package version that provides the needed declarations.

**Comment by zicodxx** [comment]
Okay so I believe my builds should have this option included for a while now. I'll also make double sure the build I am just cooking up will have it. :)

**Comment by vLKp** [comment]
@Q3BFG10K: were you ever able to replicate this?  If you can find a way for me to reproduce the problem, I can examine it in detail.  Since your save does not exhibit the problem, there is not much I can do without those steps.

**Comment by vLKp** [comment]
No response from original reporter.  Not reproducible, even by original reporter.  No steps to reproduce.  There is nothing I can do here.  Closing.  Please reopen if this is reproducible.

**Comment by Diamond-Wolf** [comment]
I have seen this issue on occasion, always when an item drops from a destroyed robot in a multiplayer game. The odds increase slightly the more items a robot drops, though this is inconsistent, and may even be irrelevant. I am unsure if non-item drops can trigger this. This crash has existed for a while. Usually the crash is only on one player, but rarely both players can crash the game; I have not played with more than two players in a long time, and I have never encountered this in singleplayer. 

All that said, I have two (speculative) theories:
 - Debris is escaping the mine (I know I talked a lot about item drops, but this was a possibility that occurred to me at one point)
 - A memory overwrite is occurring

**Comment by vLKp** [comment]
While a memory overwrite is always a risk in C++, I have made many changes aimed to prevent such bugs from occurring, and to force invalid accesses to abort at the site of the access, before memory corruption can occur.

The crash reported by the original poster is in fact an example of that.  An object was placed in an invalid location, and the first attempt to use it in the checked data structures aborted because there was no way to resolve its invalid location to a valid data structure.  The question here is how that object ended up in an invalid location at all.  That would be most readily determined by stepping through a reproduction scenario in a debugger.  However, the problem is not reproducible with the information available.
