### ISSUE TITLE
Black surfaces in Descent 1

### ISSUE THREAD

**Issue by Q3BFG10K** [dxx-rebirth/dxx-rebirth#577]
Win64-Oct20, playing Descent 1 with D2X build: https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20210126-win.zip

![Black](https://user-images.githubusercontent.com/40132921/108620250-c76eba00-748f-11eb-8387-2ae3a428c8b7.png)

Save file attached, just load it to see the problem immediately. 

Move/mouselook the ship around and you'll see the black surfaces randomly pop in and out.

Thank you.

[Save.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/6017428/Save.zip)

**Comment by vLKp** [comment]
Confirmed.  This renders correctly in D1X, but fails in D2X.  Mission: Descent: First Strike; Level: 26; Segment: 198.

**Comment by vLKp** [comment]
This seems to have been broken for a long time.  I made it back to January 2020 and have not found a commit where this works correctly in D2X.

**Comment by AlumiuN** [comment]
Possible cause (although I haven't tracked the relevant bit of code down) - the sides that exhibit this problem don't have the wall texture that displays correctly around them (rock223), but the secret door texture instead (door30), and it looks like D2 is displaying this as the last frame of the animation, rather than the first frame.

**Comment by vLKp** [comment]
@AlumiuN, thank you for investigating this.  I wonder if this also explains a similar graphical anomaly I saw in custom D1 levels played on the D2 engine, where some doors would look completely wrong until opened the first time.

**Comment by AlumiuN** [comment]
Some custom levels had that happen in vanilla D1 anyway; usually it was the more rough levels, and I think it was because they added a wall with a certain door on it but later changed the wall texture to something else without changing the door (I've seen some levels use it to hide a trigger-activated door with a robot behind it as a trap in an area where the texture used had no corresponding secret door).

**Comment by vLKp** [comment]
The black areas are because the engine computed you would not see those areas, and declined to draw them.  If the near texture had been the intended one, it would have prevented you seeing those areas, and the undrawn black segments would have been fine.  Since the near texture was wrong, you could see through it to the undrawn area.

Based on the above analysis by @AlumiuN, I did a spot fix for the specific bad texture.  I would not be surprised to find there are other textures that are mishandled by this mapping feature, but I have no ready test cases for those, and am not inclined to try to create such tests at this time.

Please reopen if this level still looks wrong for you in the latest build.
