### ISSUE TITLE
Multiplayer NAT Forwarding.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [dxx-rebirth/dxx-rebirth#579]
I am trying to get a NAT Forwarding issue resolved for multiplayer, without the use of a VPN. I  have forwarded port 42424/udp and TCP, and still people outside my NAT cannot connect without a VPN. All players are behind their own NAT. I'd like assistance with this issue.

**Comment by vLKp** [comment]
Only UDP is needed.  TCP is not used.

To play, guests must send an initial request to the host's game port.  The host must respond to the guest's data port.  All intervening firewalls must permit the traffic to pass.  Check:

- When a guest tries to connect to you, does their datagram reach your NAT device?
- Does your NAT device pass it to your computer, and on the correct port?
- Does your computer's firewall (if any) allow Rebirth to receive it?
- Does Rebirth respond?  It should, if the request is well formed and reached the Rebirth process.
- Does your NAT device permit the response to go out to the Internet, and rewrite the source address on the way out?
- Does the guest's NAT device receive that response?
- Does the guest's NAT device recognize this as associated with recent activity, and forward it back to the guest's computer?
- Does the guest's computer permit the guest's Rebirth to receive the response?

**Comment by Zombie-Ryushu** [comment]
Can the host's game port, and the guest's data port share the same port number?

**Comment by vLKp** [comment]
Rebirth supports that, and in the default configuration, that will be done.  When you wrote

> All players are behind their own NAT.

What did you mean?  Specifically, do you have N guests (N >= 2), each using a separate ISP, and all trying to join your game, or do you have N guests all sharing the same IP address (because they live in the same house/apartment/dorm)?  The latter can work, but requires a bit more competence from the NAT device.  Some consumer NAT devices may not be that clever.  Knowing which network topology is in effect will guide further answers.

**Comment by Zombie-Ryushu** [comment]
Each player is in their own house, and therefore behind at least one of their own NAT, at least with regards to IPv4. (Double NAT scenarios I'm not sure of.)
My Host NAT is powered using DD-WRT but I am not sure about them. 
I have managed to get D2X-XL to work though the NAT, but not DXX-Rebirth. 
I'm under the impression only one layer of NAT exists for each residential player.

**Comment by vLKp** [comment]
That should be fine.  Please try to answer as many as possible of the questions I posed in my first response.  The answers should lead us to which device is blocking the traffic.

**Comment by Zombie-Ryushu** [comment]
This issue has been resolved. The other person was using D2X-Rebirth with D1X rebirth Assets. 
The reason I bring it up is, while that works in D2X-XL to allow D1 levels to be played in D2X-XL, in DXX Rebirth it causes strange corruption issues.
D1X-Rebirth will enter a strangely glitched state if D2 Assets are present in the D1 folder. Menus will be corrupted.

**Comment by vLKp** [comment]
Running D2X with D1X assets is a (mostly) supported setup.  There are some known glitches, but it's quite usable.  I have completed the entire Descent: First Strike campaign using the D2X engine.  However, for multiplayer, everyone must run the same engine.  If one person is using the D2X engine in Descent1-compatibility mode, everyone must use the D2X engine.  You cannot mix engines within a multiplayer game, even if everyone has the same level assets.

Running D1X with D2X assets is an unsupported setup, and I have never tested what it would do.  I suppose it would be nice if the engine could gracefully reject this configuration, but I don't know how practical that would be.

As I interpret the first line of your most recent post, this was a problem due to mismatched engines refusing to talk to each other.  It would be nice if that would error out more gracefully.  However, given the level of manual coordination required to set up multiplayer games, I expect it is rare that people would encounter this situation.

Per your statement "This issue has been resolved.", closing.
