### ISSUE TITLE
Menu needs scrollingbars or some other indicator and some united mouse settings..

### ISSUE THREAD

**Issue by ruthan** [dxx-rebirth/dxx-rebirth#585]
Hello,
i tried to play it and setup mouse right.. i dunno why default mouselook speed is still.. slug one and useless as in original game, that is something what should works out of box, but ok.

  Main problem is there are some settings screens which have more informantion, that is one screen and there is zero inidication that there are other settings at the bottom.. so i took me lots of time to find proper mouse look mode enabler. BTW even its name sucks.. uncapped turning in.. its very strange name for it.. there should be something in mouse settings..

**Comment by vLKp** [comment]
There is an indicator.  When the menu can be scrolled down, Descent 1 will display a `+` in the bottom left corner of the menu; Descent 2 will display a down-pointing arrow in the bottom left corner of the menu.  When the menu can be scrolled up, Descent 1 will display a `+` in the top left corner of the menu; Descent will display an up-pointing arrow in the top left corner of the menu.  Although I cannot find any screenshots of this behavior in the Descent 2 manual, inspection of the pre-Rebirth Descent source suggests that this existed back then.  This is not a change from Rebirth.

Rebirth tries to preserve the feel of the original game, absent a compelling reason not to.  If you have a specific suggestion for how to change the default values, I will consider changing them.

Its name is exactly what it does.  With that option disabled, as default, turn speed is capped, limiting how fast the ship can be spun per frame.  When the option is enabled, turn speed is uncapped, allowing the ship to turn wildly in reaction to fast input device movement.  Hence, `Uncapped turning`.  It is not in mouse options because it does not apply solely to the mouse.  The cap, when enabled, is applied to the sum of keyboard+mouse+joystick movement.  Everyone, not just mouse users, is limited by the cap.  Hence, the option to disable that is not in the mouse menu, because people playing a keyboard+joystick build may also be interested.

I am closing this on the basis that:
- The menus have the requested indicator, at least as far back as February 2006.
- Uncapped turning is properly not under mouse settings, since it impacts non-mouse inputs.
- The issue as filed does not request any other changes with sufficient specificity that I can consider them.

**Comment by ruthan** [comment]
Hmm, that strange plus symbol is not really intuitive.. it looks like something similar to checkbox or other element. Even some up and down arrow would be much better.

**Comment by vLKp** [comment]
As I said, in Descent 2, it is an up/down arrow.  Although I have not checked the font to confirm this, I expect that Descent 1 uses `+` because there is no special character to draw an arrow in the Descent 1 font.

When clicked, the plus/arrow will navigate in the appropriate direction.
