### ISSUE TITLE
Possibility to disable music when is game minimalized, its annoying..

### ISSUE THREAD

**Issue by ruthan** [dxx-rebirth/dxx-rebirth#587]
Im not big fan you in-build 80,90s beeping music.. and im used to do lots of things besides of gaming, its possible to add possiblity to stop music when is game minimalized, its normal for most of games and its better way.

  Otherwise when i use to add Gog Descent soundtracks, are proper tracks played to proper levels, as in original, or its just random?

**Comment by vLKp** [comment]
I too am not a fan of in-game music, which is why I play without it.  Descent had in-game music support, so Rebirth has it too.  Rebirth even has it extended, for those people who do enjoy in-game music.  (Personally, I want to hear weapon fire that is important, and I don't want to miss part of a song because the weapon fire drowned it out.)

Yes, adding the ability to stop the music when the game is minimized is possible.  The game already pauses all digi sounds when the main window is deactivated in a single player game.

https://github.com/dxx-rebirth/dxx-rebirth/blob/809af2987594977016e06f867524dcd3345c3762/similar/main/game.cpp#L1726-L1727

@ruthan wrote:

> Otherwise when i use to add Gog Descent soundtracks, are proper tracks played to proper levels, as in original, or its just random?

Please describe in detail what you did.  I believe there is at least one way to make tracks play in original order, but Rebirth also offers random ordering of music, depending on what you set.  However, as I never use in-game music, I have limited familiarity with this area.

**Comment by vLKp** [comment]
No response from original reporter.  I think there is nothing more I can do here at this time, so closing.

@ruthan: if you would like to discuss this further, please respond and reopen the issue.
