### ISSUE TITLE
(Win10-64) movies no longer play

### ISSUE THREAD

**Issue by Q3BFG10K** [dxx-rebirth/dxx-rebirth#599]
Hi there, I have no movies or robot animations.

I'm using commit cae9c5f date 2021/07/21 from https://www.dxx-rebirth.com/download-archive-dxx-rebirth/
Checking the log file shows:

> 16:36:41.517 PHYSFS: insert canonical directory "D:\Descent 2\data\intro-h.mvl" to search path from relative name "intro-h.mvl"
16:36:41.517 PHYSFS: insert canonical directory "D:\Descent 2\data\other-h.mvl" to search path from relative name "other-h.mvl"
16:36:41.517 PHYSFS: insert canonical directory "D:\Descent 2\data\robots-h.mvl" to search path from relative name "robots-h.mvl"
16:36:41.518 Failed to open movie <pre_i.mve>: (null)
16:36:41.518 Failed to open movie <intro.mve>: (null)
16:36:41.518 Failed to open movie <titles.mve>: (null)

Previous commit b918d33 date 2021/06/23 worked, though movies had a lot of black area as they were pushed into the top-right corner and weren't being displayed properly.

Previous commit 809af29 date 2021/04/22 had no issues with anything.

**Comment by vLKp** [comment]
Robot animations (which are a type of movie in Descent 2) broke in [Unload robot movies on exit](/dxx-rebirth/dxx-rebirth/commit/d0d7545ec140fd4ce9dbff9acd436b85c26a610c) because I failed to keep the object alive long enough.  The above commit fixes that for me.  Please reopen if this does not fix it for you.

I don't see the issue with movies displaced toward the corner, in any of the commits I tested for this.  If you still see this problem with the above fix in effect, please file a new issue about it.
