### ISSUE TITLE
HUD rendering bug at 320x200 on software renderer. (tested on d2x-rebirth)

### ISSUE THREAD

**Issue by JohnnyonFlame** [dxx-rebirth/dxx-rebirth#6]
Here are a couple of screenshots of said issues.

![6rdqqhu](https://cloud.githubusercontent.com/assets/2079069/3467377/eac23c12-028f-11e4-89fc-d3b664471fec.png)
![dz5uol8](https://cloud.githubusercontent.com/assets/2079069/3467378/eac3a0d4-028f-11e4-82d5-487bce8bff4e.png)

Didn't try bisecting where the bug started yet. Filling the issue just as I found it.

**Comment by vLKp** [comment]
@zicodxx: I see in comment #<b></b>3 that you wanted to address the static escaping its bounds.  Is there any remaining work to do?

**Comment by vLKp** [comment]
The original report is very old.  @zicodxx may or may not have remaining work associated with escaping static, but has not responded in the roughly 4 months since I posted a reminder inquiring whether any work remained.

Closing.  If further work is required, please reopen and identify the required work.
