### ISSUE TITLE
Runtime bug: Can't play any PS1 (d1-playstation.dxa) music track other than the main menu track

### ISSUE THREAD

**Issue by TheMiracleMatter** [dxx-rebirth/dxx-rebirth#600]
### Environment
https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20210721-win.zip
+ the 'd1-playstation.dxa' file

#### Operating System Environment
* Microsoft Windows 7 SP1

#### CPU environment
* x86\_64 (64-bit Intel/AMD)

#### Game environment
This happens in the main mission; Descent: First Strike with the latest version of D1X-Rebirth
idk about the other missions.

### Description
Problem is simple, I want D1X-Rebirth to play the awesome playstation OSTs and not the lame DOS OSTs when playing but unfortunately, no music track other than the main menu track is played for the main menu (as it should) and every level (as it should NOT) when using the 'd1-playstation.dxa' file. The briefing period is silent and (speaking from memory) the gamelog.txt shows that it failed to load a certain briefing.ogg file <- last thing is not important to fix but I include it in case it's helpful to debug.

I tried literally everything involving the sounds and music menu, moved the d1-playstation.dxa file in so many different places (only the exe dir would even play any of it) and even fiddling with the descent.cfg file quite a lot to no avail.

This problem is NOT present with the default music tracks (when d1-playstation.dxa is not used) but this is not the music I want to hear.

#### Regression status
Although I didn't try everything again with every other version (I'm not gonna spend years on this), I did try it in the old 0.58.1 version and the problem is the same from what I could tell.

### Steps to Reproduce
Just put the 'd1-playstation.dxa' file in the same dir as the .exe and launch the exe, the main menu music plays just as it should but starting a new game results in no sound during briefing (I don't really care about that one in particular) but also, any level music is replaced by the main menu music.

* Engines affected:
  * [ yes ] D1X-Rebirth
  * [ idk ] D2X-Rebirth

* Game modes affected:
  * [ yes ] Single player
  * [ idk but presumably it's the same] Multiplayer

**Comment by vLKp** [comment]
I gather from the name that `d1-playstation.dxa` is an add-on with Playstation music.  However, I don't see it for download on the project website, and prior to this ticket, I was not aware of its existence.  Where can it be obtained?  Alternately, does the problem manifest with a music add-on that I can readily obtain?

**Comment by TheMiracleMatter** [comment]
I don't even remember where I got it from, I thought it might have been the dxx-rebirth website but the fact that it's not even there put that in question.
Anyway, the only place online I found it backed up now (which is not where I got it from originally, that I'm sure of it)... is there: https://github.com/pudlez/dxx-addons

**Comment by Diamond-Wolf** [comment]
There used to be an installer for Rebirth (v0.58.1 I believe) which contained many optional addons, including redbook soundtracks and many renditions of the midi soundtracks in a variety of soundfonts. I do not believe the source for these addons the installer used is still active, however, though the referenced repo does appear to have the right set.

**Comment by TheMiracleMatter** [comment]
> There used to be an installer for Rebirth (v0.58.1 I believe) which contained many optional addons, including redbook soundtracks and many renditions of the midi soundtracks in a variety of soundfonts. I do not believe the source for these addons the installer used is still active, however, though the referenced repo does appear to have the right set.

**Comment by TheMiracleMatter** [comment]
That was a complete misclick

**Comment by vLKp** [comment]
This seems to work fine for me.  Using both the D1X-Rebirth and D2X-rebirth engines to play their respective builtin campaigns, with music set to built-in/addon, and `d1-playstation.dxa` (size: 221679951; sha256sum: fe753c00463008f0a2218aabf018bfd68f56278c60582ea594b155a23d487871) in the per-user data directory (`~/.d1x-rebirth`, `~/.d2x-rebirth`), I see the engine play differing songs for each of the first 3 levels.  `descent.ogg` (the main menu track) for level 1, `game02.ogg` for level 2, and `game03.ogg` for level 3.  This matches with what the dxa's embedded `descent.sng` requests.

Please confirm that the dxa I used, which I got from the linked repository above, matches the one that you used.

**Comment by TheMiracleMatter** [comment]
I just verified with a file comparator and our d1-playstation.dxa files match down to the last bit.

However, I noticed you said you've put it in the "per-user data directory" and it's a hidden directory. On my side, it's in the main game directory (C:\Program Files (x86)\Descent\D1X-Rebirth) and it's on windows but there is nothing in the AppData folder.
D1x-rebirth is self-contained from what I understand.

Could this be at the origin of the issue... or do I need to be on linux to make it work ?

**Comment by vLKp** [comment]
Rebirth only searches specific places for data to load.  I put it in the per-user area because that was writeable and easy to name.  Rebirth expands `~` internally, so it works on non-Linux platforms.  If you add the command line flag `-debug`, the verbosity of the game will be increased substantially, and it will log (among many other things) the directories it is adding to the search path, so you can find other directories that you could have used.

`dxa` are just `zip` files.  zico chose to use a special extension so that Rebirth wouldn't try to search user-created zip files that happened to be in the right directory.  You can unpack the `dxa` by treating it as a zip file.  Inside it, you will find `descent.sng`, a text file that lists which sound files to play for each level, as well as some entries for special areas like the main menu.  The parser is sadly rather sloppy about line endings, and this particular sound add-on relies on that sloppiness.  Blank lines are ignored.  Non-blank lines are taken as the filename to use for that entry.    The music for level 1 is specified on line 6, since lines 1-5 are for various non-level areas.  By that rule, I see that game level 12 (on file line 17) is explicitly set to `descent.ogg`, which is the main menu music.  If you know the proper name for the level 12 music, you could change that line accordingly.

See https://github.com/dxx-rebirth/dxx-rebirth/blob/e0820e2825a8bbfafa699c8ce241dc5bef97d982/common/main/songs.h#L25-L30 for the special non-level areas.

**Comment by TheMiracleMatter** [comment]
> `dxa` are just `zip` files. 
Awww sweet ! This more than I was hoping for ! Thank you very much ! I can see everything in it now... and indeed there is no briefing.ogg. Guess that's just one more thing I should be able to fix by myself _easy._ And lol it **is** sloppy, some end of lines have just LF but most have CR/LF.

Everything should be good now !
