### ISSUE TITLE
Runtime bug: Recharging in an Energy field while at 100% power with the afterburner recharging causes sound issues

### ISSUE THREAD

**Issue by thx42de** [dxx-rebirth/dxx-rebirth#601]
### Environment

Downloaded on Arch via AUR
aur/d2x-rebirth-git 0.60.0.beta2.r760.g84fb6d499-1

#### Operating System Environment

Linux

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13
  * [ ] Mac OS X 10.14
  * [ ] Mac OS X 10.15

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [X] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Descent 2 base game

### Description
When entering an energy field with 100% energy but low afterburner, the recharging sound gets played over and over very quickly until the after burner has fully recharged

### Steps to Reproduce

Fly into an engergy field with 100% Energy (not more!) and a low afterburner

Expected behaviour: the sound gets played once, until the afterburner has recharged
Observed behaviour: the sounds starts playing over and over again in quick sucession

* Engines affected:
  * [ ] D1X-Rebirth
  * [X] D2X-Rebirth

* Game modes affected:
  * [X] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
I thought this was how it always worked.  Since you're at 100 energy, charging the afterburner drains you to below 100 energy.  Then the energy center processing notices that you are below 100 energy, charges you up to 100, and plays a sound.  Since you're very close to 100 energy, you fill up quickly.  The afterburner then pulls a bit more energy, pushing you below 100 again, and the energy center charges you, again.

It looks like this is no different from the recurring sound when you fly into an energy center while very low on energy, and need several seconds to recharge, or when you park in an energy center and continuously discharge an energy weapon.

The game has a governor to limit playing this to a few times per second (rather than every frame), but otherwise it looks like this has been that way at least since 0.57.3.

Is my analysis above wrong or inconsistent with the original game?  Or do you disagree that it should ever have worked this way?

**Comment by thx42de** [comment]
Thanks for your reply @vLKp I think your analysis is 100% correct. I do not know how the original game handled it, that being said, it does sound terrible in my opinion and I would personally consider it a bug either in the original or in d2x regardless how the original game handled it. I

think it would sound considerably better if the sound starts once, the ramp up sounds plays until the highest notes at the end and loops the highest notes until fully charged. I don't know if that is a lot of work or against the projects spirit trying to preserve the original game but I would consider it an improvement.

**Comment by vLKp** [comment]
Since the sound can be replaced, and is presently a recorded blob that is passed to the sound system, manipulating the playback to focus on a particular subsection of the sound would be more trouble than I care to pursue.  Inhibiting overlap is relatively easy, either by changing the interval between starts or by making the sound cancel prior instances of itself.

Given that the original always had special logic to rate-limit starting secondary instances of the sound, I'm confident that the original designers intended this behavior.  If they had wanted to prevent overlap, they had several options available, and none of those were used.  Interestingly, they changed the interval in Descent 2, but did not make it significantly longer.  In many other cases, questionable design decisions in Descent 1 were revisited in Descent 2.  If they had intended to prevent overlap, I would expect at least Descent 2 would have done so.

If you'd like to change this locally, the easiest fix would be to change `FUELCEN_SOUND_DELAY` to a larger value.  It is presently `F1_0 / 3` (Descent 1) or `F1_0 / 4` (Descent 2).  The comment says Descent 2 is `play every half second`, but I don't think that's right.  I thought F1_0 is one second, so `F1_0 / 4` should be four times per second, not two.

https://github.com/dxx-rebirth/dxx-rebirth/blob/e0820e2825a8bbfafa699c8ce241dc5bef97d982/similar/main/fuelcen.cpp#L561-L566

**Comment by vLKp** [comment]
No response from original reporter.  I outlined a workaround above (recompile required) for those who feel strongly about adjusting the interval.  I don't disagree that there may be better ways to present this sound to the user, but the only practical ones are to change the delay between starts or completely block overlap.  I don't consider the current behavior to be a problem worth changing `master` to do a specific new behavior, and I don't want to work on writing multiple choosable behaviors.  Therefore, closing.
