### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by Gr33nEyes** [dxx-rebirth/dxx-rebirth#607]
Will you add support of VS2019?

**Comment by vLKp** [comment]
When last I tried Visual Studio, which appears to have been Visual Studio 2017, the compiler outright crashed on constructs that gcc had handled correctly for years.  This did not inspire confidence in the quality of the eventual output, had I ever gotten the compiler to run to completion.  If Visual Studio's C++ conformance has improved to the point that it can handle valid code, then yes, it can be used.  Based on the commit message, it looks like I finally abandoned the project in [Update contributed Visual Studio files to Visual Studio 2017](/dxx-rebirth/dxx-rebirth/commit/bc9e0ea196fd48daf0e61401a8bf44c7e7b5b5b0).  The solution files added there would be a good place to start.

Please elaborate on your question, since there are several ways it could be interpreted.  Are you asking whether I plan to install Visual Studio 2019, write up a solution file for it, and investigate any build failures with it?  No, I have no plans to do so, for several reasons.

- Visual Studio has never worked well in Wine.
- Although Visual Studio Code (the text editor) is available for Linux, I can find no indication that the development tools are available for Linux.
- From what I can see, Microsoft still hasn't abandoned [their misguided attempt to force people to use an online installer program](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019), instead of providing a working download the way they did back in the Visual Studio 2007 era.  If anything, it appears to have gotten worse.  They now push you to install a bootstrapper, which can install the Visual Studio Installer, which can then install Visual Studio.  The joke about a meeting to plan the meeting is meant as a joke, not a template.  The _proper_ way to provide an installer is a download link that a browser, or `wget`, can download and that, once completed, provides everything necessary to install the program without further downloads.  The closest they seem to get is a [Windows-hosted "web installer"](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019) that can download the required bits.  This, of course, supposes that I have a Windows system with a sufficient network connection to use their installer.
- Even the free Visual Studio Community has a EULA - which I cannot read, because someone thought it would be ever so clever to have a [web page offer me a Microsoft Word docx](https://visualstudio.microsoft.com/license-terms/mlt031819/) file with the EULA terms in it.  The _proper_ way to do this is not to have a EULA on a free product, but instead to include appropriate disclaimers, as free projects have done for decades.  The improper, but not horrible, way would be to at least put the license agreement in the webpage, where it can be read and quoted.  If they can't even get the license posted for proper review, I see no reason to spend my bandwidth downloading their installer's installer in the hope that the license will actually be reasonable.
- Despite the concerns above, I decided to try installing it anyway.  The download doesn't start, and the [click here to retry](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16#) link is just an anchor pointing to the page that doesn't initiate the download.  So even if I wanted to download it, I can't.  It doesn't start, and there is no indication why.  This is not a good user experience.  It suggests no one seriously tests even the web pages.

Are you asking whether I will provide guidance to people who encounter problems trying to use Visual Studio?  I will consider such reports, but make no guarantees.

Are you asking whether I will accept patches from other people who want to use Visual Studio to build Rebirth?  I generally accept reasonable patches from the community, and if Visual Studio can build Rebirth without needing invasive modifications to the code, I have no objection to merging such patches.

If none of these possibilities is what you meant, please explain what you want.

**Comment by Gr33nEyes** [comment]
SDL2 is fully supported?

**Comment by vLKp** [comment]
Do you require assistance with these errors or are you working to resolve them?  A search tells me that Visual Studio's C1083 error is [fatal error](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1083?view=msvc-160) and can have one of several causes.  If I were to guess, I would say that the error is caused by being unable to open an include file, either because the required headers are not on the system or because they are not in the search path for the project.

**Comment by vLKp** [comment]
> Bro, I'm complete newbie

Is there a reason you are trying to use Visual Studio 2019, when the Rebirth project already supports using gcc for Windows?

> If I add SDL2 in project, i got above 200 errors

It seems you have your work cut out for you, then.  I cannot help you with the minimal amounts of information you are providing.  If you want assistance, you will need to give me something I can diagnose or debug.  I suggest you start by providing the actual error messages.  It may also be helpful if you publish your changes, so I can see how you configured your build.

**Comment by vLKp** [comment]
No response from original reporter.  Based on my analysis above, I doubt I will work on Visual Studio 2019 support in the near future.  Based on the reporter's responses to date, it seems unlikely that @Gr33nEyes will contribute this feature, so closing.

Please reopen if you wish to work on this.
