### ISSUE TITLE
First screenshot is garbage

### ISSUE THREAD

**Issue by gakizoo** [dxx-rebirth/dxx-rebirth#613]
I looked at the code. The write_screenshot_png function uses "void /*unused*" as the fourth argument.
But, trying to make .tga screenshots exhibits the same problem.
Subsequent screenshots are fine, so this is probably a C++ "magic" failure.
I tested using d2x-rebirth.

**Comment by vLKp** [comment]
I tested the latest d2x-rebirth and screenshots are fine, including the first.  Your report is missing all the standard fields that the issue template should have prompted you to provide, which greatly reduces my ability to help you.

You should use backticks, not double quotes, when citing code.  That will discourage Github's markup processor from mangling your text.

The fourth argument you cite:

https://github.com/dxx-rebirth/dxx-rebirth/blob/f99ba919986f2c8f0a0dba0b4ebd196f2aaa4f31/similar/main/game.cpp#L991

is deleted by a macro:

https://github.com/dxx-rebirth/dxx-rebirth/blob/f99ba919986f2c8f0a0dba0b4ebd196f2aaa4f31/similar/main/game.cpp#L817

which is why it is marked as unused.  Some configurations do not delete the fourth argument, which is why it has not been removed from the source.

---

Based on the very limited information provided, and the inability to reproduce this, there is nothing I can do here.  If your problem is reproducible, and you still need assistance, please reopen and provide, at minimum:

- On what operating system are you running?
- What video drivers are you using?
- Exactly what build did you test?
- In what state is the game when you take these "garbage" screenshots?  Are you in a level?  Does it matter which level?
- Provide an example of the garbage screenshot, or precisely describe what about it is garbage.
