### ISSUE TITLE
Build failure: 351elec retro handheld (aarch64, no WM)

### ISSUE THREAD

**Issue by mcpalmer1980** [dxx-rebirth/dxx-rebirth#615]
Hello,

I haven't found any better way to contact the devs for this project. Feel free to delete this issue after reading it.

I haven't personally tried to build DXX but have worked on other ports for Anbernic 351 line of retro handhelds. Most likely the X dependency on Linux is to blame. There are many users of portable devices, set top boxes, and RPis that run Linux without a window manager. Most retro handheld owners I've spoken to would love to see Descent on their device.

It would be great if someone would work on a build option that uses the KMSDRM SDL2 backend. The devices typically run aarch64 binaries and an EmuElec based Linux OS without a WM. If anyone is interested in discussing these devices the [discord](https://discord.gg/R9Er7hkRMe) link is on the 351elec [project page](https://351elec.de/).

**Comment by vLKp** [comment]
This is the proper way to contact the developer for this project.

If SDL2 covers your preferred rendering engine, the game should be able to use it.  Rebirth supports both SDL1 and SDL2.  It still defaults to SDL1, but you can choose SDL2 at build time.

What is the actual build failure?  You didn't include any output from the build, and I don't understand from the description what might be the problem.  Is Rebirth depending on some library that is not available on these devices?  If so, which one?  You say you haven't personally tried to build DXX, so I am a bit confused why you think it fails to build.  Are you just guessing it will fail based on other projects that also failed on this device?  Are you recounting that someone else told you it failed?

If you can describe what you need done, I can look into changing the code to help you - but I will warn that I do not have such a handheld, nor any way to build for it, so any changes will be speculative and you will need to test them yourself.

**Comment by mcpalmer1980** [comment]
Again, I haven't attempted to build it myself. But I have had a few discussions with people who have. An earlier version did build but the controls were broken. New versions won't build anymore. I will include a short discord blurb in a minute. My intention is only to share and gather preliminary information about this issue. The individual who will probably work on the port isn't ready to start it yet.

I have used the aarch64 chroot included with our 351elec vbox image to build other opensource projects. Right now I'm working on a pygame environment and am busy porting my own and other pygame projects to the device. In my experience, the popular firmwares for these devices strongly prefer SDL2, and SDL2 builds with xlib dependencies by default even if you select the KMSDRM backend during execution.
___
**romadu**
Today at 8:47 AM
The current source doesn’t compile but earlier versions did (black screen launch). Anberports versions had minor openglesv2 mod that’s not enough any more to successfully compile

**MichaelCPalmer**
Today at 8:49 AM
Is that changes to the dx project, or broken dependency updates?

**romadu**
Today at 8:50 AM
Changes to dx project

**MichaelCPalmer**
Today at 8:51 AM
Didn't realize it was active

**Johnny on Flame**
Today at 8:51 AM
had commits literally yesterday

**MichaelCPalmer**
Today at 8:52 AM
Has anyone posted an issue? Broad compatibility with portables seems vital as a large part of its audience will likely want to play it on a retro console.
Is there a public forum?

**romadu**
Today at 8:55 AM
https://www.dxx-rebirth.com/
DXX-Rebirth
zico
Welcome to the DXX-Rebirth project!
They have a discord for developers
I haven’t focused on it enough to offer feedback

**MichaelCPalmer**
Today at 8:57 AM
It would be nice to give the devs a heads up about the issue. I imagine they haven't put any thought to systems without a wm.

**Comment by mcpalmer1980** [comment]
**romadu**
Today at 1:02 AM
SDL1 compiles, but SDL2 has compile error _Rebirth configured with OpenGL enabled, but SDL2 configured with OpenGL disabled.  Disable Rebirth OpenGL or install an SDL2 with OpenGL enabled_. Anberports made a change to get a version to compile but making that change to current version doesn't work for me.
https://github.com/krishenriksen/dxx-rebirth-rg351p/commit/cf888df45798aeec4925190fdd917221d403d0c8#diff-d78c5c377c03dd251edc72cdb0ae7d9986fa08361eb392187218f8c670c0bc4eL3596

**romadu**
Today at 1:04 AM
sdl2             use libSDL2+SDL2_mixer (!EXPERIMENTAL!) 
Setting opengles=1 doesn't help
**romadu**

Today at 3:20 AM
I have Descent 1 working, just fixing controls

**Cebion**
Today at 3:21 AM
How?

**romadu**
Today at 3:22 AM
sdl1 version and I dropped in nl255's sdl1.2-compat libraries

**Comment by mcpalmer1980** [comment]
Does dxx-rebirth support gles? I know these devices support gles2 and maybe 3, but not full opengl.

**Comment by vLKp** [comment]
> Again, I haven't attempted to build it myself. But I have had a few discussions with people who have.

That is what I thought from above.  However, without specific error messages, there is not much I can do.

> An earlier version did build but the controls were broken.

Which controls were broken, and how?  Did they do nothing or do the wrong thing?

> The individual who will probably work on the port isn't ready to start it yet.

Understood.  For reference, I prefer to have the upstream code work on as many supported targets as possible.  To that end, I would appreciate if whoever works on the port contributes back any required patches (under suitable license terms) to this repository, so that we eventually reach the point that people can check out `master` and have it work without further patching.  This will also protect the port from some forms of bit rot, since I won't unknowingly write a conflicting change that invalidates the patch.

> In my experience, the popular firmwares for these devices strongly prefer SDL2, and SDL2 builds with xlib dependencies by default even if you select the KMSDRM backend during execution.

Rebirth supports, though does not default to, using SDL2.  It always uses a system copy, not a bundled one.  I don't work on SDL2, so there's nothing I can do about it picking different dependencies than you want.

> Today at 8:47 AM

It would be helpful if you set your client to use absolute timestamps, so that these remain clear and valid when pasted elsewhere and quoted.

> **MichaelCPalmer**
> Today at 8:52 AM
> Is there a public forum?

Not anymore.  There was once a forum hosted on the main domain, but its operator (not me) decommissioned it due to lack of time/resources to operate it.  This issue tracker is now the only venue I watch with any regularity.

> **romadu**
> Today at 8:55 AM
> They have a discord for developers

Note that I don't use Discord, so you won't find me there.  There are several fairly active regular contributors other than me (none of whom have so far requested commit access); some of them might be there.

> **MichaelCPalmer**
> Today at 8:57 AM
> It would be nice to give the devs a heads up about the issue. I imagine they haven't put any thought to systems without a wm.

You are correct.  I didn't think I needed to.  I create a window, optionally full-screen, and let the display server sort it out.  If more involvement from the application is required, please describe what special handling is needed.

> **romadu**
> Today at 1:02 AM
> SDL1 compiles, but SDL2 has compile error _Rebirth configured with OpenGL enabled, but SDL2 configured with OpenGL disabled.  Disable Rebirth OpenGL or install an SDL2 with OpenGL enabled_.

If I recall correctly, I added this test because I found that building Rebirth with OpenGL, and SDL without it, led to a guaranteed failure on startup.  If you bypass this test and force it to build anyway, does Rebirth work for you?  If so, I may need to modify the test.  The `sconf.log` from when this output occurs would be useful.

> Anberports made a change to get a version to compile but making that change to current version doesn't work for me.
> https://github.com/krishenriksen/dxx-rebirth-rg351p/commit/cf888df45798aeec4925190fdd917221d403d0c8#diff-d78c5c377c03dd251edc72cdb0ae7d9986fa08361eb392187218f8c670c0bc4eL3596

This is just the default value for `opengles_lib`.  If it doesn't work for you, you can override it on the command-line: `scons opengles_lib='some-other-GLES-implementation'`.  To reiterate the default, you would write `scons opengles_lib=GLES_CM`.  If there is a standard GLES for your platform, and a reliable way for SConstruct to recognize your platform distinct from others, I can add a branch in `selected_OGLES_LIB` to pick your platform's name.  There is already a special case to pick an alternate default name when the user enables raspberrypi mode.

> **romadu**
> Today at 3:22 AM
> sdl1 version and I dropped in nl255's sdl1.2-compat libraries

SDL2 works for me with current `master` on a typical Linux/amd64 system.  If it doesn't work on your platform, we should determine why.

> Does dxx-rebirth support gles?

Rebirth had a GLES flag when I took over as the main developer, and I haven't intentionally broken GLES support.  However, I also don't test GLES.  In trying to build it now, it fails to build, with what looks like some old bitrot.  Some of the failing lines haven't been touched since 2013, and are failing due to warning options I enabled years ago.  After fixing those compilation errors, I don't have a GLES_CM.  Speculatively linking it to `libGLX_mesa` works, and the game seems playable from the bit of flying around I did.  I pushed my compile fixes to `master`.  I did not change the default `opengles_lib` yet, so you probably need to override it with a value appropriate to your platform.

**Comment by mcpalmer1980** [comment]
| Which controls were broken, and how? Did they do nothing or do the wrong thing?

The Anberports version ran using keyboard emulation instead of as a joystick. This is probably necessary because the keyboard is sometimes necessary in the game (to select your level, enter you pilot name, etc). Unfortunately this means no analog controls :(

There are complications with these devices because the button and axis orders vary by device so they need to be configured differently for each device. This is partly why the Anberports project has been abandoned in favor of the Portmaster project, which allows easier configuration across a larger range of devices and firmwares.

I am trying to get the Portmaster dev to abandon keyboard emulation in favor of the sdl2 controller API. This API allows all kinds of handheld devices to operate the same, with the built in controls emulating the xbox360 controller layout. But first we need to get the game to compile for SDL2 of course.

**Comment by vLKp** [comment]
You might be interested in the functionality added in [make menus controllable with joystick](/dxx-rebirth/dxx-rebirth/commit/c24864b180808c2e8bc8b03bd7aeb22a4b956e07).  It provides a basic method of menu operation where Rebirth maps the joystick inputs to keyboard-equivalent actions, without requiring external software to perform keyboard emulation.

If you need help making the game work with SDL2, please post full logs from a failure.  As I wrote above, SDL2 works fine for me here, so there is currently nothing I can do for you.  There are no build failures in any of the configurations I tested, and nothing in this ticket shows a build failure with sufficient detail for me to try to address it.

**Comment by vLKp** [comment]
No response from original reporter.  No follow-up from whoever was planning to work on this port.  No actionable information is available in the ticket, so there is nothing I can do here.  Closing.  If you wish to resume work on this, please post back and reopen.

If you still need help, please provide the full log from a failed build.

If you want to pursue the issue where the SConf test aborts due to the SDL OpenGL configuration, I will also need the `sconf.log` so that I can understand how the test decided that you lacked OpenGL support.  For this failure, it would also be useful to know if bypassing that test and forcing the build to proceed anyway will result in a working game, or some other failure later.  If the build succeeds and produces a working game, then the SDL OpenGL test is too strict and may need to be loosened.  Otherwise, it seems like the test correctly protected you from a configuration that would have failed later.
