### ISSUE TITLE
OSX compile error 

### ISSUE THREAD

**Issue by btb** [dxx-rebirth/dxx-rebirth#62]
This doesn't seem to be caused by any recent commits, so I think something must have changed with the new version of XCode.

```
In file included from common/misc/ignorecase.cpp:14:
In file included from common/include/physfsx.h:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2676:32: error: no type named 'type' in 'std::__1::enable_if<false,
      std::__1::unique_ptr<char *[], PHYSFS_list_deleter>::__nat>'; 'enable_if' cannot be used to disable this declaration
            typename enable_if<__same_or_less_cv_qualified<_Pp, pointer>::value, __nat>::type = __nat()) _NOEXCEPT
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/include/physfs_list.h:33:2: note: in instantiation of member function 'std::__1::unique_ptr<char *[], PHYSFS_list_deleter>::unique_ptr' requested here
        DXX_INHERIT_CONSTRUCTORS(PHYSFS_list_template, base_ptr);
        ^
./dxxsconf.h:45:36: note: expanded from macro 'DXX_INHERIT_CONSTRUCTORS'
        using _dxx_constructor_base_type::_dxx_constructor_base_type;
                                          ^
common/include/physfs_list.h:29:7: note: while substituting deduced template arguments into function template 'PHYSFS_list_template'
      [with _Pp = PHYSFS_list_template<PHYSFS_list_deleter>]
class PHYSFS_list_template : public std::unique_ptr<char *[], D>
      ^
In file included from common/misc/ignorecase.cpp:14:
In file included from common/include/physfsx.h:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2676:32: error: no type named 'type' in 'std::__1::enable_if<false,
      std::__1::unique_ptr<char *[], PHYSFS_list_deleter>::__nat>'; 'enable_if' cannot be used to disable this declaration
            typename enable_if<__same_or_less_cv_qualified<_Pp, pointer>::value, __nat>::type = __nat()) _NOEXCEPT
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by vLKp** [comment]
It would be nice if clang would print out the instantiation parameters so that I could see what it does not like.  Based on [clang's &lt;memory> on trunk](https://llvm.org/svn/llvm-project/libcxx/trunk/include/memory), I think `_Pp` will be the type of argument 1 to the constructor and `pointer` is `typename __pointer_type<_Tp, deleter_type>::type`.  Since the constructor first argument is a template, it could be any type.  `__pointer_type<_Tp, deleter_type>::type` seems to be a shorthand for `typename __pointer_type_imp::__pointer_type<_Tp, typename remove_reference<_Dp>::type>::type`, which is clang's way of using the `pointer` type of the deleter and falling back to `_Tp *`.  This deleter has no `pointer` type, so it should fall back to `_Tp *`, which would be `char * *`.

Please disable constructor inheritance by setting `sconf_cxx11_inherit_constructor=force-failure`, then try again.  If it produces different output, please show that output.  Otherwise, this will have to be solved with guesswork.

**Comment by btb** [comment]
with sconf_cxx11_inherit_constructor=force-failure I don't get an error

**Comment by vLKp** [comment]
That should not happen.  Disabling constructor inheritance switches to a fallback forwarding method that should have equivalent semantics, but may not optimize as well.  If you can provide a minimal reproducer, I will add a configure check to blacklist the broken versions of Xcode/clang.

**Comment by btb** [comment]
Trying to get clang 3.4 working in travis, now getting the same error there: https://travis-ci.org/btb/dxx-rebirth/builds/60512089

**Comment by btb** [comment]
using libc++ `branches/release_34` instead of `trunk` fixes the problem on travis.

**Comment by vLKp** [comment]
I can reproduce the strange error with `std::unique_ptr` on Linux using clang with [libc++](http://libcxx.llvm.org/), but not when using clang with gcc's libstdc++ nor when using gcc.

**Comment by vLKp** [comment]
8daf33b422d77651d5d3fe328a4c6594c135a063 modifies the constructor inheritance test so that buggy versions of clang fail the test and fall back to variadic template forwarding.

Please test on OS X and report whether this fixes the compilation failure for you.

**Comment by btb** [comment]
That works.
