### ISSUE TITLE
Runtime bug: Unable to bind all controls on X56 HOTAS

### ISSUE THREAD

**Issue by wdcook4** [dxx-rebirth/dxx-rebirth#623]
### Environment
20220121 Descent 1 shareware
https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220121-win.zip

#### Operating System Environment
Microsoft Windows 10 21H1 (build 19043.1526) Education Edition

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Descent Shareware, downloaded from given links on the website (https://www.dxx-rebirth.com/download/dxx/content/descent-pc-shareware.zip)

### Description

I am using a Logitech X56 HOTAS and cannot use all controls on the throttle (throttle, some buttons, and one axis of a mini analog stick) and none of the controls on the joystick.

#### Regression status

Tested only on latest stable at time of writing (linked above)

### Steps to Reproduce

Connect both devices
Attempt to bind any controls with joystick enabled

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [x] Multiplayer competitive
    * [x] Anarchy
    * [x] Team Anarchy
    * [x] Robo-Anarchy
    * [x] Capture the Flag
    * [x] Bounty
  * [x] Multiplayer cooperative

**Comment by vLKp** [comment]
What happens when you try to bind the control?  Does the game bind the wrong button?  Ignore that you pressed the button?  What does the game print to the console log at startup?  It should report how many joysticks were detected, and the number of buttons on each.  Also, if I understand correctly, at least for SDL1, the joystick must be connected before you start the game.

**Comment by wdcook4** [comment]
When I try to bind the control, nothing happens. SDL sees my stick (I see 3 sticks, the throttle, my keyboard, and the actual joystick) and they were connected before starting the executable. Attached is the log for D1X and D2X, D2X has logs for my X56, and D1X has logs for a stick that worked fine (a SideWinder Precision 2 stick)
Debug not enabled, I'll try launching it again later with debug for both sticks.
[gamelog_d2x.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/8065296/gamelog_d2x.txt)
[gamelog_d1x.txt](https://github.com/dxx-rebirth/dxx-rebirth/files/8065304/gamelog_d1x.txt)

**Comment by vLKp** [comment]
Neither the good nor the bad joystick has nearly enough inputs to exceed the game's maximums.  The build you used supports 128 buttons on a joystick; above that, some would be ignored.

Are the counts shown in the log correct for your joystick?  Your X56 has:

```
21:23:35.597 sdl-joystick: 3 joysticks
21:23:35.597 sdl-joystick 0: Saitek Pro Flight X-56 Rhino Throttle
21:23:35.597 sdl-joystick: 6 axes
21:23:35.597 sdl-joystick: 32 buttons
21:23:35.597 sdl-joystick: 0 hats
21:23:35.597 sdl-joystick: 6 axes (total)
21:23:35.597 sdl-joystick: 44 buttons (total)
21:23:35.597 sdl-joystick 1: Controller (WootingHE)
21:23:35.597 sdl-joystick: 0 axes
21:23:35.597 sdl-joystick: 0 buttons
21:23:35.597 sdl-joystick: 0 hats
21:23:35.597 sdl-joystick: 6 axes (total)
21:23:35.597 sdl-joystick: 44 buttons (total)
21:23:35.597 sdl-joystick 2: Saitek Pro Flight X-56 Rhino Stick
21:23:35.597 sdl-joystick: 0 axes
21:23:35.597 sdl-joystick: 0 buttons
21:23:35.597 sdl-joystick: 0 hats
21:23:35.597 sdl-joystick: 6 axes (total)
21:23:35.597 sdl-joystick: 44 buttons (total)
```

and your SideWinder has:

```
00:02:05.471 sdl-joystick: 2 joysticks
00:02:05.471 sdl-joystick 0: SideWinder Precision 2 Joystick
00:02:05.471 sdl-joystick: 4 axes
00:02:05.471 sdl-joystick: 8 buttons
00:02:05.471 sdl-joystick: 1 hats
00:02:05.471 sdl-joystick: 4 axes (total)
00:02:05.471 sdl-joystick: 20 buttons (total)
00:02:05.471 sdl-joystick 1: Controller (WootingHE)
00:02:05.471 sdl-joystick: 0 axes
00:02:05.471 sdl-joystick: 0 buttons
00:02:05.471 sdl-joystick: 0 hats
00:02:05.471 sdl-joystick: 4 axes (total)
00:02:05.471 sdl-joystick: 20 buttons (total)
```

The numbers on the secondary joysticks look suspicious to me.  The log seems to say that the Controller and the Stick each have 0 axes, 0 buttons, and 0 hats.  If so, the device would be useless because there is nothing for the user to trigger.  The numbers shown come from SDL; if SDL is reporting incorrect counts here, then whichever component is wrong (which could be SDL, or could be something that SDL is relying on) may be losing presses on these supposedly non-existent buttons.

Were you able to obtain the `-debug` output?  For the debug output, I am primarily interested in what, if anything, the game prints to the log when you press a non-responsive button.

**Comment by vLKp** [comment]
As I read the joystick code in Rebirth, I expect that a controller which reports "0 buttons" and then sends button press events will not behave correctly.  Rebirth only sets up to handle the buttons actually reported.  The count of buttons is reported to Rebirth from SDL, so there is nothing that Rebirth can do to correct bogus values here.

---

No response from original reporter.  Not reproducible here.  There is nothing I can do to fix this.  Closing.  If you want help with this, please reopen and provide the requested information.
