### ISSUE TITLE
Feature request, bug report as well probably: 4:3 screen aspect ratio toggle

### ISSUE THREAD

**Issue by hfc2x** [dxx-rebirth/dxx-rebirth#635]
I just wanted to know if it's possible to get a user option to force 4:3 aspect ratio with pillar boxing, irrespective of selected screen resolution, mostly because the game assets look stretched in 16:9.

This suggestion comes from me finding what's likely a bug when playing at 1400x1050 resolution to make the game aspect-correct. I pick this because it's the closest 4:3 resolution to my desktop's 1920x1080. If I pick any other (or use a custom one like 1440x1080), the game force-selects 640x480 when I close the options. The biggest problem I have is that the game slows down to like 25 FPS (despite the game's own FPS counter reporting 200+ FPS) when playing at this resolution, and I know my GPU is at least decent (GTX 1050 Ti), so it shouldn't have an issue running the game like this. In fact, it runs flawlessly on any 16:9 resolution.

I'm using Windows 10 x64, by the way.

**Comment by vLKp** [comment]
When reporting a problem, please state what version of the game you are using.

---

I cannot reproduce your problem.  In Options -> Graphics -> Screen Resolution, the game allows me to choose a custom resolution of 1400x1050 with an aspect ratio of 4x3.  If I also enable the `fullscreen` checkbox, I get a pillarboxed game.  I can leave that menu and the game will size its window accordingly.  When I reopen that menu, the game shows `Use custom values` selected and my chosen `resolution` and `aspect` values are preserved.

I performed my tests using the latest code in `master`, on x86_64-pc-linux-gnu with libSDL1 and OpenGL enabled.

---

How are you determining that the game is running at a low frames-per-second rating?

**Comment by AlumiuN** [comment]
I also can't replicate this under Windows 10 - selecting 1440x1080 at 4:3 works correctly (including pillarboxing, although I don't actually know if the game enforces this, or if it's down to your screen choosing whether to stretch or pillarbox it), and the game runs with its normal performance (i.e. locked at 200).

**Comment by AlumiuN** [comment]
Some more testing has led to the discovery that, when in fullscreen, every attempt I've made to change to a custom resolution results in a 640x480 resolution, with the text for the custom resolution entered into the box being replaced with 640x480 once the user leaves the graphics options menu. I still can't replicate the perfomance problem, though.

**Comment by hfc2x** [comment]
I'm using the 81dd23b build that's available in the DXX-Rebirth website. I just tested again, and the performance problem seems to have nothing to do with D1X-Rebirth. Both the game and OCAT report 200+ FPS, but my monitor reports fixed 24 FPS on that specific resolution with its own FPS counter. Weird thing is that it only happens with Descent 1 running through D1X-Rebirth. I don't have this issue with any other game or program no matter the resolution, but it's likely that's just either my monitor or GPU doing something strange.

The forced 640x480 resolution @AlumiuN mentions is an actual problem, though.

**Comment by vLKp** [comment]
I cannot reproduce the issue with the custom resolution being reset to 640x480.  I set a stock resolution equal to my native monitor size, ticked the fullscreen box, and dismissed the menu, to get the game to occupy my entire monitor.  I reentered the resolution menu, picked `Use custom values`, and entered a custom resolution.  Regardless of whether I leave `fullscreen` ticked or if I untick it, I get the desired behavior.  The only questionable event here, which I admit is unfortunate, is that after choosing a stock resolution, the value pre-filled in `Use custom values` is the value of the stock resolution, rather than the most recently entered custom value.  It might be better if that was preserved.

---

At this point, I cannot reproduce any obvious bugs, nor am I clear what you want done with the aspect ratio, since the `Use custom values` menu option already allows entering an arbitrary `Aspect:` choice.

**Comment by hfc2x** [comment]
Well, it's probably a Windows-exclusive bug, considering how uniquely it deals with screen resolution changes.

It's easy to reproduce: in the Windows build of D1X-Rebirth, go to graphics settings and select a preset screen resolution. Then go to the custom resolution field, select the custom resolution option, and then write something like 1440x1080 and aspect ratio of 4x3 in the corresponding fields. Press enter to set, and then press the Esc key to go back to the previous menu. The screen will go black, and the resolution should jump down to 640x480, which then you can corroborate by going back into the screen resolution list. The preset for 640x480 should be selected, and the custom resolution fields will also be filled with "640x480" and "4x3" respectively.

**Comment by AlumiuN** [comment]
It seems like the Aspect option isn't designed to do what you want it to, it determines the aspect ratio of the 3D stuff (which will consequently look either stretched or squished if it doesn't match the chosen display resolution's aspect ratio), although why this is necessary, I'm not sure; regardless, generally your display determines how a particular resolution that doesn't match its aspect ratio will display (and there's often an option to change which behaviour it uses buried in its settings somewhere, so it might be worth checking that). Otherwise, Rebirth would need an option to allow it to manually pillarbox by running at a resolution that is different from the one you have selected (i.e. that matches your display's aspect ratio), which is possible, but by my understanding not trivial.

For what it's worth, I do think that an option to have Rebirth run at your screen's resolution but render at a chosen resolution and scaled up would be a worthwhile enhancement, but I have almost no understanding of what would be required to do so beyond an understanding that it's not trivial to implement.

**Comment by vLKp** [comment]
There is a behavior that may explain one of your originally reported problems.  If you pick `Use custom values`, then happen to enter a custom resolution and aspect ratio that is also offered natively, then on returning to the menu, the `Use custom values` box is _not_ checked, and instead the radio button adjacent to the stock resolution with the same value is selected.  This preserves the actual resolution of the game, but not the user's settings exactly as entered.

Does your monitor offer `1400x1050` as a natural resolution, according to the list of resolutions shown in the Rebirth screen resolution menu?

---

Rebirth's screen resolution handling code is common to all platforms.  The details of how SDL implements it vary widely, but the menu system should be the same everywhere.

> It's easy to reproduce: in the Windows build of D1X-Rebirth

I don't have regular access to a Windows computer.  That is why I test on Linux by default.  I test that the game still compiles for Windows, but that is the extent of my Windows handling on any routine basis.  I could run the game under Wine, but I doubt that would be a representative test in this case.

---

When the `fullscreen` box is ticked, then even on Linux, Rebirth will change the display resolution.  (Though interestingly, there is no flash of black.  The resolution change is seamless here.  I had to check independently that the resolution really was changing, rather than that the game was rescaling itself on my display.)  Using a custom resolution, with `fullscreen` ticked, and without adjusting the aspect ratio, I can get the game to letterbox or pillarbox itself, as appropriate.  No special handling or settings are required.  Have you tried running the game in windowed mode, and sizing its window to leave an appropriate pillarbox dead zone on each side of the game?  This would let your desktop show through in those areas, but would produce an aspect-correct game.

All my tests in this thread were done with SDL1.  SDL2 handles window and screen dimensions differently.  Among other changes, the SDL2 build of Rebirth does not offer any stock resolutions.

---

As @AlumiuN notes, Aspect Ratio is for in-game handling.  You can see this readily if you set a silly ratio, such as `40x3` instead of `4x3`.

**Comment by vLKp** [comment]
I was not able to reproduce the game force-selecting a resolution other than the user's choice.

---

The game can already be run in pillarbox mode, without needing to touch the Aspect Ratio setting.

---

No response from original reporter regarding use of either fullscreen or windowed mode to achieve letterbox/pillarbox.  Closing.  If you still wish to pursue this, please answer and reopen.

**Comment by AlumiuN** [comment]
I'm not sure if this is worth a re-open, but I just tested it again with the log showing debug output and attempting to change the screen resolution to a custom value while in fullscreen (in this case, 1600x1080) produces "14:20:47.574 Cannot set 1600x1080. Fallback to 640x480". The resolution change works fine when in windowed mode, so presumably this is an artifact of exclusive fullscreen mode, and probably not something that Rebirth can fix without _significant_ work to provide some sort of upscaling to the native res in the case that it can't get the resolution it wants.

**Comment by vLKp** [comment]
That is interesting.  I tried that before, and did it again now.  For me, on x86_64-pc-linux-gnu with SDL 1.2, setting "Custom resolution: 1600x1080" + "Fullscreen" works and produces a pillarboxed game, where the monitor runs at the nearest sufficient resolution (apparently 1920x1080), and the pillarbox keeps the 1600x1080 game canvas centered on the monitor.  This is unfortunately mostly the domain of SDL.  Rebirth asks for the resolution and full screen mode, and SDL either provides it or fails.  If I were to guess, using only what I have seen in this thread (and not checking the SDL source), my guess is that Linux SDL is providing this, and Windows SDL fails because the system does not natively provide it, and SDL does not emulate it.

---

While I don't want to put in the effort to provide that software upscaling, I would consider trying to handle this more gracefully, if better semantics than "Fall back to 640x480" can be agreed on.

**Comment by AlumiuN** [comment]
Beyond adding an in-game dialog that states a failure to select the resolution, or maybe selecting a built-in resolution closer to the one it tried to use as a fallback, I'm not sure there is much of an option.
