### ISSUE TITLE
Runtime bug: cockpit view resets when crossing exit trigger even if dead

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#637]
### Environment
e29cddd52469ca35b1445f4f53290d12e3d52aaf

#### Operating System Environment

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [ ] Microsoft Windows 10

* Mac OS X
  * [ ] Mac OS X 10.10
  * [ ] Mac OS X 10.11
  * [ ] Mac OS X 10.12
  * [ ] Mac OS X 10.13
  * [ ] Mac OS X 10.14
  * [ ] Mac OS X 10.15

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Fedora 33
  * [ ] Fedora 34
  * [x] Fedora 35
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Any mission works. Assets have no effect.

### Description

A minor visual bug. When the player crosses the exit trigger, the cockpit mode is reset, even if the player is dead. This brings the cockpit view back even if it isn't supposed to be visible during the player death roll.

#### Regression status

This bug may be as old as D2X, but is not present in the original game. The original game checks if the player is dead before calling `reset_rear_view` (which resets the cockpit view), but modern Rebirth does not.

### Steps to Reproduce
Steps:
1. Be on low shields after blowing up the reactor
2. Be moving towards the exit trigger
3. Die while moving
4. Slide through the exit door after dying

Expected:
Cockpit view stays hidden, since the player is dead and the death roll should have no cockpit view.

Actual:
The cockpit view pops back up when the player crosses the exit door.

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative

**Comment by vLKp** [comment]
It looks like this broke in [Properly record the event of reset_rear_view() while switching levels to make it work right when rewinding as well; Properly record Countdown seconds for each newdemo frame instead of second change to get display showing up right while playback and still preserving backwards compability; Suspend Game_wind when playing endlevel movie while demo playback](/dxx-rebirth/dxx-rebirth/commit/8faed77f5f3509c0ef5ba48ef768edf7e03618c9).  Modern D2X does check whether the player is dead, but that commit moved the `reset_rear_view` call to occur before the check, thus allowing the problem you reported.  Prior to that commit, including in older D2X, the check and `return` would skip the `reset_rear_view`.

**Comment by vLKp** [comment]
I believe the above commit will resolve this.  Please reopen if you still see problems.
