### ISSUE TITLE
Build failure: Haiku OS fails due to missing/incorrect flags

### ISSUE THREAD

**Issue by LambdaCalculus37** [dxx-rebirth/dxx-rebirth#641]
#### Operating System Environment

* [X] Haiku

#### CPU environment

* [X] x86 (32-bit Intel/AMD)
* [X] x86\_64 (64-bit Intel/AMD)
* 
### Description

Building in Haiku fails with missing and/or incorrect flags. Specifically, per a forum thread on the Haiku forums (https://discuss.haiku-os.org/t/building-dxx-rebirth-in-haiku/10801/11), the two flags needed to compile the dxx-rebirth source under Haiku are -lpthread instead of -pthread, and -lnetwork added to ensure network code compilation.

### Steps to Reproduce

* Downloaded git repo from this project page
* All prerequisites installed
* Ensured Python 3.7 available
* Launched 'scons' as directed by documentation

**Comment by vLKp** [comment]
I don't think changing `-pthread` to `-lpthread` is necessarily correct.  According to the gcc documentation, `-pthread` will:
```
     Define additional macros required for using the POSIX threads
     library.  You should use this option consistently for both
     compilation and linking.  This option is supported on GNU/Linux
     targets, most other Unix derivatives, and also on x86 Cygwin and
     MinGW targets.
```
I would expect that Haiku g++ should accept `-pthread` and perform Haiku-appropriate thread setup.  If Haiku needs nothing for extra thread support (such as if Haiku always enables all thread support automatically), then `-pthread` ought to be accepted and be a no-op.  If Haiku needs special preprocessor macros for thread support, then `-pthread` ought to be defined and should set those.  In the latter case, replacing it with `-lpthread` would be incorrect, as `-lpthread` would only link thread libraries, but not enable thread-related preprocessor macros.  Does Rebirth work correctly on Haiku if neither `-pthread` nor `-lpthread` are used?  If so, I would be inclined to define a path that uses neither of them.

---

Regarding `-lnetwork`: it's unfortunate that Haiku doesn't provide that in the C library, but adding that by default in SCons is fairly straightforward.

**Comment by vLKp** [comment]
The above commit implements the rule about using `network` in the `LIBS` list.  Original reporter never responded with regard to the `-pthread` versus `-lpthread` issue, so for now Haiku will pass neither.  Please report if you still see problems building for Haiku.

**Comment by LambdaCalculus37** [comment]
Apologies that I haven't responded right away.

Regarding compiling Rebirth under Haiku without using either `-pthread` or `-lpthread`, I have not tried this out since this post. However, I have cloned the repo since commit d84de58 was made, and building now gives a different error with `similar/main/net_udp.cpp` which you can see in this post I made on the Haiku forum: [Haiku compile error](https://discuss.haiku-os.org/t/building-dxx-rebirth-in-haiku/10801/15?u=lambdacalculus)

**Comment by vLKp** [comment]
As an aside, I would have written my earlier commit much sooner, but I was hoping to get an answer to my question about `-pthread`.  Eventually, I decided that I would not get an answer, and that I should just fix the known problems.

---

When posting error messages, it is better to post them as text than as a screenshot.  Similarly, it is better to report the problem here if you want it fixed here, rather than posting it on the Haiku forum and linking to it here.

I see in your screenshot there that your platform has a non-required member `sin_len`, which triggers a warning because it is not set.  No such member exists on Linux or Windows.  It appears to be an obsolete feature of early BSD-based systems.  The easy fix would be to modify the definition to include something like:

```c++
#ifdef SOCKADDR_IN_HAS_SIN_LEN
  .sin_len = 0,
#endif
```

However, the difficult part is in determining what preprocessor symbol to test.  It must be defined on Haiku and any other systems with this member.  It must be undefined on Linux and Windows, which lack the member.  What preprocessor symbols does Haiku set in this area?  I would prefer not to have a hardcoded rule that assumes Haiku always has this member and everything else always lacks it.  However, I can do that if there are no better alternatives.
