### ISSUE TITLE
Build failure: "offset never less than length" with LTO

### ISSUE THREAD

**Issue by heftig** [dxx-rebirth/dxx-rebirth#642]
### Environment

Git 0a5ecd77c60178bf6902cf17c606820887ad11bf

#### Operating System Environment

* [x] Arch Linux, up-to-date

#### CPU environment

* [x] x86\_64 (64-bit Intel/AMD)

### Description

LTO build fails to link `d2x-rebirth`:
```
In function ‘unchecked_partial_range_advance’,
    inlined from ‘unchecked_partial_range’ at common/include/partial_range.h:371:88,
    inlined from ‘partial_range’ at common/include/partial_range.h:473:48,
    inlined from ‘partial_range’ at common/include/partial_range.h:489:88,
    inlined from ‘partial_const_range’ at common/include/partial_range.h:512:78,
    inlined from ‘piggy_find_bitmap’ at similar/main/piggy.cpp:404:2:
common/include/partial_range.h:319:9: error: call to ‘partial_range_is_always_empty’ declared with attribute error: offset never less than length
  319 |         DXX_ALWAYS_ERROR_FUNCTION(partial_range_is_always_empty, "offset never less than length");
      |         ^
```

#### Regression status

This seems to have broken when Arch upgraded from GCC 11 to GCC 12. My last successful build was 163a6222c with GCC 11, but that no longer builds.

### Steps to Reproduce

- The `scons` command executed: `scons -j16 lto=16 sdl2=True verbosebuild=1`
- All output from `scons`: [scons.log](https://github.com/dxx-rebirth/dxx-rebirth/files/8872729/scons.log)
- If `dxxsconf.h` is generated, attach it: [dxxsconf.h](https://github.com/dxx-rebirth/dxx-rebirth/files/8872748/dxxsconf.h.txt)

**Comment by vLKp** [comment]
gcc-12 seems to have some problems in this area.  It claims that the offset of 0 is never less than a variable length that itself is unsigned and therefore never less than 0.  (Offset=0, length=0 is valid and does not provoke a warning.)  Since the offset is always 0, and the length is always at least 0, it cannot be the case that "offset never less than length."  I do not see how gcc can claim this to be true, particularly since `Num_aliases` is a global and therefore proving any value range for it is difficult.

I expect if you continue on you will also get a spurious report about `std::sort` from the render code, where gcc warns that a gcc header exceeds array bounds.

```
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/bits/stl_algo.h:1849:28: error: array subscript 16 is outside array bounds of 'dcx::{anonymous}::sort_child_array_t [1]' {aka 'dcx::enumerated_array<dcx::sidenum_t, 6, dcx::sidenum_t> [1]'} [-Werror=array-bounds]
```

**Comment by heftig** [comment]
I think the D2 build never calls `bm_read_alias` because it never calls `gamedata_read_tbl`. So all that dead code gets eliminated and with LTO the compiler can prove `Num_aliases` is never modified and thus always zero.

**Comment by vLKp** [comment]
I was slightly incorrect above.  Offset=0, length=0 is weakly valid.  It is legal at runtime and will not throw an exception.  However, if it is proved to occur, it triggers the shown failure, because if the range is always empty, then it is useless.

You are partially correct.  Descent 2 _without editor features_ never calls `gamedata_read_tbl`.  When editor features are enabled, then Descent 2 uses `gamedata_read_tbl`.  This failure can be fixed by changing the preprocessor guards not to define or use `Num_aliases` in builds where `gamedata_read_tbl` is never used.

The above commit implements that change.  This fixes the failure for me when building with gcc-12 and LTO.  Please sync and try it out.  Reopen if you still see this failure.
