### ISSUE TITLE
[Feature Request] Pitch Speed Equal to Yaw Speed Option

### ISSUE THREAD

**Issue by narzepatel** [dxx-rebirth/dxx-rebirth#650]
Similar but separate to the option of uncapped turning, I'm requesting an option to have the pitching speed be the same as the yaw speed. To clarify, this is not a sensitivity issue. With uncapped turning disabled, the pitch speed is clearly not as fast as the yaw speed.

**Comment by vLKp** [comment]
When ship performance is capped, the cap for pitch speed is half the cap for yaw and roll.  This is implemented at the bottom of `kconfig_end_loop`:

https://github.com/dxx-rebirth/dxx-rebirth/blob/1c8ff1ac0f137aef68a50611c6714cd1cdf0a043/similar/main/kconfig.cpp#L1396-L1401

Removing the `/ 2` divisor would allow pitch to equal yaw.

**Comment by narzepatel** [comment]
oh there it is, was searching for it but didnt think to check kconfig, thanks

**Comment by vLKp** [comment]
I am undecided as to whether to require a custom build for this, so I will leave the issue open for now.  If there are other users who would like to see this feature included, I encourage them to leave a thumbs-up emoji response to the initial comment, so that I can gauge community interest.  Adding a build time flag to support this would be pretty easy.  Adding a user-configurable toggle would be a bit more work.

Given the release frequency of the project, one might say that putting anything into the next release is out of the question, since the date of the next release is presently indeterminate. ;)

**Comment by vLKp** [comment]
Another user proposed an implementation for this in #657, which I merged.  It includes an in-game tunable to allow the player to activate/deactivate the new rule.  Please reopen if this feature does not satisfy your goal.
