### ISSUE TITLE
Runtime crash: Crash when raising resolution above desktop resolution.

### ISSUE THREAD

**Issue by BryanFRitt** [dxx-rebirth/dxx-rebirth#671]
Linux
Debian Stable, Debian GNU/Linux 11 (bullseye)
KDE desktop with Compiz

d2x-rebirth crashes if resolution is raised higher than the desktop resolution, even if the display, etc.. is capable of handling it.
e.g. if on a 3840x2160 display, d2x-rebirth is set to 3200x1800, and the desktop is also at that 3200x1800 resolution when d2x-rebirth starts, and then d2x-rebirth is later set to 3840x2160, d2x-rebirth will crash.

Crash Error Message:

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x7bc
  Serial number of failed request:  209
  Current serial number in output stream:  211
DXX-Rebirth: OpenGL: fence sync object was never destroyed!

(didn't test with d1x-rebirth)

**Comment by BryanFRitt** [comment]
For these dxx-rebirth resolution changes I was doing them in full screen mode.

set desktop dxx-rebirth's and desktop resolution to a lower resolution than the display/system is capable of, exit and restart dxx-rebirth, then in full screen mode, change the dxx-rebirth resolution to a higher resolution than these that the system/display is capable of.

> Rebirth might be able to detect that you have requested something impossible and prevent it,

I'm not changing the full screen resolution to anything the system/display can't handle. I've had and can do desktops and 3d games at these resolutions before on this setup without any issues. Would the bug be it thinking the the maximum full screen a game could go should be limited to whatever the desktop is set to, even if the system/display could handle more?

> Note that an X error of BadValue is an X library issue, not a Rebirth issue.

Ok, If so, where should the issue be forwarded to? url?

**Comment by vLKp** [comment]
Confirmed.

- Use xrandr to set a low resolution.
- Start the game in that resolution.
- Tell the game to switch to a resolution that the monitor can handle, but which is higher than the current resolution.
- Xlib raises BadValue and kills the program.  No backtrace is available, because the program did not crash.  Xlib deliberately killed it.

More debugging will be required.  Given SDL's automatic and forced grab when in full screen mode, this will be somewhat tedious, so it may need to wait a few days.  That grab is one of the reasons that I prefer and recommend people use a full desktop dimension window, rather than run in full screen mode.  In SDL1, full screen always grabs.  A desktop-sized window can choose whether to grab, and can automatically drop the grab when a menu is open.

**Comment by vLKp** [comment]
I am now satisfied that this is not a bug in Rebirth.  To demonstrate:

1. Compile the below program with `g++ -O2 sdl.cpp -lSDL -o sdl-modeset`
2. Set your screen resolution to 1920x1080.
3. Run the program.  Observe successful output:

```
Checking video mode ...
SDL_VideoModeOK=32
Changing video mode ...
SDL_SetVideoMode returned 0x5555555a6cb0
```

4. Set your screen resolution to 800x600.
5. Run the program again.
6. Desired results: your screen changes to 1024x768 again.  Observed results on my system: program terminates with an error:

```
Checking video mode ...
SDL_VideoModeOK=32
Changing video mode ...
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x6bc
  Serial number of failed request:  128
  Current serial number in output stream:  130
```

In my opinion, if SDL were behaving properly, it would return a failure status from `SDL_SetVideoMode`, which could then be observed and handled.  Instead, it invokes Xlib in a way that leads to the program's termination.  None of the comments I see in `SDL_video.h` lead me to believe that `SDL_SetVideoMode` can terminate the program like this.  If you have a reference that states that the program is obligated to perform specific checks before hand, please link to it and I will investigate whether it will enable Rebirth to survive this configuration.  I explored whether `SDL_VideoModeOK` could serve this purpose, but since it returns the same value in both the good and bad cases, it does not appear to be useful here.

Demo program source:
```c++
#include <SDL/SDL.h>
#include <SDL/SDL_video.h>
#include <stdio.h>

int main(int argc, char **argv)
{
	const int width = 1024;
	const int height = 768;
	const int bpp = 32;
	const Uint32 flags = SDL_OPENGL | SDL_FULLSCREEN;
	SDL_Init(SDL_INIT_VIDEO);
	printf("Checking video mode ...\n");
	fflush(stdout);
	int ok = SDL_VideoModeOK(width, height, bpp, flags);
	printf("SDL_VideoModeOK=%i\nChanging video mode ...\n", ok);
	fflush(stdout);
	SDL_Surface *s = SDL_SetVideoMode(width, height, bpp, flags);
	printf("SDL_SetVideoMode returned %p\n", s);
	return 0;
}
```

I also experimented (not shown) with changing the resolution without setting fullscreen, then adding fullscreen later.  The first call, which changed the resolution without going to full screen mode, succeeded.  The second call, which added the full screen flag, still caused Xlib to terminate the program.

---

I should also note that SDL2 does not offer `SDL_SetVideoMode`, and therefore cannot exhibit this failure mode.  Window management is done differently in SDL2.

**Comment by BryanFRitt** [comment]
Tried something like this with `Supper Tux Kart`, instead of crashing, it simply changed the game to the desktop resolution; It didn't even have an error message saying that it changed to a resolution other than what it was set to go to.

**Comment by vLKp** [comment]
It appears that Super Tux Kart always uses SDL2.  I noted above that SDL2 does not even provide the function which causes the hard exit in this scenario.  Rebirth optionally can use SDL2, if requested at build time.  Does the demo program I posted in https://github.com/dxx-rebirth/dxx-rebirth/issues/671#issuecomment-1287560954 work for you, or abort like Rebirth does?

**Comment by BryanFRitt** [comment]
>  Does the demo program I posted in #671 (comment) work for you, or abort like Rebirth does?

saved the code from https://github.com/dxx-rebirth/dxx-rebirth/issues/671#issuecomment-1287560954 as `sdl.cpp`, then ran `g++ -O2 sdl.cpp -lSDL -o sdl-modeset` and then `./sdl-modeset` for each code run.

Desktop 3840x2160, The first run it changed the resolution, I set the resolution back, but after that, each run just blinked the display very briefly and outputted text. Then tried setting desktop to 800x600, then each run all it did was blink the display briefly and outputted text. [I'll try rebooting, trying again, and updating this post.]

```
Checking video mode ...
SDL_VideoModeOK=32
Changing video mode ...
SDL_SetVideoMode returned 0x560f8ac1f2b0
```
The SDL_SetVideoMod returned always started with a 0x5 and always ended with 2b0, the stuff in-between varied each run.

**Comment by parkerlreed** [comment]
SDL2 is the way forwards anyways. Are there still things keeping DXX from being full time SDL2?

I stopped using SDL1 for the exact reason of poor monitor handling and the fact that it COULD change video modes. 

SDL2 will leave your native desktop resolution and render at whatever you request internally preserving alt tab, monitors blanking out, and your sanity.

**Comment by vLKp** [comment]
https://github.com/dxx-rebirth/dxx-rebirth/issues/474 reported several problems with SDL2.  All but the sound problem were fixed quite a while ago.  @raptor contributed https://github.com/dxx-rebirth/dxx-rebirth/pull/651 to try to fix the sound problem.  However, according to https://github.com/dxx-rebirth/dxx-rebirth/issues/474#issuecomment-1328134869, there are problems with it.  I have not yet had time to fix those.

As I understand https://github.com/dxx-rebirth/dxx-rebirth/issues/671#issuecomment-1301101617, that confirms my prior posts: SDL1 provokes an Xlib problem in these circumstances, even when Rebirth is not used.  Since Rebirth is only telling SDL1 to set the video mode, and is relying on SDL1 to do that or report an error (but not terminate the program), I do not see that there is anything I can do here.  As I invited above, if you have a reference for how I can detect that the requested mode will be fatal, I could look at handling it.  Otherwise, this will need to be treated as an SDL1 bug.
