### ISSUE TITLE
Cockpit option dont show the cockpit

### ISSUE THREAD

**Issue by orderorder** [dxx-rebirth/dxx-rebirth#677]
* [X ] Manjaro Linux

* [X ] x86\_64 (64-bit Intel/AMD)

* Engines affected:
  * [ X] D1X-Rebirth
  * [ X] D2X-Rebirth

* Game modes affected:
  * [X ] Single player

Version "v0.61 0.60.0-beta2-2247-gfc9de5830225" 

compile with:
scons opengl=0 

When I play the game the cockpit view option dont show the cockpit. It resets to fullscreen view without cockpit.

**Comment by AlumiuN** [comment]
What resolution are you running at? If you compile without OpenGL, the software renderer will only display the cockpit at certain resolutions (IIRC, 320x200 in D1, that or 640x400 in D2).

**Comment by orderorder** [comment]
in my case if i try to set 320x200 or 640x400 only accept 640x480. In this resolution dont render de cockpit. But with scons sdl2=1 it renders at higher resolutions

**Comment by vLKp** [comment]
[Fix cockpit switch in SDL-only build](/dxx-rebirth/dxx-rebirth/commit/16c86edabc275b728fd94ff117b9f790594f7b04) should resolve this.  An earlier commit changed the default resolution for new installs to 1024x768, and as an unintended side effect, changed the SDL cockpit test to only enable the high resolution cockpit graphic in 1024x768 mode, even though that looks wrong because the graphic is always drawn as a 640x480 overlay in the top left corner of the screen.

As AlumiuN notes, SDL restricts you to using the cockpit only at resolutions where the graphic would look right.  The OpenGL build can scale the cockpit graphic as needed, and so lets you use the cockpit in any resolution.

Please sync and retest.  If you still see problems, please reopen.
