### ISSUE TITLE
Runtime bug: Extremely distorted and ringy ingame audio.

### ISSUE THREAD

**Issue by KynikossDragonn** [dxx-rebirth/dxx-rebirth#686]
### Environment

GCC 12.2.0
SDL2 2.26.1
SDL2_mixer 2.0.4

Commit df8e99872135c01cda17d7b4c1995cbf953d9f71

```
D1X-Rebirth v0.61 0.60.0-beta2-2327-gdf8e99872135  Dec 26 2022 04:19:11
D2X-Rebirth v0.61 0.60.0-beta2-2327-gdf8e99872135  Dec 26 2022 04:20:26
```

Default CPPFLAGS as provided by the project itself.
`'-Wno-sign-compare'`

Default CXXFLAGS as provided by the project itself.
`'-g', '-O2', '-ftabstop=4', '-Wall', '-Werror=extra', '-Werror=format=2', '-Werror=missing-braces', '-Werror=missing-include-dirs', '-Werror=uninitialized', '-Werror=undef', '-Werror=pointer-arith', '-Werror=cast-qual', '-Werror=missing-declarations', '-Werror=vla', '-pthread', '-funsigned-char'`

#### Operating System Environment

Void Linux (recent system-wide update was ran yesterday)
Linux Kernel 6.0.15

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Both Descent: First Strike and Descent 2: Counterstrike.

### Description

Audio is severely distorted and clipping across both games, worse in Descent 1 as all audio is 11025 Hz only. Descent 2's audio suffers slightly less but is very much clipping and causing distortion when many loud sounds are played at once no matter the volume of them.

This seems to be caused by the new "fixed point resampler" as the old sound handling before then was completely fine if not rather muffled at times. (especially for 11025 Hz sounds being quite muffled)

#### Regression status

Before #651 was pulled into the source tree.

### Steps to Reproduce

Start D1X-ReBirth first as Descent 1 only has 11025 Hz audio. Go into the options and change sound volume to produce the prox bomb sound, or go ingame and fire any weapons ,etc.

Start D2X-ReBirth, repeat same previous steps.

Observed behaviour:
D1X-ReBirth has extremely distorted and ringing audio, the audio is severely clipped as well.
D2X-ReBirth has distorted/clipped audio but not as badly ringing as Descent 1's all 11025 Hz sounds.

Expected behaviour: The sounds shouldn't be extremely distorted and ringing. I very much remember playing Descent on actual Sound Blaster hardware according to that one pull request and it never sounded anything like what's happening here.

* Engines affected:
  * [x] D1X-Rebirth
  * [x] D2X-Rebirth

**Comment by vLKp** [comment]
This was also reported in https://github.com/dxx-rebirth/dxx-rebirth/issues/474#issuecomment-1328134869 by @AlumiuN.  Unfortunately, I have limited ability to debug sound related problems.  I looked at this when it was mentioned there, but found no promising leads.  I will likely need to revert to the old sampler.  I would prefer not to do that, since the new sampler was created specifically to deal with problems in the new SDL2 mixer.

**Comment by KynikossDragonn** [comment]
I'm unfortunately not that great at math or audio engineering myself to figure out what's wrong with the new resampler, Void Linux being a rolling release type distro doesn't make it very feasible for me to roll back the compiler incase it's a weird code generation issue either.

The PipeWire project has a very neatly written custom resampler that's very efficient at it's job, but it may muffle the old 11025 Hz audio too badly if I were to try to test transplanting that to DXX-ReBirth.

**Comment by vLKp** [comment]
The new resampler generates very different output bytes than the old SDL_mixer resampler.  The new code is relatively small and I read through all of it before merging it.  I saw nothing obviously wrong from a standards-conformance perspective.  While it is possible that this is a code generation issue, my expectation is that it is a logic error in the code and that varying compiler versions will not impact the correctness of the generated audio.

I tried running the new resampler under `-fsanitizer=undefined` and found one issue (https://github.com/dxx-rebirth/dxx-rebirth/issues/474#issuecomment-1336265787 : value overflow while computing a summation), which unfortunately had no impact on the generated bytes when I fixed it.  I believe I also ran it under `-fsanitizer=address`, and found nothing.

**Comment by Brunnis** [comment]
I can confirm that the same issue occurs on the Raspberry Pi 4, which I guess is to be expected. The audio effects sound very nasty, unfortunately.

**Comment by ziplantil** [comment]
I believe I started having audio issues after updating SDL2 to 2.26.0. My initial issue was that some sound effects (seemingly at random) had high-pitched distorted sounds at the end of them. (After I presume another SDL2 update, the game crashes due to a double free...)

**Comment by vLKp** [comment]
Based on several reports of audio problems with the new resampler, I intend to push an update that reverts to the old SDL_mixer-based resampler by default.

**Comment by KynikossDragonn** [comment]
That may very well be the only recourse unless the individual who came up with the new resampler was still around to figure out what went wrong with it.

Another idea would be to move the audio away from SDL_mixer and into OpenALSoft which has a bunch of different resamplers but this is not a very straightforward thing to switch into.

**Comment by pachuco** [comment]
![indecent_descent](https://user-images.githubusercontent.com/1591054/211166303-ed5274b8-959a-4ab1-a0ff-6cbfd03efdd9.png)

Looking mighty jank here.

**Comment by vLKp** [comment]
I am not familiar with that tool, and its labels are not sufficient to explain what it shows.  What are you trying to tell us?

**Comment by vLKp** [comment]
When you test this, are you using @raptor's original code from #651, or are you using HEAD?  I made some changes to @raptor's code around the time I merged it.  I checked that those changes had no effect on the generated output for a few sounds, and that the game sounded the same to me.  Therefore, I hope that I did not break the code that @raptor submitted.  However, I still have the sense that I am simply not hearing some of the undesirable changes.  The ringing is very noticeable to me (but not at all to one of my playtesters).  The "clipped" sounds reported in #474 are either very subtle, or I can't hear the distinction between good and bad for that.  @AlumiuN is astonished I do not notice that distinction ( https://github.com/dxx-rebirth/dxx-rebirth/issues/474#issuecomment-1368542994 ).

If we are fortunate, then I broke @raptor's working code and a simple bisect through my amendments will find where I broke it.  If @raptor's code had these artifacts at submission time, fixing this will be harder.  Just now, I went back to 5165efbc46b9f31a4f36b935322387e86955894a (the original submission) and tested it in Descent 1, and I hear the ringing artifact there, which is unfortunate.

---

As I understand the custom sampler, its conversion process is:

- `convert_audio` calls `upsample`, which will take the input unsigned 8-bit sound, and produce as output a 16-bit signed sound, with `factor` 0-valued shorts of padding between each the output values.  `factor` appears to be computed as the output frequency divided by the input frequency.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L301

- `convert_audio` passes the result of `upsample` to `filter_fir` to "Apply LPF filter to smooth out upscaled points".  `filter_fir` picks a slice of the input buffer, and accumulates a series of `product` values, where each `product` is the chosen value multiplied by a coefficient from one of `coeffs_quarterband` or `coeffs_halfband`, depending on whether the source is 11Khz or 22Khz.  After the series is accumulated, it is downshifted, truncated, and saved into `output[nn]`.
- `convert_audio` passes the result of `filter_fir` to `replicateChannel`, which appears to be a straight duplication function.  Each sample in the input is written to `chFactor` consecutive elements in the output buffer.

The result of that step is then considered the final sound.

---

I'm happy to try to explain this new sampler's logic in more detail, if you think that would help you determine where these undesirable upper frequency values are being generated.  Alternatively, if you can explain to me how to programmatically recognize these upper frequencies, I can step through the algorithm to try to find them.  I can dump the raw bytes of the generated sound, but presently I do not know how to recognize which bytes represent good frequencies versus bad ones.

**Comment by KynikossDragonn** [comment]
I opened my issue originally with HEAD, I haven't actually tried compiling the original pull request, I assume that should be simple enough for me to do? (do I just clone the repo the pull request came from?)

**Comment by vLKp** [comment]
Since that pull request is now part of the history of Rebirth, it should suffice to `cd` into your existing clone of `dxx-rebirth.git`, then `git checkout 5165efbc46b9f31a4f36b935322387e86955894a` to switch your checked out files to that commit.  Then, run `scons` with your favorite options.  When done, `git checkout master` to return to your regular `master` branch.

**Comment by KynikossDragonn** [comment]
Oh that's incredibly convenient, I'll check this out later tonight. (Or tomorrow depending how things go tonight)

**Comment by gamefreq0** [comment]
I've just compiled and run against the commit that merged the PR, and it's present in that version; I then went and tested by further building against the commit prior to the merge, and it's present in that version as well, so it doesn't seem the PR is causing the issue.

**Comment by KynikossDragonn** [comment]
So, I asked around on a forum I regular on and I'll copy over what was told to me:
https://forum.zdoom.org/viewtopic.php?p=1234989#p1234989

> Given the ringing peak being around 11khz (near the nyquist frequency of 22khz, that does make me think of some kind of aliasing problem. Seeing comments in the code like
> 
> ```
> // Coefficient set for half-band (e.g. 22050 -> 44100)
> ...
> // We expect a 4x upscaling 11025 -> 44100
> ...
> int upFactor = out_freq / freq; // Should be integer, 2 or 4
> ```
> 
> my first thought is... is that true? Your recording is 48khz, not 44100, and while it doesn't necessarily mean that's a problem (that may well do 11khz->44khz as designed, with an separate resample pass to do 44khz->48khz for system output), I'd still check those values to make sure they're as expected.
> 
> Another possible culprit is the filter_fir function doesn't seem to have any protection against overflow. Given 16-bit signed samples, and the filter peaks at 32767 or 65535 depending on the filter, a convolution could potentially overflow the signed 32-bit accumulator.
> 
> Also, the upscaling factor looks like it's handled wrong:
> 
> `int upFactor = out_freq / freq;`
> 
> Results in upFactor=1 if there's no upscaling (e.g. 44khz->44khz), 2 if it's upscaling 2x (22->44), 4 if it's upscaling 4x (11->44), etc. Yet later on in convert_audio, it's simply checked for being non-0:
> 
> `auto &coeffs = upFactor ? coeffs_halfband : coeffs_quarterband;`
> 
> The code would fail elsewhere if it was actually 0 (it would be trying to downscale 22khz->0hz or 11->0 or something), making it seem like an incorrect check, resulting in the wrong coefficients being used for one of the expected upscaling factors.

For context, my audio recording is 48000 because PipeWire is running at 48000 so all audio going in and out, is always going to be 48000. I know PipeWire's resampling isn't causing this problem because I can listen to straight up 11025 audio just fine in any media player with PipeWire doing it's usual internal resampling.

**Comment by pachuco** [comment]
> I am not familiar with that tool, and its labels are not sufficient to explain what it shows. What are you trying to tell us?

Sorry. I think I can put it this way.

Sounds like a triangle wave at 11khz rate that is bouncing between sample's amplitude and 0.
Double that(nyquist) and it's 22khz.

But final audio is playing at 48khz!(KynikossDragonn recording)

**Comment by KynikossDragonn** [comment]
The final audio in my recording is because PipeWire is running at 48000:
![Screenshot_2023-01-08_10-37-46](https://user-images.githubusercontent.com/8813106/211208308-b0c08a3c-8cc1-4b0e-8d19-cc3ba49d5e1f.png)

The audio in DXX-ReBirth is still 44100 so whatevers going wrong isn't PipeWire's fault, because I don't get distortions in any other program, and I never gotten distortion with very old versions of DXX-ReBirth.

For the record, this is a recording of playing back a 8000hz sound in Audacious, letting PipeWire resample the audio:
![Screenshot_2023-01-08_10-43-45](https://user-images.githubusercontent.com/8813106/211208547-d6ceafbe-26ef-48c8-b9b0-a4e832f86763.png)
![Screenshot_2023-01-08_10-46-18](https://user-images.githubusercontent.com/8813106/211208629-e8d069ac-133c-49d9-a65a-45e589963f66.png)


Notice how the resampling PipeWire is doing is not causing any artefacts.

**Comment by vLKp** [comment]
> > Another possible culprit is the filter_fir function doesn't seem to have any protection against overflow. 

There was an overflow in one of the samples according to `-fsanitize=undefined`.  I fixed that logic in a yet-unpublished commit, but it didn't help with any of the problems I could observe.  If I recall correctly, both the fixed and bad versions of that logic ultimately produced the same output for the sounds I tested it on, despite the overflow.

> > Yet later on in convert_audio, it's simply checked for being non-0:

Agreed, now that this has been pointed out, I too think it looks wrong.  I should have caught that in a code review.  I think I missed it because the computation was in one function and the offending use in another, and I wasn't specifically looking for logic bugs like that.  The originally submitted code (before I converted it to a ternary) reads:

https://github.com/dxx-rebirth/dxx-rebirth/blob/5165efbc46b9f31a4f36b935322387e86955894a/similar/arch/sdl/digi_mixer.cpp#L260

Now that my attention has been drawn to this line, I wonder if the oddity of a trailing space is an artifact of a missing test, rather than just a code style choice.

---

I hear the ringing (but not the "clipped" panel destruction) even when using straight ALSA, with the game not using PulseAudio/Pipewire, so I agree the extra transform from 44Khz->48Khz cannot be responsible for that.

---

> Speculation: maybe mixer borks when output/input rate ratio is not integer?

Maybe, but due to game limitations, that is not a concern here.  The input rate is always either 11Khz or 22Khz.  The output rate is always 44Khz.  The 48Khz in the recording from @KynikossDragonn was due to Pipewire resampling the game's 44Khz output up to 48Khz.  I wonder if the sound might be better if Rebirth could pass the bare 11Khz to Pipewire and let Pipewire resample that up directly from 11Khz to 48Khz, rather than letting the game resample to 44Khz, then asking Pipewire to resample that in turn up to 48Khz.  However, even if the double resample is causing worse sound than a single pass, the Rebirth pass is clearly wrong on its own.

**Comment by KynikossDragonn** [comment]
A interesting idea but you'd have to spawn two output streams, one for the ingame audio, the other for the jukebox. It'd be rather inefficient, but Shockolate actually spawns two clients because the way it uses FluidSynth makes it start another audio client in addition to the one handling the sound effects.

I think it'd be worth a test to see what will even happen if we remove the custom resampler, have SDL2_mixer output out in 11025 Hz under D1X-ReBirth and just see what'll result when that hits PipeWire. It should be exactly like what happened in my screenshot playing low sampled audio through Audacious, it shouldn't "ring modulate" or distort.

**Comment by vLKp** [comment]
I am not aware of a way to make SDL_mixer run separate streams with different sample rates.  If that were supported, I would prefer to use that over resampling in the Rebirth code.

Removing the custom resampler is not trivial since SDL_mixer is presently told to expect that the blobs passed to it are 44Khz sound files.  If the game's sounds are not resampled, either internally or via SDL_ConvertAudio, then SDL_mixer would almost certainly do the wrong thing, by treating the 22Khz sound as if it were 44Khz.  As far as I know, there is no way on a per-sound basis to report the frequency.  SDL_mixer simply assumes that all sound passed to it is the frequency specified when SDL_mixer was initialized.  I believe I have seen claims that a related error is responsible for the Descent 1 Class 1 Driller ("Vulcan Driller") using a very shrill screech activation in Descent 2.

---

Switching to the correct coefficient table for 11Khz resolved the ringing sound.  I appreciate the commentary calling my attention to that.

As a related point, I put the old SDL_mixer-based resampling code back into the source, gated behind a preprocessor define.  The default is to build with DXX_FEATURE_INTERNAL_RESAMPLER=1, which uses the resampler under discussion here.  If built with DXX_FEATURE_INTERNAL_RESAMPLER=0 (via adding CPPFLAGS `-DDXX_FEATURE_INTERNAL_RESAMPLER=0` or changing the `#define` in `similar/arch/sdl/digi_mixer.cpp`, around line 52), then the old logic that delegates to SDL_mixer will be used.

You might get interesting results if you disable the use of SDL_mixer entirely, with the command line option `-nosdlmixer`.  This will bypass all the resampling code.

**Comment by vLKp** [comment]
I believe the ringing problem is now resolved.  So far I have not noticed obvious audio distortion problems.  For those who do encounter that, it would be interesting to know if `-nosdlmixer` fixes it.

**Comment by KynikossDragonn** [comment]
The issue seems completely fixed in D1X-ReBirth but not in D2X-ReBirth:
![Screenshot_2023-01-10_21-55-40](https://user-images.githubusercontent.com/8813106/211714350-ded31c73-677d-4569-9c18-b1e2a9bb17c1.png)

[d2xdistorted.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/10388763/d2xdistorted.zip)


Not all sounds seem to be messed up though. Now, I know the way Descent 2 did sounds is slightly goofy. You have a S11 file and S22 file but are some of the sounds in the S22 file just the S11 sounds upsampled via nearest neighbor/zero-order hold resampling? That MIGHT be causing the problem with some of these sounds when they go through the custom resampler.

**Comment by AlumiuN** [comment]
[I believe this is the distortion I referred to here](https://github.com/dxx-rebirth/dxx-rebirth/issues/474#issuecomment-1328140563) - unfortunately I don't have the experience (or energy to make up for a lack of experience, at the moment) to determine why this is the case.

**Comment by Brunnis** [comment]
Built and tested commit 9fd0cc96a58b5d5dc92e91ae375d0e9b025b4f17 on my Raspberry Pi 4 running Raspberry Pi Os 64-bit. Only tested Descent 1. While the distorted audio seems to be fixed, the sound effects volume is now so low that to balance out the music and sound effects, the music slider needs to be pulled down to the very lowest level. Then, obviously, the speaker volume needs to be cranked in order to get a descent overall audio volume. Setting the audio effects and music to the same level leads to the sound effects being barely audible over the music.

**Comment by vLKp** [comment]
[Add alternative mixer resamplers](/dxx-rebirth/dxx-rebirth/commit/56d181448903a164bab8aa16467054a034f7b126) switches the game back to the native SDL mixing by default, with an option to use the SoundBlaster16 emulation that caused a problem here.  For SDL2 users, it also offers a way to emulate SDL1's mixing rule.  I hope that using the native SDL mixing will solve this problem.

**Comment by vLKp** [comment]
Per the above comment, I think that the default of using SDL-native, with a user choice of fallback to SDL1-style or the SoundBlaster16 emulation, will fix this by default.  I have not been able to resolve the reported problem with the SoundBlaster16 emulation, so it is not enabled by default for end users.  This should keep unsuspecting users from encountering the problem.  Therefore, I am closing this issue.  If anyone wants to revisit the SoundBlaster16 emulation code to try to resolve the reported distortion with it, please file a pull request with the proposed changes.
