### ISSUE TITLE
Robot homers don't track while host is dead

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#69]
Title pretty much says it all.

You can test on level 27 of D1 First Strike. If you allow the host to die, then enter the first room with one of the clients, the homers from the Red Hulk won't track you.

**Comment by vLKp** [comment]
Has this ever worked correctly?

**Comment by Mako88** [comment]
I'm not sure honestly. I don't have a dosbox setup to test either.

**Comment by zicodxx** [comment]
I do have DOSBox set up but I never got a game to run back then. However I traced this back to the very beginnings of Rebirth - before we had version control and it was broken back then, too if I recall correctly. I looked for this bug a long time ago but I could never find the source of it.

**Comment by vLKp** [comment]
This is an FVI problem.  When the host is dead, the missile looks right through the guest, sees a wall, and declares that there is a wall in its path.  Since robot homing weapons never set `track_goal`, they fly straight whenever FVI says there is a wall between the missile and every possible target.

**Comment by zicodxx** [comment]
This makes sense, especially if their projectiles miss track_goal. I'll check this out. But shouldn't the missiles work at least if the robot is controlled by a client itself? And if a player (host in this case) dies, the robots controlled by that player should be released so they can be controlled by other players.

**Comment by vLKp** [comment]
The missiles are not controlled by any particular player.  Every system steers them independently, and they happen to get the same result because they mostly have the same starting inputs.  I seem to recall some coop games where very lucky dodges resulted in two players each insisting that the missile hit the other guy, and a couple of games where very unlucky dodges resulted in two players each insisting that the same missile chased them.

Every frame where the missile may turn, each system independently plots potential targets and chooses the best target to chase based on distance, dot product, visibility, and various other eligibility factors (cloaking, ancestry, object type).  When this bug is active, the object visibility check fails, so the missile reverts to flying straight.  You can see this by enabling `FQ_SEGLIST` on the `object_to_object_visibility` call and printing the segment list after it returns.  I do not see any FVI code that should care whether the host is alive, but my results were that when the host is dead, the missile FVI examines segments behind the living player, then returns `HIT_WALL`.

**Comment by zicodxx** [comment]
Yeah, that was a bad wording. I know the missiles are controlled locally for every player. But the robots that fire the missiles aren't. I can see that if their missiles do not contain a track_goal, tracking on remote players may go wrong, but the local tracking should always work as for the specific client, controlling the robot, the homing tracking should work as if in Singleplayer. I wonder if the FVI code somewhere uses Player[0] instead of ConsoleObject... well, at least I got a few points to look for now.

**Comment by zicodxx** [comment]
Okay, I pushed cbaac9632459e36e951cb89e4d7d1a5d607ff2d1 that fixes the problem. As established in track_track_goal (going back to the original source), they do seem to hook on an object even if it's OBJ_GHOST, making it impossible to identify any other target that if NO OBJ_GHOST. I added a check to revert this to OBJ_PLAYER if this is the case.

However this doesn't fix the root of the problem and I added this in a comment with my "fix" (which is probably more of a hack). Creating the missile I think should rather check for OBJ_GHOST and prevent doing so. But since the tracking code is so convoluted and this only affects the bot tracking, I added the fix in track_track_goal, in the condition that handles robot tracking. I seriously hesitate to go to do that anywhere else as I do not want to break more than I aim to fix. But I guess it should be done proper at some point.

**Comment by vLKp** [comment]
@zicodxx hacked around this in [Fixed (hacked) homing missiles fired by bots that would not track players if player with lowest objnum is dead](/dxx-rebirth/dxx-rebirth/commit/cbaac9632459e36e951cb89e4d7d1a5d607ff2d1).  For ticket #274, I pushed [Initialize track_goal for homing weapons](/dxx-rebirth/dxx-rebirth/commit/bf662e0bcc3302ccaf7b07db55958bbaeaec2582) which fixed the problem properly.

Closing.
