### ISSUE TITLE
Build failure: sizeof(callsign_t) doesn't necessarily equals to CALLSIGN_LEN+1

### ISSUE THREAD

**Issue by mikrosk** [dxx-rebirth/dxx-rebirth#695]
Believe or not but on my (big endian) g++ 7.5.0 sizeof(callsign_t) equals to 10 and not 9 (=CALLSIGN_LEN+1). And indeed, the standard doesn't forbid it: https://stackoverflow.com/a/25173547/21009.

It's easy to change the `#define` however it causes more serious trouble in `struct player_rw` which is, I presume, used for serialization or network transfer as the its assert requires hardcoded size of 116 (and I get 117...).

**Comment by vLKp** [comment]
gcc below gcc-10 is not supported on current `master`.  When reporting a build failure, please attach the build log showing the failure.

---

Yes, structures can in some cases contain padding.  I added static asserts about structure sizes specifically because so much of the legacy code assumes no padding, so these asserts catch the problem at build time instead of manifesting in weird bugs at runtime when the game reads the wrong number of bytes from the file.

**Comment by mikrosk** [comment]
So what would you suggest in this case? `static_assert` worked as expected (and I'm grateful for that) but I wasn't sure how to fix it. When "real" sizeof() is 8, the actual sizeof() is 8. When "real" sizeof() is 9, the actual sizeof() is 10, so it seems there's some align process in the works (and yes, I tried to use `__pack__`, no difference).

About the gcc version, yes, that's another pain. I had to revert back to commit 1bcc5c40 because on my platform gcc7 is the most stable/proven compiler.

Let me be clear - if this kind of build failure reports annoy you (because you are not seeing them in normal environment), I understand. My original aim was to use dxx-rebirth as an experiment on a low end platform but from I have seen, the code is long gone from the 8bpp rendering anyway and full of modern C++ constructs.

If you see value in fixing stuff like this (another tip: try to compile dxx-rebirth with `opengl=0` on a platform _without opengl at all`, you'll see quite a lot of build failures because the project basically expects OpenGL always installed), I'm happy to help, otherwise feel free to close both my issues and I wont bother you with similar reports.

**Comment by vLKp** [comment]
I suggest updating to a currently supported compiler.  I doubt gcc-7 will get any interest from the upstream gcc developers at this point, so if you encounter any compiler bugs, you will be on your own.  I am surprised any current generation platform is stuck with such an old gcc.  I only moved the minimum up to gcc-10 because even Debian stable had access to that, and Debian is well known for being slow to update.

---

You could try finding all the sites that use `sizeof(callsign_t)` (including those that take `sizeof(x)` where `x` is defined as `callsign_t`) and changing them to depend directly on the expected size.  From what I recall, when a size is wrong like this, the typical manifestation is that the file reader consumes too many or too few bytes from the underlying stream, so the next record is loaded from the wrong offset.  This typically manifests as garbage values loaded into all fields that follow the incorrectly sized object.  If you are lucky, there are few or no places like this.  Changing `callsign_t` to inherit `prohibit_void_ptr` might help find these sites, but I do not know if that will automatically find them all.

---

I do not mind failure reports for unusual environments, but I would appreciate if they came with enough information I could attempt to debug them.

---

`opengl=0` is meant to disable use of the GL renderer.  In theory, it would be nice if it worked on a system with no GL headers, but in practice, I don't have a good way to test that without completely breaking my ability to test the GL-enabled builds.  I can make changes as needed when people report that the no-GL build is depending on GL headers, but I do not care to set up a parallel no-GL-development-headers environment for that purpose.

**Comment by mikrosk** [comment]
> any current generation platform is stuck with such an old gcc

It's not any current generation at all. ;) It's a 30 years old hardware.

>  the typical manifestation is that the file reader consumes too many or too few bytes from the underlying stream, so the next record is loaded from the wrong offset

Yes, this is exactly what I'm fearing that will happen in `struct player_rw`: the static assert insists on having the struct size == 116 but thanks to its `callsign_t callsign` member it is 117. In this concrete situation I think the only real solution is to (somehow) make the callsign_t again `CALLSIGN_LEN + 1` big? I could came up with only a really lame workaround, I made CALLSIGN_LEN = 7 (instead of 8) and put a `char` padding after the `callsign` member. However this leads to a cascade effect of some code complaining that it requires one more character (i.e. "[TARGET]") so I had to cut it to "[TRGET]" (as I sait, a really lame one...).

**Comment by vLKp** [comment]
You could try implementing `callsign_t` with a C-style array of the right type and dimensions.  The existing implementation has quite a few spots that assume that the inner storage is a `std::array` though.

I would be interested to know why your compiler is using extra padding here.  It may not be specifically prohibited by the standard, but it is a strange behavior to pad after an array of `char`, and seems like it causes more problems than it solves.  I would also like to know whether the same padding is used on a more recent gcc for that platform.

**Comment by mikrosk** [comment]
As discussed in the linked issues, this is tied to `STRUCTURE_SIZE_BOUNDARY` setting in gcc which most platforms have set to 8 (1-byte = no padding) while some platforms have this set to 16 (2-byte padding).

Strictly speaking, having struct sizes aligned to two bytes doesn't break any C/C++ standard but I can understand if troubles with fixing this issue outweigh the benefits (which is basically just one: 100% compatibility and cleanness of C++ code).

So feel free to close if desired.

**Comment by th-otto** [comment]
> You could try implementing `callsign_t` with a C-style array of the right type and dimensions. The existing implementation has quite a few spots that assume that the inner storage is a `std::array` though.

That doesn't help, since the array is still part of the struct callsign_t

> I would be interested to know why your compiler is using extra padding here.

See the linked issue. The compiler was configured with ``STRUCTURE_SIZE_BOUNDARY = 16`` , which makes any structure a multiple of 2 bytes. This also affect recent gccs up to version 13.2. This may be a bit uncommon, 

But may i ask why this assertions to a specific byte size of the structure are in place? The structures in question are not compatible between different machines anyway, because of endian differences. So for structures where it matters, there are already existing functions like state_player_to_player_rw in similar/main/state.cpp that copy to/from the internal and external representation, and player_rw_swap that convert endianness. Those could just be rewritten so read/write from byte arrays instead, which should solve such issues.



It may not be specifically prohibited by the standard, but it is a strange behavior to pad after an array of `char`, and seems like it causes more problems than it solves. I would also like to know whether the same padding is used on a more recent gcc for that platform.

**Comment by vLKp** [comment]
Although big-endian vs little-endian is a concern, there are multiple platforms that use little-endian (and also likely multiple platforms that use big-endian).  Compatibility within an endianness is a concern.  More importantly, for historical reasons, the game has many places where the original authors used a `struct` as a way of laying out data that would be written to a file.  They got away with it because as released, the game ran on DOS and on 90s era Mac, but nowhere else.  (Descent 2 had a Windows95 version too, but I suspect foresaw running it on anywhere near the variety that exists today.)  I am not sure whether they even considered it useful to have DOS and Mac files be exchangeable, but I suspect not, since the demo format is written in host-endian, and demos seem like the most likely place to care about compatibility.

Yes, rewriting every access not to rely on structure layout when doing file I/O is the right solution.  I've done that in some places.  In others, I settled for a static assertion to prevent unknowingly breaking anything.  If I recall correctly, as released, the game would have happily let you build with `callsign_t` enlarged to 32 bytes, which would break its ability to access files written by a stock build.  The static assertion at least stops you from doing that, so you won't break something accidentally.

**Comment by mikrosk** [comment]
As this has been solved by switching to a more recent gcc with more "compatible" presets, closing.
