### ISSUE TITLE
Build failure: similar/main/iff.cpp:102:47: error: parameter 'len' set but not used [-Werror,-Wunused-but-set-parameter]

### ISSUE THREAD

**Issue by pkubaj** [dxx-rebirth/dxx-rebirth#702]
### Environment

https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220929-src.tar.xz

#### Operating System Environment

* [ ] Microsoft Windows (32-bit)
* [ ] Microsoft Windows (64-bit)
* [ ] Mac OS X
* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [ ] Fedora 28
  * [ ] Fedora 29
  * [ ] Fedora 30
  * [ ] Fedora 31
  * [ ] Fedora 32
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [x] FreeBSD
* [ ] NetBSD

#### CPU environment

* [x] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [x] ARM (32-bit)
* [x] ARM64 (64-bit; sometimes called AArch64)

### Description

Failure to build in FreeBSD's main branch:
```
similar/main/iff.cpp:102:47: error: parameter 'len' set but not used [-Werror,-Wunused-but-set-parameter]
static int parse_bmhd(PHYSFS_File *ifile,long len,iff_bitmap_header *bmheader)
                                              ^
1 error generated.
```

#### Regression status

The problem is related to FreeBSD's upgrade to LLVM 15.

### Steps to Reproduce
`make -C /usr/ports/games/dxx-rebirth`

**Comment by vLKp** [comment]
This looks easy enough to fix next time I am in the code.

Note though that clang-15 is currently not tested, due to problems with Apple Xcode.  Apple's non-beta Xcode still ships only clang-14 and libc++-14, even though clang-15 came out some months ago.  clang's library support for C++20 is sufficiently behind that I can readily break clang-14 support when doing routine maintenance (and this has happened before), so I need to keep libc++-14 around to test for that.  To install clang-15, I must install libc++-15, which requires removing libc++-14.  I plan to update to clang-15 as soon as Apple ships a non-beta Xcode that uses libc++-15.  In the meantime, clang-15 support is considered nice to have, and I will respond to problem reports for it, but I cannot test it locally.

**Comment by vLKp** [comment]
[Remove unused argument to parse_bmhd](/dxx-rebirth/dxx-rebirth/commit/114cdef1d2d4a326bebcfcc408805bc083097437) (Sun Feb 26 18:42:12 2023 +0000) should resolve this.  Closing.  Please advise if you encounter any other issues with clang-15.
