### ISSUE TITLE
invalid index used in array script

### ISSUE THREAD

**Issue by GitInMotion** [dxx-rebirth/dxx-rebirth#713]
Was playing D2 vertigo level 8 with the guide bot by the red door. Error happened a few times: 

https://imgur.com/a/YYeEoC3
![image](https://user-images.githubusercontent.com/28665533/236130334-1f2740bd-a547-4609-ad9e-f5744c5ba275.png)

**Comment by vLKp** [comment]
When filing a report like this, please follow the steps in `ISSUE_TEMPLATE/02-runtime-crash.md`, which in particular prompt you for the build that you are playing and steps to reproduce.  The cited line is impossible for the current code, because that line is blank.

https://github.com/dxx-rebirth/dxx-rebirth/blob/5b4bf16bfa68449e5a7534bcabce67bb0a787822/d2x-rebirth/main/escort.cpp#L718

If you tell what build you used, I can map the cited line to the corresponding code.  A dump file would also be quite helpful for reporting the state of the game at the time of the crash.

**Comment by GitInMotion** [comment]
I was running build dxx-rebirth_20220929-win
I'm not sure what you're referring to with ISSUE_TEMPLATE/02-runtime-crash.md :-/

Here is the savegame right before it crashes: https://www.dropbox.com/s/kjlhrls978zqyse/livenuke.sg0?dl=0

**Comment by vLKp** [comment]
When you try to file an issue, Github presents you with:

https://github.com/dxx-rebirth/dxx-rebirth/issues/new/choose

On that page, it offers you:

- Failure to build
- Runtime crash
- Runtime bug

and a link at the bottom for using none of those templates.  You appear to have used none of them, so you skipped over the instructions in `Runtime crash`.  In particular, you skipped over:

```
If the issue occurs at some particular place in the level, give a description how to reach that point from the beginning of the level.  Assume that the maintainer can use cheats to acquire keys, skip difficult fights, etc., but that the maintainer is not familiar with the optimal route to get from the start point to the affected location.
```

```
- Steps, starting from the main menu, to reach the problem state.  Assume the maintainer can cheat to any level and knows Descent input controls, but is unfamiliar with the particular level.
- If possible, describe the frequency of the problem.  Does it happen every time the steps to reproduce are followed?  If it is intermittent, are there any events correlated with the error?
- If the game produced any error messages, include their text verbatim.  If you paraphrase the message, you will likely be asked to reproduce the error and collect a verbatim copy of the text.
```

The error message _as text_ would be nice to record, so that it can be quoted and searched.  Your screenshot of the error message is not searchable.  The instructions in your screenshot also state to "provide steps to reproduce, starting from the game main menu."

For my future use, the error message in your screenshot reads:

---

```
Rebirth encountered a fatal error.  Please report this to the developers.

Include in your report:
* The exception message text:
  "d2x-rebirth/main/escort.cpp:718: invalid index used in array subscript: base=00007ff75fca0e68 size=350 index=65535"
* The level(s) played this session, including download URLs for any add-on missions

Dump file generation is not enabled in this build.

To the extent possible, provide steps to reproduce, starting from the game main menu.
```

---

Please prefer attaching critical files to the ticket, rather than hosting them on external services that may delete them unexpectedly.

Using that savegame, I see a different, but bad behavior.  After loading, the Guidebot seems stuck on the red door for several seconds, then I get these messages on the terminal:

```
d2x-rebirth/main/escort.cpp:716: BUG: object 0x555555f80bf0 has type 255, expected 2
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/array:208: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = d2x::robot_info; long unsigned int _Nm = 85; reference = d2x::robot_info&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

Then the program aborts due to the failed assertion.  This differs from your report, where the crash is an invalid `Buddy_objnum`.  I see a valid `Buddy_objnum` that points to an invalid `d2x::object`.  This is strange, since `Buddy_objnum` should either be `object_none` if there is no Guidebot, or should refer to the `d2x::object` representing the Guidebot.  I can see the Guidebot in front of me at the red door, so there is a Guidebot on the level.  Therefore, `Buddy_objnum` ought to refer to it, but instead refers to an invalid or destroyed object.  How did you get the game into this state?  Was the Guidebot killed and recreated?  Have you used any cheats on this level?

**Comment by vLKp** [comment]
After bypassing the crash, this save looks strange.  I found a marker for the guidebot death site, even though there is a live guidebot in play.  This should not happen in normal play.  Additionally, the player has ~90 seconds left on invulnerability at load time, which is not possible normally.

**Comment by GitInMotion** [comment]
Oh jeez. Well looks like there's a consequence for cheating :(  I...may
have used some cheat codes to revive the guidebot and give myself a little
invulnerability. Is that what is likely causing the crashes?

**Comment by vLKp** [comment]
I believe the above commit will allow your game to load and not crash when the guidebot performs its next update.  Please sync to `master` and retry.  If you still see problems, please reopen.
