### ISSUE TITLE
Runtime crash: index_range_exception during loading old save-game (2012)

### ISSUE THREAD

**Issue by Quix0r** [dxx-rebirth/dxx-rebirth#716]
### Environment

- Source: git
- Commit: 5b4bf16bfa68449e5a7534bcabce67bb0a787822

#### Operating System Environment

- Distribution Devuan Chimaera
- Kernel: Linux version 5.10.0-19-amd64

#### CPU environment

x86\_64 (64-bit Intel/AMD)

#### Game environment

Base mission

### Description

The game crashes loading a save-game of the base game:

````
terminate called after throwing an instance of 'valptridx<d2x::object>::index_range_exception'
  what():  similar/main/state.cpp:589: invalid index used in array subscript: base=(nil) size=350 index=511
Aborted
````

#### Regression status

Did not happen with older releases of DXX

### Steps to Reproduce

* Download `20230515_-_d2x_crashing_save_game.zip` from https://cloud.mxchange.org/index.php/s/public?path=%2Fdxx-rebirth
* Unpack it into ~/.d2x-rebirth/ folder
* Load mission "Quix0r"

* Engines affected:
  * [x] D2X-Rebirth

* Game modes affected:
  * [x] Single player

**Comment by vLKp** [comment]
Please attach files to the ticket instead of hosting them on external services.

The value of `last_hitobj` is corrupt in the savegame.  It indicates the most recently hit object was 511, but there are only 350 objects possible in the level.  I recall seeing a report like this years ago due to a bug in the 0.58.x series which would perform an out-of-bounds write, corrupting `last_hitobj` for a future resave.  I thought a workaround for the loader was added back then, but I cannot find the details of that change now.

Treating an invalid value as `object_none` should avoid the crash here.

**Comment by vLKp** [comment]
I believe the above commit should prevent this crash.  Please sync to current `master` and retry.  If you still see the crash, please reopen.

**Comment by Quix0r** [comment]
Yes, the map is loading again. Thank you for fixing it!
