### ISSUE TITLE
Build failure: possibly dangling reference to a temporary

### ISSUE THREAD

**Issue by ziplantil** [dxx-rebirth/dxx-rebirth#718]
### Environment
5b4bf16bfa68449e5a7534bcabce67bb0a787822

#### Operating System Environment

* [ ] Microsoft Windows (32-bit)
* [ ] Microsoft Windows (64-bit)
* [ ] Mac OS X

* Debian
  * [ ] Debian Stretch
  * [ ] Debian Buster
  * [ ] Debian Bullseye
  * [ ] Debian Sid
* Fedora
  * [x] Fedora 38
  * [ ] Rawhide
* Ubuntu
  * [ ] Ubuntu 16.04 LTS (Xenial Xerus)
  * [ ] Ubuntu 18.04 LTS (Bionic Beaver)
  * [ ] Ubuntu 18.10 (Cosmic Cuttlefish)
  * [ ] Ubuntu 19.04 (Disco Dingo)
  * [ ] Ubuntu 19.10 (Eoan Ermine)
  * [ ] Ubuntu 20.04 LTS (Focal Fossa)

* [ ] Arch
* [ ] Gentoo

* [ ] OpenBSD
* [ ] FreeBSD
* [ ] NetBSD

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)
* [ ] PowerPC (32-bit, sometimes called ppc)
* [ ] PowerPC64 (64-bit, big-endian, sometimes called ppc64)
* [ ] PowerPC64Le (64-bit, little-endian, sometimes called ppc64le)

### Description
Build failure:

```
similar/main/digiobj.cpp: In function ‘void d1x::digi_sync_sounds()’:
similar/main/digiobj.cpp:625:31: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  625 |                 const object &objp = [&vcobjptr, &s]{
      |                               ^~~~
similar/main/digiobj.cpp:632:19: note: the temporary was destroyed at the end of the full expression ‘<lambda closure object>d1x::digi_sync_sounds()::<lambda()>{d1x::LevelUniqueObjectState.d1x::d_level_unique_object_state::Objects.valptridx<d1x::object>::array_managed_type::<anonymous>.valptridx<d1x::object>::array_base_count_type::<anonymous>.valptridx<d1x::object>::array_base_count_type::<unnamed union>::vcptr, (* & s)}.d1x::digi_sync_sounds()::<lambda()>().valptridx<d1x::object>::ptr<valptridx<d1x::object>::vc>::operator valptridx<d1x::object>::partial_policy::apply_cv_policy<std::add_const>::reference_type()’
  632 |                 }();
      |                   ^
cc1plus: some warnings being treated as errors
```

#### Regression status

Unknown. The block of code the error happens in had its last changes 5 months ago according to blame, but I don't think that change causes the issue.

### Steps to Reproduce

Command: `scons sdl2=1`

Compiler version: gcc (GCC) 13.1.1 20230511 (Red Hat 13.1.1-2)

**Comment by vLKp** [comment]
`-Wdangling-reference` is new in gcc-13, so older versions cannot report this.  From reading https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106393#c1 where the warning was added, it looks like this is a heuristic warning that may or may not be correct in this case.  The warning sounds scary, assuming it is accurate.  From looking at the generated code for this area, I am not convinced that the warning is correct in this case.  It looks to me like no temporary is created, and instead the code computes and uses the address of the global `d2x::object`.

**Comment by ziplantil** [comment]
In theory, we are returning a reference from a function, which without further context could potentially be temporary. (I have no idea what `vcptr` is and cannot find references to anything defining it in the source code, so I do not know what `vcobjptr` ends up being.)

**Comment by vLKp** [comment]
`vcptr` -> Valid Const Pointer.  `Valid` means the input index `i` must be legal to use in `array[i]`.  It cannot be one of the magic invalid indexes, such as the placeholder for "No such element".  `Const` is in the C sense.  The returned reference will be a `const object &`, so writing through it is not legal.  `Pointer` distinguishes this from `ptridx`, which returns an object containing both the pointer and the index that produced it.  (Such objects are useful in many places, since the game sometimes wants a pointer and sometimes wants the array index.)

The reference from `vcobjptr(object_first)` refers to `Objects[object_first]`, which currently is a global variable.  Someday, `Objects` might be a heap variable, but the game is not there yet.  Therefore, such a reference is never dangling.

**Comment by vLKp** [comment]
I ran a test build in gcc-13.  I see several other sites that raise this warning.  All of them appear to me to be incorrect.  After reviewing the gcc bug reports around this warning, my opinion is that this warning was released too soon, and is too prone to false positives.

- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109671
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109642
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109538

As described in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106393#c1 by the original author, this warning is speculative:

```
    The warning works by checking if a reference is initialized with a function
    that returns a reference, and at least one parameter of the function is
    a reference that is bound to a temporary.  It assumes that such a function
    actually returns one of its arguments!
```

I acknowledge that such a function _may_ be dangerous, but as evidenced by the spurious warnings in the Rebirth code, such a function _may_ be safe, and yet is reported anyway.  In one such report, the author recommends ( https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109642#c3 ) suppressing the warning around the safe class.  This is unfortunate, since most warnings, once suppressed, are never restored.  Such a problem is particularly likely in a project like Rebirth, where I cannot restore the warning until all supported versions of gcc implement the good semantics that avoid the false positive.  The release of one good version of gcc is insufficient.

**Comment by vLKp** [comment]
After some experimentation, I believe the compiler's warning is a false positive, and one that is fairly difficult to avoid without either (1) changing the code to preserve unnecessary temporaries just to placate the compiler or (2) changing the semantics of the code.  I may yet do (2), but that is more involved than I want to work on for this ticket.

The above commit will detect when the compiler issues warnings for certain safe uses, and react by adding a command line option to disable the warning.  Hopefully, a future release of gcc will be more careful about false positives, and the configure test will react to that improvement by not adding `-Wno-dangling-reference`.

---

I also found some other things that gcc-13 rejected.  None of them were real bugs, but they were relatively easy to change the code to eliminate the construct it disliked, so I made those changes.  With current `master` (695e8b9ba1e5eacfc47e47fc7f0ad2b6407bb0c3), gcc-13 can now build Rebirth cleanly.  I believe that addresses this ticket.  Please sync and retry.  If you still see problems, please reopen.
