### ISSUE TITLE
Build failure: similar/main/scores.cpp:110:34: error: static assertion failed: high score size wrong

### ISSUE THREAD

**Issue by mikrosk** [dxx-rebirth/dxx-rebirth#724]
### Environment

Git commit: 5c900ca7a72398a9d9e46428cb1d684eba0a5cc5

#### Operating System Environment

Arch Linux/x64, gcc 13.1.1 (works)
FreeMiNT/m68k gcc 13.2.0 (prints the error)

### Description

This is somewhat related to #695 at least in a sense that dxx-rebirth fails to compile on a more exotic platform due to different alignment expectations (`sizeof(callsign_t)` is correct in this case = new gcc and configuration).

### Steps to Reproduce

scons host_platform=freemint host_endian=big opengl=0 screenshot=none sdlimage=0 sdlmixer=0 verbosebuild=1 CHOST=m68k-atari-mintelf

(this is based on https://github.com/mikrosk/dxx-rebirth/tree/master-latest but this is not so important, I don't expect you to install the environment from scratch -- just to show you that I haven't added any odd flags or anything of that matter)

```
m68k-atari-mintelf-g++ -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=vla -m68020-60 -fomit-frame-pointer -D__STDC_LIMIT_MACROS -Wno-error=format-truncation -funsigned-char -std=gnu++20 -Werror=unused -Werror=useless-cast -Wimplicit-fallthrough=5 -Wno-dangling-reference -fvisibility=hidden -Wduplicated-branches -Wduplicated-cond -Wsuggest-attribute=noreturn -Wsuggest-final-types -Wsuggest-override -Wlogical-op -Wold-style-cast -Wredundant-decls -Wno-sign-compare -DPHYSFS_DEPRECATED= -DDXX_USE_SHAREPATH=1 -DNDEBUG -DRELEASE -DDXX_BUILD_DESCENT_II -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -Ibuild -I/home/mikro/gnu-tools/m68000/m68k-atari-mintelf/sys-root/usr/include -I/home/mikro/gnu-tools/m68000/m68k-atari-mintelf/sys-root/usr/include/SDL -Id2x-rebirth/main similar/main/scores.cpp -o build/similar/main/.d2x-rebirth.scores.o
similar/main/scores.cpp:110:34: error: static assertion failed: high score size wrong
  110 | static_assert(sizeof(all_scores) == 336, "high score size wrong");
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~
similar/main/scores.cpp:110:34: note: the comparison reduces to '(314 == 336)'
```
What makes this issue different is the cause: in this case it seems that the alignment is failing because there's just a generic expectation that the struct:

https://github.com/dxx-rebirth/dxx-rebirth/blob/5c900ca7a72398a9d9e46428cb1d684eba0a5cc5/similar/main/scores.cpp#L110

 will be always default-aligned in the way that it produces 336 bytes without any packing or further instructions for the compiler (see the empty `#define DXX_SCORE_STRUCT_PACK` for `DXX_BUILD_DESCENT_II`) which is not true in this case (32-bit big endian).

[dxxsconf.zip](https://github.com/dxx-rebirth/dxx-rebirth/files/12422968/dxxsconf.zip)

**Comment by vLKp** [comment]
As I read your compiler's diagnostic, the problem is not that the structure is insufficiently packed, but that it is insufficiently padded.  The generated structure is too small, which is the opposite of the problem that this structure exhibited on more traditional platforms.

The original Descent code used C `struct` definitions as a shortcut for establishing binary file formats.  This is fragile, and I added `static_assert` checks so that building on platforms with differing packing rules would not result in parsing the files incorrectly.  For this particular case, at the minor expense of generating high-score files that do not interoperate with other platforms, you could probably just remove the check.

I see in https://github.com/freemint/m68k-atari-mint-gcc/issues/18#issuecomment-1690584149 you wrote:

> (I guess assuming 32-bit alignment rules while ours are still 16-bit?)

Am I correct to read that as being that your compiler is using 16-bit alignment for a C `int`?  Is your `int` 16 bits wide or 32 bits wide?  If it is not 32 bits wide, I expect a lot of Descent code may be broken for you.  I have tried to use the more specific stdint types where possible, but there is a substantial amount of old code, particularly in the ad-hoc file format structures, that may still use the non-specific types of `short` and `int` and expect specific results.

Ideally, all these file format `struct` cases would be rewritten as code that explicitly describes where and how much padding it uses.  However, that has been low priority since the major platforms all do the right thing as-is.

**Comment by mikrosk** [comment]
`int`s are 32-bit but AFAIK they are aligned on 16-bit boundaries in `struct`s because the original platform (Atari ST/Falcon) didn't have 32-bit memory access therefore aligning `int`s on 4-byte boundary didn't bring better performance and eat some memory for no real benefit.

Maybe a solution would be to make that struct packed with explicit padding added where the original descent code expects it?

**Comment by vLKp** [comment]
The structure was already marked as packed in Descent 1, although not in Descent 2.  Padding might have solved it, but I ended up rewriting the score input/output code to process the file as an array of bytes, with explicit serialization separate from structure layout.  This makes the code a bit cleaner.  Please sync to `master` and try it out.

**Comment by mikrosk** [comment]
Thanks!. Will try as soon as #776 gets resolved.

**Comment by mikrosk** [comment]
With the work around mentioned in https://github.com/dxx-rebirth/dxx-rebirth/issues/776#issuecomment-2179345832 I am indeed able to fully compile both d1x and d2x on m68k.

Cheers & closing.
