### ISSUE TITLE
Runtime bug: Sometimes after loading a multiplayer game I can't fire my primary guns

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [dxx-rebirth/dxx-rebirth#726]
### Environment

**Linux:** Installed from AUR: https://aur.archlinux.org/packages/d2x-rebirth
**Windows:** Installed from official GitHub release.

#### Operating System Environment

**NOTE:** The host player was on ArchLinux, the guest was on Windows 10.

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10 (Version 22H2)

* Linux

Operating System: Arch Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.11-arch2-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 27.3 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570S UD

**NOTE:** I usually don't take more than 1 week to update my system.

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

**Assets:**

descent2.hog:
- Obtained from: GoG
- Size: 7.2 MiB (7,595,079)
- SHA256: f1abf516512739c97b43e2e93611a2398fc9f8bc7a014095ebc2b6b2fd21b703

### Description

Sometimes after loading a multiplayer game I can't fire my primary guns. Didn't have time to test on Single Player mode. This error is intermittent. Maybe it needs players playing normally, beating levels and saving periodically to happen.

#### Regression status

I didn't check other versions.

### Steps to Reproduce

**Engines affected:** D2X-Rebirth

1. Start up the game
2. Load a savefile (or some savefiles in sequence)
3. Check the reticle and try firing with primary weapons right after loading the savefile(s)

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [x] Multiplayer cooperative

* Players affected by issue:
  * [x] Game host
  * [x] Game guests

**Comment by vLKp** [comment]
I cannot reproduce this with the information available.  I tried loading a variety of my old multiplayer save games, and my primary guns were always functional.  I tried creating new multiplayer savegames from several different levels, and then loading those new games.  My primary guns were always functional.

> **Linux:** Installed from AUR: https://aur.archlinux.org/packages/d2x-rebirth

As I read [AUR: d2x-rebirth](https://aur.archlinux.org/packages/d2x-rebirth), that would mean you used the source [dxx-rebirth_20220929](https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220929-src.tar.xz), which by its filename is now approximately 11 months old. 

It is possible that the problem you are reporting has been fixed sometime since then.  Since the problem is described as intermittent, no reliable steps to reproduce are available, and the frequency (10% success / 90% failure vs 90% success / 10% failure, for example) is unclear, attempting to bisect for it would be very tedious.  Please retest on current code, and reopen if you still see the problem.

When the problem manifests, is the bad savegame permanently bad, such that you can restart Rebirth, load the savegame again, and the bug appears again?  If so, providing the savegame may help me narrow down the problem.
