### ISSUE TITLE
Runtime bug: Robot bumping causing to freeze or kill robots

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [dxx-rebirth/dxx-rebirth#728]
### Environment

**Linux:** Installed from AUR: https://aur.archlinux.org/packages/d2x-rebirth
**Windows:** Installed from official GitHub release.

#### Operating System Environment

**NOTE:** The host player was on ArchLinux, the guest was on Windows 10.

* Microsoft Windows
  * [ ] Microsoft Windows XP
  * [ ] Microsoft Windows Vista
  * [ ] Microsoft Windows 7
  * [ ] Microsoft Windows 8
  * [ ] Microsoft Windows 8.1
  * [x] Microsoft Windows 10 (Version 22H2)

* Linux

Operating System: Arch Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.11-arch2-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 27.3 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570S UD

**NOTE:** I usually don't take more than 1 week to update my system.

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [ ] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

**Assets:**

descent2.hog:
- Obtained from: GoG
- Size: 7.2 MiB (7,595,079)
- SHA256: f1abf516512739c97b43e2e93611a2398fc9f8bc7a014095ebc2b6b2fd21b703

### Description

Sometimes robots bump into each other. This happens quite frequently with Guide Bot too, and when this happens the Guide Bot makes another robot freeze. Sometimes the Thief Bot also dies because of this effect, I suppose.

#### Regression status

I didn't check other versions.

### Steps to Reproduce

**Engines affected:** D2X-Rebirth

By playing normally, this situation should be noticed.

* Engines affected:
  * [ ] D1X-Rebirth
  * [x] D2X-Rebirth

* Game modes affected:
  * [ ] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [x] Multiplayer cooperative

* Players affected by issue:
  * [x] Game host
  * [x] Game guests

**Comment by vLKp** [comment]
> **Linux:** Installed from AUR: https://aur.archlinux.org/packages/d2x-rebirth

As I read [AUR: d2x-rebirth](https://aur.archlinux.org/packages/d2x-rebirth), that would mean you used the source [dxx-rebirth_20220929](https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220929-src.tar.xz), which by its filename is now approximately 11 months old.  While Rebirth has seen less development recently due to Apple Clang being behind on C++20 standard support, that still means you are missing 409 commits:

```
$ git log --oneline origin/master --since=2022-09-29 | wc
    409    2601   22824
```

> **Windows:** Installed from official GitHub release.

There are no full releases for Windows hosted in the GitHub repository.  There are 2 [very old pre-releases](https://github.com/dxx-rebirth/dxx-rebirth/releases): [v0.59.100](https://github.com/dxx-rebirth/dxx-rebirth/releases/tag/0.59.100) (December 2016) and [v0.60.0-beta2](https://github.com/dxx-rebirth/dxx-rebirth/releases/tag/0.60.0-beta2) (April 2018).  I recommend against using them, as they are even older than the Arch package.

> Sometimes robots bump into each other. This happens quite frequently with Guide Bot too, and when this happens the Guide Bot makes another robot freeze. Sometimes the Thief Bot also dies because of this effect, I suppose.

That sounds like https://github.com/dxx-rebirth/dxx-rebirth/issues/665 , which was reported 2022-10-03 and fixed 2022-10-10.

Please try using a version from this year.  Reopen if the problem is reproducible on recent code.

**Comment by WilliamWeberBerrutti** [comment]
> As I read AUR: d2x-rebirth, that would mean you used the source dxx-rebirth_20220929, which by its filename is now approximately 11 months old. While Rebirth has seen less development recently due to Apple Clang being behind on C++20 standard support, that still means you are missing 409 commits:

Oh boy! But strangely that package wasn't marked as "Out-of-date". So all my recent reports wouldn't be adequate then. My apologies!

>There are no full releases for Windows hosted in the GitHub repository. There are 2 very old pre-releases: v0.59.100 (December 2016) and v0.60.0-beta2 (April 2018). I recommend against using them, as they are even older than the Arch package.

That's what I meant, but maybe I wasn't clear. Maybe I should've specified the links.

> That sounds like #665 , which was reported 2022-10-03 and fixed 2022-10-10.
> Please try using a version from this year. Reopen if the problem is reproducible on recent code.

Got it! As soon as I have time, I intend to check it out!

**Comment by WilliamWeberBerrutti** [comment]
This issue is fixed. No need to reopen.
