### ISSUE TITLE
Runtime bug: If vsync option is enabled, -maxfps parameter doesn't work

### ISSUE THREAD

**Issue by k0zyrev** [dxx-rebirth/dxx-rebirth#743]
https://www.dxx-rebirth.com/download/dxx/rebirth/dxx-rebirth_20220929-win.zip
WIN10

I don't know if it's intended behaviour or not, but I didn't expect that. First of all, I'd expect VSYNC option to lock fps to my screen framerate (60) which didn't happen. Then without disabling vsync I tried both starting the game with a -maxfps parameter and when that didn't work tried to edit the .ini. With vsync option still on, none of those methods limited fps.

Only tried it with D1X-Rebirth

Singleplayer

**Comment by k0zyrev** [comment]
> What are you trying to achieve by adjusting maxfps? 

I'm using old hardware with subpar cooling. I don't think that playing at 200fps adds any value to my experience, I'd rather drop to 100 and have my cpu run 5 degrees colder. It's not a technical problem, I was just confused and thought that the option didn't work when I enabled -maxfps 100 and yet game fps counter stayed at 200.

**Comment by vLKp** [comment]
The game already tries to limit CPU utilization by sleeping as time permits.  When vsync is enabled, it should delegate the delay to your graphics driver.  That would be system dependent as to what it would do, which could include not sleeping at all.  Vsync is meant to prevent screen tearing, not to slow down the game, though some implementations might slow the game as a side effect of preventing tearing.  A brief read of Wikipedia ( https://en.wikipedia.org/wiki/Screen_tearing#Vertical_synchronization ) suggests that some graphics drivers may ignore vsync if the game is running fast enough that tearing can be avoided without use of vsync.

Are you actually seeing a notable temperature difference with FPS forced to a much lower value (Vsync=OFF + MaxFPS=100)?  Given the game's age and that it already sleeps between frames, I would not have expected adjusting the frame rate to be that measurable.

**Comment by k0zyrev** [comment]
Okay, on closer inspection it turned out it was only a couple of degrees difference (49C vs 47C cpu and 43C vs 41C igpu). 

Anyway, the point of my post was to point out a confusing behaviour when enabling both options. My solution would be adding an extra sentence of explanation in d1x.ini to the -maxfps line saying that framerate would be different if vsync is enabled or something like that.

**Comment by InfernalCore** [comment]
This bug should be closed because it concerns an obsolete package.

`First of all, I'd expect VSYNC option to lock fps to my screen framerate (60) which didn't happen.`

It is true, k0zyrev is right. 
I checked in Windows 10 the version `dxx-rebirth_20220929-win.zip` downloaded from www.dxx-rebirth.com which now is no more available (but unfortunately the version now available there is much older and _much_ worse).

However, package 20220929 is now totally obsolete. 

It was superseded by a more recent Windows package that can be downloaded from https://github.com/maggu2810/dxx-rebirth/releases. In this version VSYNC works. Just relaunch the program (as per displayed message). Then sometime in Windows (only in Windows) you need to briefly open the option menu again to make the settings effective.

IMHO it should be made clear in the main page that Windows packages _are_ available, and where they can be downloaded.

**Comment by vLKp** [comment]
Per above comment and the reaction from @k0zyrev, closing.  The issue with the website offering only an ancient build will need to be addressed separately.
