### ISSUE TITLE
Homers Exploding Early On Relock

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#75]
Sometimes (not always) when a homer loses lock and then regains it, it will explode before reaching the target. This also happens in Retro, so it's an old bug.

**Comment by zicodxx** [comment]
This may or may not be related to the lifetime of the homer (~20 seconds). As many projectiles, they have a limited time until they will simply explode. Usually this isn't visible as they fly pretty fast and hit their target or solid walls before it's over. The effect is much more visible with smart projectiles as they fly much slower. The trick is that - additionally to the "march towards death counter" - homing missiles also lose more life the harder they turn and this function is also only applied if an actual target is given to the homing missile which would explain why it only happens when the missile locks again. 
This calculation can cut the homing missile lifetime in half (~10 seconds).
If you want to test, if your observation is connected to the lifetime, you can look up laser_do_weapon_sequence() and add a printout for the lifetime directly under the lifetime calculation (line 1589 as of today's commits):
> printf("%f\n",((float)(obj->lifeleft+1)/F1_0));
This will print the lifetime of the current homers into the console (bash/cmd - not the game console). If the missile explodes when this value is close to 0, we are probably not dealing with a bug here but an intended behavior.

**Comment by Mako88** [comment]
OK, I'll check it out! Thanks!

**Comment by zicodxx** [comment]
I tested this with current master in a D2 test level and compared to the results in the same level in Descent 2 running in DOSBox at roughly 30 FPS. I am not able to notice any behavior out of the ordinary. If this bug existed in earlier revisions, the newly restored homing/tracking code restored the original behavior in this case as well.
