### ISSUE TITLE
Explosions Hidden

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#76]
In multiplayer when you are destroyed, for the first half second you can't see your ship. I believe it has to do with the "clang" sprite hiding things.

**Comment by Mako88** [comment]
After further testing, it is definitely the hit animation that covers the ship and makes it invisible. (Not the explosion, but the gray dots sprite).

**Comment by zicodxx** [comment]
There is a few more little annoyances that I need to fix when it comes to rendering order of transparent elements. Such as objects behind force fields for example. I'll assign this to me but since from all I can tell it's just minor glitches with transparency effects enabled, I will put this off till the next version after the 0.60 milestone.

**Comment by Mako88** [comment]
I was told this bug isn't present when filtering is disabled, though I haven't verified that myself yet.

**Comment by zicodxx** [comment]
Correction: This issue is only present with Transparency effects enabled. Sometimes sprites and 3D models render in the wrong order - sprite being rendered first even tho it is in front of the 3D model (relative to the player). Without transparency effects, this glitch is fixed by Depth Testing but alpha blending will still have issues properly showing the object behind the sprite (as it wasn't there at the moment the transparent texture was generated).

**Comment by zicodxx** [comment]
This issue should be fixed - among with a few other rendering order glitches in bd391e2363cacc74f88719822e255567cce56629.
