### ISSUE TITLE
Build failure: GCC 13.2.0 buildroot x86_64 to x86_64

### ISSUE THREAD

**Issue by rtissera** [dxx-rebirth/dxx-rebirth#778]
### Environment
Buildroot 2024.02
GCC 13.2.0
x86_64 to x86_64 compiler
Running in Docker (Ubuntu 22.04 LTS)

Git commit : ea01f707d539b99e537b54afe67705c5e8443dbc

#### Operating System Environment
Linux Mint 21.3 Cinnamon (host)

#### CPU environment
* [ ] x86\_64 (64-bit Intel/AMD)

### Description

Build failure with GCC 13.2.0.

#### Regression status
No idea, try to revert to Nov 2023 build, still fails under GCC 13.2.0

### Steps to Reproduce

Log : https://dpaste.org/62iUU

**Comment by vLKp** [comment]
When reporting a build failure, please include the failure text inline in the ticket.  Pastebins expire - and in this case, it even seems to allow anonymous users to delete its content early.

The relevant error appears to be:

```
d2x-rebirth/main/movie.cpp: In constructor ‘d2x::BuiltinMovies::BuiltinMovies()’:
d2x-rebirth/main/movie.cpp:620:49: error: ‘%s’ directive output may be truncated writing up to 23 bytes into a region of size 15 [-Werror=format-truncation=]
  620 |     snprintf(filename.data(), filename.size(), "%s-%c.mvl", movielib, resolution);
      |                                                 ^~
In file included from ../../host/x86_64-buildroot-linux-gnu/sysroot/usr/include/stdio.h:964,
                 from ./d2x-rebirth/libmve/mvelib.h:10,
                 from d2x-rebirth/main/movie.h:30,
                 from d2x-rebirth/main/movie.cpp:37:
In function ‘int snprintf(char*, size_t, const char*, ...)’,
    inlined from ‘PHYSFS_ErrorCode d2x::{anonymous}::init_movie(const char*, char, int, d2x::LoadedMovie&)’ at d2x-rebirth/main/movie.cpp:620:10,
    inlined from ‘std::pair<PHYSFS_ErrorCode, d2x::movie_resolution> d2x::{anonymous}::init_movie(const char*, int, d2x::LoadedMovie&)’ at d2x-rebirth/main/movie.cpp:634:26,
    inlined from ‘d2x::BuiltinMovies::BuiltinMovies()’ at d2x-rebirth/main/movie.cpp:653:13:
../../host/x86_64-buildroot-linux-gnu/sysroot/usr/include/bits/stdio2.h:54:35: note: ‘__builtin_snprintf’ output between 7 and 30 bytes into a destination of size 15
   54 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |                    __glibc_objsize (__s), __fmt,
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |                    __va_arg_pack ());
      |                    ~~~~~~~~~~~~~~~~~
d2x-rebirth/main/movie.cpp: In constructor ‘d2x::BuiltinMovies::BuiltinMovies()’:
d2x-rebirth/main/movie.cpp:620:49: error: ‘%s’ directive output may be truncated writing up to 23 bytes into a region of size 15 [-Werror=format-truncation=]
  620 |     snprintf(filename.data(), filename.size(), "%s-%c.mvl", movielib, resolution);
      |                                                 ^~
In function ‘int snprintf(char*, size_t, const char*, ...)’,
    inlined from ‘PHYSFS_ErrorCode d2x::{anonymous}::init_movie(const char*, char, int, d2x::LoadedMovie&)’ at d2x-rebirth/main/movie.cpp:620:10,
    inlined from ‘std::pair<PHYSFS_ErrorCode, d2x::movie_resolution> d2x::{anonymous}::init_movie(const char*, int, d2x::LoadedMovie&)’ at d2x-rebirth/main/movie.cpp:637:20,
    inlined from ‘d2x::BuiltinMovies::BuiltinMovies()’ at d2x-rebirth/main/movie.cpp:653:13:
../../host/x86_64-buildroot-linux-gnu/sysroot/usr/include/bits/stdio2.h:54:35: note: ‘__builtin_snprintf’ output between 7 and 30 bytes into a destination of size 15
   54 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   55 |                    __glibc_objsize (__s), __fmt,
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   56 |                    __va_arg_pack ());
      |                    ~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
scons: *** [build/d2x-rebirth/main/movie.o] Error 1
```

---

I do not see a failure using gcc-13.2.1 on commit ea01f707d539b99e537b54afe67705c5e8443dbc.  I have seen that warning before, so it is not suppressed in my environment.  In your case, the warning is incorrect.  `BuiltinMovies` only initializes from `movielib_files`, which is `std::array<std::array<char, 8>, 3>`, so the individual strings pulled from it cannot be more than 7 bytes plus a null terminator.  The compiler is wrong to predict that it could write up to 23 bytes.  This is likely the result of `8 * 3`, but since the entire array is `constexpr`, the compiler should be able to prove that each of the elements is individually null terminated, and so the read should use the dimension of one element, not the sum of all elements.  I cannot explain where it is determining that it could write up to 30 bytes of output.

Oddly, the call from `init_extra_robot_movie` is far more difficult to statically prove correct, and yet the compiler does not warn about it.  The compiler warns about the path that is provably safe, and fails to warn about the path that is not provably safe.

---

Changing `FILENAME_LEN` may have unwanted effects elsewhere, as it is used for a variety of buffer lengths.  Some of these may need to be its current value, for compatibility with existing retail game data files.

---

Adding an unnecessary check for overflow, either by using `%.8s` instead of `%s`, or by checking the return code afterward, should silence the reported diagnostic.

---

Since this commit builds fine for me with gcc-13, I cannot determine what "heavy C++ templating" issue you may be encountering.  Please share that output.
