### ISSUE TITLE
Sound Stacking

### ISSUE THREAD

**Issue by Mako88** [dxx-rebirth/dxx-rebirth#88]
Currently there is no limit to the number times the same sound will stack on itself.

This can be demonstrated by setting switch weapon to the mouse wheel, then going to town (Make sure you lower your volume first, or this WILL blow your speakers).

There should be a cap set on the maximum number of times the same sound is allowed to stack (maybe 2 or 3?)

**Comment by zicodxx** [comment]
Revisiting my TODO list today I came back to this issue and I thought about how to practically solve this. And instead of cancelling out certain effects (which I think may sound weird if it happens within the action - think of explosions) might sound weird. Wouldn't it also be possible to simply normalize the sound output according to the set volume level? I figure this may need to be done within the SDL part of the code but I do not know from the top of my head how to make this happen.

**Comment by vLKp** [comment]
Cancelling the effect could be an acceptable workaround pending a full fix, especially if it is limited to cancelling sounds that are completely user-controlled, like the example of flooding weapon switch events.

**Comment by ryusei117** [comment]
Cool, someone already reported this for me. :-P I've successfully annoyed many Co-op teammates by rapidly scrolling through my weapons right behind them. Apparently, the original MS-DOS engines only allow one of each weapon switching sound effect at once. For example, if you switch your primary weapon multiple times, each new sound effect will cancel the previous one - but if you switch both your primary and secondary, then both sound effects will play at once. Descent 3 actually works this way too. I don't know if any other types of sound effect have the same issue, but I'd vote for restoring this original behavior for weapon switching sounds at least.

**Comment by zicodxx** [comment]
Come to think of it - apart from switching weapons, is there any other occurrence where sound stacking is a problem? For the Vulcan Cannon for example it is what creates its unique sound effect so preventing stacking there may be undesired. Same as for explosion effects - especially during the escape sequence but also in general. 
Just fixing this issue where it seems to be a problem (i.e. during weapon switching - let's say HUD sounds altogether) sounds to me like the more reasonable approach instead of trying to find a magic balance for all the sound effects in the game - which may not be possible without defining different rulesets for different situations and effects.

**Comment by ryusei117** [comment]
Yeah, the weapon switching sounds are the only eardrum-shredding repeating sound effects I know. And of course some people might consider the other HUD sounds an issue as well - for example, if a player rapidly spams chat macros, or if you scroll the mouse wheel when you don't have any other weapons. So limiting only the HUD sounds seems like a good plan to me, although I wonder if @Mako88 found any other situations where sound stacking is a problem.

**Comment by ryusei117** [comment]
Hmm, it seems there's an issue with the "materialization" sound effect now. In both D1 and D2, when you enter a level and your ship teleports in, the sound effect plays loudly at first and then gets cut off before it finishes. Strangely, the same sound effect plays correctly when a robot generator spawns a robot. I found this problem while testing commit 784213ec1f6414bf7a61a2d604442434decb7190.

As for the sound stacking issue, though, it's fixed! :-) A couple of sound effects still stack: the one that plays when you try to select a weapon you don't have and the one that plays when you press "cycle primary" or "cycle secondary" when you don't have any other weapons. Personally, however, I never found those problematic, since I can't think of a situation where normal gameplay would trigger them rapidly - but if anyone thinks those shouldn't stack either, it should be OK to fix them as well.

**Comment by vLKp** [comment]
I thought the materialize sound was truncated too, but I think it was doing that even before my change.

Yes, the stacking is only inhibited on sounds that use `digi_play_sample_once` or its variants.  Some sound effects may be played through functions that do not preempt.  They are probably not hard to fix.  If any of them can be stacked for players other than the person triggering it, I want to fix those.  I care less about a player spamming himself than I do about him spamming others.

**Comment by ryusei117** [comment]
Huh, odd ... I just tested commit "Prevent stacking weapon rotation sounds" (4a98e796abb099eb4c592d9520e4edbef7a15d7e) and the commit before it (12cc5860fe5ad82e579f37de84ffaa380955fb1a). 4a98e796abb099eb4c592d9520e4edbef7a15d7e has the materialization sound bug, but 12cc5860fe5ad82e579f37de84ffaa380955fb1a doesn't. Is that different from what you're seeing?

**Comment by vLKp** [comment]
I must have been mistaken previously.  The reported problem was real, and was an interaction of multiple bugs.

- First bug: the sound effect outlived the video clip
- Second bug: the sound subsystem, when given a non-permanent sound to link to an object, proceeded to ignore that link and instead play the sound to completion, regardless of the lifetime of the supposedly linked object.  (This is technically a hack, because they did document that this was done - but it caused problems elsewhere and needed to be fixed.)

The original commit for this issue fixed the second bug by removing the hack, at which point the game began correctly terminating the sound effect when the associated object (the plus-shaped appearance effect) ended.  Unfortunately, players expect the incorrect (but historically present) result of the sound effect outliving its video clip.  The sound effect does sound wrong when truncated early.  To fix this, I changed the code that creates the sound effect to link it to the location, not the object.  That allows it to play to completion, even when the object terminates early.  See the commit log for [Fix player appearance sound truncation](/dxx-rebirth/dxx-rebirth/commit/5d74fd48b51d5953f36a18cd859f29cb24a2c4be) for more details.

**Comment by ryusei117** [comment]
Yep, the player ship materialization sound effect is working properly now. Thanks!

**Comment by vLKp** [comment]
[Prevent stacking weapon rotation sounds](/dxx-rebirth/dxx-rebirth/commit/4a98e796abb099eb4c592d9520e4edbef7a15d7e) addressed the worst of the original problem.  [Fix player appearance sound truncation](/dxx-rebirth/dxx-rebirth/commit/5d74fd48b51d5953f36a18cd859f29cb24a2c4be) fixed the regression caused by the first change.  I think this can be closed now.  If anyone disagrees, please reopen and state which other sounds need to be suppressed when duplicated.
